<?php

namespace Tests\Feature\Print;

use App\Models\Bank;
use App\Models\Branch;
use App\Models\Customer;
use App\Models\Employee;
use App\Models\Ledger;
use App\Models\Product;
use App\Models\Supplier;
use App\Models\User;
use App\Models\Warehouse;
use Tests\Helpers\BuildsRoleUsers;
use Tests\Helpers\InsertsBankDependencies;
use Tests\TestCase;

/**
 * Phase 19 (Task 19-RATELIMIT-PRINT) — Print view feature tests.
 *
 * Covers the 9 master-data modules that expose a print-friendly directory
 * view via BaseMasterDataController::print():
 *
 *   GET /admin/branches/print    (admin, manager, warehouse_manager)
 *   GET /admin/warehouses/print  (admin, manager, warehouse_manager)
 *   GET /admin/products/print    (admin, manager, warehouse_manager)
 *   GET /admin/customers/print   (admin, manager, salesman)
 *   GET /admin/suppliers/print    (admin, manager, accountant)
 *   GET /admin/employees/print    (admin, manager, hr)
 *   GET /admin/banks/print        (admin, manager, accountant)
 *   GET /admin/users/print        (admin, manager)
 *   GET /admin/ledgers/print      (admin, accountant)
 *
 * Each test verifies:
 *   - The route returns 200 + text/html Content-Type.
 *   - The view is the module's print.blade.php extending the shared layout.
 *   - Table headers (from printColumns()) are present.
 *   - At least one data row is rendered for seeded records.
 *   - The "Print" button (window.print() trigger) is present in the toolbar.
 *
 * Auth + RBAC tests:
 *   - Unauthenticated → redirect to login.
 *   - Salesman (denied on branches) → redirect to dashboard.
 */
class PrintViewTest extends TestCase
{
    use BuildsRoleUsers, InsertsBankDependencies;

    // ====================================================================
    // SHARED ASSERTIONS
    // ====================================================================

    /**
     * Assert the response looks like a print HTML page: 200, text/html,
     * contains the shared print-layout markers + Print button.
     */
    private function assertPrintResponse($response, string $moduleName, array $expectedHeaders = []): string
    {
        $response->assertOk();
        $response->assertHeader('Content-Type', 'text/html; charset=UTF-8');

        $body = $response->getContent();
        $this->assertNotEmpty($body, "Print page body for {$moduleName} is empty.");

        // The shared layout's print button (window.print trigger).
        $this->assertStringContainsString('window.print()', $body, "Print button missing for {$moduleName}.");

        // The shared layout's footer signature.
        $this->assertStringContainsString('Generated by', $body, "Footer missing for {$moduleName}.");
        $this->assertStringContainsString('RC ERP', $body, "RC ERP signature missing for {$moduleName}.");

        // @media print CSS rule must be present.
        $this->assertStringContainsString('@media print', $body, "@media print CSS missing for {$moduleName}.");

        // Each expected header label should appear in the table head.
        foreach ($expectedHeaders as $header) {
            $this->assertStringContainsString(
                '>' . $header . '<',
                $body,
                "Header '{$header}' not found in print view for {$moduleName}.",
            );
        }

        return $body;
    }

    /**
     * Assert the response body contains at least one row of data (excluding
     * the "empty" placeholder row).
     */
    private function assertHasDataRows(string $body, string $needle): void
    {
        $this->assertStringContainsString(
            $needle,
            $body,
            "Expected data row containing '{$needle}' not found in print view body.",
        );
    }

    // ====================================================================
    // PER-MODULE PRINT TESTS
    // ====================================================================

    public function test_branch_print_returns_200(): void
    {
        $this->actingAsRole('admin');
        $branch = Branch::factory()->create([
            'branch_code' => 'PRBR-' . substr(uniqid(), -4),
            'branch_name' => 'Printable Branch',
        ]);

        $body = $this->assertPrintResponse(
            $this->get(route('admin.branches.print')),
            'branches',
            ['Code', 'Branch Name'],
        );

        $this->assertHasDataRows($body, 'Printable Branch');
    }

    public function test_warehouse_print_returns_200(): void
    {
        $this->actingAsRole('admin');
        $branch = Branch::factory()->create(['branch_name' => 'WH-Print-Branch']);
        $wh = Warehouse::factory()->forBranch($branch->id)->create([
            'warehouse_code' => 'PRWH-' . substr(uniqid(), -4),
            'warehouse_name' => 'Printable Warehouse',
        ]);

        $body = $this->assertPrintResponse(
            $this->get(route('admin.warehouses.print')),
            'warehouses',
            ['Code', 'Warehouse Name', 'Branch Name'],
        );

        $this->assertHasDataRows($body, 'Printable Warehouse');
    }

    public function test_product_print_returns_200(): void
    {
        $this->actingAsRole('admin');
        Product::factory()->create([
            'product_code' => 'PRP-' . substr(uniqid(), -4),
            'product_name' => 'Printable Product',
            'unit'         => 'Pcs',
        ]);

        $body = $this->assertPrintResponse(
            $this->get(route('admin.products.print')),
            'products',
            ['Code', 'Product Name', 'Unit'],
        );

        $this->assertHasDataRows($body, 'Printable Product');
    }

    public function test_customer_print_returns_200(): void
    {
        $this->actingAsRole('admin');
        $branch = Branch::factory()->create(['branch_name' => 'Cust-Print-Branch']);
        Customer::factory()->forBranch($branch->id)->create([
            'customer_code' => 'PRCUS-' . substr(uniqid(), -4),
            'customer_name' => 'Printable Customer',
        ]);

        $body = $this->assertPrintResponse(
            $this->get(route('admin.customers.print')),
            'customers',
            ['Code', 'Customer Name'],
        );

        $this->assertHasDataRows($body, 'Printable Customer');
    }

    public function test_supplier_print_returns_200(): void
    {
        $this->actingAsRole('admin');
        Supplier::factory()->create([
            'supplier_code' => 'PRSUP-' . substr(uniqid(), -4),
            'supplier_name' => 'Printable Supplier',
        ]);

        $body = $this->assertPrintResponse(
            $this->get(route('admin.suppliers.print')),
            'suppliers',
            ['Code', 'Supplier Name'],
        );

        $this->assertHasDataRows($body, 'Printable Supplier');
    }

    public function test_employee_print_returns_200(): void
    {
        $this->actingAsRole('admin');
        $branch = Branch::factory()->create(['branch_name' => 'Emp-Print-Branch']);
        Employee::factory()->forBranch($branch->id)->withRole('salesman')->create([
            'employee_code' => 'PREMP-' . substr(uniqid(), -4),
            'name'          => 'Printable Employee',
        ]);

        $body = $this->assertPrintResponse(
            $this->get(route('admin.employees.print')),
            'employees',
            ['Code', 'Name', 'Role'],
        );

        $this->assertHasDataRows($body, 'Printable Employee');
    }

    public function test_bank_print_returns_200(): void
    {
        $this->actingAsRole('admin');
        Bank::factory()->create([
            'bank_name'      => 'Printable Bank',
            'account_number' => 'PRBANK-' . substr(uniqid(), -4),
        ]);

        $body = $this->assertPrintResponse(
            $this->get(route('admin.banks.print')),
            'banks',
            ['Bank Name', 'Account Number'],
        );

        $this->assertHasDataRows($body, 'Printable Bank');
    }

    public function test_user_print_returns_200(): void
    {
        $this->actingAsRole('admin');
        $branch = Branch::factory()->create();
        $employee = Employee::factory()->forBranch($branch->id)->withRole('manager')->create([
            'name' => 'Printable Linked Employee',
        ]);
        User::factory()->forEmployee($employee->id)->create([
            'username' => 'pruser_' . substr(uniqid(), -4),
        ]);

        $body = $this->assertPrintResponse(
            $this->get(route('admin.users.print')),
            'users',
            ['Username', 'Employee Name'],
        );

        $this->assertStringContainsString('pruser_', $body);
    }

    public function test_ledger_print_returns_200(): void
    {
        $this->actingAsRole('admin');
        Ledger::factory()->withNature('cash_bank')->create([
            'ledger_code' => 'PRLED-' . substr(uniqid(), -4),
            'ledger_name' => 'Printable Ledger',
        ]);

        $body = $this->assertPrintResponse(
            $this->get(route('admin.ledgers.print')),
            'ledgers',
            ['Code', 'Ledger Name', 'Account Type'],
        );

        $this->assertHasDataRows($body, 'Printable Ledger');
    }

    // ====================================================================
    // AUTH + RBAC
    // ====================================================================

    public function test_print_requires_auth(): void
    {
        // No actingAs — should redirect to login.
        $this->get(route('admin.branches.print'))
            ->assertRedirect(route('login'));
    }

    public function test_print_requires_manager_role(): void
    {
        // Salesman has no access to branches (admin/manager/warehouse_manager).
        $this->actingAsRole('salesman')
            ->get(route('admin.branches.print'))
            ->assertRedirect(route('dashboard'));
    }

    // ====================================================================
    // CONTENT-LEVEL ASSERTIONS
    // ====================================================================

    public function test_print_view_contains_table_headers(): void
    {
        $this->actingAsRole('admin');
        Branch::factory()->create();

        $body = $this->assertPrintResponse(
            $this->get(route('admin.branches.print')),
            'branches',
            ['Code', 'Branch Name', 'Address', 'Phone', 'Email'],
        );

        // Table structure: thead + tbody.
        $this->assertStringContainsString('<thead>', $body);
        $this->assertStringContainsString('<tbody>', $body);
    }

    public function test_print_view_contains_data_rows(): void
    {
        $this->actingAsRole('admin');
        Branch::factory()->create(['branch_name' => 'Unique Print Row Branch']);
        Branch::factory()->create(['branch_name' => 'Another Print Row Branch']);

        $body = $this->assertPrintResponse(
            $this->get(route('admin.branches.print')),
            'branches',
        );

        $this->assertHasDataRows($body, 'Unique Print Row Branch');
        $this->assertHasDataRows($body, 'Another Print Row Branch');
    }

    public function test_print_view_has_print_button(): void
    {
        $this->actingAsRole('admin');
        Branch::factory()->create();

        $response = $this->get(route('admin.branches.print'));
        $response->assertOk();

        $body = $response->getContent();

        // The shared layout's print toolbar button.
        $this->assertStringContainsString('window.print()', $body);
        // The "no-print" class hides it when actually printing.
        $this->assertStringContainsString('no-print', $body);
        // The printer icon (FontAwesome) should be present.
        $this->assertStringContainsString('fa-print', $body);
    }
}
