<?php

declare(strict_types=1);

namespace App\Services\Sales;

use App\Models\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Log;

/**
 * Below-Min Approval Service — Session 6.
 *
 * Allows a sale line below the product's minimum price ONLY when an
 * admin or manager actively approves it with a reason (≥ 10 chars).
 * The approval is written to `user_audit_log` with
 * `action = 'below_min_override'`, and the returned audit-log id is
 * stored on the cart line (items_json.below_min_override_id) and
 * eventually on `sales_invoice_items.below_min_override_id` at finalize.
 *
 * ── Design (synchronous, single-call approval) ──────────────────────
 *
 * Unlike the plan's original draft (which proposed a persistent
 * "pending approval" row + a separate request step), this service
 * implements a SYNCHRONOUS approval flow:
 *
 *   1. Cashier enters a rate below min in the cart UI.
 *   2. The cart JS shows a SweetAlert2 modal asking for:
 *        - approver username
 *        - approver password (re-authentication)
 *        - reason (textarea, min 10 chars)
 *   3. The modal POSTs to /admin/sales/below-min-approvals with the
 *      above + product_id, requested_rate, min_rate, customer_id,
 *      branch_id, cart_id.
 *   4. BelowMinApprovalService::approve() re-authenticates the
 *      approver against the `web` guard, checks the role AT APPROVAL
 *      TIME (not request time — closes the privilege-escalation race
 *      where a manager's role is revoked between request and approval),
 *      validates the reason length, and inserts a `user_audit_log` row.
 *   5. The audit-log row's id is returned to the JS.
 *   6. The JS then calls the existing /admin/sales/cart/add endpoint
 *      with the line + `below_min_override_id` set. SalesCartService
 *      sees the override id and skips the below-min hard-throw.
 *   7. At finalize, SalesInvoiceService::finalizeFromCart() reads
 *      `below_min_override_id` from each cart line and writes it to
 *      `sales_invoice_items.below_min_override_id`. It also forces
 *      `price_classification = 'below_min'` for those lines.
 *
 * ── Why synchronous instead of async-with-pending-table ─────────────
 *
 * - No new DB table needed (the S5 migration already added the
 *   `below_min_override_id` column to sales_invoice_items).
 * - Mirrors the existing `credit_limit_override` pattern (in-flow
 *   approval at the moment of action, no separate pending state).
 * - The audit row is written BEFORE the cart line is added — so if
 *   the cart add fails (e.g. stock insufficient), the audit row is
 *   orphaned. This is acceptable: the audit row records the
 *   APPROVAL DECISION, not the sale. The cashier may reuse the
 *   approval for a retry. Orphaned rows are visible in the audit
 *   trail with `details.invoice_id = null` and can be cleaned up
 *   by a future retention job if needed.
 * - Re-authentication at approval time (not session-based) means
 *   the approver's role is checked fresh — a cashier whose session
 *   was hijacked cannot approve their own below-min lines without
 *   the admin's password.
 *
 * ── Audit row schema ────────────────────────────────────────────────
 *
 * `user_audit_log` columns (existing, see 06_payment_and_misc.sql):
 *   - user_id          → the APPROVER's user id (not the cashier's)
 *   - action           → 'below_min_override'
 *   - target_user_id   → the CASHIER's user id (who requested the override)
 *   - branch_id        → the branch context
 *   - details (jsonb)  → { product_id, requested_rate, min_rate, reason,
 *                          customer_id, cart_id, invoice_id (null until
 *                          finalize), sale_line_index }
 *   - ip_address       → request IP
 *   - user_agent       → request UA
 *   - created_at       → now()
 *
 * Note: user_audit_log is RANGE-partitioned by created_at and its PK
 * is (id, created_at). The id column is GENERATED BY DEFAULT AS
 * IDENTITY, so insertGetId() works (PG returns the sequence currval).
 * The S5 migration deliberately did NOT add a declarative FK from
 * sales_invoice_items.below_min_override_id to user_audit_log(id)
 * because of the partitioned-PK constraint — see S5 migration
 * docblock. Referential integrity is enforced here, at the application
 * layer: the audit row is inserted first, its id is captured, and
 * only then is it written to the cart line / sale item.
 *
 * @see \App\Services\Sales\SalesCartService::addItem()
 * @see \App\Services\Sales\SalesInvoiceService::finalizeFromCart()
 * @see \App\Services\Sales\SalesAuditLogger::belowMinOverride()
 * @see docs/IMPLEMENTATION_PLAN_FY_ISOLATION_AND_BRANCH_PNL.md Session 6
 */
class BelowMinApprovalService
{
    /**
     * Approve a below-min sale line.
     *
     * Re-authenticates the approver against the `web` guard using the
     * supplied username + password (NOT the session user — this is a
     * fresh credential check). Validates the approver's role is admin
     * or manager AT THIS MOMENT (closes the privilege-escalation race
     * where a manager's role is revoked between request and approval).
     *
     * @param array $data {
     *     approver_username: string,
     *     approver_password: string,
     *     product_id: int,
     *     product_name: string,
     *     requested_rate: float,
     *     min_rate: float,
     *     max_rate: float,
     *     default_rate: float,
     *     reason: string (min 10 chars),
     *     customer_id: int,
     *     branch_id: int,
     *     cart_id: int|null,
     *     sale_line_index: int|null,
     *     cashier_user_id: int|null (the requesting user, defaults to auth id)
     * }
     * @return array{ audit_log_id: int, approver_user_id: int }
     * @throws \InvalidArgumentException If reason < 10 chars or required fields missing.
     * @throws \RuntimeException If approver credentials invalid or role insufficient.
     */
    public function approve(array $data): array
    {
        $approverUsername = trim($data['approver_username'] ?? '');
        $approverPassword = $data['approver_password'] ?? '';
        $productId        = (int) ($data['product_id'] ?? 0);
        $requestedRate    = (float) ($data['requested_rate'] ?? 0);
        $minRate          = (float) ($data['min_rate'] ?? 0);
        $maxRate          = (float) ($data['max_rate'] ?? 0);
        $defaultRate      = (float) ($data['default_rate'] ?? 0);
        $reason           = trim($data['reason'] ?? '');
        $customerId       = (int) ($data['customer_id'] ?? 0);
        $branchId         = (int) ($data['branch_id'] ?? 0);
        $cartId           = $data['cart_id'] ?? null;
        $saleLineIndex    = $data['sale_line_index'] ?? null;
        $cashierUserId    = $data['cashier_user_id'] ?? auth()->id();

        // ── 1. Validate inputs ────────────────────────────────────
        if ($approverUsername === '' || $approverPassword === '') {
            throw new \InvalidArgumentException('Approver username and password are required.');
        }
        if ($productId <= 0) {
            throw new \InvalidArgumentException('product_id is required.');
        }
        if ($requestedRate <= 0 || $minRate <= 0) {
            throw new \InvalidArgumentException('requested_rate and min_rate must be positive.');
        }
        if ($requestedRate >= $minRate - 0.01) {
            throw new \InvalidArgumentException(
                "Rate {$requestedRate} is not below min {$minRate} — no override needed."
            );
        }
        if (strlen($reason) < 10) {
            throw new \InvalidArgumentException(
                'Override reason must be at least 10 characters.'
            );
        }

        // ── 2. Re-authenticate the approver ──────────────────────
        // Look up the user by username, verify the password against the
        // legacy `password_hash` column (User::getAuthPassword() returns
        // this). We do NOT use Auth::attempt() because that would log
        // the approver in, replacing the cashier's session. We just need
        // a one-shot credential check.
        $approver = User::where('username', $approverUsername)
            ->where('is_active', true)
            ->first();

        if (!$approver) {
            throw new \RuntimeException('Approver not found or inactive.');
        }

        $storedHash = $approver->getAuthPassword();
        if (empty($storedHash) || !Hash::check($approverPassword, $storedHash)) {
            // Slight delay to slow brute-force (best-effort, non-blocking).
            usleep(300000); // 300ms
            throw new \RuntimeException('Invalid approver credentials.');
        }

        // ── 3. Role check AT APPROVAL TIME ───────────────────────
        // This is the critical privilege-escalation defense. The plan's
        // acceptance test "try to approve with a user whose role was
        // changed from manager to cashier between request and approval
        // — should fail with a 403" is satisfied here: we read the
        // role from the FRESH user record, not from a cached request-time
        // snapshot.
        if (!$approver->isAdmin() && !$approver->hasRole('manager')) {
            throw new \RuntimeException(
                'Approver role is not sufficient. Only admin or manager can approve below-min sales.'
            );
        }

        // ── 4. Write the audit row ───────────────────────────────
        // Insert FIRST, capture the id, then return it to the caller.
        // The caller (controller) returns it to the JS, which then
        // passes it to /cart/add as `below_min_override_id`.
        //
        // Note: insertGetId on a partitioned table works in PG because
        // the `id` column is GENERATED BY DEFAULT AS IDENTITY — PG
        // returns the currval of the underlying sequence. The row lands
        // in the partition matching created_at (CURRENT_DATE).
        $details = [
            'action_type'      => 'below_min_sale_approval',
            'product_id'       => $productId,
            'product_name'     => $data['product_name'] ?? null,
            'requested_rate'   => round($requestedRate, 4),
            'min_rate'         => round($minRate, 4),
            'max_rate'         => round($maxRate, 4),
            'default_rate'     => round($defaultRate, 4),
            'reason'           => $reason,
            'customer_id'      => $customerId,
            'cart_id'          => $cartId,
            'sale_line_index'  => $saleLineIndex,
            // invoice_id is NULL at approval time — populated at finalize
            // by SalesInvoiceService when the sale line is written. We
            // don't update the audit row at finalize (would require a
            // second write); instead, the sale line's
            // below_min_override_id points back to this audit row, and
            // the audit row's details point forward to the cart (not
            // the invoice). This is sufficient for the audit trail.
            'invoice_id'       => null,
            'invoice_code'     => null,
            'cashier_user_id'  => $cashierUserId,
            'approver_role'    => $approver->getRole(),
        ];

        $request = request();
        $auditLogId = DB::table('user_audit_log')->insertGetId([
            'user_id'        => $approver->id,
            'action'         => 'below_min_override',
            'target_user_id' => $cashierUserId,
            'branch_id'      => $branchId,
            'details'        => json_encode($details, JSON_UNESCAPED_UNICODE),
            'ip_address'     => $request?->ip(),
            'user_agent'     => $request?->userAgent()
                ? mb_substr(preg_replace('/[\r\n\t]/', ' ', $request->userAgent()), 0, 255)
                : null,
            'created_at'     => now(),
        ]);

        // Dual-write to the audit log file (defense in depth — mirrors
        // UserAuditLogger::log() but inline because we need insertGetId
        // for the audit row id, and UserAuditLogger::log() does not
        // return it).
        try {
            $logEntry = json_encode([
                'timestamp'      => now()->toISOString(),
                'audit_log_id'   => $auditLogId,
                'user_id'        => $approver->id,
                'action'         => 'below_min_override',
                'target_user_id' => $cashierUserId,
                'branch_id'      => $branchId,
                'ip'             => $request?->ip(),
                'user_agent'     => $request?->userAgent(),
                'details'        => $details,
            ], JSON_UNESCAPED_UNICODE);
            file_put_contents(
                storage_path('logs/user_audit.log'),
                $logEntry . "\n",
                FILE_APPEND | LOCK_EX
            );
        } catch (\Throwable $e) {
            Log::error('BelowMinApprovalService: file write failed', [
                'audit_log_id' => $auditLogId,
                'error'        => $e->getMessage(),
            ]);
        }

        Log::info('Below-min override approved', [
            'audit_log_id'    => $auditLogId,
            'approver_id'     => $approver->id,
            'cashier_id'      => $cashierUserId,
            'product_id'      => $productId,
            'requested_rate'  => $requestedRate,
            'min_rate'        => $minRate,
            'branch_id'       => $branchId,
        ]);

        return [
            'audit_log_id'      => (int) $auditLogId,
            'approver_user_id'  => (int) $approver->id,
        ];
    }

    /**
     * Reject a pending below-min approval (remove the cart line).
     *
     * In the synchronous flow, "rejection" is just the JS not calling
     * /cart/add after the modal is dismissed. This method exists for
     * completeness — it's a no-op that logs the rejection for audit
     * purposes. The cart line was never added (the below-min rate was
     * blocked at /cart/add until an override id is supplied), so there
     * is nothing to remove.
     *
     * If a future async flow is added (pending approvals table), this
     * method would delete the pending row.
     *
     * @param int|null $cashierUserId
     * @param int|null $productId
     * @param float|null $requestedRate
     * @param float|null $minRate
     * @param string|null $reason  The approver's rejection reason (optional).
     */
    public function reject(
        ?int $cashierUserId = null,
        ?int $productId = null,
        ?float $requestedRate = null,
        ?float $minRate = null,
        ?string $reason = null
    ): void {
        Log::info('Below-min override rejected', [
            'cashier_id'     => $cashierUserId,
            'product_id'     => $productId,
            'requested_rate' => $requestedRate,
            'min_rate'       => $minRate,
            'reason'         => $reason,
        ]);
    }

    /**
     * List recent below-min approvals for a branch.
     *
     * Used by the GET /admin/sales/below-min-approvals endpoint. Returns
     * the last N below_min_override audit rows for the branch, with the
     * JSONB details decoded. Useful for an audit dashboard.
     *
     * @param int $branchId
     * @param int $limit
     * @return \Illuminate\Support\Collection
     */
    public function pendingForBranch(int $branchId, int $limit = 50)
    {
        return DB::table('user_audit_log')
            ->where('action', 'below_min_override')
            ->where('branch_id', $branchId)
            ->orderByDesc('id')
            ->limit($limit)
            ->get()
            ->map(function ($row) {
                $row->details = json_decode($row->details ?? '{}', true);
                return $row;
            });
    }

    /**
     * Verify that a below_min_override_id still points to a valid
     * audit row at finalize time.
     *
     * Called by SalesInvoiceService::finalizeFromCart() as a
     * defense-in-depth check before writing the sale line. The audit
     * row was inserted at approval time, so it should always exist —
     * but if a DBA manually deletes audit rows (rare, compliance
     * violation), we want to fail loudly rather than write a dangling
     * reference.
     *
     * @param int $auditLogId
     * @return bool
     */
    public function isValidOverride(int $auditLogId): bool
    {
        if ($auditLogId <= 0) {
            return false;
        }
        return DB::table('user_audit_log')
            ->where('id', $auditLogId)
            ->where('action', 'below_min_override')
            ->exists();
    }
}
