<?php

return [
    'show_warnings' => false,
    'orientation' => 'portrait',
    'paper' => 'a4',
    'definesecondary' => false,
    'default_font' => 'Noto Sans SC',
    'dpi' => 96,
    'enable_php' => false,
    'enable_javascript' => false,
    'enable_remote' => true,
    'font_cache' => storage_path('fonts/'),
    'font_dir' => storage_path('fonts/'),
    'images' => true,
    'is_unicode' => true,
    'is_font_subsetting' => true,
    'debug_png' => false,
    'debug_keep_temp' => false,
    'debug_css' => false,
    'debug_layout' => false,
    'debug_layout_lines' => false,
    'debug_layout_blocks' => false,
    'debug_layout_inline' => false,
    'debug_padding_box' => false,
    'cl' => [],
    'custom_font_dir' => storage_path('fonts/'),
    'custom_font_file' => storage_path('fonts/dompdf_font_family_cache.php'),
];
