<?php
/**
 * Role matrix for routes (controller/action => allowed roles).
 * Admin-tier users (admin + superadmin) always have full access via
 * RouteAccess::allows() (Auth::hasAdminRouteBypass()).
 *
 * Unlisted actions are allowed for any logged-in role (menu permissions
 * may still restrict operational users). Register sensitive reads/writes here.
 */
return [
    'UserController' => [
        'index'               => ['admin'],
        'create'              => ['admin'],
        'store'               => ['admin'],
        'edit'                => ['admin'],
        'update'              => ['admin'],
        'toggle'              => ['admin'],
        'delete'              => ['admin'],
        'restore'             => ['admin'],
        'unlock'              => ['admin'],
        'generate_reset_link' => ['admin'],
        'permission'          => ['admin'],
        'permission_json'     => ['admin'],
        'save_permissions'    => ['admin'],
        'audit'               => ['admin'],
        'security_audit'      => ['admin'],
        // Phase 0: 'admin_disable_two_factor' removed (2FA disabled).
    ],
    'EmployeeController' => [
        'index'     => ['admin'],
        'audit'     => ['admin'],
        'quickView' => ['admin'],
        'account'   => ['admin'],
        'create'    => ['admin'],
        'store'     => ['admin'],
        'edit'      => ['admin'],
        'update'    => ['admin'],
        'toggle'    => ['admin'],
        'delete'    => ['admin'],
        'restore'   => ['admin'],
    ],
    'InvestigationController' => [
        'settings'         => ['superadmin'],
        'save_activator'   => ['superadmin'],
        'remove_activator' => ['superadmin'],
        'scan'             => ['admin'],
    ],

    // Sales
    'SalesController' => [
        'today'                   => ['admin', 'manager', 'salesman', 'accountant'],
        'today_filter_summary'    => ['admin', 'manager', 'salesman', 'accountant'],
        'cancel_stale_drafts'     => ['admin', 'manager'],
        'datatable_invoices'      => ['admin', 'manager', 'salesman', 'accountant'],
        'guide'                   => ['admin', 'manager', 'salesman', 'accountant'],
        'go_live_checklist'       => ['admin', 'manager', 'accountant', 'warehouse_manager', 'salesman'],
        'audit'                   => ['admin', 'manager', 'accountant'],
        'search_customer'         => ['admin', 'manager', 'salesman'],
        'search_product'          => ['admin', 'manager', 'salesman'],
        'product_by_code'         => ['admin', 'manager', 'salesman'],
        'get_branch'              => ['admin', 'manager', 'salesman'],
        'product_stock_at_branch' => ['admin', 'manager', 'salesman'],
        'get_warehouse_stock'     => ['admin', 'manager', 'salesman'],
        'get_employees'           => ['admin', 'manager', 'salesman'],
        'customer_details'        => ['admin', 'manager', 'salesman'],
        'add_to_cart'             => ['admin', 'manager', 'salesman'],
        'load_cart'               => ['admin', 'manager', 'salesman'],
        'validate_cart'           => ['admin', 'manager', 'salesman'],
        'hydrate_edit_cart'       => ['admin', 'manager', 'salesman'],
        'list_draft_carts'        => ['admin', 'manager', 'salesman'],
        'clear_tab_cart'          => ['admin', 'manager', 'salesman'],
        'delete_tab_cart'         => ['admin', 'manager', 'salesman'],
        'delete_from_cart'        => ['admin', 'manager', 'salesman'],
        'update_cart_item'        => ['admin', 'manager', 'salesman'],
        'save_fcm_token'          => ['admin', 'manager', 'salesman'],
        'edit'                    => ['admin', 'manager', 'salesman'],
        'get_invoice_for_edit'    => ['admin', 'manager', 'salesman'],
        'receive_modal'           => ['admin', 'manager', 'salesman', 'accountant'],
        'print_receipt'           => ['admin', 'manager', 'salesman', 'accountant'],
        'invoice_copy'            => ['admin', 'manager', 'salesman', 'accountant'],
        'show'                    => ['admin', 'manager', 'accountant'],
        'create'                  => ['admin', 'manager', 'salesman'],
        'final_sales'             => ['admin', 'manager', 'salesman'],
        'update'                  => ['admin', 'manager', 'salesman'],
        'delete_invoice'          => ['admin', 'manager', 'salesman'],
        'save_payment'            => ['admin', 'manager', 'salesman', 'accountant'],
        'reverse_payment'         => ['admin', 'manager', 'accountant'],
        'reconcile'               => ['admin', 'manager', 'accountant'],
        'call_it_a_day'           => ['admin', 'manager', 'salesman'],
        'export'                  => ['admin', 'manager', 'salesman', 'accountant'],
    ],
    'SalesReturnController' => [
        'index'                       => ['admin', 'manager', 'salesman', 'accountant', 'warehouse_manager'],
        'return_filter_summary'       => ['admin', 'manager', 'salesman', 'accountant', 'warehouse_manager'],
        'datatable_returns'           => ['admin', 'manager', 'salesman', 'accountant', 'warehouse_manager'],
        'search_invoice'              => ['admin', 'manager', 'salesman'],
        'get_invoice_for_return'      => ['admin', 'manager', 'salesman'],
        'warehouse_stock_for_receive' => ['admin', 'manager', 'warehouse_manager'],
        'slip'                        => ['admin', 'manager', 'salesman', 'accountant', 'warehouse_manager'],
        'details'                     => ['admin', 'manager', 'accountant', 'warehouse_manager'],
        'audit'                       => ['admin', 'manager', 'accountant'],
        'export'                      => ['admin', 'manager', 'salesman', 'accountant'],
        'create'                      => ['admin', 'manager', 'salesman'],
        'store'                       => ['admin', 'manager', 'salesman'],
        'confirm'                     => ['admin', 'manager', 'warehouse_manager', 'accountant'],
        'confirm_store'               => ['admin', 'manager', 'warehouse_manager', 'accountant'],
        'reverse'                     => ['admin', 'manager', 'accountant'],
    ],
    'SalesAuditController' => [
        'checklist'           => ['admin', 'manager', 'accountant'],
        'run_checks'          => ['admin', 'manager', 'accountant'],
        'cancel_stale_drafts' => ['admin', 'manager'],
    ],
    'ChallanController' => [
        'index'                => ['admin', 'manager', 'warehouse_manager', 'dispatcher'],
        'details'              => ['admin', 'manager', 'accountant', 'warehouse_manager'],
        'prepare_godown'       => ['admin', 'manager', 'warehouse_manager', 'dispatcher'],
        'create_final_challan' => ['admin', 'manager', 'warehouse_manager', 'dispatcher'],
        'reverse_challan'      => ['admin', 'manager'],
        'export'               => ['admin', 'manager', 'warehouse_manager'],
    ],

    // Master data
    'CustomerController' => [
        'index'   => ['admin', 'manager', 'salesman', 'accountant'],
        'show'    => ['admin', 'manager', 'salesman', 'accountant'],
        'audit'   => ['admin', 'manager'],
        'create'  => ['admin', 'manager', 'salesman'],
        'store'   => ['admin', 'manager', 'salesman'],
        'edit'    => ['admin', 'manager', 'salesman'],
        'update'  => ['admin', 'manager', 'salesman'],
        'toggle'  => ['admin', 'manager'],
        'delete'  => ['admin'],
        'restore' => ['admin'],
    ],
    'SupplierController' => [
        'index'   => ['admin', 'manager', 'accountant', 'warehouse_manager'],
        'show'    => ['admin', 'manager', 'accountant', 'warehouse_manager'],
        'audit'   => ['admin', 'manager', 'accountant'],
        'create'  => ['admin', 'manager'],
        'store'   => ['admin', 'manager'],
        'edit'    => ['admin', 'manager'],
        'update'  => ['admin', 'manager'],
        'toggle'  => ['admin', 'manager'],
        'delete'  => ['admin'],
        'restore' => ['admin'],
    ],
    'BranchController' => [
        'index'  => ['admin', 'manager', 'warehouse_manager'],
        'show'   => ['admin', 'manager', 'warehouse_manager'],
        'audit'  => ['admin'],
        'create' => ['admin'],
        'store'  => ['admin'],
        'edit'   => ['admin'],
        'update' => ['admin'],
        'toggle' => ['admin'],
    ],
    'WarehouseController' => [
        'index'        => ['admin', 'manager', 'warehouse_manager'],
        'show'         => ['admin', 'manager', 'warehouse_manager'],
        'stock_search' => ['admin', 'manager', 'warehouse_manager'],
        'audit'        => ['admin'],
        'create'       => ['admin'],
        'store'        => ['admin'],
        'edit'         => ['admin'],
        'update'       => ['admin'],
        'toggle'       => ['admin'],
    ],
    'ProductController' => [
        'index'           => ['admin', 'manager', 'warehouse_manager'],
        'price_history'   => ['admin', 'manager', 'warehouse_manager'],
        'categories'      => ['admin', 'manager'],
        'groups'          => ['admin', 'manager'],
        'audit'           => ['admin'],
        'create'          => ['admin', 'manager'],
        'store'           => ['admin', 'manager'],
        'edit'            => ['admin', 'manager'],
        'update'          => ['admin', 'manager'],
        'add_price'       => ['admin', 'manager'],
        'categoryCreate'  => ['admin', 'manager'],
        'categoryStore'   => ['admin', 'manager'],
        'categoryEdit'    => ['admin', 'manager'],
        'categoryUpdate'  => ['admin', 'manager'],
        'groupCreate'     => ['admin', 'manager'],
        'groupStore'      => ['admin', 'manager'],
        'groupEdit'       => ['admin', 'manager'],
        'groupUpdate'     => ['admin', 'manager'],
        'delete'          => ['admin'],
        'restore'         => ['admin'],
        'bulkAction'      => ['admin'],
        'delete_price'    => ['admin'],
        'categoryDelete'  => ['admin'],
        'categoryRestore' => ['admin'],
        'groupDelete'     => ['admin'],
        'groupRestore'    => ['admin'],
    ],

    // Purchase
    'PurchaseOrderController' => [
        'index'           => ['admin', 'manager', 'warehouse_manager', 'accountant'],
        'Details'         => ['admin', 'manager', 'warehouse_manager', 'accountant'],
        'search_products' => ['admin', 'manager', 'warehouse_manager'],
        'export'          => ['admin', 'manager', 'accountant'],
        'audit'           => ['admin', 'manager', 'accountant'],
        'create'          => ['admin', 'manager', 'warehouse_manager'],
        'store'           => ['admin', 'manager', 'warehouse_manager'],
        'edit'            => ['admin', 'manager', 'warehouse_manager'],
        'update'          => ['admin', 'manager', 'warehouse_manager'],
        'delete'          => ['admin', 'manager'],
    ],
    'PurchaseReceiveController' => [
        'index'          => ['admin', 'manager', 'warehouse_manager', 'accountant'],
        'details'        => ['admin', 'manager', 'warehouse_manager', 'accountant'],
        'get_po_details' => ['admin', 'manager', 'warehouse_manager'],
        'export'         => ['admin', 'manager', 'accountant'],
        'audit'          => ['admin', 'manager', 'accountant'],
        'create'         => ['admin', 'manager', 'warehouse_manager'],
        'store'          => ['admin', 'manager', 'warehouse_manager'],
        'cancel'         => ['admin', 'manager'],
    ],
    'PurchaseReturnController' => [
        'index'                  => ['admin', 'manager', 'warehouse_manager', 'accountant'],
        'return_filter_summary'  => ['admin', 'manager', 'warehouse_manager', 'accountant'],
        'search_receive'         => ['admin', 'manager', 'warehouse_manager'],
        'get_receive_for_return' => ['admin', 'manager', 'warehouse_manager'],
        'slip'                   => ['admin', 'manager', 'warehouse_manager', 'accountant'],
        'details'                => ['admin', 'manager', 'warehouse_manager', 'accountant'],
        'export'                 => ['admin', 'manager', 'accountant'],
        'audit'                  => ['admin', 'manager', 'accountant'],
        'create'                 => ['admin', 'manager', 'warehouse_manager'],
        'store'                  => ['admin', 'manager', 'warehouse_manager'],
        'reverse'                => ['admin', 'manager', 'accountant'],
    ],
    'PurchaseAuditController' => [
        'index'      => ['admin', 'manager', 'accountant'],
        'checklist'  => ['admin', 'manager', 'accountant'],
        'run_checks' => ['admin', 'manager', 'accountant'],
    ],

    // Inventory / warehouse ops
    'DamageController' => [
        'index'                   => ['admin', 'manager', 'warehouse_manager'],
        'details'                 => ['admin', 'manager', 'warehouse_manager'],
        'getBranchWarehouses'     => ['admin', 'manager', 'warehouse_manager'],
        'getProducts'             => ['admin', 'manager', 'warehouse_manager'],
        'getProductStockAndPrice' => ['admin', 'manager', 'warehouse_manager'],
        'export'                  => ['admin', 'manager', 'warehouse_manager'],
        'create'                  => ['admin', 'manager', 'warehouse_manager'],
        'store'                   => ['admin', 'manager', 'warehouse_manager'],
        'reverse'                 => ['admin', 'manager'],
    ],
    'StockAdjustmentController' => [
        'index'           => ['admin', 'manager', 'warehouse_manager'],
        'details'         => ['admin', 'manager', 'warehouse_manager'],
        'getProductPrice' => ['admin', 'manager', 'warehouse_manager'],
        'checklist'       => ['admin', 'manager', 'accountant'],
        'run_checks'      => ['admin', 'manager', 'accountant'],
        'export'          => ['admin', 'manager', 'warehouse_manager'],
        'create'          => ['admin', 'manager', 'warehouse_manager'],
        'store'           => ['admin', 'manager', 'warehouse_manager'],
        'reverse'         => ['admin', 'manager'],
    ],
    'StockTakeController' => [
        'index'                => ['admin', 'manager', 'warehouse_manager', 'accountant'],
        'details'              => ['admin', 'manager', 'warehouse_manager', 'accountant'],
        'checklist'            => ['admin', 'manager', 'accountant'],
        'run_checks'           => ['admin', 'manager', 'accountant'],
        'weekly'               => ['admin', 'manager', 'warehouse_manager'],
        'exportWeekly'         => ['admin', 'manager', 'warehouse_manager'],
        'variance'             => ['admin', 'manager', 'warehouse_manager', 'accountant'],
        'getSessionsList'      => ['admin', 'manager', 'warehouse_manager'],
        'getVarianceReport'    => ['admin', 'manager', 'warehouse_manager', 'accountant'],
        'exportVarianceReport' => ['admin', 'manager', 'warehouse_manager', 'accountant'],
        'WarehousesByBranch'   => ['admin', 'manager', 'warehouse_manager'],
        'count'                => ['admin', 'manager', 'warehouse_manager'],
        'export'               => ['admin', 'manager', 'warehouse_manager'],
        'create'               => ['admin', 'manager', 'warehouse_manager'],
        'store'                => ['admin', 'manager', 'warehouse_manager'],
        'saveCount'            => ['admin', 'manager', 'warehouse_manager'],
        'post'                 => ['admin', 'manager', 'warehouse_manager'],
        'delete'               => ['admin', 'manager'],
        'reverse'              => ['admin', 'manager'],
    ],
    'WarehouseTransferController' => [
        'index'                   => ['admin', 'manager', 'warehouse_manager', 'dispatcher'],
        'details'                 => ['admin', 'manager', 'warehouse_manager', 'dispatcher'],
        'getWarehouses'           => ['admin', 'manager', 'warehouse_manager', 'dispatcher'],
        'getWarehousesByBranch'   => ['admin', 'manager', 'warehouse_manager', 'dispatcher'],
        'getProducts'             => ['admin', 'manager', 'warehouse_manager', 'dispatcher'],
        'getProductStockAndPrice' => ['admin', 'manager', 'warehouse_manager', 'dispatcher'],
        'checklist'               => ['admin', 'manager', 'accountant'],
        'run_checks'              => ['admin', 'manager', 'accountant'],
        'export'                  => ['admin', 'manager', 'warehouse_manager'],
        'create'                  => ['admin', 'manager', 'warehouse_manager', 'dispatcher'],
        'store'                   => ['admin', 'manager', 'warehouse_manager', 'dispatcher'],
        'reverse'                 => ['admin', 'manager'],
    ],
    'BranchDemandController' => [
        'index'                 => ['admin', 'manager', 'warehouse_manager'],
        'pending'               => ['admin', 'manager', 'warehouse_manager'],
        'details'               => ['admin', 'manager', 'warehouse_manager', 'accountant'],
        'weekly'                => ['admin', 'manager', 'warehouse_manager'],
        'checklist'             => ['admin', 'manager', 'accountant'],
        'run_checks'            => ['admin', 'manager', 'accountant'],
        'getBranches'           => ['admin', 'manager', 'warehouse_manager'],
        'getProducts'           => ['admin', 'manager', 'warehouse_manager'],
        'getWarehousesByBranch' => ['admin', 'manager', 'warehouse_manager'],
        'export'                => ['admin', 'manager', 'warehouse_manager'],
        'create'                => ['admin', 'manager', 'warehouse_manager'],
        'store'                 => ['admin', 'manager', 'warehouse_manager'],
        'send'                  => ['admin', 'manager', 'warehouse_manager'],
        'delete'                => ['admin', 'manager'],
        'reverse'               => ['admin', 'manager'],
    ],

    // Accounting / finance
    'BankController' => [
        'index'   => ['admin', 'manager', 'accountant'],
        'show'    => ['admin', 'manager', 'accountant'],
        'audit'   => ['admin', 'manager', 'accountant'],
        'create'  => ['admin', 'manager', 'accountant'],
        'store'   => ['admin', 'manager', 'accountant'],
        'edit'    => ['admin', 'manager', 'accountant'],
        'update'  => ['admin', 'manager', 'accountant'],
        'toggle'  => ['admin', 'manager'],
        'delete'  => ['admin'],
        'restore' => ['admin'],
    ],
    'AccountingController' => [
        'index' => ['admin', 'manager', 'accountant'],
        'guide' => ['admin', 'manager', 'accountant'],
    ],
    'LedgerController' => [
        'index'  => ['admin', 'manager', 'accountant'],
        'show'   => ['admin', 'manager', 'accountant'],
        'audit'  => ['admin', 'manager', 'accountant'],
        'create' => ['admin', 'accountant'],
        'store'  => ['admin', 'accountant'],
        'edit'   => ['admin', 'accountant'],
        'update' => ['admin', 'accountant'],
        'toggle' => ['admin', 'manager'],
        'delete' => ['admin'],
    ],
    'ReconciliationController' => [
        'index' => ['admin', 'manager', 'accountant'],
    ],
    'ManualJournalController' => [
        'index'   => ['admin', 'accountant'],
        'create'  => ['admin', 'accountant'],
        'store'   => ['admin', 'accountant'],
        'details' => ['admin', 'accountant'],
        'reverse' => ['admin', 'accountant'],
        'audit'   => ['admin', 'accountant'],
    ],
    'AccountingPeriodController' => [
        'index'               => ['admin'],
        'close'               => ['admin'],
        'reopen'              => ['superadmin'],
        'year_end'            => ['admin', 'accountant'],
        'run_year_end_checks' => ['admin', 'accountant'],
        'export_year_tb'      => ['admin', 'accountant'],
        'export_year_gl'      => ['admin', 'accountant'],
    ],
    'PaymentController' => [
        'receive' => ['admin', 'manager', 'salesman', 'accountant'],
        'store'   => ['admin', 'manager', 'salesman', 'accountant'],
    ],
    'MoneyTransferController' => [
        'index'              => ['admin', 'manager', 'accountant'],
        'preview_settlement' => ['admin', 'manager', 'accountant'],
        'details'            => ['admin', 'manager', 'accountant'],
        'slip'               => ['admin', 'manager', 'accountant'],
        'audit'              => ['admin', 'manager', 'accountant'],
        'create'             => ['admin', 'manager', 'accountant'],
        'store'              => ['admin', 'manager', 'accountant'],
        'reverse'            => ['admin', 'manager', 'accountant'],
    ],
    'OtherExpenseController' => [
        'index'   => ['admin', 'manager', 'accountant'],
        'details' => ['admin', 'manager', 'accountant'],
        'slip'    => ['admin', 'manager', 'accountant'],
        'audit'   => ['admin', 'manager', 'accountant'],
        'create'  => ['admin', 'manager', 'accountant'],
        'store'   => ['admin', 'manager', 'accountant'],
        'reverse' => ['admin', 'manager', 'accountant'],
    ],
    'OtherIncomeController' => [
        'index'   => ['admin', 'manager', 'accountant'],
        'details' => ['admin', 'manager', 'accountant'],
        'slip'    => ['admin', 'manager', 'accountant'],
        'audit'   => ['admin', 'manager', 'accountant'],
        'create'  => ['admin', 'manager', 'accountant'],
        'store'   => ['admin', 'manager', 'accountant'],
        'reverse' => ['admin', 'manager', 'accountant'],
    ],
    // Entity transactions — role matrix (Phase 3D):
    // admin / manager / accountant: full access on supplier + employee modules.
    // Customer: salesman may view/create/slip; reverse + audit require admin/manager/accountant.
    'EmployeeTransactionController' => [
        'index'   => ['admin', 'manager', 'accountant'],
        'get_due' => ['admin', 'manager', 'accountant'],
        'slip'    => ['admin', 'manager', 'accountant'],
        'details' => ['admin', 'manager', 'accountant'],
        'create'  => ['admin', 'manager', 'accountant'],
        'store'   => ['admin', 'manager', 'accountant'],
        'reverse' => ['admin', 'manager', 'accountant'],
        'audit'   => ['admin', 'manager', 'accountant'],
    ],
    'CustomerTransactionController' => [
        'index'           => ['admin', 'manager', 'accountant', 'salesman'],
        'search_customer' => ['admin', 'manager', 'accountant', 'salesman'],
        'get_due'         => ['admin', 'manager', 'accountant', 'salesman'],
        'slip'    => ['admin', 'manager', 'accountant', 'salesman'],
        'details' => ['admin', 'manager', 'accountant', 'salesman'],
        'create'  => ['admin', 'manager', 'accountant', 'salesman'],
        'store'   => ['admin', 'manager', 'accountant', 'salesman'],
        'reverse' => ['admin', 'manager', 'accountant'],
        'audit'   => ['admin', 'manager', 'accountant'],
    ],
    'SupplierTransactionController' => [
        'index'           => ['admin', 'manager', 'accountant'],
        'search_supplier' => ['admin', 'manager', 'accountant'],
        'get_due'         => ['admin', 'manager', 'accountant'],
        'slip'    => ['admin', 'manager', 'accountant'],
        'details' => ['admin', 'manager', 'accountant'],
        'create'  => ['admin', 'manager', 'accountant'],
        'store'   => ['admin', 'manager', 'accountant'],
        'reverse' => ['admin', 'manager', 'accountant'],
        'audit'   => ['admin', 'manager', 'accountant'],
    ],

    // Reports
    'ReportController' => [
        'index'                      => ['admin', 'manager', 'accountant', 'warehouse_manager', 'salesman'],
        'ProductStockAnalysis'       => ['admin', 'manager', 'warehouse_manager', 'accountant'],
        'getWarehousesByBranches'    => ['admin', 'manager', 'warehouse_manager', 'accountant'],
        'SupplierWisePurchase'       => ['admin', 'manager', 'accountant'],
        'BranchWiseLedger'           => ['admin', 'manager', 'accountant'],
        'DailyCashBook'              => ['admin', 'manager', 'accountant'],
        'TrialBalance'               => ['admin', 'manager', 'accountant'],
        'ProfitAndLoss'              => ['admin', 'manager', 'accountant'],
        'CashFlow'                   => ['admin', 'manager', 'accountant'],
        'BalanceSheet'               => ['admin', 'manager', 'accountant'],
        'GeneralLedger'              => ['admin', 'manager', 'accountant'],
        'JournalEntries'             => ['admin', 'manager', 'accountant'],
        'PayableAging'               => ['admin', 'manager', 'accountant'],
        'ReceivableAging'            => ['admin', 'manager', 'accountant'],
        'ProductMovement'            => ['admin', 'manager', 'warehouse_manager', 'accountant'],
        'ProductMovementExplanation' => ['admin', 'manager', 'warehouse_manager', 'accountant'],
        'revenueOverview'            => ['admin', 'manager', 'salesman', 'accountant'],
        'grossMargin'                => ['admin', 'manager', 'accountant'],
        'salesFunnelPipeline'        => ['admin', 'manager', 'salesman', 'accountant'],
        'customerPerformance'        => ['admin', 'manager', 'salesman', 'accountant'],
    ],
];
