<?php

namespace App\Policies;

use App\Models\CommissionEntry;
use App\Models\User;

/**
 * Commission Entry Policy — Task 37 (Sales cluster — commission tracking).
 *
 * Centralizes the role rules for the commission-entry module. Each method
 * returns true for the EXACT set of roles the corresponding route
 * middleware already allows — `$this->authorize()` in the controller is
 * defense-in-depth (the middleware gated first; the policy re-confirms
 * the same rule). This does NOT change behavior; it makes the rules
 * testable + discoverable in one place.
 *
 * The Commission module is currently API-ONLY (no web UI — gap G12 in
 * `commission.md` documents this). Routes live in `routes/api.php`
 * (L249-280). Commission entries are AUTO-GENERATED by
 * `CommissionService::calculateForInvoice` when a customer payment is
 * allocated, and AUTO-REVERSED by `CommissionService::reverseOnReturn`
 * when a sales return is confirmed. The only user-initiated actions on
 * entries are READ (listEntries, salesmanSummary, branchSummary) and
 * CONFIRM-PERIOD (admin only).
 *
 * Commission entries carry `branch_id` + `salesman_id` (the entry
 * belongs to the salesman's branch). BranchScope is applied to the
 * model (non-admin users see only their branch's entries). This policy
 * is the role-only layer; per-row policy (e.g. "salesman can only see
 * their own entries") is NOT enforced here — it would require a
 * salesman-aware filter in the controller (future enhancement, gap G11).
 *
 * NOTE: the API routes for entries/summaries (listEntries,
 * salesmanSummary, branchSummary) currently have NO `api.auth:admin`
 * middleware — only `api.rate:60` (gap G10 in `commission.md`). The
 * INTENDED role matrix per the route-group comment block (api.php L252:
 * "Admin/manager endpoints for commission rule management and reporting")
 * is admin + manager. This policy mirrors that INTENDED matrix as the
 * defense-in-depth layer (gap G11 is closed by creating this class;
 * gap G10 remains open for the API middleware to be tightened).
 *
 * Role reference (User::getRole() reads from Employee):
 *   admin, manager              — full read + confirm access.
 *   accountant                  — read access (finance review).
 *   salesman, warehouse_manager, dispatcher, hr, user, other — NO direct
 *       access (salesman sees their own entries via the salesmanSummary
 *       endpoint, which the controller filters by `salesman_id = auth()->id()`
 *       — that filter is the per-row gate, NOT this policy).
 *   superadmin → bypasses everything via EnsureRole middleware.
 *
 * @see routes/api.php  sales/commission route group (L249-280)
 * @see AI_CONTEXT/sales/commission.md §11 G11 (gap closed by this class)
 */
class CommissionEntryPolicy
{
    /**
     * View commission entries (listEntries, salesmanSummary,
     * branchSummary). Routes: api.sales.commission.{entries,
     * salesman-summary,branch-summary} — currently `api.rate:60` only
     * (no api.auth — gap G10); INTENDED matrix per the route-group
     * comment is admin + manager. This policy mirrors the intent:
     * admin, manager, accountant (accountant added for finance review).
     *
     * No branch.isolation (BranchScope on the model filters non-admin
     * reads to their session branch).
     */
    public function view(User $user, ?CommissionEntry $entry = null): bool
    {
        return $user->hasRole('admin', 'manager', 'accountant');
    }

    /**
     * Confirm a commission period (lock entries + post GL accrual).
     * Route: api.sales.commission.confirm-period — api.auth:admin only.
     * DESTRUCTIVE (GL write + locks entries from further modification).
     */
    public function confirm(User $user): bool
    {
        return $user->hasRole('admin');
    }

    /**
     * Create alias — entries are auto-generated by
     * CommissionService::calculateForInvoice (no user-initiated create).
     * Exposed here for signature completeness; mirrors the same role
     * matrix as the auto-calculation caller (sales-invoice finalize:
     * salesman, manager, admin — but the policy is for the ENTRY model,
     * not the invoice, so this method is rarely invoked directly).
     */
    public function create(User $user): bool
    {
        return $user->hasRole('admin', 'manager');
    }

    /**
     * Reverse an entry (DESTRUCTIVE — reverses GL + marks is_reversed).
     * Auto-triggered by `CommissionService::reverseOnReturn` when a
     * sales return is confirmed (sales-return gate: warehouse_manager,
     * accountant, manager, admin). For manual entry reversal (rare),
     * admin/manager only. This policy method mirrors the manual path
     * (the auto path goes through the sales-return policy).
     */
    public function delete(User $user, CommissionEntry $entry): bool
    {
        return $user->hasRole('admin', 'manager');
    }

    /**
     * Reverse alias — same gate as delete(), exposed under the
     * conventional reverse() name matching the service method.
     */
    public function reverse(User $user, CommissionEntry $entry): bool
    {
        return $this->delete($user, $entry);
    }
}
