<?php

namespace App\Policies;

use App\Models\EliminationEntry;
use App\Models\User;

/**
 * Elimination Entry Policy — Phase 8 (Finance cluster — consolidation output).
 *
 * Centralizes the role rules for the consolidation elimination-entry
 * module. Each method returns true for the EXACT set of roles the
 * corresponding route middleware already allows — `$this->authorize()`
 * in the controller is defense-in-depth (the middleware gated first;
 * the policy re-confirms the same rule). This does NOT change behavior;
 * it makes the rules testable + discoverable in one place.
 *
 * Elimination entries are GENERATED by posting a ConsolidationRun (they
 * are the auto-calculated Dr/Cr rows that eliminate intercompany
 * balances). They have no dedicated routes — they are read through
 * ConsolidationRun views (show, consolidated-TB/BS/PnL, reconciliation)
 * and destroyed when a run is reversed. Their access matrix therefore
 * MIRRORS ConsolidationRun's matrix exactly: `role:accountant,manager,admin`
 * via the prefix-group middleware (routes/web.php L1733).
 *
 * Elimination entries reference from_branch_id + to_branch_id (the
 * eliminated intercompany pair) but are GROUP-LEVEL output — NOT
 * subject to `branch.isolation` or `BranchScope`.
 *
 * Role reference (User::getRole() reads from Employee):
 *   admin, manager, accountant — have access.
 *   superadmin → bypasses everything via EnsureRole middleware.
 *
 * @see routes/web.php  admin/consolidation route group (L1733-1766)
 * @see \App\Policies\ConsolidationRunPolicy  (parent-run policy — same matrix)
 */
class EliminationEntryPolicy
{
    /**
     * View elimination entries (read through ConsolidationRun views —
     * show, consolidated-TB/BS/PnL, intercompany reconciliation).
     * Mirrors ConsolidationRun view: role:accountant,manager,admin.
     */
    public function view(User $user, ?EliminationEntry $entry = null): bool
    {
        return $user->hasRole('accountant', 'manager', 'admin');
    }

    /**
     * Create elimination entries (auto-generated by posting a run —
     * admin.consolidation.post). Mirrors ConsolidationRun post.
     */
    public function create(User $user): bool
    {
        return $user->hasRole('accountant', 'manager', 'admin');
    }

    /**
     * Delete elimination entries (auto-deleted by reversing a run —
     * admin.consolidation.reverse). Mirrors ConsolidationRun reverse.
     */
    public function delete(User $user, EliminationEntry $entry): bool
    {
        return $user->hasRole('accountant', 'manager', 'admin');
    }
}
