<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

/**
 * Phase 10.1 — Phase 6.3: Partition journal_entries by entry_date.
 *
 * This is the most critical phase of the entire partitioning project.
 * journal_entries is the crown-jewel table of the accounting system —
 * every business module writes to it via JournalPostingService. Getting
 * this wrong breaks the entire GL.
 *
 * Pre-requisites (must all be true before this migration runs):
 *   - Phase 6.2 (migration 2026_08_22_000001) has added entry_date to journal_lines.
 *   - Phase 0.3 (migration 2026_08_15_000003) has converted 15 child FKs
 *     to journal_entries(id) into trigger-based FKs. PostgreSQL REJECTS
 *     partitioning a table that is referenced by declarative FKs from
 *     non-partitioned children (or partitioned children whose partition
 *     key does not include the FK columns).
 *   - Phase 5 (migration 2026_08_20_000001) has partitioned the 6
 *     multi-FK transaction header tables. Their FKs to journal_entries
 *     were made DEFERRABLE but NOT YET trigger-based — Phase 6.6
 *     (migration 000004) will convert them.
 *
 * IMPORTANT: At this point in the migration sequence, journal_lines is
 * still NON-partitioned (Phase 6.4 hasn't run yet). The declarative FK
 * journal_lines.journal_entry_id REFERENCES journal_entries(id) ON DELETE
 * CASCADE will BLOCK partitioning journal_entries — PostgreSQL requires
 * the child's FK column list to include the parent's partition key.
 *
 * SOLUTION: This migration FIRST drops the journal_lines → journal_entries
 * declarative FK (it was made DEFERRABLE in Phase 0.5 but is still
 * declarative). Phase 6.6 (migration 000004) will re-create it as a
 * trigger-based FK AFTER journal_lines itself is partitioned.
 *
 * The trg_journal_balanced trigger on journal_lines (which JOINs
 * journal_entries) keeps working through the rename because it uses
 * the table name at runtime, but it must be dropped+recreated as well
 * because the OLD journal_lines table is renamed in Phase 6.4 — wait,
 * no. journal_lines is NOT renamed in THIS migration. Only
 * journal_entries is renamed here. The trg_journal_balanced trigger
 * on journal_lines references journal_entries — which is being
 * renamed. So:
 *
 *   - Before rename: trg_journal_balanced is on journal_lines, joins journal_entries.
 *   - After rename:  journal_entries now refers to the NEW partitioned
 *                    parent. trg_journal_balanced still works — it
 *                    queries `journal_entries WHERE id = ...` which
 *                    hits the new partitioned parent. PostgreSQL
 *                    transparently routes the query to the right
 *                    partition(s).
 *
 * So we do NOT need to drop trg_journal_balanced here. We only need to
 * drop the triggers ON journal_entries (the table being renamed):
 *   - trg_notify_journal_entries      (LISTEN/NOTIFY)
 *   - trg_audit_journal_entries       (financial audit)
 *   - Any declarative triggers on journal_entries get auto-dropped
 *     when the table is renamed (they remain attached to the renamed
 *     table — but we DROP the renamed table at the end anyway).
 *
 * Schema source: laravel/database/sql/02_accounting.sql lines 31-49 +
 *   migration 2025_01_20_000001_add_partial_indexes_business_queries.php line 110 +
 *   migration 2025_01_20_000002_add_covering_indexes_high_freq_queries.php lines 60-72 +
 *   sql/07_views_triggers_constraints.sql lines 125, 542-548.
 *
 * DESIGN NOTES
 * ------------
 * - PK(id) → PK(id, entry_date) for partitioned parent (PostgreSQL requirement).
 * - GENERATED ALWAYS → GENERATED BY DEFAULT for OVERRIDING SYSTEM VALUE data copy.
 * - UNIQUE(entry_no) → UNIQUE(entry_no, entry_date) — PostgreSQL requires
 *   the partition key in every UNIQUE constraint on a partitioned table.
 * - journal_entries has NO deleted_at column (not soft-deleted). Confirmed
 *   by reading 02_accounting.sql lines 31-49.
 * - journal_entries has RLS (single-branch policy: branch_id = app.branch_id).
 *   Confirmed by reading 07_views_triggers_constraints.sql lines 542-548.
 * - journal_entries has NO updated_at trigger (only customer_payments etc.
 *   in Phase 5 had one). The updated_at column is set by application code.
 *   Confirmed by grepping migrations for "CREATE TRIGGER.*journal_entries"
 *   — zero matches (only the audit + notify triggers exist).
 *
 * IDEMPOTENT: early-returns if journal_entries is already partitioned.
 *
 * ⚠️  Run during a maintenance window — locks the table during the data copy phase.
 */
return new class extends Migration
{
    private ?bool $hasPgPartman = null;

    // ═══════════════════════════════════════════════════════════════
    //  Helpers (copied verbatim from the Phase 5 migration pattern)
    // ═══════════════════════════════════════════════════════════════

    private function hasPgPartman(): bool
    {
        if ($this->hasPgPartman !== null) {
            return $this->hasPgPartman;
        }
        $row = DB::selectOne("
            SELECT EXISTS (
                SELECT 1 FROM pg_available_extensions WHERE name = 'pg_partman'
            ) AS installed
        ");
        $this->hasPgPartman = (bool) ($row->installed ?? false);
        if (! $this->hasPgPartman) {
            logger()->warning('pg_partman is not installed. Automatic partition maintenance is disabled.');
        }
        return $this->hasPgPartman;
    }

    private function isAlreadyPartitioned(string $tableName): bool
    {
        $row = DB::selectOne("
            SELECT 1
            FROM pg_partitioned_table pt
            JOIN pg_class c ON c.oid = pt.partrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relname = ? AND n.nspname = current_schema()
            LIMIT 1
        ", [$tableName]);
        return $row !== null;
    }

    private function relationExists(string $name): bool
    {
        $row = DB::selectOne("
            SELECT 1
            FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relname = ? AND n.nspname = current_schema()
            LIMIT 1
        ", [$name]);
        return $row !== null;
    }

    /**
     * Create 12 monthly partitions for the given year + a _default partition.
     */
    private function createMonthlyPartitions(string $parent, string $year): void
    {
        for ($m = 1; $m <= 12; $m++) {
            $from = sprintf('%s-%02d-01', $year, $m);
            $to   = $m < 12
                ? sprintf('%s-%02d-01', $year, $m + 1)
                : sprintf('%d-01-01', (int) $year + 1);
            $name = sprintf('%s_%s_%02d', $parent, $year, $m);

            if (! $this->relationExists($name)) {
                DB::statement(
                    "CREATE TABLE {$name} PARTITION OF {$parent}
                     FOR VALUES FROM ('{$from}') TO ('{$to}')"
                );
            }
        }

        $defaultName = "{$parent}_default";
        if (! $this->relationExists($defaultName)) {
            DB::statement(
                "CREATE TABLE {$defaultName} PARTITION OF {$parent} DEFAULT"
            );
        }
    }

    /**
     * Create monthly partitions for a partial year (e.g., Jan-Jun 2027).
     * Does NOT create a _default partition (the caller must have created one
     * already, or call createMonthlyPartitions() first for the full year).
     */
    private function createMonthlyPartitionsRange(string $parent, string $year, int $fromMonth, int $toMonth): void
    {
        for ($m = $fromMonth; $m <= $toMonth; $m++) {
            $from = sprintf('%s-%02d-01', $year, $m);
            $to   = $m < 12
                ? sprintf('%s-%02d-01', $year, $m + 1)
                : sprintf('%d-01-01', (int) $year + 1);
            $name = sprintf('%s_%s_%02d', $parent, $year, $m);

            if (! $this->relationExists($name)) {
                DB::statement(
                    "CREATE TABLE {$name} PARTITION OF {$parent}
                     FOR VALUES FROM ('{$from}') TO ('{$to}')"
                );
            }
        }
    }

    private function createPreYearPartition(string $parent, string $preYear, string $startYear): void
    {
        $name = "{$parent}_{$preYear}";
        if (! $this->relationExists($name)) {
            DB::statement(
                "CREATE TABLE {$name} PARTITION OF {$parent}
                 FOR VALUES FROM ('2020-01-01') TO ('{$startYear}-01-01')"
            );
        }
    }

    private function registerPartman(string $parent, string $control, string $startPartition): void
    {
        if (! $this->hasPgPartman()) {
            return;
        }
        try {
            DB::statement(<<<SQL
                SELECT partman.create_parent(
                    p_parent_table    := 'public.{$parent}',
                    p_control         := '{$control}',
                    p_type            := 'range',
                    p_interval        := '1 month',
                    p_premake         := 6,
                    p_start_partition := '{$startPartition}'
                )
            SQL);
        } catch (\Throwable $e) {
            // Already registered with pg_partman — safe to ignore.
        }
    }

    private function fixSequence(string $table): void
    {
        DB::statement(<<<SQL
            SELECT setval(
                pg_get_serial_sequence('{$table}', 'id'),
                GREATEST(COALESCE((SELECT MAX(id) FROM {$table}), 0), 1)
            )
        SQL);
    }

    private function dropRlsPolicies(string $tableName): void
    {
        $policies = DB::select("
            SELECT polname
            FROM pg_policy p
            JOIN pg_class c ON c.oid = p.polrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relname = ? AND n.nspname = current_schema()
        ", [$tableName]);

        foreach ($policies as $policy) {
            DB::statement("DROP POLICY IF EXISTS {$policy->polname} ON {$tableName}");
        }
    }

    /**
     * Drop ALL declarative FK constraints that reference $parentTable.
     * Used BEFORE renaming/partitioning a parent — PostgreSQL blocks
     * DROP TABLE on a table that has inbound declarative FKs (RESTRICT
     * is the default). The trigger-based replacements are created in
     * migration 000004 (Phase 6.6).
     *
     * Returns the list of (child_table, constraint_name, fk_column, deltype)
     * that were dropped, so the caller can log them.
     *
     * @return list<array{child: string, conname: string, col: string, deltype: string}>
     */
    private function dropAllDeclarativeFksToParent(string $parentTable): array
    {
        // Find all FK constraints referencing $parentTable.
        // confdeltype values: 'a' = NO ACTION, 'r' = RESTRICT,
        //                    'c' = CASCADE, 'n' = SET NULL, 'd' = SET DEFAULT
        $fks = DB::select(<<<SQL
            SELECT
                child.relname  AS child_table,
                c.conname      AS conname,
                a.attname      AS col,
                c.confdeltype  AS deltype
            FROM pg_constraint c
            JOIN pg_class child       ON child.oid  = c.conrelid
            JOIN pg_namespace childns ON childns.oid = child.relnamespace
            JOIN pg_class parent      ON parent.oid = c.confrelid
            JOIN pg_namespace parentns ON parentns.oid = parent.relnamespace
            JOIN pg_attribute a ON a.attrelid = child.oid AND a.attnum = ANY(c.conkey)
            WHERE parent.relname = ?
              AND parentns.nspname = 'public'
              AND childns.nspname = 'public'
              AND c.contype = 'f'
            ORDER BY child.relname, a.attname
        SQL, [$parentTable]);

        $dropped = [];
        foreach ($fks as $fk) {
            DB::statement(
                "ALTER TABLE {$fk->child_table} DROP CONSTRAINT IF EXISTS {$fk->conname}"
            );
            $dropped[] = [
                'child'    => $fk->child_table,
                'conname'  => $fk->conname,
                'col'      => $fk->col,
                'deltype'  => $fk->deltype,
            ];
            Log::info("Phase 6.3: Dropped declarative FK {$fk->conname} on {$fk->child_table}.{$fk->col} → {$parentTable}(id) [deltype={$fk->deltype}] — will be re-created as trigger-based in migration 000004.");
        }
        return $dropped;
    }

    private function dropIndexesExceptPK(string $tableName): void
    {
        // ── First, drop UNIQUE / EXCLUDE constraints ──
        // These constraints own a backing index that CANNOT be dropped directly
        // via DROP INDEX — PostgreSQL raises SQLSTATE 2BP01 ("cannot drop index
        // ... because constraint ... requires it"). We must DROP CONSTRAINT
        // instead; the backing index is removed automatically. PK constraints
        // (contype='p') are preserved — the old table (renamed later) carries
        // its PK until it is dropped wholesale at the end of partitioning.
        $constraints = DB::select("
            SELECT c.conname
            FROM pg_constraint c
            JOIN pg_class cl ON cl.oid = c.conrelid
            JOIN pg_namespace n ON n.oid = cl.relnamespace
            WHERE cl.relname = ?
              AND n.nspname = current_schema()
              AND c.contype IN ('u', 'x')
        ", [$tableName]);

        foreach ($constraints as $c) {
            DB::statement("ALTER TABLE {$tableName} DROP CONSTRAINT IF EXISTS {$c->conname}");
        }

        // ── Then drop any remaining standalone indexes (excluding PK backing index) ──
        $indexes = DB::select("
            SELECT indexname
            FROM pg_indexes
            WHERE tablename = ? AND indexname NOT LIKE '%_pkey'
        ", [$tableName]);

        foreach ($indexes as $idx) {
            DB::statement("DROP INDEX IF EXISTS {$idx->indexname}");
        }
    }

    /**
     * Re-enable single-branch RLS with the standard 5-policy pattern.
     * Identical to the pattern in Phase 5 migration's enableSingleBranchRls().
     */
    private function enableSingleBranchRls(string $table): void
    {
        DB::statement("ALTER TABLE {$table} ENABLE ROW LEVEL SECURITY");
        DB::statement("ALTER TABLE {$table} FORCE ROW LEVEL SECURITY");

        $cond = "current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int";
        DB::statement("CREATE POLICY rls_{$table}_select ON {$table} FOR SELECT USING ({$cond})");
        DB::statement("CREATE POLICY rls_{$table}_insert ON {$table} FOR INSERT WITH CHECK ({$cond})");
        DB::statement("CREATE POLICY rls_{$table}_update ON {$table} FOR UPDATE USING ({$cond}) WITH CHECK ({$cond})");
        DB::statement("CREATE POLICY rls_{$table}_delete ON {$table} FOR DELETE USING ({$cond})");
        DB::statement("CREATE POLICY rls_{$table}_admin ON {$table} FOR ALL USING (current_setting('app.is_admin', true) = 'true') WITH CHECK (current_setting('app.is_admin', true) = 'true')");
    }

    // ═══════════════════════════════════════════════════════════════
    //  up()
    // ═══════════════════════════════════════════════════════════════

    public function up(): void
    {
        if ($this->hasPgPartman()) {
            DB::statement('CREATE EXTENSION IF NOT EXISTS pg_partman');
            DB::statement('CREATE SCHEMA IF NOT EXISTS partman');
        }

        $this->partitionJournalEntries();
    }

    private function partitionJournalEntries(): void
    {
        if ($this->isAlreadyPartitioned('journal_entries')) {
            return;
        }

        // ============================================================
        // 0. CRITICAL: Drop ALL declarative FKs that reference
        //    journal_entries BEFORE partitioning. PostgreSQL blocks
        //    DROP TABLE on a table that has inbound declarative FKs
        //    (RESTRICT is the default). Phase 0.3 already converted
        //    15 of these (Batch A — partitioned Phase 1/2/4 children).
        //    The remaining 15 tables (Batches B-G) are still declarative
        //    and must be dropped here. Migration 000004 (Phase 6.6)
        //    will re-create them as trigger-based FKs.
        //
        //    This step also drops the journal_lines → journal_entries
        //    declarative FK (CASCADE) which is explicitly required —
        //    PostgreSQL would reject partitioning journal_entries while
        //    a non-partitioned child has a declarative FK to it.
        //
        //    The trg_journal_balanced trigger on journal_lines queries
        //    journal_entries by id at runtime — it keeps working after
        //    the rename because it uses the table name (which is
        //    resolved at query time to the new partitioned parent).
        //    We do NOT drop trg_journal_balanced here.
        // ============================================================
        $this->dropAllDeclarativeFksToParent('journal_entries');

        // ============================================================
        // 0a. Drop the dependent view v_journal_entries_with_lines.
        //     The view reads FROM journal_entries JOIN journal_lines —
        //     it depends on journal_entries by OID. When we rename
        //     journal_entries → journal_entries_unpartitioned, the view
        //     follows the rename (still reads from the renamed table).
        //     But when we DROP journal_entries_unpartitioned at the end,
        //     the DROP would fail (RESTRICT) because the view depends
        //     on it. So we drop the view here and recreate it after
        //     the new partitioned parent is in place.
        // ============================================================
        DB::statement('DROP VIEW IF EXISTS v_journal_entries_with_lines');

        // ============================================================
        // 0b. Drop 5 ADDITIONAL dependent views / materialized views
        //     that reference journal_entries by OID. These were not
        //     enumerated in the original migration scope but block
        //     DROP TABLE journal_entries_unpartitioned with the SAME
        //     SQLSTATE 2BP01 dependency error as v_journal_entries_with_lines:
        //       - mv_ledger_balances              (materialized view)
        //       - mv_journal_entry_summary        (materialized view)
        //       - budget_vs_actual                (view)
        //       - mv_consolidated_trial_balance   (materialized view)
        //       - v_unreconciled_bank_entries     (view)
        //     PostgreSQL tracks view/MV → table OID dependencies, so
        //     the DROP TABLE at step 11 would fail while any of these
        //     exist. Each is recreated in step 13a after the new
        //     partitioned journal_entries is in place.
        //     CASCADE handles any downstream dependents (none today
        //     per scope audit, but future-proofs the drop).
        // ============================================================
        DB::statement('DROP MATERIALIZED VIEW IF EXISTS mv_ledger_balances CASCADE');
        DB::statement('DROP MATERIALIZED VIEW IF EXISTS mv_journal_entry_summary CASCADE');
        DB::statement('DROP VIEW IF EXISTS budget_vs_actual CASCADE');
        DB::statement('DROP MATERIALIZED VIEW IF EXISTS mv_consolidated_trial_balance CASCADE');
        DB::statement('DROP VIEW IF EXISTS v_unreconciled_bank_entries CASCADE');

        // ============================================================
        // 1. Drop triggers ON journal_entries (the table being renamed).
        //    These triggers reference journal_entries by OID, so they
        //    follow the table through the rename — but the renamed
        //    table is dropped at the end, so we must recreate them on
        //    the new partitioned parent.
        //
        //    Triggers to drop (verified by reading
        //    07_views_triggers_constraints.sql):
        //      - trg_notify_journal_entries      (LISTEN/NOTIFY) [2025_01_21_000001]
        //      - trg_audit_journal_entries       (financial audit) [02_accounting.sql:446]
        //      - trg_journal_entries_updated_at  (updated_at)      [07_views_triggers_constraints.sql:51-81 DO block]
        //
        //    The updated_at trigger is created by a dynamic DO block
        //    that iterates over a list of tables including journal_entries
        //    (line 58). The trigger name follows the pattern trg_<table>_updated_at.
        // ============================================================
        DB::statement('DROP TRIGGER IF EXISTS trg_notify_journal_entries ON journal_entries');
        DB::statement('DROP TRIGGER IF EXISTS trg_audit_journal_entries ON journal_entries');
        DB::statement('DROP TRIGGER IF EXISTS trg_journal_entries_updated_at ON journal_entries');

        // ============================================================
        // 2. Drop indexes except PK + drop RLS policies.
        // ============================================================
        $this->dropIndexesExceptPK('journal_entries');
        $this->dropRlsPolicies('journal_entries');

        // ============================================================
        // 3. Rename the existing table to _unpartitioned.
        // ============================================================
        DB::statement('ALTER TABLE journal_entries RENAME TO journal_entries_unpartitioned');

        // ============================================================
        // 4. Create the new partitioned parent.
        //    Schema source: 02_accounting.sql lines 31-49.
        //
        //    NOTE: source column has DEFAULT 'manual' but no CHECK
        //    constraint (Phase 9 migration 2026_08_11_000001 dropped
        //    any source CHECK constraint to allow free-form categorization).
        // ============================================================
        DB::statement(<<<'SQL'
            CREATE TABLE journal_entries (
                id                    INTEGER GENERATED BY DEFAULT AS IDENTITY,
                entry_no              VARCHAR(30) NOT NULL,
                entry_date            DATE NOT NULL,
                reference_type        VARCHAR(30),
                reference_id          INTEGER,
                branch_id             INTEGER,
                description           TEXT,
                source                VARCHAR(30) DEFAULT 'manual',
                is_reversed           BOOLEAN NOT NULL DEFAULT false,
                reversal_of_entry_id  INTEGER,
                reversed_at           TIMESTAMP(0),
                reversed_by           INTEGER,
                reverse_reason        TEXT,
                created_by            INTEGER,
                created_at            TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                updated_at            TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (id, entry_date),
                CONSTRAINT journal_entries_entry_no_unique UNIQUE (entry_no, entry_date)
            ) PARTITION BY RANGE (entry_date)
        SQL);

        // ============================================================
        // 5. Create partitions with IDENTICAL boundaries to journal_lines
        //    (Phase 6.4 will create the same boundaries).
        //    This is REQUIRED for partition-wise joins (plan §3.2 principle 8).
        //    - pre2026: 2020-01-01 .. 2026-01-01 (historical catch-all)
        //    - 12 monthly partitions for 2026
        //    - 6 monthly partitions for 2027-01 .. 2027-06
        //    - _default: catch-all for out-of-range dates
        // ============================================================
        $this->createPreYearPartition('journal_entries', 'pre2026', '2026');
        $this->createMonthlyPartitions('journal_entries', '2026');
        $this->createMonthlyPartitionsRange('journal_entries', '2027', 1, 6);

        // ============================================================
        // 6. Copy data from the unpartitioned table into the partitioned
        //    parent. OVERRIDING SYSTEM VALUE allows inserting explicit
        //    id values into the IDENTITY column. Ordering by entry_date, id
        //    ensures rows go into the correct partition in sequence —
        //    this also makes the copy more cache-friendly.
        // ============================================================
        DB::statement(<<<'SQL'
            INSERT INTO journal_entries (
                id, entry_no, entry_date, reference_type, reference_id,
                branch_id, description, source, is_reversed,
                reversal_of_entry_id, reversed_at, reversed_by, reverse_reason,
                created_by, created_at, updated_at
            )
            OVERRIDING SYSTEM VALUE
            SELECT
                id, entry_no, entry_date, reference_type, reference_id,
                branch_id, description, source, is_reversed,
                reversal_of_entry_id, reversed_at, reversed_by, reverse_reason,
                created_by, created_at, updated_at
            FROM journal_entries_unpartitioned
            ORDER BY entry_date, id
        SQL);

        // Flush any deferred constraint triggers before dropping the old table.
        DB::statement('SET CONSTRAINTS ALL IMMEDIATE');

        // ============================================================
        // 7. Fix the identity sequence so the next INSERT gets a fresh id.
        // ============================================================
        $this->fixSequence('journal_entries');

        // ============================================================
        // 8. Recreate indexes (B-tree only — BRIN is added in Phase 6.5
        //    / migration 000004 to keep this migration focused).
        //
        //    Index inventory (verified by grepping migrations + sql files):
        //      - idx_je_reference            (reference_type, reference_id)  [02_accounting.sql:50]
        //        ↑ upgraded to (reference_type, reference_id, is_reversed) per Phase 6 plan
        //      - idx_je_branch               (branch_id)                     [02_accounting.sql:52]
        //      - idx_je_reversed             (is_reversed)                   [02_accounting.sql:53]
        //      - idx_je_reference_covering   (reference_type, reference_id, is_reversed)
        //                                   INCLUDE (id, entry_no, entry_date, branch_id,
        //                                            description, source, created_by)
        //                                                                   [2025_01_20_000002:60-72]
        //      - idx_je_active               (entry_date, branch_id, reference_type)
        //                                   WHERE is_reversed = false       [2025_01_20_000001:108-112]
        //      - idx_je_date_branch          (entry_date, branch_id)         [07_views_triggers_constraints.sql:125]
        //
        //    NOTE: The original idx_je_entry_date (B-tree on entry_date)
        //    is NOT recreated here — Phase 6.5 replaces it with a BRIN
        //    index (pages_per_range=32), which is more space-efficient
        //    for the monotonically-increasing entry_date column.
        // ============================================================
        DB::statement('CREATE INDEX IF NOT EXISTS idx_je_reference ON journal_entries (reference_type, reference_id, is_reversed)');
        DB::statement('CREATE INDEX IF NOT EXISTS idx_je_branch ON journal_entries (branch_id)');
        DB::statement('CREATE INDEX IF NOT EXISTS idx_je_reversed ON journal_entries (is_reversed)');
        DB::statement(<<<'SQL'
            CREATE INDEX IF NOT EXISTS idx_je_reference_covering
                ON journal_entries (reference_type, reference_id, is_reversed)
                INCLUDE (id, entry_no, entry_date, branch_id, description, source, created_by)
        SQL);
        // Partial index for non-reversed entries (used by GL reports / Trial Balance).
        DB::statement(<<<'SQL'
            CREATE INDEX IF NOT EXISTS idx_je_active
                ON journal_entries (entry_date, branch_id, reference_type)
                WHERE is_reversed = false
        SQL);
        // Convenience index for branch + date filters (used by branch-level GL reports).
        DB::statement(<<<'SQL'
            CREATE INDEX IF NOT EXISTS idx_je_branch_date
                ON journal_entries (entry_date, branch_id, reference_type)
        SQL);

        // ============================================================
        // 9. Recreate triggers ON journal_entries (parent).
        //    Creating a trigger on the partitioned parent automatically
        //    applies it to all current AND future partitions (PostgreSQL
        //    13+ behavior).
        // ============================================================
        // LISTEN/NOTIFY trigger (function rcerp_notify_journal_entry exists).
        DB::statement(<<<'SQL'
            CREATE TRIGGER trg_notify_journal_entries
                AFTER INSERT ON journal_entries
                FOR EACH ROW EXECUTE FUNCTION rcerp_notify_journal_entry()
        SQL);

        // Financial audit trigger (function fn_financial_audit_trigger exists).
        DB::statement(<<<'SQL'
            CREATE TRIGGER trg_audit_journal_entries
                AFTER INSERT OR UPDATE OR DELETE ON journal_entries
                FOR EACH ROW EXECUTE FUNCTION fn_financial_audit_trigger()
        SQL);

        // Updated_at trigger (function update_updated_at_column exists).
        // Recreated from the DO block in 07_views_triggers_constraints.sql:51-81.
        DB::statement(<<<'SQL'
            CREATE TRIGGER trg_journal_entries_updated_at
                BEFORE UPDATE ON journal_entries
                FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()
        SQL);

        // ============================================================
        // 10. Recreate RLS policies (single-branch: branch_id = app.branch_id).
        // ============================================================
        $this->enableSingleBranchRls('journal_entries');

        // ============================================================
        // 11. Drop the unpartitioned table.
        //     Safe now — all declarative FKs to journal_entries were dropped
        //     in step 0, and the dependent view was dropped in step 0a.
        // ============================================================
        DB::statement('DROP TABLE journal_entries_unpartitioned');

        // ============================================================
        // 12. Register with pg_partman + configure 84-month retention.
        //     84 months = 7 years (financial compliance retention).
        // ============================================================
        $this->registerPartman('journal_entries', 'entry_date', '2027-07-01');

        if ($this->hasPgPartman()) {
            try {
                DB::statement(<<<SQL
                    UPDATE partman.part_config
                    SET retention = '84 months',
                        retention_keep_table = true,
                        retention_schema = 'archive'
                    WHERE parent_table = 'public.journal_entries'
                SQL);
            } catch (\Throwable $e) {
                Log::warning("Phase 6.3: Failed to set retention for journal_entries: {$e->getMessage()}");
            }
        }

        // ============================================================
        // 13. Recreate the dependent view (dropped in step 0a).
        //     At this point journal_lines is still NON-partitioned —
        //     migration 000003 will partition it next. The view reads
        //     from journal_entries (now partitioned) + journal_lines
        //     (still flat). Both work fine.
        //     Migration 000003 will drop + recreate this view again
        //     after journal_lines is partitioned.
        // ============================================================
        DB::statement(<<<'SQL'
            CREATE OR REPLACE VIEW v_journal_entries_with_lines AS
            SELECT
                je.id AS journal_entry_id,
                je.entry_no,
                je.entry_date,
                je.reference_type,
                je.reference_id,
                je.branch_id,
                je.description,
                je.is_reversed,
                je.created_at,
                jl.id AS journal_line_id,
                jl.ledger_id,
                l.ledger_code,
                l.ledger_name,
                l.account_type,
                l.ledger_nature,
                jl.debit,
                jl.credit,
                jl.entity_type,
                jl.entity_id,
                jl.memo
            FROM journal_entries je
            JOIN journal_lines jl ON jl.journal_entry_id = je.id
            LEFT JOIN ledgers l ON l.id = jl.ledger_id
        SQL);

        // ============================================================
        // 13a. Recreate the 5 dependent views / materialized views
        //      dropped in step 0b. CREATE statements are copied
        //      VERBATIM from their original migrations:
        //        - mv_ledger_balances            (2025_01_03_000001:30-51)
        //        - mv_journal_entry_summary      (2025_01_03_000001:155-177)
        //        - budget_vs_actual              (2026_08_10_000002:118-162)
        //        - mv_consolidated_trial_balance (2026_08_11_000001:464-503)
        //        - v_unreconciled_bank_entries   (2026_08_12_000001:185-222)
        //      None schema-qualify journal_entries, so they resolve
        //      to the NEW partitioned parent by name at query time.
        //      CREATE MATERIALIZED VIEW populates the MV with data
        //      immediately (WITH DATA is the default) — no separate
        //      REFRESH needed. The 8 indexes (3+4+1) are recreated
        //      right after each MV.
        //      All 5 are mutually independent (no inter-view deps,
        //      verified by scope audit), so recreation order is
        //      arbitrary. The scheduled refresh_all_report_views()
        //      pg_cron job (every 5 min) will keep MVs current.
        // ============================================================

        // ── mv_ledger_balances ──────────────────────────────────────
        DB::statement(<<<'SQL'
            CREATE MATERIALIZED VIEW IF NOT EXISTS mv_ledger_balances AS
            SELECT
                l.id AS ledger_id,
                l.ledger_code,
                l.ledger_name,
                l.account_type,
                l.ledger_nature,
                l.is_control_account,
                l.is_active,
                l.parent_id,
                COALESCE(SUM(jl.debit), 0) AS total_debit,
                COALESCE(SUM(jl.credit), 0) AS total_credit,
                COALESCE(SUM(jl.debit), 0) - COALESCE(SUM(jl.credit), 0) AS net_debit,
                COUNT(jl.id) AS line_count,
                MAX(je.entry_date) AS last_entry_date
            FROM ledgers l
            LEFT JOIN journal_lines jl ON jl.ledger_id = l.id
            LEFT JOIN journal_entries je ON je.id = jl.journal_entry_id AND COALESCE(je.is_reversed, false) = false
            GROUP BY l.id, l.ledger_code, l.ledger_name, l.account_type, l.ledger_nature,
                     l.is_control_account, l.is_active, l.parent_id
        SQL);
        DB::statement('CREATE UNIQUE INDEX IF NOT EXISTS mv_ledger_balances_ledger_id_idx ON mv_ledger_balances (ledger_id)');
        DB::statement('CREATE INDEX IF NOT EXISTS mv_ledger_balances_account_type_idx ON mv_ledger_balances (account_type)');
        DB::statement('CREATE INDEX IF NOT EXISTS mv_ledger_balances_nature_idx ON mv_ledger_balances (ledger_nature)');

        // ── mv_journal_entry_summary ────────────────────────────────
        DB::statement(<<<'SQL'
            CREATE MATERIALIZED VIEW IF NOT EXISTS mv_journal_entry_summary AS
            SELECT
                je.id AS journal_entry_id,
                je.entry_no,
                je.entry_date,
                je.reference_type,
                je.reference_id,
                je.branch_id,
                je.description,
                je.is_reversed,
                je.created_by,
                je.created_at,
                b.branch_name,
                COALESCE(SUM(jl.debit), 0) AS total_debit,
                COALESCE(SUM(jl.credit), 0) AS total_credit,
                COUNT(jl.id) AS line_count
            FROM journal_entries je
            LEFT JOIN journal_lines jl ON jl.journal_entry_id = je.id
            LEFT JOIN branches b ON b.id = je.branch_id
            GROUP BY je.id, je.entry_no, je.entry_date, je.reference_type, je.reference_id,
                     je.branch_id, je.description, je.is_reversed, je.created_by, je.created_at, b.branch_name
        SQL);
        DB::statement('CREATE UNIQUE INDEX IF NOT EXISTS mv_journal_entry_summary_je_id_idx ON mv_journal_entry_summary (journal_entry_id)');
        DB::statement('CREATE INDEX IF NOT EXISTS mv_journal_entry_summary_date_idx ON mv_journal_entry_summary (entry_date)');
        DB::statement('CREATE INDEX IF NOT EXISTS mv_journal_entry_summary_branch_idx ON mv_journal_entry_summary (branch_id)');
        DB::statement('CREATE INDEX IF NOT EXISTS mv_journal_entry_summary_ref_idx ON mv_journal_entry_summary (reference_type, reference_id)');

        // ── budget_vs_actual ────────────────────────────────────────
        DB::statement(<<<'SQL'
            CREATE OR REPLACE VIEW budget_vs_actual AS
            SELECT
                bl.id AS budget_line_id,
                b.id AS budget_id,
                b.name AS budget_name,
                b.fiscal_year,
                b.branch_id AS budget_branch_id,
                bl.ledger_id,
                l.ledger_code,
                l.ledger_name,
                l.account_type,
                l.normal_balance,
                bl.period,
                bl.amount AS budget_amount,
                COALESCE(actual.actual_amount, 0) AS actual_amount,
                bl.amount - COALESCE(actual.actual_amount, 0) AS variance_amount,
                CASE
                    WHEN bl.amount = 0 THEN NULL
                    ELSE ROUND(
                        ((bl.amount - COALESCE(actual.actual_amount, 0)) / bl.amount) * 100,
                        2
                    )
                END AS variance_percent
            FROM budget_lines bl
            JOIN budgets b ON b.id = bl.budget_id
            JOIN ledgers l ON l.id = bl.ledger_id
            LEFT JOIN LATERAL (
                SELECT SUM(
                    CASE l.normal_balance
                        WHEN 'debit'  THEN jl2.debit  - jl2.credit
                        WHEN 'credit' THEN jl2.credit - jl2.debit
                    END
                ) AS actual_amount
                FROM journal_lines jl2
                JOIN journal_entries je2 ON je2.id = jl2.journal_entry_id
                WHERE jl2.ledger_id = bl.ledger_id
                  AND je2.is_reversed = false
                  AND EXTRACT(YEAR FROM je2.entry_date)::text = b.fiscal_year
                  AND EXTRACT(MONTH FROM je2.entry_date) = bl.period
                  AND (b.branch_id IS NULL OR je2.branch_id = b.branch_id)
            ) actual ON true
            WHERE b.deleted_at IS NULL
              AND l.deleted_at IS NULL
        SQL);

        // ── mv_consolidated_trial_balance ───────────────────────────
        DB::statement(<<<'SQL'
            CREATE MATERIALIZED VIEW IF NOT EXISTS mv_consolidated_trial_balance AS
            SELECT
                l.id AS ledger_id,
                l.ledger_code,
                l.ledger_name,
                l.account_type,
                l.ledger_nature,
                l.normal_balance,
                l.is_elimination,
                -- Aggregate across all branches
                COALESCE(SUM(jl.debit), 0) AS total_debit,
                COALESCE(SUM(jl.credit), 0) AS total_credit,
                -- Elimination adjustment (from elimination entries)
                COALESCE(elim.elim_debit, 0) AS elimination_debit,
                COALESCE(elim.elim_credit, 0) AS elimination_credit,
                -- Consolidated (net of elimination)
                COALESCE(SUM(jl.debit), 0) - COALESCE(elim.elim_debit, 0) AS consolidated_debit,
                COALESCE(SUM(jl.credit), 0) - COALESCE(elim.elim_credit, 0) AS consolidated_credit
            FROM ledgers l
            LEFT JOIN journal_lines jl ON jl.ledger_id = l.id
            LEFT JOIN journal_entries je ON je.id = jl.journal_entry_id
                AND COALESCE(je.is_reversed, false) = false
                AND je.source != 'elimination'
            LEFT JOIN LATERAL (
                SELECT
                    SUM(elim_jl.debit) AS elim_debit,
                    SUM(elim_jl.credit) AS elim_credit
                FROM elimination_entries ee
                JOIN consolidation_runs cr ON cr.id = ee.consolidation_run_id
                JOIN journal_entries elim_je ON elim_je.id = ee.journal_entry_id
                JOIN journal_lines elim_jl ON elim_jl.journal_entry_id = elim_je.id
                WHERE elim_jl.ledger_id = l.id
                  AND cr.status = 'posted'
                  AND COALESCE(elim_je.is_reversed, false) = false
            ) elim ON TRUE
            WHERE l.is_active = true
            GROUP BY l.id, l.ledger_code, l.ledger_name, l.account_type, l.ledger_nature,
                     l.normal_balance, l.is_elimination, elim.elim_debit, elim.elim_credit
        SQL);
        DB::statement('CREATE UNIQUE INDEX IF NOT EXISTS mv_ctb_ledger_idx ON mv_consolidated_trial_balance (ledger_id)');

        // ── v_unreconciled_bank_entries ─────────────────────────────
        DB::statement(<<<'SQL'
            CREATE OR REPLACE VIEW v_unreconciled_bank_entries AS
            SELECT
                jl.id AS journal_line_id,
                jl.journal_entry_id,
                je.entry_no,
                je.entry_date,
                je.description AS entry_description,
                je.source AS entry_source,
                je.reference_type,
                je.reference_id,
                jl.ledger_id,
                jl.debit,
                jl.credit,
                jl.memo,
                jl.is_bank_reconciled,
                l.ledger_code,
                l.ledger_name,
                b.id AS bank_id,
                b.bank_name,
                b.account_number,
                blm.bank_id AS mapping_bank_id,
                je.branch_id,
                br.branch_name
            FROM journal_lines jl
            JOIN journal_entries je ON je.id = jl.journal_entry_id
            JOIN ledgers l ON l.id = jl.ledger_id
            LEFT JOIN bank_ledger_mappings blm ON blm.ledger_id = l.id
            LEFT JOIN banks b ON b.id = blm.bank_id
            LEFT JOIN branches br ON br.id = je.branch_id
            WHERE jl.is_bank_reconciled = false
              AND COALESCE(je.is_reversed, false) = false
              AND blm.bank_id IS NOT NULL
              AND l.deleted_at IS NULL
              AND l.is_active = true
            ORDER BY je.entry_date, je.entry_no
        SQL);

        // ============================================================
        // 14. ANALYZE to refresh planner statistics.
        // ============================================================
        DB::statement('ANALYZE journal_entries');
    }

    // ═══════════════════════════════════════════════════════════════
    //  down() — rollback is manual (trigger-based FK reversal is complex)
    // ═══════════════════════════════════════════════════════════════

    public function down(): void
    {
        // Rollback of a partitioned-+-trigger-based-FK migration is non-trivial:
        //   1. Re-create the declarative FK on journal_lines (requires data
        //      integrity check — orphaned rows may exist if journal_entries
        //      were deleted during the trigger-based period).
        //   2. Detach all partitions, copy data back to a flat table, drop
        //      the partitioned parent.
        //   3. Rename flat table back, re-create all indexes/triggers/RLS.
        //
        // Per the Phase 4/5 migrations' precedent (which leave rollbacks as
        // manual operations), we document the rollback procedure but do not
        // implement an automated one. Restoring from a pre-migration DB
        // snapshot is the recommended rollback path.
        Log::warning(
            'Phase 6.3 rollback: automated down() is intentionally a no-op. '
            . 'Restoring from a pre-migration DB snapshot is the recommended rollback path. '
            . 'Manual rollback requires: (1) re-creating declarative FK on journal_lines.journal_entry_id, '
            . '(2) detaching all partitions, (3) copying data back to a flat table, '
            . '(4) re-creating indexes/triggers/RLS policies per the original schema.'
        );
    }
};
