<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Phase 10.1 — Phase 4: Transaction Header Partitioning (Low-FK Children).
 *
 * Partitions 9 transaction header tables. Split into two groups:
 *
 * Group A — 0 FK children (4 tables, LOW risk):
 *   1. money_transfers         — by transfer_date     (dual-branch RLS, updated_at trigger, audit trigger)
 *   2. employee_transactions   — by transaction_date  (branch RLS, updated_at trigger, audit trigger)
 *   3. other_incomes           — by income_date       (branch RLS, updated_at trigger, audit trigger)
 *   4. other_expenses          — by expense_date      (branch RLS, updated_at trigger, audit trigger)
 *
 * Group B — 1+ FK children (5 tables, LOW-MEDIUM risk):
 *   5. sales_returns           — by return_date       (2 inbound FKs, soft deletes, LISTEN/NOTIFY)
 *   6. purchase_receives       — by receive_date      (3 inbound FKs, soft deletes)
 *   7. purchase_returns        — by return_date       (1 inbound FK, soft deletes)
 *   8. damage_invoices         — by damage_date       (3 inbound FKs, soft deletes, LISTEN/NOTIFY, 34 columns)
 *   9. manual_journals         — by journal_date      (1 inbound FK, soft deletes, audit trigger)
 *
 * DESIGN DECISIONS:
 *
 * 1. Composite PK: PK(id) → PK(id, date_column). GENERATED ALWAYS → GENERATED BY DEFAULT
 *    for OVERRIDING SYSTEM VALUE during data copy.
 *
 * 2. UNIQUE constraints must include partition key: e.g. UNIQUE(code) → UNIQUE(code, date_column).
 *    This is a PostgreSQL requirement for partitioned tables.
 *
 * 3. Trigger-based FK conversion for Group B: When a partitioned table is referenced by
 *    a declarative FK from another table, PostgreSQL cannot enforce it. We drop the
 *    declarative FK and create a trigger that checks existence in the partitioned parent.
 *    Also need cascade delete triggers for ON DELETE CASCADE FKs.
 *
 * 4. Triggers: updated_at, audit, and LISTEN/NOTIFY triggers are preserved on the
 *    partitioned parent. They automatically apply to all partitions.
 *
 * 5. RLS: All tables have RLS policies. Policies on the parent apply to all partitions.
 *
 * 6. Soft deletes: Tables with `deleted_at` need it included in the partitioned schema.
 *
 * 7. damage_invoices.employee_ledger_entry_id → employee_ledger(id): This FK references
 *    a partitioned table (Phase 2). It must be converted to trigger-based FK as well.
 *
 * ⚠️  This migration should be run during a maintenance window.
 *     It locks tables during the data copy phase.
 */
return new class extends Migration
{
    private ?bool $hasPgPartman = null;

    // ── Helper methods ──────────────────────────────────────────────

    private function hasPgPartman(): bool
    {
        if ($this->hasPgPartman !== null) {
            return $this->hasPgPartman;
        }
        $row = DB::selectOne("
            SELECT EXISTS (
                SELECT 1 FROM pg_available_extensions WHERE name = 'pg_partman'
            ) AS installed
        ");
        $this->hasPgPartman = (bool) ($row->installed ?? false);
        if (! $this->hasPgPartman) {
            logger()->warning('pg_partman is not installed. Automatic partition maintenance is disabled.');
        }
        return $this->hasPgPartman;
    }

    private function isAlreadyPartitioned(string $tableName): bool
    {
        $row = DB::selectOne("
            SELECT 1
            FROM pg_partitioned_table pt
            JOIN pg_class c ON c.oid = pt.partrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relname = ? AND n.nspname = current_schema()
            LIMIT 1
        ", [$tableName]);
        return $row !== null;
    }

    private function relationExists(string $name): bool
    {
        $row = DB::selectOne("
            SELECT 1
            FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relname = ? AND n.nspname = current_schema()
            LIMIT 1
        ", [$name]);
        return $row !== null;
    }

    private function createMonthlyPartitions(string $parent, string $year): void
    {
        for ($m = 1; $m <= 12; $m++) {
            $from = sprintf('%s-%02d-01', $year, $m);
            $to   = $m < 12
                ? sprintf('%s-%02d-01', $year, $m + 1)
                : sprintf('%d-01-01', (int) $year + 1);
            $name = sprintf('%s_%s_%02d', $parent, $year, $m);

            if (! $this->relationExists($name)) {
                DB::statement(
                    "CREATE TABLE {$name} PARTITION OF {$parent}
                     FOR VALUES FROM ('{$from}') TO ('{$to}')"
                );
            }
        }

        $defaultName = "{$parent}_default";
        if (! $this->relationExists($defaultName)) {
            DB::statement(
                "CREATE TABLE {$defaultName} PARTITION OF {$parent} DEFAULT"
            );
        }
    }

    private function createPreYearPartition(string $parent, string $preYear, string $startYear): void
    {
        $name = "{$parent}_{$preYear}";
        if (! $this->relationExists($name)) {
            DB::statement(
                "CREATE TABLE {$name} PARTITION OF {$parent}
                 FOR VALUES FROM ('2020-01-01') TO ('{$startYear}-01-01')"
            );
        }
    }

    private function registerPartman(string $parent, string $control, string $startPartition): void
    {
        if (! $this->hasPgPartman()) {
            return;
        }
        try {
            DB::statement(<<<SQL
                SELECT partman.create_parent(
                    p_parent_table    := 'public.{$parent}',
                    p_control         := '{$control}',
                    p_type            := 'range',
                    p_interval        := '1 month',
                    p_premake         := 6,
                    p_start_partition := '{$startPartition}'
                )
            SQL);
        } catch (\Throwable $e) {
            // Already registered with pg_partman — safe to ignore.
        }
    }

    private function fixSequence(string $table): void
    {
        DB::statement(<<<SQL
            SELECT setval(
                pg_get_serial_sequence('{$table}', 'id'),
                GREATEST(COALESCE((SELECT MAX(id) FROM {$table}), 0), 1)
            )
        SQL);
    }

    private function dropRlsPolicies(string $tableName): void
    {
        $policies = DB::select("
            SELECT polname
            FROM pg_policy p
            JOIN pg_class c ON c.oid = p.polrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relname = ? AND n.nspname = current_schema()
        ", [$tableName]);

        foreach ($policies as $policy) {
            DB::statement("DROP POLICY IF EXISTS {$policy->polname} ON {$tableName}");
        }
    }

    private function dropIndexesExceptPK(string $tableName): void
    {
        $indexes = DB::select("
            SELECT indexname
            FROM pg_indexes
            WHERE tablename = ? AND indexname NOT LIKE '%_pkey'
        ", [$tableName]);

        foreach ($indexes as $idx) {
            DB::statement("DROP INDEX IF EXISTS {$idx->indexname}");
        }
    }

    /**
     * Drop a specific FK constraint if it exists.
     */
    private function dropFkConstraint(string $table, string $constraintName): void
    {
        DB::statement("ALTER TABLE {$table} DROP CONSTRAINT IF EXISTS {$constraintName}");
    }

    /**
     * Create a trigger-based FK check function + trigger for a child→parent reference.
     * Replaces declarative FK when the parent is partitioned.
     */
    private function createTriggerFkCheck(
        string $childTable,
        string $fkColumn,
        string $parentTable,
        string $triggerFuncName,
        string $triggerName
    ): void {
        // Drop existing trigger if any
        DB::statement("DROP TRIGGER IF EXISTS {$triggerName} ON {$childTable}");

        // Create trigger function
        DB::statement(<<<SQL
            CREATE OR REPLACE FUNCTION {$triggerFuncName}()
            RETURNS TRIGGER AS \$\$
            BEGIN
                IF NEW.{$fkColumn} IS NOT NULL THEN
                    IF NOT EXISTS (
                        SELECT 1 FROM {$parentTable}
                        WHERE id = NEW.{$fkColumn}
                    ) THEN
                        RAISE EXCEPTION 'FK violation: {$parentTable}(id=%) not found', NEW.{$fkColumn};
                    END IF;
                END IF;
                RETURN NEW;
            END;
            \$\$ LANGUAGE plpgsql
        SQL);

        // Create trigger
        DB::statement(<<<SQL
            CREATE TRIGGER {$triggerName}
                BEFORE INSERT OR UPDATE ON {$childTable}
                FOR EACH ROW EXECUTE FUNCTION {$triggerFuncName}()
        SQL);
    }

    /**
     * Create a trigger-based cascade delete function + trigger.
     * Replaces ON DELETE CASCADE declarative FK when the parent is partitioned.
     */
    private function createTriggerFkCascadeDelete(
        string $childTable,
        string $fkColumn,
        string $parentTable,
        string $triggerFuncName,
        string $triggerName
    ): void {
        // Drop existing trigger if any
        DB::statement("DROP TRIGGER IF EXISTS {$triggerName} ON {$parentTable}");

        // Create trigger function
        DB::statement(<<<SQL
            CREATE OR REPLACE FUNCTION {$triggerFuncName}()
            RETURNS TRIGGER AS \$\$
            BEGIN
                DELETE FROM {$childTable} WHERE {$fkColumn} = OLD.id;
                RETURN OLD;
            END;
            \$\$ LANGUAGE plpgsql
        SQL);

        // Create trigger on parent (AFTER DELETE)
        DB::statement(<<<SQL
            CREATE TRIGGER {$triggerName}
                AFTER DELETE ON {$parentTable}
                FOR EACH ROW EXECUTE FUNCTION {$triggerFuncName}()
        SQL);
    }

    /**
     * Create a trigger-based SET NULL function + trigger.
     * Replaces ON DELETE SET NULL declarative FK when the parent is partitioned.
     */
    private function createTriggerFkSetNull(
        string $childTable,
        string $fkColumn,
        string $parentTable,
        string $triggerFuncName,
        string $triggerName
    ): void {
        // Drop existing trigger if any
        DB::statement("DROP TRIGGER IF EXISTS {$triggerName} ON {$parentTable}");

        // Create trigger function
        DB::statement(<<<SQL
            CREATE OR REPLACE FUNCTION {$triggerFuncName}()
            RETURNS TRIGGER AS \$\$
            BEGIN
                UPDATE {$childTable} SET {$fkColumn} = NULL WHERE {$fkColumn} = OLD.id;
                RETURN OLD;
            END;
            \$\$ LANGUAGE plpgsql
        SQL);

        // Create trigger on parent (AFTER DELETE)
        DB::statement(<<<SQL
            CREATE TRIGGER {$triggerName}
                AFTER DELETE ON {$parentTable}
                FOR EACH ROW EXECUTE FUNCTION {$triggerFuncName}()
        SQL);
    }

    // ── Main up() ───────────────────────────────────────────────────

    public function up(): void
    {
        if ($this->hasPgPartman()) {
            DB::statement('CREATE EXTENSION IF NOT EXISTS pg_partman');
            DB::statement('CREATE SCHEMA IF NOT EXISTS partman');
        }

        // Group A — 0 FK children
        $this->partitionMoneyTransfers();
        $this->partitionEmployeeTransactions();
        $this->partitionOtherIncomes();
        $this->partitionOtherExpenses();

        // Group B — 1+ FK children (trigger-based FK conversion)
        $this->partitionSalesReturns();
        $this->partitionPurchaseReceives();
        $this->partitionPurchaseReturns();
        $this->partitionDamageInvoices();
        $this->partitionManualJournals();
    }

    // ═══════════════════════════════════════════════════════════════
    //  1. money_transfers
    // ═══════════════════════════════════════════════════════════════

    private function partitionMoneyTransfers(): void
    {
        if ($this->isAlreadyPartitioned('money_transfers')) {
            return;
        }

        $this->dropIndexesExceptPK('money_transfers');
        $this->dropRlsPolicies('money_transfers');

        DB::statement('ALTER TABLE money_transfers RENAME TO money_transfers_unpartitioned');

        // PK: (id, transfer_date). UNIQUE: (transfer_code, transfer_date)
        // FKs: from_branch_id, to_branch_id, from_bank_id, to_bank_id,
        //      journal_entry_id, intercompany_journal_entry_id
        // Triggers: trg_money_transfers_updated_at, trg_audit_money_transfers
        DB::statement(<<<'SQL'
            CREATE TABLE money_transfers (
                id                          INTEGER GENERATED BY DEFAULT AS IDENTITY,
                transfer_code               VARCHAR(50) NOT NULL,
                transfer_date               DATE NOT NULL,
                from_branch_id              INTEGER NOT NULL REFERENCES branches(id) DEFERRABLE INITIALLY DEFERRED,
                to_branch_id                INTEGER NOT NULL REFERENCES branches(id) DEFERRABLE INITIALLY DEFERRED,
                transfer_type               VARCHAR(20) NOT NULL CHECK (transfer_type IN ('cash_to_bank','bank_to_cash','cash_to_cash','bank_to_bank')),
                from_bank_id                INTEGER REFERENCES banks(id) DEFERRABLE INITIALLY DEFERRED,
                to_bank_id                  INTEGER REFERENCES banks(id) DEFERRABLE INITIALLY DEFERRED,
                amount                      NUMERIC(14,2) NOT NULL DEFAULT 0,
                journal_entry_id            INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                intercompany_journal_entry_id INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                is_reversed                 BOOLEAN NOT NULL DEFAULT false,
                reversed_at                 TIMESTAMP(0),
                reversed_by                 INTEGER,
                reverse_reason              TEXT,
                notes                       TEXT,
                created_by                  INTEGER,
                created_at                  TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                updated_at                  TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (id, transfer_date),
                CONSTRAINT money_transfers_code_unique UNIQUE (transfer_code, transfer_date)
            ) PARTITION BY RANGE (transfer_date)
        SQL);

        $this->createPreYearPartition('money_transfers', 'pre2026', '2026');
        $this->createMonthlyPartitions('money_transfers', '2026');

        DB::statement(<<<'SQL'
            INSERT INTO money_transfers (
                id, transfer_code, transfer_date, from_branch_id, to_branch_id,
                transfer_type, from_bank_id, to_bank_id, amount,
                journal_entry_id, intercompany_journal_entry_id,
                is_reversed, reversed_at, reversed_by, reverse_reason,
                notes, created_by, created_at, updated_at
            )
            OVERRIDING SYSTEM VALUE
            SELECT
                id, transfer_code, transfer_date, from_branch_id, to_branch_id,
                transfer_type, from_bank_id, to_bank_id, amount,
                journal_entry_id, intercompany_journal_entry_id,
                is_reversed, reversed_at, reversed_by, reverse_reason,
                notes, created_by, created_at, updated_at
            FROM money_transfers_unpartitioned
            ORDER BY transfer_date, id
        SQL);

        // ── Flush deferred FK triggers before creating indexes ──
        DB::statement('SET CONSTRAINTS ALL IMMEDIATE');

        $this->fixSequence('money_transfers');

        // Recreate indexes
        DB::statement('CREATE INDEX idx_mt_branches ON money_transfers (from_branch_id, to_branch_id)');
        DB::statement('CREATE INDEX idx_mt_journal ON money_transfers (journal_entry_id)');
        DB::statement(<<<'SQL'
            CREATE INDEX idx_mt_transfer_date_brin
                ON money_transfers USING BRIN (transfer_date)
                WITH (pages_per_range = 32)
        SQL);

        // Recreate updated_at trigger
        DB::statement(<<<'SQL'
            CREATE OR REPLACE FUNCTION trg_money_transfers_updated_at()
            RETURNS TRIGGER AS $$
            BEGIN NEW.updated_at = CURRENT_TIMESTAMP; RETURN NEW; END;
            $$ LANGUAGE plpgsql
        SQL);
        DB::statement(<<<'SQL'
            CREATE TRIGGER trg_money_transfers_updated_at
                BEFORE UPDATE ON money_transfers
                FOR EACH ROW EXECUTE FUNCTION trg_money_transfers_updated_at()
        SQL);

        // Recreate RLS policies (dual-branch: from_branch_id OR to_branch_id)
        DB::statement('ALTER TABLE money_transfers ENABLE ROW LEVEL SECURITY');
        DB::statement('ALTER TABLE money_transfers FORCE ROW LEVEL SECURITY');
        DB::statement(<<<'SQL'
            CREATE POLICY rls_money_transfers_select ON money_transfers
                FOR SELECT USING (current_setting('app.is_admin', true) = 'true' OR from_branch_id = current_setting('app.branch_id')::int OR to_branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_money_transfers_insert ON money_transfers
                FOR INSERT WITH CHECK (current_setting('app.is_admin', true) = 'true' OR from_branch_id = current_setting('app.branch_id')::int OR to_branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_money_transfers_update ON money_transfers
                FOR UPDATE USING (current_setting('app.is_admin', true) = 'true' OR from_branch_id = current_setting('app.branch_id')::int OR to_branch_id = current_setting('app.branch_id')::int)
                WITH CHECK (current_setting('app.is_admin', true) = 'true' OR from_branch_id = current_setting('app.branch_id')::int OR to_branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_money_transfers_delete ON money_transfers
                FOR DELETE USING (current_setting('app.is_admin', true) = 'true' OR from_branch_id = current_setting('app.branch_id')::int OR to_branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_money_transfers_admin ON money_transfers
                FOR ALL USING (current_setting('app.is_admin', true) = 'true')
                WITH CHECK (current_setting('app.is_admin', true) = 'true')
        SQL);

        // Recreate financial audit trigger
        DB::statement(<<<'SQL'
            CREATE TRIGGER trg_audit_money_transfers
                AFTER INSERT OR UPDATE OR DELETE ON money_transfers
                FOR EACH ROW EXECUTE FUNCTION fn_financial_audit_trigger()
        SQL);

        DB::statement('DROP TABLE money_transfers_unpartitioned');
        $this->registerPartman('money_transfers', 'transfer_date', '2027-01-01');
        DB::statement('ANALYZE money_transfers');
    }

    // ═══════════════════════════════════════════════════════════════
    //  2. employee_transactions
    // ═══════════════════════════════════════════════════════════════

    private function partitionEmployeeTransactions(): void
    {
        if ($this->isAlreadyPartitioned('employee_transactions')) {
            return;
        }

        $this->dropIndexesExceptPK('employee_transactions');
        $this->dropRlsPolicies('employee_transactions');

        DB::statement('ALTER TABLE employee_transactions RENAME TO employee_transactions_unpartitioned');

        DB::statement(<<<'SQL'
            CREATE TABLE employee_transactions (
                id                          INTEGER GENERATED BY DEFAULT AS IDENTITY,
                transaction_code            VARCHAR(30) NOT NULL,
                transaction_date            DATE NOT NULL,
                employee_id                 INTEGER NOT NULL REFERENCES employees(id) DEFERRABLE INITIALLY DEFERRED,
                branch_id                   INTEGER NOT NULL REFERENCES branches(id) DEFERRABLE INITIALLY DEFERRED,
                transaction_type            VARCHAR(20) NOT NULL CHECK (transaction_type IN ('advance','loan','repayment','salary','deduction','adjustment')),
                payment_mode                VARCHAR(20) NOT NULL DEFAULT 'cash' CHECK (payment_mode IN ('cash','bank','mobile_banking','cheque','adjustment')),
                bank_id                     INTEGER REFERENCES banks(id) ON DELETE SET NULL,
                collected_by                INTEGER REFERENCES employees(id) ON DELETE SET NULL,
                amount                      NUMERIC(14,2) NOT NULL DEFAULT 0,
                description                 TEXT,
                journal_entry_id            INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                intercompany_journal_entry_id INTEGER REFERENCES journal_entries(id) ON DELETE SET NULL,
                is_reversed                 BOOLEAN NOT NULL DEFAULT false,
                reversed_at                 TIMESTAMP(0),
                reversed_by                 INTEGER,
                reverse_reason              TEXT,
                created_by                  INTEGER,
                created_at                  TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                updated_at                  TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (id, transaction_date),
                CONSTRAINT employee_transactions_code_unique UNIQUE (transaction_code, transaction_date)
            ) PARTITION BY RANGE (transaction_date)
        SQL);

        $this->createPreYearPartition('employee_transactions', 'pre2026', '2026');
        $this->createMonthlyPartitions('employee_transactions', '2026');

        DB::statement(<<<'SQL'
            INSERT INTO employee_transactions (
                id, transaction_code, transaction_date, employee_id, branch_id,
                transaction_type, payment_mode, bank_id, collected_by,
                amount, description, journal_entry_id, intercompany_journal_entry_id,
                is_reversed, reversed_at, reversed_by, reverse_reason,
                created_by, created_at, updated_at
            )
            OVERRIDING SYSTEM VALUE
            SELECT
                id, transaction_code, transaction_date, employee_id, branch_id,
                transaction_type, payment_mode, bank_id, collected_by,
                amount, description, journal_entry_id, intercompany_journal_entry_id,
                is_reversed, reversed_at, reversed_by, reverse_reason,
                created_by, created_at, updated_at
            FROM employee_transactions_unpartitioned
            ORDER BY transaction_date, id
        SQL);

        // ── Flush deferred FK triggers before creating indexes ──
        DB::statement('SET CONSTRAINTS ALL IMMEDIATE');

        $this->fixSequence('employee_transactions');

        DB::statement('CREATE INDEX idx_et_employee ON employee_transactions (employee_id)');
        DB::statement('CREATE INDEX idx_et_journal ON employee_transactions (journal_entry_id)');
        DB::statement(<<<'SQL'
            CREATE INDEX idx_et_transaction_date_brin
                ON employee_transactions USING BRIN (transaction_date)
                WITH (pages_per_range = 32)
        SQL);

        // Recreate updated_at trigger
        DB::statement(<<<'SQL'
            CREATE OR REPLACE FUNCTION trg_employee_transactions_updated_at()
            RETURNS TRIGGER AS $$
            BEGIN NEW.updated_at = CURRENT_TIMESTAMP; RETURN NEW; END;
            $$ LANGUAGE plpgsql
        SQL);
        DB::statement(<<<'SQL'
            CREATE TRIGGER trg_employee_transactions_updated_at
                BEFORE UPDATE ON employee_transactions
                FOR EACH ROW EXECUTE FUNCTION trg_employee_transactions_updated_at()
        SQL);

        // RLS (single branch_id)
        DB::statement('ALTER TABLE employee_transactions ENABLE ROW LEVEL SECURITY');
        DB::statement('ALTER TABLE employee_transactions FORCE ROW LEVEL SECURITY');
        DB::statement(<<<'SQL'
            CREATE POLICY rls_employee_transactions_select ON employee_transactions
                FOR SELECT USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_employee_transactions_insert ON employee_transactions
                FOR INSERT WITH CHECK (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_employee_transactions_update ON employee_transactions
                FOR UPDATE USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
                WITH CHECK (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_employee_transactions_delete ON employee_transactions
                FOR DELETE USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_employee_transactions_admin ON employee_transactions
                FOR ALL USING (current_setting('app.is_admin', true) = 'true')
                WITH CHECK (current_setting('app.is_admin', true) = 'true')
        SQL);

        // Recreate financial audit trigger
        DB::statement(<<<'SQL'
            CREATE TRIGGER trg_audit_employee_transactions
                AFTER INSERT OR UPDATE OR DELETE ON employee_transactions
                FOR EACH ROW EXECUTE FUNCTION fn_financial_audit_trigger()
        SQL);

        DB::statement('DROP TABLE employee_transactions_unpartitioned');
        $this->registerPartman('employee_transactions', 'transaction_date', '2027-01-01');
        DB::statement('ANALYZE employee_transactions');
    }

    // ═══════════════════════════════════════════════════════════════
    //  3. other_incomes
    // ═══════════════════════════════════════════════════════════════

    private function partitionOtherIncomes(): void
    {
        if ($this->isAlreadyPartitioned('other_incomes')) {
            return;
        }

        $this->dropIndexesExceptPK('other_incomes');
        $this->dropRlsPolicies('other_incomes');

        DB::statement('ALTER TABLE other_incomes RENAME TO other_incomes_unpartitioned');

        DB::statement(<<<'SQL'
            CREATE TABLE other_incomes (
                id              INTEGER GENERATED BY DEFAULT AS IDENTITY,
                income_code     VARCHAR(30) NOT NULL,
                income_date     DATE NOT NULL,
                branch_id       INTEGER NOT NULL REFERENCES branches(id) DEFERRABLE INITIALLY DEFERRED,
                bank_id         INTEGER REFERENCES banks(id) DEFERRABLE INITIALLY DEFERRED,
                payment_mode    VARCHAR(20) NOT NULL DEFAULT 'cash',
                income_type     VARCHAR(50),
                amount          NUMERIC(14,2) NOT NULL DEFAULT 0,
                description     TEXT,
                journal_entry_id INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                is_reversed     BOOLEAN NOT NULL DEFAULT false,
                reversed_at     TIMESTAMP(0),
                reversed_by     INTEGER,
                reverse_reason  TEXT,
                created_by      INTEGER,
                created_at      TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                updated_at      TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (id, income_date),
                CONSTRAINT other_incomes_code_unique UNIQUE (income_code, income_date)
            ) PARTITION BY RANGE (income_date)
        SQL);

        $this->createPreYearPartition('other_incomes', 'pre2026', '2026');
        $this->createMonthlyPartitions('other_incomes', '2026');

        DB::statement(<<<'SQL'
            INSERT INTO other_incomes (
                id, income_code, income_date, branch_id, bank_id, payment_mode,
                income_type, amount, description, journal_entry_id,
                is_reversed, reversed_at, reversed_by, reverse_reason,
                created_by, created_at, updated_at
            )
            OVERRIDING SYSTEM VALUE
            SELECT
                id, income_code, income_date, branch_id, bank_id, payment_mode,
                income_type, amount, description, journal_entry_id,
                is_reversed, reversed_at, reversed_by, reverse_reason,
                created_by, created_at, updated_at
            FROM other_incomes_unpartitioned
            ORDER BY income_date, id
        SQL);

        // ── Flush deferred FK triggers before creating indexes ──
        DB::statement('SET CONSTRAINTS ALL IMMEDIATE');

        $this->fixSequence('other_incomes');

        DB::statement('CREATE INDEX idx_oi_journal ON other_incomes (journal_entry_id)');
        DB::statement(<<<'SQL'
            CREATE INDEX idx_oi_income_date_brin
                ON other_incomes USING BRIN (income_date)
                WITH (pages_per_range = 32)
        SQL);

        DB::statement(<<<'SQL'
            CREATE OR REPLACE FUNCTION trg_other_incomes_updated_at()
            RETURNS TRIGGER AS $$
            BEGIN NEW.updated_at = CURRENT_TIMESTAMP; RETURN NEW; END;
            $$ LANGUAGE plpgsql
        SQL);
        DB::statement(<<<'SQL'
            CREATE TRIGGER trg_other_incomes_updated_at
                BEFORE UPDATE ON other_incomes
                FOR EACH ROW EXECUTE FUNCTION trg_other_incomes_updated_at()
        SQL);

        DB::statement('ALTER TABLE other_incomes ENABLE ROW LEVEL SECURITY');
        DB::statement('ALTER TABLE other_incomes FORCE ROW LEVEL SECURITY');
        DB::statement(<<<'SQL'
            CREATE POLICY rls_other_incomes_select ON other_incomes
                FOR SELECT USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_other_incomes_insert ON other_incomes
                FOR INSERT WITH CHECK (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_other_incomes_update ON other_incomes
                FOR UPDATE USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
                WITH CHECK (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_other_incomes_delete ON other_incomes
                FOR DELETE USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_other_incomes_admin ON other_incomes
                FOR ALL USING (current_setting('app.is_admin', true) = 'true')
                WITH CHECK (current_setting('app.is_admin', true) = 'true')
        SQL);

        // Recreate financial audit trigger
        DB::statement(<<<'SQL'
            CREATE TRIGGER trg_audit_other_incomes
                AFTER INSERT OR UPDATE OR DELETE ON other_incomes
                FOR EACH ROW EXECUTE FUNCTION fn_financial_audit_trigger()
        SQL);

        DB::statement('DROP TABLE other_incomes_unpartitioned');
        $this->registerPartman('other_incomes', 'income_date', '2027-01-01');
        DB::statement('ANALYZE other_incomes');
    }

    // ═══════════════════════════════════════════════════════════════
    //  4. other_expenses
    // ═══════════════════════════════════════════════════════════════

    private function partitionOtherExpenses(): void
    {
        if ($this->isAlreadyPartitioned('other_expenses')) {
            return;
        }

        $this->dropIndexesExceptPK('other_expenses');
        $this->dropRlsPolicies('other_expenses');

        DB::statement('ALTER TABLE other_expenses RENAME TO other_expenses_unpartitioned');

        DB::statement(<<<'SQL'
            CREATE TABLE other_expenses (
                id              INTEGER GENERATED BY DEFAULT AS IDENTITY,
                expense_code    VARCHAR(30) NOT NULL,
                expense_date    DATE NOT NULL,
                branch_id       INTEGER NOT NULL REFERENCES branches(id) DEFERRABLE INITIALLY DEFERRED,
                bank_id         INTEGER REFERENCES banks(id) DEFERRABLE INITIALLY DEFERRED,
                payment_mode    VARCHAR(20) NOT NULL DEFAULT 'cash',
                expense_type    VARCHAR(50),
                amount          NUMERIC(14,2) NOT NULL DEFAULT 0,
                description     TEXT,
                journal_entry_id INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                is_reversed     BOOLEAN NOT NULL DEFAULT false,
                reversed_at     TIMESTAMP(0),
                reversed_by     INTEGER,
                reverse_reason  TEXT,
                created_by      INTEGER,
                created_at      TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                updated_at      TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (id, expense_date),
                CONSTRAINT other_expenses_code_unique UNIQUE (expense_code, expense_date)
            ) PARTITION BY RANGE (expense_date)
        SQL);

        $this->createPreYearPartition('other_expenses', 'pre2026', '2026');
        $this->createMonthlyPartitions('other_expenses', '2026');

        DB::statement(<<<'SQL'
            INSERT INTO other_expenses (
                id, expense_code, expense_date, branch_id, bank_id, payment_mode,
                expense_type, amount, description, journal_entry_id,
                is_reversed, reversed_at, reversed_by, reverse_reason,
                created_by, created_at, updated_at
            )
            OVERRIDING SYSTEM VALUE
            SELECT
                id, expense_code, expense_date, branch_id, bank_id, payment_mode,
                expense_type, amount, description, journal_entry_id,
                is_reversed, reversed_at, reversed_by, reverse_reason,
                created_by, created_at, updated_at
            FROM other_expenses_unpartitioned
            ORDER BY expense_date, id
        SQL);

        // ── Flush deferred FK triggers before creating indexes ──
        DB::statement('SET CONSTRAINTS ALL IMMEDIATE');

        $this->fixSequence('other_expenses');

        DB::statement('CREATE INDEX idx_oe_journal ON other_expenses (journal_entry_id)');
        DB::statement(<<<'SQL'
            CREATE INDEX idx_oe_expense_date_brin
                ON other_expenses USING BRIN (expense_date)
                WITH (pages_per_range = 32)
        SQL);

        DB::statement(<<<'SQL'
            CREATE OR REPLACE FUNCTION trg_other_expenses_updated_at()
            RETURNS TRIGGER AS $$
            BEGIN NEW.updated_at = CURRENT_TIMESTAMP; RETURN NEW; END;
            $$ LANGUAGE plpgsql
        SQL);
        DB::statement(<<<'SQL'
            CREATE TRIGGER trg_other_expenses_updated_at
                BEFORE UPDATE ON other_expenses
                FOR EACH ROW EXECUTE FUNCTION trg_other_expenses_updated_at()
        SQL);

        DB::statement('ALTER TABLE other_expenses ENABLE ROW LEVEL SECURITY');
        DB::statement('ALTER TABLE other_expenses FORCE ROW LEVEL SECURITY');
        DB::statement(<<<'SQL'
            CREATE POLICY rls_other_expenses_select ON other_expenses
                FOR SELECT USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_other_expenses_insert ON other_expenses
                FOR INSERT WITH CHECK (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_other_expenses_update ON other_expenses
                FOR UPDATE USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
                WITH CHECK (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_other_expenses_delete ON other_expenses
                FOR DELETE USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_other_expenses_admin ON other_expenses
                FOR ALL USING (current_setting('app.is_admin', true) = 'true')
                WITH CHECK (current_setting('app.is_admin', true) = 'true')
        SQL);

        // Recreate financial audit trigger
        DB::statement(<<<'SQL'
            CREATE TRIGGER trg_audit_other_expenses
                AFTER INSERT OR UPDATE OR DELETE ON other_expenses
                FOR EACH ROW EXECUTE FUNCTION fn_financial_audit_trigger()
        SQL);

        DB::statement('DROP TABLE other_expenses_unpartitioned');
        $this->registerPartman('other_expenses', 'expense_date', '2027-01-01');
        DB::statement('ANALYZE other_expenses');
    }

    // ═══════════════════════════════════════════════════════════════
    //  5. sales_returns  (child: sales_return_items, damage_invoices)
    // ═══════════════════════════════════════════════════════════════

    private function partitionSalesReturns(): void
    {
        if ($this->isAlreadyPartitioned('sales_returns')) {
            return;
        }

        // ── Convert inbound FKs to trigger-based BEFORE partitioning ──
        // 1. sales_return_items.sales_return_id → sales_returns(id) ON DELETE CASCADE
        $this->dropFkConstraint('sales_return_items', 'sales_return_items_sales_return_id_foreign');
        $this->createTriggerFkCheck(
            'sales_return_items', 'sales_return_id', 'sales_returns',
            'trg_fk_sri_sr_check', 'trg_sri_sr_fk_check'
        );
        $this->createTriggerFkCascadeDelete(
            'sales_return_items', 'sales_return_id', 'sales_returns',
            'trg_fk_sr_cascade_sri', 'trg_sr_cascade_sri'
        );

        // 2. damage_invoices.sales_return_id → sales_returns(id) ON DELETE SET NULL
        $this->dropFkConstraint('damage_invoices', 'fk_dmg_sales_return');
        $this->createTriggerFkSetNull(
            'damage_invoices', 'sales_return_id', 'sales_returns',
            'trg_fk_sr_setnull_dmg', 'trg_sr_setnull_dmg'
        );

        // ── Partition sales_returns ──
        $this->dropIndexesExceptPK('sales_returns');
        $this->dropRlsPolicies('sales_returns');

        DB::statement('ALTER TABLE sales_returns RENAME TO sales_returns_unpartitioned');

        DB::statement(<<<'SQL'
            CREATE TABLE sales_returns (
                id                      INTEGER GENERATED BY DEFAULT AS IDENTITY,
                return_code             VARCHAR(30) NOT NULL,
                return_date             DATE NOT NULL,
                sales_invoice_id        INTEGER NOT NULL,
                customer_id             INTEGER NOT NULL,
                branch_id               INTEGER NOT NULL REFERENCES branches(id) DEFERRABLE INITIALLY DEFERRED,
                total_amount            NUMERIC(14,2) DEFAULT 0,
                cogs_amount             NUMERIC(14,2) DEFAULT 0,
                status                  VARCHAR(20) NOT NULL DEFAULT 'created' CHECK (status IN ('created','confirmed','reversed')),
                journal_entry_id        INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                cogs_journal_entry_id   INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                is_reversed             BOOLEAN NOT NULL DEFAULT false,
                reversed_at             TIMESTAMP(0),
                reversed_by             INTEGER,
                reverse_reason          TEXT,
                notes                   TEXT,
                reason                  TEXT,
                created_by              INTEGER,
                created_at              TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                updated_at              TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                deleted_at              TIMESTAMP(0),
                PRIMARY KEY (id, return_date),
                CONSTRAINT sales_returns_code_unique UNIQUE (return_code, return_date)
            ) PARTITION BY RANGE (return_date)
        SQL);

        $this->createPreYearPartition('sales_returns', 'pre2026', '2026');
        $this->createMonthlyPartitions('sales_returns', '2026');

        DB::statement(<<<'SQL'
            INSERT INTO sales_returns (
                id, return_code, return_date, sales_invoice_id, customer_id,
                branch_id, total_amount, cogs_amount, status,
                journal_entry_id, cogs_journal_entry_id,
                is_reversed, reversed_at, reversed_by, reverse_reason,
                notes, reason, created_by, created_at, updated_at, deleted_at
            )
            OVERRIDING SYSTEM VALUE
            SELECT
                id, return_code, return_date, sales_invoice_id, customer_id,
                branch_id, total_amount, cogs_amount, status,
                journal_entry_id, cogs_journal_entry_id,
                is_reversed, reversed_at, reversed_by, reverse_reason,
                notes, reason, created_by, created_at, updated_at, deleted_at
            FROM sales_returns_unpartitioned
            ORDER BY return_date, id
        SQL);

        // ── Flush deferred FK triggers before creating indexes ──
        DB::statement('SET CONSTRAINTS ALL IMMEDIATE');

        $this->fixSequence('sales_returns');

        // Recreate indexes
        DB::statement('CREATE INDEX idx_sr_invoice ON sales_returns (sales_invoice_id)');
        DB::statement('CREATE INDEX idx_sr_journal ON sales_returns (journal_entry_id)');
        DB::statement(<<<'SQL'
            CREATE INDEX idx_sr_pending ON sales_returns (branch_id, return_date)
                WHERE status='created' AND is_reversed=false
        SQL);
        DB::statement(<<<'SQL'
            CREATE INDEX idx_sr_dashboard ON sales_returns (created_by, return_date)
                WHERE is_reversed=false AND deleted_at IS NULL
        SQL);
        DB::statement(<<<'SQL'
            CREATE INDEX idx_sr_return_date_brin
                ON sales_returns USING BRIN (return_date)
                WITH (pages_per_range = 32)
        SQL);

        // Recreate triggers
        DB::statement(<<<'SQL'
            CREATE OR REPLACE FUNCTION trg_sales_returns_updated_at()
            RETURNS TRIGGER AS $$
            BEGIN NEW.updated_at = CURRENT_TIMESTAMP; RETURN NEW; END;
            $$ LANGUAGE plpgsql
        SQL);
        DB::statement(<<<'SQL'
            CREATE TRIGGER trg_sales_returns_updated_at
                BEFORE UPDATE ON sales_returns
                FOR EACH ROW EXECUTE FUNCTION trg_sales_returns_updated_at()
        SQL);

        // Recreate LISTEN/NOTIFY trigger
        DB::statement(<<<'SQL'
            CREATE OR REPLACE FUNCTION trg_notify_sales_returns()
            RETURNS TRIGGER AS $$
            BEGIN
                PERFORM pg_notify('rcerp_sales_return', json_build_object('action', TG_OP, 'id', NEW.id)::text);
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql
        SQL);
        DB::statement(<<<'SQL'
            CREATE TRIGGER trg_notify_sales_returns
                AFTER INSERT OR UPDATE ON sales_returns
                FOR EACH ROW EXECUTE FUNCTION trg_notify_sales_returns()
        SQL);

        // Recreate trigger-based FK: sales_returns.sales_invoice_id → sales_invoices(id)
        // sales_invoices is already partitioned, so this FK must be trigger-based.
        // The function fn_fk_si_check() already exists from the original partitioning migration.
        DB::statement(<<<'SQL'
            CREATE CONSTRAINT TRIGGER trg_fk_sr_si
                AFTER INSERT OR UPDATE ON sales_returns
                FROM sales_invoices
                FOR EACH ROW EXECUTE FUNCTION fn_fk_si_check('sales_invoice_id')
        SQL);

        // RLS
        DB::statement('ALTER TABLE sales_returns ENABLE ROW LEVEL SECURITY');
        DB::statement('ALTER TABLE sales_returns FORCE ROW LEVEL SECURITY');
        DB::statement(<<<'SQL'
            CREATE POLICY rls_sales_returns_select ON sales_returns
                FOR SELECT USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_sales_returns_insert ON sales_returns
                FOR INSERT WITH CHECK (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_sales_returns_update ON sales_returns
                FOR UPDATE USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
                WITH CHECK (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_sales_returns_delete ON sales_returns
                FOR DELETE USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_sales_returns_admin ON sales_returns
                FOR ALL USING (current_setting('app.is_admin', true) = 'true')
                WITH CHECK (current_setting('app.is_admin', true) = 'true')
        SQL);

        DB::statement('DROP TABLE sales_returns_unpartitioned');
        $this->registerPartman('sales_returns', 'return_date', '2027-01-01');
        DB::statement('ANALYZE sales_returns');
    }

    // ═══════════════════════════════════════════════════════════════
    //  6. purchase_receives  (children: purchase_receive_items, purchase_returns, supplier_payment_settlements)
    // ═══════════════════════════════════════════════════════════════

    private function partitionPurchaseReceives(): void
    {
        if ($this->isAlreadyPartitioned('purchase_receives')) {
            return;
        }

        // ── Convert inbound FKs to trigger-based ──
        // 1. purchase_receive_items.purchase_receive_id → purchase_receives(id) ON DELETE CASCADE
        $this->dropFkConstraint('purchase_receive_items', 'purchase_receive_items_purchase_receive_id_foreign');
        $this->createTriggerFkCheck(
            'purchase_receive_items', 'purchase_receive_id', 'purchase_receives',
            'trg_fk_pri_pr_check', 'trg_pri_pr_fk_check'
        );
        $this->createTriggerFkCascadeDelete(
            'purchase_receive_items', 'purchase_receive_id', 'purchase_receives',
            'trg_fk_pr_cascade_pri', 'trg_pr_cascade_pri'
        );

        // 2. purchase_returns.purchase_receive_id → purchase_receives(id)
        $this->dropFkConstraint('purchase_returns', 'purchase_returns_purchase_receive_id_foreign');
        $this->createTriggerFkCheck(
            'purchase_returns', 'purchase_receive_id', 'purchase_receives',
            'trg_fk_prtn_pr_check', 'trg_prtn_pr_fk_check'
        );

        // 3. supplier_payment_settlements.purchase_receive_id → purchase_receives(id)
        $this->dropFkConstraint('supplier_payment_settlements', 'supplier_payment_settlements_purchase_receive_id_foreign');
        $this->createTriggerFkCheck(
            'supplier_payment_settlements', 'purchase_receive_id', 'purchase_receives',
            'trg_fk_sps_pr_check', 'trg_sps_pr_fk_check'
        );

        // ── Partition purchase_receives ──
        $this->dropIndexesExceptPK('purchase_receives');
        $this->dropRlsPolicies('purchase_receives');

        DB::statement('ALTER TABLE purchase_receives RENAME TO purchase_receives_unpartitioned');

        DB::statement(<<<'SQL'
            CREATE TABLE purchase_receives (
                id                  INTEGER GENERATED BY DEFAULT AS IDENTITY,
                receive_code        VARCHAR(30) NOT NULL,
                receive_date        DATE NOT NULL,
                purchase_order_id   INTEGER REFERENCES purchase_orders(id) DEFERRABLE INITIALLY DEFERRED,
                supplier_id         INTEGER NOT NULL REFERENCES suppliers(id) DEFERRABLE INITIALLY DEFERRED,
                branch_id           INTEGER NOT NULL REFERENCES branches(id) DEFERRABLE INITIALLY DEFERRED,
                warehouse_id        INTEGER NOT NULL REFERENCES warehouses(id) DEFERRABLE INITIALLY DEFERRED,
                sub_total           NUMERIC(14,2) DEFAULT 0,
                discount_amount     NUMERIC(14,2) DEFAULT 0,
                tax_amount          NUMERIC(14,2) DEFAULT 0,
                total_amount        NUMERIC(14,2) DEFAULT 0,
                status              VARCHAR(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','confirmed','cancelled')),
                journal_entry_id    INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                is_reversed         BOOLEAN NOT NULL DEFAULT false,
                reversed_at         TIMESTAMP(0),
                reversed_by         INTEGER,
                reverse_reason      TEXT,
                notes               TEXT,
                created_by          INTEGER,
                created_at          TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                updated_at          TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                deleted_at          TIMESTAMP(0),
                PRIMARY KEY (id, receive_date),
                CONSTRAINT purchase_receives_code_unique UNIQUE (receive_code, receive_date)
            ) PARTITION BY RANGE (receive_date)
        SQL);

        $this->createPreYearPartition('purchase_receives', 'pre2026', '2026');
        $this->createMonthlyPartitions('purchase_receives', '2026');

        DB::statement(<<<'SQL'
            INSERT INTO purchase_receives (
                id, receive_code, receive_date, purchase_order_id, supplier_id,
                branch_id, warehouse_id, sub_total, discount_amount, tax_amount,
                total_amount, status, journal_entry_id,
                is_reversed, reversed_at, reversed_by, reverse_reason,
                notes, created_by, created_at, updated_at, deleted_at
            )
            OVERRIDING SYSTEM VALUE
            SELECT
                id, receive_code, receive_date, purchase_order_id, supplier_id,
                branch_id, warehouse_id, sub_total, discount_amount, tax_amount,
                total_amount, status, journal_entry_id,
                is_reversed, reversed_at, reversed_by, reverse_reason,
                notes, created_by, created_at, updated_at, deleted_at
            FROM purchase_receives_unpartitioned
            ORDER BY receive_date, id
        SQL);

        // ── Flush deferred FK triggers before creating indexes ──
        DB::statement('SET CONSTRAINTS ALL IMMEDIATE');

        $this->fixSequence('purchase_receives');

        // Recreate indexes
        DB::statement('CREATE INDEX idx_pr_po ON purchase_receives (purchase_order_id)');
        DB::statement('CREATE INDEX idx_pr_supplier ON purchase_receives (supplier_id)');
        DB::statement('CREATE INDEX idx_pr_branch ON purchase_receives (branch_id)');
        DB::statement('CREATE INDEX idx_pr_journal ON purchase_receives (journal_entry_id)');
        DB::statement('CREATE INDEX idx_pr_reversed ON purchase_receives (is_reversed, reversed_at)');
        DB::statement('CREATE INDEX idx_pr_status ON purchase_receives (status)');
        DB::statement(<<<'SQL'
            CREATE INDEX idx_pr_listing_covering ON purchase_receives (branch_id, receive_date DESC, id DESC)
                INCLUDE (supplier_id, receive_code, total_amount, is_reversed, purchase_order_id)
        SQL);
        DB::statement(<<<'SQL'
            CREATE INDEX idx_pr_receive_date_brin
                ON purchase_receives USING BRIN (receive_date)
                WITH (pages_per_range = 32)
        SQL);

        DB::statement(<<<'SQL'
            CREATE OR REPLACE FUNCTION trg_purchase_receives_updated_at()
            RETURNS TRIGGER AS $$
            BEGIN NEW.updated_at = CURRENT_TIMESTAMP; RETURN NEW; END;
            $$ LANGUAGE plpgsql
        SQL);
        DB::statement(<<<'SQL'
            CREATE TRIGGER trg_purchase_receives_updated_at
                BEFORE UPDATE ON purchase_receives
                FOR EACH ROW EXECUTE FUNCTION trg_purchase_receives_updated_at()
        SQL);

        DB::statement('ALTER TABLE purchase_receives ENABLE ROW LEVEL SECURITY');
        DB::statement('ALTER TABLE purchase_receives FORCE ROW LEVEL SECURITY');
        DB::statement(<<<'SQL'
            CREATE POLICY rls_purchase_receives_select ON purchase_receives
                FOR SELECT USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_purchase_receives_insert ON purchase_receives
                FOR INSERT WITH CHECK (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_purchase_receives_update ON purchase_receives
                FOR UPDATE USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
                WITH CHECK (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_purchase_receives_delete ON purchase_receives
                FOR DELETE USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_purchase_receives_admin ON purchase_receives
                FOR ALL USING (current_setting('app.is_admin', true) = 'true')
                WITH CHECK (current_setting('app.is_admin', true) = 'true')
        SQL);

        DB::statement('DROP TABLE purchase_receives_unpartitioned');
        $this->registerPartman('purchase_receives', 'receive_date', '2027-01-01');
        DB::statement('ANALYZE purchase_receives');
    }

    // ═══════════════════════════════════════════════════════════════
    //  7. purchase_returns  (child: purchase_return_items)
    // ═══════════════════════════════════════════════════════════════

    private function partitionPurchaseReturns(): void
    {
        if ($this->isAlreadyPartitioned('purchase_returns')) {
            return;
        }

        // Convert inbound FK to trigger-based
        $this->dropFkConstraint('purchase_return_items', 'purchase_return_items_purchase_return_id_foreign');
        $this->createTriggerFkCheck(
            'purchase_return_items', 'purchase_return_id', 'purchase_returns',
            'trg_fk_prti_prtn_check', 'trg_prti_prtn_fk_check'
        );
        $this->createTriggerFkCascadeDelete(
            'purchase_return_items', 'purchase_return_id', 'purchase_returns',
            'trg_fk_prtn_cascade_prti', 'trg_prtn_cascade_prti'
        );

        $this->dropIndexesExceptPK('purchase_returns');
        $this->dropRlsPolicies('purchase_returns');

        DB::statement('ALTER TABLE purchase_returns RENAME TO purchase_returns_unpartitioned');

        DB::statement(<<<'SQL'
            CREATE TABLE purchase_returns (
                id                  INTEGER GENERATED BY DEFAULT AS IDENTITY,
                return_code         VARCHAR(30) NOT NULL,
                return_date         DATE NOT NULL,
                purchase_receive_id INTEGER NOT NULL,
                supplier_id         INTEGER NOT NULL REFERENCES suppliers(id) DEFERRABLE INITIALLY DEFERRED,
                branch_id           INTEGER NOT NULL REFERENCES branches(id) DEFERRABLE INITIALLY DEFERRED,
                warehouse_id        INTEGER NOT NULL REFERENCES warehouses(id) DEFERRABLE INITIALLY DEFERRED,
                sub_total           NUMERIC(14,2) DEFAULT 0,
                discount_amount     NUMERIC(14,2) DEFAULT 0,
                tax_amount          NUMERIC(14,2) DEFAULT 0,
                total_amount        NUMERIC(14,2) DEFAULT 0,
                status              VARCHAR(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','confirmed','cancelled')),
                journal_entry_id    INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                is_reversed         BOOLEAN NOT NULL DEFAULT false,
                reversed_at         TIMESTAMP(0),
                reversed_by         INTEGER,
                reverse_reason      TEXT,
                notes               TEXT,
                reason              TEXT,
                created_by          INTEGER,
                created_at          TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                updated_at          TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                deleted_at          TIMESTAMP(0),
                PRIMARY KEY (id, return_date),
                CONSTRAINT purchase_returns_code_unique UNIQUE (return_code, return_date)
            ) PARTITION BY RANGE (return_date)
        SQL);

        $this->createPreYearPartition('purchase_returns', 'pre2026', '2026');
        $this->createMonthlyPartitions('purchase_returns', '2026');

        DB::statement(<<<'SQL'
            INSERT INTO purchase_returns (
                id, return_code, return_date, purchase_receive_id, supplier_id,
                branch_id, warehouse_id, sub_total, discount_amount, tax_amount,
                total_amount, status, journal_entry_id,
                is_reversed, reversed_at, reversed_by, reverse_reason,
                notes, reason, created_by, created_at, updated_at, deleted_at
            )
            OVERRIDING SYSTEM VALUE
            SELECT
                id, return_code, return_date, purchase_receive_id, supplier_id,
                branch_id, warehouse_id, sub_total, discount_amount, tax_amount,
                total_amount, status, journal_entry_id,
                is_reversed, reversed_at, reversed_by, reverse_reason,
                notes, reason, created_by, created_at, updated_at, deleted_at
            FROM purchase_returns_unpartitioned
            ORDER BY return_date, id
        SQL);

        // ── Flush deferred FK triggers before creating indexes ──
        DB::statement('SET CONSTRAINTS ALL IMMEDIATE');

        $this->fixSequence('purchase_returns');

        DB::statement('CREATE INDEX idx_prtn_receive ON purchase_returns (purchase_receive_id)');
        DB::statement('CREATE INDEX idx_prtn_supplier ON purchase_returns (supplier_id)');
        DB::statement('CREATE INDEX idx_prtn_branch ON purchase_returns (branch_id)');
        DB::statement('CREATE INDEX idx_prtn_journal ON purchase_returns (journal_entry_id)');
        DB::statement('CREATE INDEX idx_prtn_reversed ON purchase_returns (is_reversed, reversed_at)');
        DB::statement('CREATE INDEX idx_prtn_status ON purchase_returns (status)');
        DB::statement(<<<'SQL'
            CREATE INDEX idx_prtn_pending ON purchase_returns (supplier_id, branch_id)
                WHERE is_reversed=false
        SQL);
        DB::statement(<<<'SQL'
            CREATE INDEX idx_prtn_return_date_brin
                ON purchase_returns USING BRIN (return_date)
                WITH (pages_per_range = 32)
        SQL);

        DB::statement(<<<'SQL'
            CREATE OR REPLACE FUNCTION trg_purchase_returns_updated_at()
            RETURNS TRIGGER AS $$
            BEGIN NEW.updated_at = CURRENT_TIMESTAMP; RETURN NEW; END;
            $$ LANGUAGE plpgsql
        SQL);
        DB::statement(<<<'SQL'
            CREATE TRIGGER trg_purchase_returns_updated_at
                BEFORE UPDATE ON purchase_returns
                FOR EACH ROW EXECUTE FUNCTION trg_purchase_returns_updated_at()
        SQL);

        DB::statement('ALTER TABLE purchase_returns ENABLE ROW LEVEL SECURITY');
        DB::statement('ALTER TABLE purchase_returns FORCE ROW LEVEL SECURITY');
        DB::statement(<<<'SQL'
            CREATE POLICY rls_purchase_returns_select ON purchase_returns
                FOR SELECT USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_purchase_returns_insert ON purchase_returns
                FOR INSERT WITH CHECK (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_purchase_returns_update ON purchase_returns
                FOR UPDATE USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
                WITH CHECK (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_purchase_returns_delete ON purchase_returns
                FOR DELETE USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_purchase_returns_admin ON purchase_returns
                FOR ALL USING (current_setting('app.is_admin', true) = 'true')
                WITH CHECK (current_setting('app.is_admin', true) = 'true')
        SQL);

        DB::statement('DROP TABLE purchase_returns_unpartitioned');
        $this->registerPartman('purchase_returns', 'return_date', '2027-01-01');
        DB::statement('ANALYZE purchase_returns');
    }

    // ═══════════════════════════════════════════════════════════════
    //  8. damage_invoices  (children: damage_invoice_items, damage_attachments, sales_return_items)
    // ═══════════════════════════════════════════════════════════════

    private function partitionDamageInvoices(): void
    {
        if ($this->isAlreadyPartitioned('damage_invoices')) {
            return;
        }

        // ── Convert inbound FKs to trigger-based ──
        // 1. damage_invoice_items.damage_invoice_id → damage_invoices(id) ON DELETE CASCADE
        $this->dropFkConstraint('damage_invoice_items', 'damage_invoice_items_damage_invoice_id_foreign');
        $this->createTriggerFkCheck(
            'damage_invoice_items', 'damage_invoice_id', 'damage_invoices',
            'trg_fk_dii_dmg_check', 'trg_dii_dmg_fk_check'
        );
        $this->createTriggerFkCascadeDelete(
            'damage_invoice_items', 'damage_invoice_id', 'damage_invoices',
            'trg_fk_dmg_cascade_dii', 'trg_dmg_cascade_dii'
        );

        // 2. damage_attachments.damage_invoice_id → damage_invoices(id) ON DELETE CASCADE
        $this->dropFkConstraint('damage_attachments', 'damage_attachments_damage_invoice_id_foreign');
        $this->createTriggerFkCheck(
            'damage_attachments', 'damage_invoice_id', 'damage_invoices',
            'trg_fk_da_dmg_check', 'trg_da_dmg_fk_check'
        );
        $this->createTriggerFkCascadeDelete(
            'damage_attachments', 'damage_invoice_id', 'damage_invoices',
            'trg_fk_dmg_cascade_da', 'trg_dmg_cascade_da'
        );

        // 3. sales_return_items.damage_invoice_id → damage_invoices(id) ON DELETE SET NULL
        $this->dropFkConstraint('sales_return_items', 'fk_sri_damage_invoice');
        $this->createTriggerFkSetNull(
            'sales_return_items', 'damage_invoice_id', 'damage_invoices',
            'trg_fk_dmg_setnull_sri', 'trg_dmg_setnull_sri'
        );

        // ── Also convert damage_invoices.employee_ledger_entry_id → employee_ledger(id) ──
        // employee_ledger is now partitioned (Phase 2), so this FK must be trigger-based
        $this->dropFkConstraint('damage_invoices', 'damage_invoices_employee_ledger_entry_id_foreign');
        $this->createTriggerFkCheck(
            'damage_invoices', 'employee_ledger_entry_id', 'employee_ledger',
            'trg_fk_dmg_el_check', 'trg_dmg_el_fk_check'
        );

        // ── Partition damage_invoices ──
        $this->dropIndexesExceptPK('damage_invoices');
        $this->dropRlsPolicies('damage_invoices');

        DB::statement('ALTER TABLE damage_invoices RENAME TO damage_invoices_unpartitioned');

        DB::statement(<<<'SQL'
            CREATE TABLE damage_invoices (
                id                          INTEGER GENERATED BY DEFAULT AS IDENTITY,
                damage_code                 VARCHAR(30) NOT NULL,
                damage_date                 DATE NOT NULL,
                warehouse_id                INTEGER NOT NULL REFERENCES warehouses(id) DEFERRABLE INITIALLY DEFERRED,
                sales_return_id             INTEGER,
                branch_id                   INTEGER NOT NULL REFERENCES branches(id) DEFERRABLE INITIALLY DEFERRED,
                total_value                 NUMERIC(14,2) DEFAULT 0,
                status                      VARCHAR(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','submitted','approved','confirmed','cancelled','rejected')),
                damage_type                 VARCHAR(30) NOT NULL DEFAULT 'real_damage' CHECK (damage_type IN ('real_damage','missing','theft','quality_reject','customer_return','other')),
                reason                      TEXT,
                reason_code                 VARCHAR(50),
                reason_detail               TEXT,
                journal_entry_id            INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                is_reversed                 BOOLEAN NOT NULL DEFAULT false,
                reversed_at                 TIMESTAMP(0),
                reversed_by                 INTEGER,
                reverse_reason              TEXT,
                created_by                  INTEGER,
                witness_employee_id         INTEGER REFERENCES employees(id) ON DELETE NO ACTION,
                accountable_employee_id      INTEGER REFERENCES employees(id) ON DELETE NO ACTION,
                recovery_amount             NUMERIC(14,2) DEFAULT 0,
                employee_ledger_entry_id    INTEGER,
                recovery_journal_entry_id   INTEGER REFERENCES journal_entries(id) ON DELETE NO ACTION,
                submitted_by                INTEGER,
                submitted_at                TIMESTAMP,
                approved_by                 INTEGER,
                approved_at                 TIMESTAMP,
                approval_rejected_by        INTEGER,
                approval_rejected_at        TIMESTAMP,
                approval_notes              TEXT,
                created_at                  TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                updated_at                  TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                deleted_at                  TIMESTAMP(0),
                PRIMARY KEY (id, damage_date),
                CONSTRAINT damage_invoices_code_unique UNIQUE (damage_code, damage_date)
            ) PARTITION BY RANGE (damage_date)
        SQL);

        $this->createPreYearPartition('damage_invoices', 'pre2026', '2026');
        $this->createMonthlyPartitions('damage_invoices', '2026');

        DB::statement(<<<'SQL'
            INSERT INTO damage_invoices (
                id, damage_code, damage_date, warehouse_id, sales_return_id,
                branch_id, total_value, status, damage_type,
                reason, reason_code, reason_detail, journal_entry_id,
                is_reversed, reversed_at, reversed_by, reverse_reason,
                created_by, witness_employee_id, accountable_employee_id,
                recovery_amount, employee_ledger_entry_id, recovery_journal_entry_id,
                submitted_by, submitted_at, approved_by, approved_at,
                approval_rejected_by, approval_rejected_at, approval_notes,
                created_at, updated_at, deleted_at
            )
            OVERRIDING SYSTEM VALUE
            SELECT
                id, damage_code, damage_date, warehouse_id, sales_return_id,
                branch_id, total_value, status, damage_type,
                reason, reason_code, reason_detail, journal_entry_id,
                is_reversed, reversed_at, reversed_by, reverse_reason,
                created_by, witness_employee_id, accountable_employee_id,
                recovery_amount, employee_ledger_entry_id, recovery_journal_entry_id,
                submitted_by, submitted_at, approved_by, approved_at,
                approval_rejected_by, approval_rejected_at, approval_notes,
                created_at, updated_at, deleted_at
            FROM damage_invoices_unpartitioned
            ORDER BY damage_date, id
        SQL);

        // ── Flush deferred FK triggers before creating indexes ──
        DB::statement('SET CONSTRAINTS ALL IMMEDIATE');

        $this->fixSequence('damage_invoices');

        // Recreate indexes
        DB::statement('CREATE INDEX idx_dmg_journal ON damage_invoices (journal_entry_id)');
        DB::statement(<<<'SQL'
            CREATE INDEX idx_dmg_sales_return ON damage_invoices (sales_return_id)
                WHERE sales_return_id IS NOT NULL
        SQL);
        DB::statement('CREATE INDEX idx_dmg_type ON damage_invoices (damage_type)');
        DB::statement(<<<'SQL'
            CREATE INDEX idx_dmg_accountable ON damage_invoices (accountable_employee_id)
                WHERE accountable_employee_id IS NOT NULL
        SQL);
        DB::statement(<<<'SQL'
            CREATE INDEX idx_dmg_witness ON damage_invoices (witness_employee_id)
                WHERE witness_employee_id IS NOT NULL
        SQL);
        DB::statement(<<<'SQL'
            CREATE INDEX idx_dmg_recovery ON damage_invoices (accountable_employee_id)
                WHERE accountable_employee_id IS NOT NULL AND recovery_amount=0 AND status='confirmed'
        SQL);
        DB::statement(<<<'SQL'
            CREATE INDEX idx_dmg_submitted ON damage_invoices (branch_id, submitted_at)
                WHERE status='submitted'
        SQL);
        DB::statement(<<<'SQL'
            CREATE INDEX idx_dmg_approved_pending ON damage_invoices (branch_id, approved_at)
                WHERE status='approved'
        SQL);
        DB::statement(<<<'SQL'
            CREATE INDEX idx_dmg_dashboard ON damage_invoices (approved_by, approved_at)
                WHERE is_reversed=false
        SQL);
        DB::statement(<<<'SQL'
            CREATE INDEX idx_dmg_damage_date_brin
                ON damage_invoices USING BRIN (damage_date)
                WITH (pages_per_range = 32)
        SQL);

        // Recreate triggers
        DB::statement(<<<'SQL'
            CREATE OR REPLACE FUNCTION trg_damage_invoices_updated_at()
            RETURNS TRIGGER AS $$
            BEGIN NEW.updated_at = CURRENT_TIMESTAMP; RETURN NEW; END;
            $$ LANGUAGE plpgsql
        SQL);
        DB::statement(<<<'SQL'
            CREATE TRIGGER trg_damage_invoices_updated_at
                BEFORE UPDATE ON damage_invoices
                FOR EACH ROW EXECUTE FUNCTION trg_damage_invoices_updated_at()
        SQL);

        DB::statement(<<<'SQL'
            CREATE OR REPLACE FUNCTION trg_notify_damage_invoices()
            RETURNS TRIGGER AS $$
            BEGIN
                PERFORM pg_notify('rcerp_damage_change', json_build_object('action', TG_OP, 'id', NEW.id)::text);
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql
        SQL);
        DB::statement(<<<'SQL'
            CREATE TRIGGER trg_notify_damage_invoices
                AFTER INSERT OR UPDATE ON damage_invoices
                FOR EACH ROW EXECUTE FUNCTION trg_notify_damage_invoices()
        SQL);

        DB::statement('ALTER TABLE damage_invoices ENABLE ROW LEVEL SECURITY');
        DB::statement('ALTER TABLE damage_invoices FORCE ROW LEVEL SECURITY');
        DB::statement(<<<'SQL'
            CREATE POLICY rls_damage_invoices_select ON damage_invoices
                FOR SELECT USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_damage_invoices_insert ON damage_invoices
                FOR INSERT WITH CHECK (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_damage_invoices_update ON damage_invoices
                FOR UPDATE USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
                WITH CHECK (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_damage_invoices_delete ON damage_invoices
                FOR DELETE USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_damage_invoices_admin ON damage_invoices
                FOR ALL USING (current_setting('app.is_admin', true) = 'true')
                WITH CHECK (current_setting('app.is_admin', true) = 'true')
        SQL);

        DB::statement('DROP TABLE damage_invoices_unpartitioned');
        $this->registerPartman('damage_invoices', 'damage_date', '2027-01-01');
        DB::statement('ANALYZE damage_invoices');
    }

    // ═══════════════════════════════════════════════════════════════
    //  9. manual_journals  (child: manual_journal_lines)
    // ═══════════════════════════════════════════════════════════════

    private function partitionManualJournals(): void
    {
        if ($this->isAlreadyPartitioned('manual_journals')) {
            return;
        }

        // Convert inbound FK to trigger-based
        $this->dropFkConstraint('manual_journal_lines', 'manual_journal_lines_manual_journal_id_foreign');
        $this->createTriggerFkCheck(
            'manual_journal_lines', 'manual_journal_id', 'manual_journals',
            'trg_fk_mjl_mj_check', 'trg_mjl_mj_fk_check'
        );
        $this->createTriggerFkCascadeDelete(
            'manual_journal_lines', 'manual_journal_id', 'manual_journals',
            'trg_fk_mj_cascade_mjl', 'trg_mj_cascade_mjl'
        );

        $this->dropIndexesExceptPK('manual_journals');
        $this->dropRlsPolicies('manual_journals');

        DB::statement('ALTER TABLE manual_journals RENAME TO manual_journals_unpartitioned');

        DB::statement(<<<'SQL'
            CREATE TABLE manual_journals (
                id                  INTEGER GENERATED BY DEFAULT AS IDENTITY,
                journal_code        VARCHAR(30) NOT NULL,
                journal_date        DATE NOT NULL,
                branch_id           INTEGER NOT NULL,
                description         TEXT,
                total_debit         NUMERIC(15,2) NOT NULL DEFAULT 0,
                total_credit        NUMERIC(15,2) NOT NULL DEFAULT 0,
                status              VARCHAR(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','submitted','approved','posted','reversed','rejected')),
                journal_entry_id    INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                created_by          INTEGER,
                reversed_by         INTEGER,
                reversed_at         TIMESTAMP,
                reverse_reason      VARCHAR(500),
                deleted_at          TIMESTAMP(0),
                created_at          TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                updated_at          TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                submitted_by        INTEGER,
                submitted_at        TIMESTAMP,
                approved_by         INTEGER,
                approved_at         TIMESTAMP,
                approval_comments   TEXT,
                rejected_by         INTEGER,
                rejected_at         TIMESTAMP,
                PRIMARY KEY (id, journal_date),
                CONSTRAINT manual_journals_code_unique UNIQUE (journal_code, journal_date)
            ) PARTITION BY RANGE (journal_date)
        SQL);

        $this->createPreYearPartition('manual_journals', 'pre2026', '2026');
        $this->createMonthlyPartitions('manual_journals', '2026');

        DB::statement(<<<'SQL'
            INSERT INTO manual_journals (
                id, journal_code, journal_date, branch_id, description,
                total_debit, total_credit, status, journal_entry_id,
                created_by, reversed_by, reversed_at, reverse_reason,
                deleted_at, created_at, updated_at,
                submitted_by, submitted_at, approved_by, approved_at,
                approval_comments, rejected_by, rejected_at
            )
            OVERRIDING SYSTEM VALUE
            SELECT
                id, journal_code, journal_date, branch_id, description,
                total_debit, total_credit, status, journal_entry_id,
                created_by, reversed_by, reversed_at, reverse_reason,
                deleted_at, created_at, updated_at,
                submitted_by, submitted_at, approved_by, approved_at,
                approval_comments, rejected_by, rejected_at
            FROM manual_journals_unpartitioned
            ORDER BY journal_date, id
        SQL);

        // ── Flush deferred FK triggers before creating indexes ──
        DB::statement('SET CONSTRAINTS ALL IMMEDIATE');

        $this->fixSequence('manual_journals');

        // Recreate indexes
        DB::statement('CREATE INDEX idx_mj_branch_date ON manual_journals (branch_id, journal_date)');
        DB::statement('CREATE INDEX idx_mj_journal ON manual_journals (journal_entry_id)');
        DB::statement(<<<'SQL'
            CREATE INDEX idx_mj_reversed_by ON manual_journals (reversed_by)
                WHERE reversed_by IS NOT NULL
        SQL);
        DB::statement('CREATE INDEX idx_mj_status ON manual_journals (status)');
        DB::statement('CREATE INDEX idx_mj_submitted ON manual_journals (status, submitted_at)');
        DB::statement(<<<'SQL'
            CREATE INDEX idx_mj_journal_date_brin
                ON manual_journals USING BRIN (journal_date)
                WITH (pages_per_range = 32)
        SQL);

        DB::statement(<<<'SQL'
            CREATE OR REPLACE FUNCTION trg_manual_journals_updated_at()
            RETURNS TRIGGER AS $$
            BEGIN NEW.updated_at = CURRENT_TIMESTAMP; RETURN NEW; END;
            $$ LANGUAGE plpgsql
        SQL);
        DB::statement(<<<'SQL'
            CREATE TRIGGER trg_manual_journals_updated_at
                BEFORE UPDATE ON manual_journals
                FOR EACH ROW EXECUTE FUNCTION trg_manual_journals_updated_at()
        SQL);

        DB::statement('ALTER TABLE manual_journals ENABLE ROW LEVEL SECURITY');
        DB::statement('ALTER TABLE manual_journals FORCE ROW LEVEL SECURITY');
        DB::statement(<<<'SQL'
            CREATE POLICY rls_manual_journals_select ON manual_journals
                FOR SELECT USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_manual_journals_insert ON manual_journals
                FOR INSERT WITH CHECK (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_manual_journals_update ON manual_journals
                FOR UPDATE USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
                WITH CHECK (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_manual_journals_delete ON manual_journals
                FOR DELETE USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_manual_journals_admin ON manual_journals
                FOR ALL USING (current_setting('app.is_admin', true) = 'true')
                WITH CHECK (current_setting('app.is_admin', true) = 'true')
        SQL);

        // Recreate financial audit trigger
        DB::statement(<<<'SQL'
            CREATE TRIGGER trg_audit_manual_journals
                AFTER INSERT OR UPDATE OR DELETE ON manual_journals
                FOR EACH ROW EXECUTE FUNCTION fn_financial_audit_trigger()
        SQL);

        DB::statement('DROP TABLE manual_journals_unpartitioned');
        $this->registerPartman('manual_journals', 'journal_date', '2027-01-01');
        DB::statement('ANALYZE manual_journals');
    }

    // ── Rollback ──────────────────────────────────────────────────

    public function down(): void
    {
        // Reverse order to handle dependencies
        $this->rollbackManualJournals();
        $this->rollbackDamageInvoices();
        $this->rollbackPurchaseReturns();
        $this->rollbackPurchaseReceives();
        $this->rollbackSalesReturns();
        $this->rollbackOtherExpenses();
        $this->rollbackOtherIncomes();
        $this->rollbackEmployeeTransactions();
        $this->rollbackMoneyTransfers();
    }

    /**
     * Generic rollback: detach all partitions, create flat table, copy data,
     * drop partitioned parent, rename flat table.
     */
    private function rollbackPartitionedTable(
        string $tableName,
        string $createFlatSQL,
        array $columns,
        array $indexDefinitions,
        array $rlsPolicyDefinitions,
        array $triggerDefinitions = []
    ): void {
        if (! $this->isAlreadyPartitioned($tableName)) {
            return;
        }

        $tempName = "{$tableName}_flat";
        $partitions = DB::select("
            SELECT c.relname
            FROM pg_inherits i
            JOIN pg_class c ON c.oid = i.inhrelid
            JOIN pg_class p ON p.oid = i.inhparent
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE p.relname = ? AND n.nspname = current_schema()
        ", [$tableName]);

        foreach ($partitions as $part) {
            DB::statement("ALTER TABLE {$tableName} DETACH PARTITION {$part->relname}");
        }

        DB::statement($createFlatSQL);

        $colList = implode(', ', $columns);
        foreach ($partitions as $part) {
            DB::statement(<<<SQL
                INSERT INTO {$tempName} ({$colList})
                SELECT {$colList} FROM {$part->relname}
                ORDER BY id
            SQL);
        }
        $parentCount = DB::selectOne("SELECT count(*) AS cnt FROM ONLY {$tableName}")->cnt;
        if ($parentCount > 0) {
            DB::statement(<<<SQL
                INSERT INTO {$tempName} ({$colList})
                SELECT {$colList} FROM ONLY {$tableName} ORDER BY id
            SQL);
        }

        $this->fixSequence($tempName);

        foreach ($indexDefinitions as $idxSQL) {
            DB::statement($idxSQL);
        }

        DB::statement("DROP TABLE {$tableName}");
        foreach ($partitions as $part) {
            DB::statement("DROP TABLE IF EXISTS {$part->relname}");
        }

        DB::statement("ALTER TABLE {$tempName} RENAME TO {$tableName}");

        // Recreate triggers
        foreach ($triggerDefinitions as $triggerSQL) {
            DB::statement($triggerSQL);
        }

        // Recreate RLS
        DB::statement("ALTER TABLE {$tableName} ENABLE ROW LEVEL SECURITY");
        DB::statement("ALTER TABLE {$tableName} FORCE ROW LEVEL SECURITY");
        foreach ($rlsPolicyDefinitions as $policySQL) {
            DB::statement($policySQL);
        }

        DB::statement("ANALYZE {$tableName}");
    }

    // Individual rollback methods — each creates a flat table matching
    // the ORIGINAL schema (PK(id) only, UNIQUE without date column)

    private function rollbackMoneyTransfers(): void
    {
        $this->rollbackPartitionedTable('money_transfers',
            <<<'SQL'
                CREATE TABLE money_transfers_flat (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    transfer_code VARCHAR(50) NOT NULL,
                    transfer_date DATE NOT NULL,
                    from_branch_id INTEGER NOT NULL REFERENCES branches(id) DEFERRABLE INITIALLY DEFERRED,
                    to_branch_id INTEGER NOT NULL REFERENCES branches(id) DEFERRABLE INITIALLY DEFERRED,
                    transfer_type VARCHAR(20) NOT NULL CHECK (transfer_type IN ('cash_to_bank','bank_to_cash','cash_to_cash','bank_to_bank')),
                    from_bank_id INTEGER REFERENCES banks(id) DEFERRABLE INITIALLY DEFERRED,
                    to_bank_id INTEGER REFERENCES banks(id) DEFERRABLE INITIALLY DEFERRED,
                    amount NUMERIC(14,2) NOT NULL DEFAULT 0,
                    journal_entry_id INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                    intercompany_journal_entry_id INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                    is_reversed BOOLEAN NOT NULL DEFAULT false,
                    reversed_at TIMESTAMP(0), reversed_by INTEGER,
                    reverse_reason TEXT, notes TEXT, created_by INTEGER,
                    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT money_transfers_code_unique UNIQUE (transfer_code)
                )
            SQL,
            ['id','transfer_code','transfer_date','from_branch_id','to_branch_id','transfer_type','from_bank_id','to_bank_id','amount','journal_entry_id','intercompany_journal_entry_id','is_reversed','reversed_at','reversed_by','reverse_reason','notes','created_by','created_at','updated_at'],
            ['CREATE INDEX idx_mt_branches ON money_transfers_flat (from_branch_id, to_branch_id)',
             'CREATE INDEX idx_mt_journal ON money_transfers_flat (journal_entry_id)'],
            ["CREATE POLICY rls_money_transfers_select ON money_transfers FOR SELECT USING (current_setting('app.is_admin', true) = 'true' OR from_branch_id = current_setting('app.branch_id')::int OR to_branch_id = current_setting('app.branch_id')::int)",
             "CREATE POLICY rls_money_transfers_insert ON money_transfers FOR INSERT WITH CHECK (current_setting('app.is_admin', true) = 'true' OR from_branch_id = current_setting('app.branch_id')::int OR to_branch_id = current_setting('app.branch_id')::int)",
             "CREATE POLICY rls_money_transfers_update ON money_transfers FOR UPDATE USING (current_setting('app.is_admin', true) = 'true' OR from_branch_id = current_setting('app.branch_id')::int OR to_branch_id = current_setting('app.branch_id')::int) WITH CHECK (current_setting('app.is_admin', true) = 'true' OR from_branch_id = current_setting('app.branch_id')::int OR to_branch_id = current_setting('app.branch_id')::int)",
             "CREATE POLICY rls_money_transfers_delete ON money_transfers FOR DELETE USING (current_setting('app.is_admin', true) = 'true' OR from_branch_id = current_setting('app.branch_id')::int OR to_branch_id = current_setting('app.branch_id')::int)",
             "CREATE POLICY rls_money_transfers_admin ON money_transfers FOR ALL USING (current_setting('app.is_admin', true) = 'true') WITH CHECK (current_setting('app.is_admin', true) = 'true')"],
            ["CREATE TRIGGER trg_money_transfers_updated_at BEFORE UPDATE ON money_transfers FOR EACH ROW EXECUTE FUNCTION trg_money_transfers_updated_at()"]
        );
    }

    private function rollbackEmployeeTransactions(): void
    {
        $this->rollbackPartitionedTable('employee_transactions',
            <<<'SQL'
                CREATE TABLE employee_transactions_flat (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    transaction_code VARCHAR(30) NOT NULL,
                    transaction_date DATE NOT NULL,
                    employee_id INTEGER NOT NULL REFERENCES employees(id) DEFERRABLE INITIALLY DEFERRED,
                    branch_id INTEGER NOT NULL REFERENCES branches(id) DEFERRABLE INITIALLY DEFERRED,
                    transaction_type VARCHAR(20) NOT NULL CHECK (transaction_type IN ('advance','loan','repayment','salary','deduction','adjustment')),
                    payment_mode VARCHAR(20) NOT NULL DEFAULT 'cash' CHECK (payment_mode IN ('cash','bank','mobile_banking','cheque','adjustment')),
                    bank_id INTEGER REFERENCES banks(id) ON DELETE SET NULL,
                    collected_by INTEGER REFERENCES employees(id) ON DELETE SET NULL,
                    amount NUMERIC(14,2) NOT NULL DEFAULT 0,
                    description TEXT,
                    journal_entry_id INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                    intercompany_journal_entry_id INTEGER REFERENCES journal_entries(id) ON DELETE SET NULL,
                    is_reversed BOOLEAN NOT NULL DEFAULT false,
                    reversed_at TIMESTAMP(0), reversed_by INTEGER,
                    reverse_reason TEXT, created_by INTEGER,
                    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT employee_transactions_code_unique UNIQUE (transaction_code)
                )
            SQL,
            ['id','transaction_code','transaction_date','employee_id','branch_id','transaction_type','payment_mode','bank_id','collected_by','amount','description','journal_entry_id','intercompany_journal_entry_id','is_reversed','reversed_at','reversed_by','reverse_reason','created_by','created_at','updated_at'],
            ['CREATE INDEX idx_et_employee ON employee_transactions_flat (employee_id)',
             'CREATE INDEX idx_et_journal ON employee_transactions_flat (journal_entry_id)'],
            ["CREATE POLICY rls_employee_transactions_select ON employee_transactions FOR SELECT USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)",
             "CREATE POLICY rls_employee_transactions_insert ON employee_transactions FOR INSERT WITH CHECK (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)",
             "CREATE POLICY rls_employee_transactions_update ON employee_transactions FOR UPDATE USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int) WITH CHECK (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)",
             "CREATE POLICY rls_employee_transactions_delete ON employee_transactions FOR DELETE USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)",
             "CREATE POLICY rls_employee_transactions_admin ON employee_transactions FOR ALL USING (current_setting('app.is_admin', true) = 'true') WITH CHECK (current_setting('app.is_admin', true) = 'true')"],
            ["CREATE TRIGGER trg_employee_transactions_updated_at BEFORE UPDATE ON employee_transactions FOR EACH ROW EXECUTE FUNCTION trg_employee_transactions_updated_at()"]
        );
    }

    private function rollbackOtherIncomes(): void
    {
        $this->rollbackPartitionedTable('other_incomes',
            <<<'SQL'
                CREATE TABLE other_incomes_flat (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    income_code VARCHAR(30) NOT NULL,
                    income_date DATE NOT NULL,
                    branch_id INTEGER NOT NULL REFERENCES branches(id) DEFERRABLE INITIALLY DEFERRED,
                    bank_id INTEGER REFERENCES banks(id) DEFERRABLE INITIALLY DEFERRED,
                    payment_mode VARCHAR(20) NOT NULL DEFAULT 'cash',
                    income_type VARCHAR(50),
                    amount NUMERIC(14,2) NOT NULL DEFAULT 0,
                    description TEXT,
                    journal_entry_id INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                    is_reversed BOOLEAN NOT NULL DEFAULT false,
                    reversed_at TIMESTAMP(0), reversed_by INTEGER,
                    reverse_reason TEXT, created_by INTEGER,
                    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT other_incomes_code_unique UNIQUE (income_code)
                )
            SQL,
            ['id','income_code','income_date','branch_id','bank_id','payment_mode','income_type','amount','description','journal_entry_id','is_reversed','reversed_at','reversed_by','reverse_reason','created_by','created_at','updated_at'],
            ['CREATE INDEX idx_oi_journal ON other_incomes_flat (journal_entry_id)'],
            ["CREATE POLICY rls_other_incomes_select ON other_incomes FOR SELECT USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)",
             "CREATE POLICY rls_other_incomes_insert ON other_incomes FOR INSERT WITH CHECK (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)",
             "CREATE POLICY rls_other_incomes_update ON other_incomes FOR UPDATE USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int) WITH CHECK (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)",
             "CREATE POLICY rls_other_incomes_delete ON other_incomes FOR DELETE USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)",
             "CREATE POLICY rls_other_incomes_admin ON other_incomes FOR ALL USING (current_setting('app.is_admin', true) = 'true') WITH CHECK (current_setting('app.is_admin', true) = 'true')"],
            ["CREATE TRIGGER trg_other_incomes_updated_at BEFORE UPDATE ON other_incomes FOR EACH ROW EXECUTE FUNCTION trg_other_incomes_updated_at()"]
        );
    }

    private function rollbackOtherExpenses(): void
    {
        $this->rollbackPartitionedTable('other_expenses',
            <<<'SQL'
                CREATE TABLE other_expenses_flat (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    expense_code VARCHAR(30) NOT NULL,
                    expense_date DATE NOT NULL,
                    branch_id INTEGER NOT NULL REFERENCES branches(id) DEFERRABLE INITIALLY DEFERRED,
                    bank_id INTEGER REFERENCES banks(id) DEFERRABLE INITIALLY DEFERRED,
                    payment_mode VARCHAR(20) NOT NULL DEFAULT 'cash',
                    expense_type VARCHAR(50),
                    amount NUMERIC(14,2) NOT NULL DEFAULT 0,
                    description TEXT,
                    journal_entry_id INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                    is_reversed BOOLEAN NOT NULL DEFAULT false,
                    reversed_at TIMESTAMP(0), reversed_by INTEGER,
                    reverse_reason TEXT, created_by INTEGER,
                    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT other_expenses_code_unique UNIQUE (expense_code)
                )
            SQL,
            ['id','expense_code','expense_date','branch_id','bank_id','payment_mode','expense_type','amount','description','journal_entry_id','is_reversed','reversed_at','reversed_by','reverse_reason','created_by','created_at','updated_at'],
            ['CREATE INDEX idx_oe_journal ON other_expenses_flat (journal_entry_id)'],
            ["CREATE POLICY rls_other_expenses_select ON other_expenses FOR SELECT USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)",
             "CREATE POLICY rls_other_expenses_insert ON other_expenses FOR INSERT WITH CHECK (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)",
             "CREATE POLICY rls_other_expenses_update ON other_expenses FOR UPDATE USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int) WITH CHECK (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)",
             "CREATE POLICY rls_other_expenses_delete ON other_expenses FOR DELETE USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)",
             "CREATE POLICY rls_other_expenses_admin ON other_expenses FOR ALL USING (current_setting('app.is_admin', true) = 'true') WITH CHECK (current_setting('app.is_admin', true) = 'true')"],
            ["CREATE TRIGGER trg_other_expenses_updated_at BEFORE UPDATE ON other_expenses FOR EACH ROW EXECUTE FUNCTION trg_other_expenses_updated_at()"]
        );
    }

    private function rollbackSalesReturns(): void { /* Trigger-based FK reversal is complex — kept for manual rollback */ }
    private function rollbackPurchaseReceives(): void { /* Trigger-based FK reversal is complex — kept for manual rollback */ }
    private function rollbackPurchaseReturns(): void { /* Trigger-based FK reversal is complex — kept for manual rollback */ }
    private function rollbackDamageInvoices(): void { /* Trigger-based FK reversal is complex — kept for manual rollback */ }
    private function rollbackManualJournals(): void { /* Trigger-based FK reversal is complex — kept for manual rollback */ }
};
