<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Phase 10.1 — Phase 2: Sub-Ledger Partitioning (Low Risk).
 *
 * Partitions all 5 sub-ledger tables by transaction_date (RANGE, monthly).
 * These are append-only, high-growth tables that benefit from date-range
 * partitioning and BRIN indexes.
 *
 * Tables (in order):
 *   1. customer_ledger   — partition by transaction_date (0 FK children, RLS)
 *   2. supplier_ledger   — partition by transaction_date (0 FK children, RLS)
 *   3. employee_ledger   — partition by transaction_date (0 FK children, RLS)
 *   4. cash_ledger       — partition by transaction_date (0 FK children, RLS)
 *   5. branch_ledger     — partition by transaction_date (0 FK children, RLS dual-branch)
 *
 * DESIGN DECISIONS:
 *
 * 1. Partition key: All sub-ledgers use RANGE by transaction_date with monthly
 *    partitions. This enables:
 *    - Partition pruning for aging report queries (WHERE transaction_date BETWEEN ...)
 *    - Easy archival of old months (DETACH PARTITION)
 *    - Faster VACUUM per partition
 *    - Partition-wise joins with journal_entries (Phase 6/7) when both use
 *      compatible date-based partitioning
 *
 * 2. Composite PK: On partitioned tables, the PK must include the partition
 *    key. All tables change from PK(id) to PK(id, transaction_date).
 *    GENERATED ALWAYS AS IDENTITY → GENERATED BY DEFAULT AS IDENTITY to
 *    allow OVERRIDING SYSTEM VALUE during data copy.
 *
 * 3. BRIN indexes: Replace B-tree indexes on transaction_date with BRIN.
 *    Sub-ledgers are append-only and naturally ordered by transaction_date,
 *    making BRIN 100-300x smaller and equally effective.
 *
 * 4. Outbound FKs: FKs FROM these tables TO other tables (e.g.
 *    customer_ledger.customer_id → customers(id)) work normally on partitioned
 *    tables. They are included in the CREATE TABLE statement.
 *    NOTE: customer_ledger.journal_entry_id → journal_entries(id) is a standard
 *    outbound FK. When journal_entries is later partitioned (Phase 6), this FK
 *    will need to be converted to trigger-based.
 *
 * 5. RLS: RLS policies defined on the parent table automatically apply to
 *    all partitions. We drop policies on the old table and recreate on the
 *    new partitioned parent.
 *    - customer_ledger, supplier_ledger, employee_ledger, cash_ledger:
 *      single branch_id column
 *    - branch_ledger: dual-branch (from_branch_id OR to_branch_id)
 *
 * 6. Materialized views: mv_ar_aging, mv_ap_aging, mv_branch_intercompany
 *    reference sub-ledger tables. PostgreSQL tracks column-level dependencies,
 *    so we must DROP + recreate these MVs after the table swap.
 *
 * 7. cash_ledger special handling:
 *    - Uses `amount` instead of `debit`/`credit`
 *    - branch_id is NOT NULL (other sub-ledgers have nullable branch_id)
 *    - No `is_reversed` column
 *    - No Eloquent model (accessed via DB::table() only)
 *
 * 8. branch_ledger special handling:
 *    - Dual-branch RLS (from_branch_id OR to_branch_id)
 *    - Uses `running_balance` instead of `balance`
 *    - Uses `remarks` instead of `description`
 *    - No Eloquent model (accessed via DB::table() only)
 *    - reference_type is varchar(50) not varchar(30)
 *
 * MIGRATION STRATEGY (per table):
 *   a. Drop materialized views that reference the table
 *   b. Drop indexes on old table
 *   c. Drop RLS policies on old table
 *   d. Rename old table to _unpartitioned
 *   e. Create new partitioned table with composite PK + outbound FKs
 *   f. Create monthly partitions (2026-01 to 2026-12) + default partition
 *   g. Copy data from old table (OVERRIDING SYSTEM VALUE)
 *   h. Fix identity sequence
 *   i. Recreate indexes on parent (propagated to partitions)
 *   j. Recreate RLS policies on parent
 *   k. Drop old table
 *   l. Register with pg_partman
 *   m. Recreate materialized views
 *   n. Analyze
 *
 * ⚠️  This migration should be run during a maintenance window.
 *     It locks tables during the data copy phase.
 */
return new class extends Migration
{
    private ?bool $hasPgPartman = null;

    // ── Helper methods ──────────────────────────────────────────────

    private function hasPgPartman(): bool
    {
        if ($this->hasPgPartman !== null) {
            return $this->hasPgPartman;
        }
        $row = DB::selectOne("
            SELECT EXISTS (
                SELECT 1 FROM pg_available_extensions WHERE name = 'pg_partman'
            ) AS installed
        ");
        $this->hasPgPartman = (bool) ($row->installed ?? false);
        if (! $this->hasPgPartman) {
            logger()->warning('pg_partman is not installed. Automatic partition maintenance is disabled.');
        }
        return $this->hasPgPartman;
    }

    private function isAlreadyPartitioned(string $tableName): bool
    {
        $row = DB::selectOne("
            SELECT 1
            FROM pg_partitioned_table pt
            JOIN pg_class c ON c.oid = pt.partrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relname = ? AND n.nspname = current_schema()
            LIMIT 1
        ", [$tableName]);
        return $row !== null;
    }

    private function relationExists(string $name): bool
    {
        $row = DB::selectOne("
            SELECT 1
            FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relname = ? AND n.nspname = current_schema()
            LIMIT 1
        ", [$name]);
        return $row !== null;
    }

    private function indexExists(string $indexName): bool
    {
        $row = DB::selectOne(
            "SELECT 1 FROM pg_indexes WHERE indexname = ? LIMIT 1",
            [$indexName]
        );
        return $row !== null;
    }

    /**
     * Create 12 monthly partitions for a given year + a default partition.
     * Idempotent — skips partitions that already exist.
     */
    private function createMonthlyPartitions(string $parent, string $year): void
    {
        for ($m = 1; $m <= 12; $m++) {
            $from = sprintf('%s-%02d-01', $year, $m);
            $to   = $m < 12
                ? sprintf('%s-%02d-01', $year, $m + 1)
                : sprintf('%d-01-01', (int) $year + 1);
            $name = sprintf('%s_%s_%02d', $parent, $year, $m);

            if (! $this->relationExists($name)) {
                DB::statement(
                    "CREATE TABLE {$name} PARTITION OF {$parent}
                     FOR VALUES FROM ('{$from}') TO ('{$to}')"
                );
            }
        }

        $defaultName = "{$parent}_default";
        if (! $this->relationExists($defaultName)) {
            DB::statement(
                "CREATE TABLE {$defaultName} PARTITION OF {$parent} DEFAULT"
            );
        }
    }

    /**
     * Create a pre-year catch-all partition for historical data.
     * Idempotent — skips if it already exists.
     */
    private function createPreYearPartition(string $parent, string $preYear, string $startYear): void
    {
        $name = "{$parent}_{$preYear}";
        if (! $this->relationExists($name)) {
            DB::statement(
                "CREATE TABLE {$name} PARTITION OF {$parent}
                 FOR VALUES FROM ('2020-01-01') TO ('{$startYear}-01-01')"
            );
        }
    }

    /**
     * Register a table with pg_partman for automatic monthly partition creation.
     * Wrapped in try/catch so re-runs don't fail if already registered.
     */
    private function registerPartman(string $parent, string $control, string $startPartition): void
    {
        if (! $this->hasPgPartman()) {
            return;
        }
        try {
            DB::statement(<<<SQL
                SELECT partman.create_parent(
                    p_parent_table    := 'public.{$parent}',
                    p_control         := '{$control}',
                    p_type            := 'range',
                    p_interval        := '1 month',
                    p_premake         := 6,
                    p_start_partition := '{$startPartition}'
                )
            SQL);
        } catch (\Throwable $e) {
            // Already registered with pg_partman — safe to ignore.
        }
    }

    /**
     * Fix the identity sequence after data copy.
     */
    private function fixSequence(string $table): void
    {
        DB::statement(<<<SQL
            SELECT setval(
                pg_get_serial_sequence('{$table}', 'id'),
                GREATEST(COALESCE((SELECT MAX(id) FROM {$table}), 0), 1)
            )
        SQL);
    }

    /**
     * Drop all RLS policies on a table. Used before renaming the old table.
     */
    private function dropRlsPolicies(string $tableName): void
    {
        $policies = DB::select("
            SELECT polname
            FROM pg_policy p
            JOIN pg_class c ON c.oid = p.polrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relname = ? AND n.nspname = current_schema()
        ", [$tableName]);

        foreach ($policies as $policy) {
            DB::statement("DROP POLICY IF EXISTS {$policy->polname} ON {$tableName}");
        }
    }

    /**
     * Drop all indexes on a table (except the primary key).
     */
    private function dropIndexesExceptPK(string $tableName): void
    {
        $indexes = DB::select("
            SELECT indexname
            FROM pg_indexes
            WHERE tablename = ? AND indexname NOT LIKE '%_pkey'
        ", [$tableName]);

        foreach ($indexes as $idx) {
            DB::statement("DROP INDEX IF EXISTS {$idx->indexname}");
        }
    }

    // ── Main up() ───────────────────────────────────────────────────

    public function up(): void
    {
        // Install pg_partman if available
        if ($this->hasPgPartman()) {
            DB::statement('CREATE EXTENSION IF NOT EXISTS pg_partman');
            DB::statement('CREATE SCHEMA IF NOT EXISTS partman');
        }

        // ── Drop materialized views that reference sub-ledger tables ──
        // PostgreSQL tracks column-level dependencies and will block
        // ALTER TABLE ... RENAME if MVs depend on the table.
        $this->dropMaterializedViews();

        $this->partitionCustomerLedger();
        $this->partitionSupplierLedger();
        $this->partitionEmployeeLedger();
        $this->partitionCashLedger();
        $this->partitionBranchLedger();

        // ── Recreate materialized views against partitioned tables ──
        $this->recreateMaterializedViews();
    }

    // ═══════════════════════════════════════════════════════════════
    //  Materialized view helpers
    // ═══════════════════════════════════════════════════════════════

    private function dropMaterializedViews(): void
    {
        // Aging report MVs
        DB::statement('DROP MATERIALIZED VIEW IF EXISTS mv_ar_aging CASCADE');
        DB::statement('DROP MATERIALIZED VIEW IF EXISTS mv_ap_aging CASCADE');
        DB::statement('DROP MATERIALIZED VIEW IF EXISTS mv_branch_intercompany CASCADE');
        // Running balance check MVs
        DB::statement('DROP MATERIALIZED VIEW IF EXISTS mv_customer_ledger_balance_check CASCADE');
        DB::statement('DROP MATERIALIZED VIEW IF EXISTS mv_supplier_ledger_balance_check CASCADE');
        DB::statement('DROP MATERIALIZED VIEW IF EXISTS mv_employee_ledger_balance_check CASCADE');
        DB::statement('DROP MATERIALIZED VIEW IF EXISTS mv_cash_ledger_balance_check CASCADE');
    }

    private function recreateMaterializedViews(): void
    {
        // ── mv_ar_aging — customer receivable aging buckets ──
        // Must match original definition from 2025_01_03_000001 exactly.
        DB::statement(<<<'SQL'
            CREATE MATERIALIZED VIEW mv_ar_aging AS
            SELECT
                c.id AS customer_id,
                c.customer_code,
                c.customer_name,
                c.mobile,
                cl.branch_id,
                b.branch_name,
                SUM(CASE WHEN (CURRENT_DATE - cl.transaction_date) <= 30
                    THEN (cl.debit - cl.credit) ELSE 0 END) AS bucket_0_30,
                SUM(CASE WHEN (CURRENT_DATE - cl.transaction_date) BETWEEN 31 AND 60
                    THEN (cl.debit - cl.credit) ELSE 0 END) AS bucket_31_60,
                SUM(CASE WHEN (CURRENT_DATE - cl.transaction_date) BETWEEN 61 AND 90
                    THEN (cl.debit - cl.credit) ELSE 0 END) AS bucket_61_90,
                SUM(CASE WHEN (CURRENT_DATE - cl.transaction_date) > 90
                    THEN (cl.debit - cl.credit) ELSE 0 END) AS bucket_90_plus,
                SUM(cl.debit - cl.credit) AS total_receivable
            FROM customer_ledger cl
            INNER JOIN customers c ON c.id = cl.customer_id
            LEFT JOIN branches b ON b.id = cl.branch_id
            WHERE COALESCE(cl.is_reversed, false) = false
            GROUP BY c.id, c.customer_code, c.customer_name, c.mobile, cl.branch_id, b.branch_name
            HAVING SUM(cl.debit - cl.credit) > 0.005
        SQL);
        DB::statement('CREATE UNIQUE INDEX mv_ar_aging_customer_branch_idx ON mv_ar_aging (customer_id, branch_id)');
        DB::statement('CREATE INDEX mv_ar_aging_branch_idx ON mv_ar_aging (branch_id)');

        // ── mv_ap_aging — supplier payable aging buckets ──
        // Must match original definition from 2025_01_03_000001 exactly.
        DB::statement(<<<'SQL'
            CREATE MATERIALIZED VIEW mv_ap_aging AS
            SELECT
                s.id AS supplier_id,
                s.supplier_code,
                s.supplier_name,
                s.mobile,
                sl.branch_id,
                b.branch_name,
                SUM(CASE WHEN (CURRENT_DATE - sl.transaction_date) <= 30
                    THEN (sl.credit - sl.debit) ELSE 0 END) AS bucket_0_30,
                SUM(CASE WHEN (CURRENT_DATE - sl.transaction_date) BETWEEN 31 AND 60
                    THEN (sl.credit - sl.debit) ELSE 0 END) AS bucket_31_60,
                SUM(CASE WHEN (CURRENT_DATE - sl.transaction_date) BETWEEN 61 AND 90
                    THEN (sl.credit - sl.debit) ELSE 0 END) AS bucket_61_90,
                SUM(CASE WHEN (CURRENT_DATE - sl.transaction_date) > 90
                    THEN (sl.credit - sl.debit) ELSE 0 END) AS bucket_90_plus,
                SUM(sl.credit - sl.debit) AS total_payable
            FROM supplier_ledger sl
            INNER JOIN suppliers s ON s.id = sl.supplier_id
            LEFT JOIN branches b ON b.id = sl.branch_id
            WHERE COALESCE(sl.is_reversed, false) = false
            GROUP BY s.id, s.supplier_code, s.supplier_name, s.mobile, sl.branch_id, b.branch_name
            HAVING SUM(sl.credit - sl.debit) > 0.005
        SQL);
        DB::statement('CREATE UNIQUE INDEX mv_ap_aging_supplier_branch_idx ON mv_ap_aging (supplier_id, branch_id)');
        DB::statement('CREATE INDEX mv_ap_aging_branch_idx ON mv_ap_aging (branch_id)');

        // ── mv_branch_intercompany — Due-from/Due-to balances per branch pair ──
        // Must match definition from 2026_07_30_000003 exactly.
        DB::statement(<<<'SQL'
            CREATE MATERIALIZED VIEW mv_branch_intercompany AS
            SELECT
                bl.from_branch_id,
                bl.to_branch_id,
                fb.branch_name AS from_branch_name,
                tb.branch_name AS to_branch_name,
                SUM(bl.debit) AS total_debit,
                SUM(bl.credit) AS total_credit,
                SUM(bl.debit) - SUM(bl.credit) AS net_balance,
                SUM(CASE WHEN NOT bl.is_reversed THEN bl.debit - bl.credit ELSE 0 END) AS outstanding_amount,
                COUNT(*) AS entry_count
            FROM branch_ledger bl
            INNER JOIN branches fb ON fb.id = bl.from_branch_id
            INNER JOIN branches tb ON tb.id = bl.to_branch_id
            GROUP BY bl.from_branch_id, bl.to_branch_id, fb.branch_name, tb.branch_name
        SQL);
        DB::statement('CREATE UNIQUE INDEX mv_branch_intercompany_from_to_idx ON mv_branch_intercompany (from_branch_id, to_branch_id)');

        // ── mv_customer_ledger_balance_check ──
        // Running balance verification: SUM(debit - credit) OVER (PARTITION BY customer_id ORDER BY id)
        DB::statement(<<<'SQL'
            CREATE MATERIALIZED VIEW mv_customer_ledger_balance_check AS
            SELECT
                id,
                customer_id,
                transaction_date,
                transaction_type,
                debit,
                credit,
                balance AS stored_balance,
                SUM(debit - credit) OVER (
                    PARTITION BY customer_id
                    ORDER BY id
                    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
                ) AS computed_balance,
                ROUND(balance - SUM(debit - credit) OVER (
                    PARTITION BY customer_id
                    ORDER BY id
                    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
                ), 2) AS drift
            FROM customer_ledger
            WHERE COALESCE(is_reversed, false) = false
            WITH DATA
        SQL);
        DB::statement('CREATE UNIQUE INDEX idx_mv_clbc_id ON mv_customer_ledger_balance_check (id)');

        // ── mv_supplier_ledger_balance_check ──
        // Running balance verification: SUM(credit - debit) OVER (PARTITION BY supplier_id ORDER BY id)
        DB::statement(<<<'SQL'
            CREATE MATERIALIZED VIEW mv_supplier_ledger_balance_check AS
            SELECT
                id,
                supplier_id,
                transaction_date,
                transaction_type,
                debit,
                credit,
                balance AS stored_balance,
                SUM(credit - debit) OVER (
                    PARTITION BY supplier_id
                    ORDER BY id
                    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
                ) AS computed_balance,
                ROUND(balance - SUM(credit - debit) OVER (
                    PARTITION BY supplier_id
                    ORDER BY id
                    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
                ), 2) AS drift
            FROM supplier_ledger
            WHERE COALESCE(is_reversed, false) = false
            WITH DATA
        SQL);
        DB::statement('CREATE UNIQUE INDEX idx_mv_slbc_id ON mv_supplier_ledger_balance_check (id)');

        // ── mv_employee_ledger_balance_check ──
        // Running balance verification: SUM(credit - debit) OVER (PARTITION BY employee_id ORDER BY id)
        DB::statement(<<<'SQL'
            CREATE MATERIALIZED VIEW mv_employee_ledger_balance_check AS
            SELECT
                id,
                employee_id,
                transaction_date,
                transaction_type,
                debit,
                credit,
                balance AS stored_balance,
                SUM(credit - debit) OVER (
                    PARTITION BY employee_id
                    ORDER BY id
                    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
                ) AS computed_balance,
                ROUND(balance - SUM(credit - debit) OVER (
                    PARTITION BY employee_id
                    ORDER BY id
                    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
                ), 2) AS drift
            FROM employee_ledger
            WHERE COALESCE(is_reversed, false) = false
            WITH DATA
        SQL);
        DB::statement('CREATE UNIQUE INDEX idx_mv_elbc_id ON mv_employee_ledger_balance_check (id)');

        // ── mv_cash_ledger_balance_check ──
        // Running balance verification: SUM(amount) OVER (PARTITION BY branch_id ORDER BY id)
        // NOTE: cash_ledger has no is_reversed column
        DB::statement(<<<'SQL'
            CREATE MATERIALIZED VIEW mv_cash_ledger_balance_check AS
            SELECT
                id,
                branch_id,
                transaction_date,
                transaction_type,
                amount,
                balance AS stored_balance,
                SUM(amount) OVER (
                    PARTITION BY branch_id
                    ORDER BY id
                    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
                ) AS computed_balance,
                ROUND(balance - SUM(amount) OVER (
                    PARTITION BY branch_id
                    ORDER BY id
                    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
                ), 2) AS drift
            FROM cash_ledger
            WITH DATA
        SQL);
        DB::statement('CREATE UNIQUE INDEX idx_mv_cashlbc_id ON mv_cash_ledger_balance_check (id)');

        // ── Refresh all views ──
        $views = [
            'mv_ar_aging', 'mv_ap_aging', 'mv_branch_intercompany',
            'mv_customer_ledger_balance_check', 'mv_supplier_ledger_balance_check',
            'mv_employee_ledger_balance_check', 'mv_cash_ledger_balance_check',
        ];
        foreach ($views as $view) {
            try {
                DB::statement("REFRESH MATERIALIZED VIEW CONCURRENTLY {$view}");
            } catch (\Throwable $e) {
                DB::statement("REFRESH MATERIALIZED VIEW {$view}");
            }
        }
    }

    // ═══════════════════════════════════════════════════════════════
    //  1. customer_ledger
    // ═══════════════════════════════════════════════════════════════

    private function partitionCustomerLedger(): void
    {
        if ($this->isAlreadyPartitioned('customer_ledger')) {
            return;
        }

        // ── Drop indexes on old table ──
        $this->dropIndexesExceptPK('customer_ledger');

        // ── Drop RLS policies on old table ──
        $this->dropRlsPolicies('customer_ledger');

        // ── Rename old table ──
        DB::statement(
            'ALTER TABLE customer_ledger RENAME TO customer_ledger_unpartitioned'
        );

        // ── Create partitioned table ──
        // PK must include partition key: (id, transaction_date)
        // GENERATED ALWAYS → GENERATED BY DEFAULT for OVERRIDING SYSTEM VALUE
        // Outbound FKs: customer_id → customers(id), journal_entry_id → journal_entries(id)
        // Both are DEFERRABLE INITIALLY DEFERRED (from migration 2025_01_21_000005)
        DB::statement(<<<'SQL'
            CREATE TABLE customer_ledger (
                id                INTEGER GENERATED BY DEFAULT AS IDENTITY,
                customer_id       INTEGER NOT NULL,
                branch_id         INTEGER,
                transaction_date  DATE NOT NULL,
                transaction_type  VARCHAR(30) NOT NULL,
                reference_type    VARCHAR(30),
                reference_id      INTEGER,
                debit             NUMERIC(14,2) DEFAULT 0,
                credit            NUMERIC(14,2) DEFAULT 0,
                balance           NUMERIC(14,2) DEFAULT 0,
                is_reversed       BOOLEAN NOT NULL DEFAULT false,
                reversed_at       TIMESTAMP(0),
                reversed_by       BIGINT,
                description       TEXT,
                journal_entry_id  INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                created_by        INTEGER,
                created_at        TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (id, transaction_date)
            ) PARTITION BY RANGE (transaction_date)
        SQL);

        // ── Create partitions ──
        $this->createPreYearPartition('customer_ledger', 'pre2026', '2026');
        $this->createMonthlyPartitions('customer_ledger', '2026');

        // ── Copy data ──
        DB::statement(<<<'SQL'
            INSERT INTO customer_ledger (
                id, customer_id, branch_id, transaction_date, transaction_type,
                reference_type, reference_id, debit, credit, balance,
                is_reversed, reversed_at, reversed_by, description,
                journal_entry_id, created_by, created_at
            )
            OVERRIDING SYSTEM VALUE
            SELECT
                id, customer_id, branch_id, transaction_date, transaction_type,
                reference_type, reference_id, debit, credit, balance,
                is_reversed, reversed_at, reversed_by, description,
                journal_entry_id, created_by, created_at
            FROM customer_ledger_unpartitioned
            ORDER BY transaction_date, id
        SQL);

        // ── Flush deferred FK triggers before creating indexes ──
        // DEFERRABLE INITIALLY DEFERRED constraints leave pending trigger events
        // after the INSERT, which blocks CREATE INDEX with:
        //   "cannot CREATE INDEX because it has pending trigger events"
        DB::statement('SET CONSTRAINTS ALL IMMEDIATE');

        // ── Fix sequence ──
        $this->fixSequence('customer_ledger');

        // ── Recreate indexes on parent (propagated to partitions) ──
        // Composite indexes for common query patterns
        DB::statement(
            'CREATE INDEX idx_cl_customer_date ON customer_ledger (customer_id, transaction_date)'
        );
        DB::statement(
            'CREATE INDEX idx_cl_reference ON customer_ledger (reference_type, reference_id)'
        );
        DB::statement(
            'CREATE INDEX idx_cl_branch ON customer_ledger (branch_id)'
        );
        DB::statement(
            'CREATE INDEX idx_cl_journal ON customer_ledger (journal_entry_id)'
        );
        DB::statement(
            'CREATE INDEX idx_cl_customer_branch ON customer_ledger (customer_id, branch_id)'
        );
        // Covering index for balance queries
        DB::statement(<<<'SQL'
            CREATE INDEX idx_cl_balance_covering
                ON customer_ledger (customer_id, is_reversed)
                INCLUDE (debit, credit)
        SQL);
        // Partial index for outstanding balances
        DB::statement(<<<'SQL'
            CREATE INDEX idx_cl_outstanding
                ON customer_ledger (customer_id, transaction_date, balance)
                WHERE balance > 0
        SQL);
        // BRIN index on partition key — replaces B-tree for append-only
        DB::statement(<<<'SQL'
            CREATE INDEX idx_cl_transaction_date_brin
                ON customer_ledger USING BRIN (transaction_date)
                WITH (pages_per_range = 32)
        SQL);
        // BRIN on created_at for time-range queries
        DB::statement(<<<'SQL'
            CREATE INDEX idx_cl_created_at_brin
                ON customer_ledger USING BRIN (created_at)
                WITH (pages_per_range = 32)
        SQL);

        // ── Recreate RLS policies ──
        DB::statement('ALTER TABLE customer_ledger ENABLE ROW LEVEL SECURITY');
        DB::statement('ALTER TABLE customer_ledger FORCE ROW LEVEL SECURITY');

        DB::statement(<<<'SQL'
            CREATE POLICY rls_customer_ledger_select ON customer_ledger
                FOR SELECT USING (
                    current_setting('app.is_admin', true) = 'true'
                    OR branch_id = current_setting('app.branch_id')::int
                )
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_customer_ledger_insert ON customer_ledger
                FOR INSERT WITH CHECK (
                    current_setting('app.is_admin', true) = 'true'
                    OR branch_id = current_setting('app.branch_id')::int
                )
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_customer_ledger_update ON customer_ledger
                FOR UPDATE USING (
                    current_setting('app.is_admin', true) = 'true'
                    OR branch_id = current_setting('app.branch_id')::int
                )
                WITH CHECK (
                    current_setting('app.is_admin', true) = 'true'
                    OR branch_id = current_setting('app.branch_id')::int
                )
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_customer_ledger_delete ON customer_ledger
                FOR DELETE USING (
                    current_setting('app.is_admin', true) = 'true'
                    OR branch_id = current_setting('app.branch_id')::int
                )
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_customer_ledger_admin ON customer_ledger
                FOR ALL USING (
                    current_setting('app.is_admin', true) = 'true'
                )
                WITH CHECK (
                    current_setting('app.is_admin', true) = 'true'
                )
        SQL);

        // ── Drop old table ──
        DB::statement('DROP TABLE customer_ledger_unpartitioned');

        // ── Register with pg_partman ──
        $this->registerPartman('customer_ledger', 'transaction_date', '2027-01-01');

        // ── Configure retention (7 years = 84 months) ──
        if ($this->hasPgPartman()) {
            DB::statement(<<<'SQL'
                UPDATE partman.part_config
                SET retention = '84 months',
                    retention_keep_table = true,
                    retention_schema = 'archive'
                WHERE parent_table = 'public.customer_ledger'
            SQL);
        }

        // ── Analyze ──
        DB::statement('ANALYZE customer_ledger');
    }

    // ═══════════════════════════════════════════════════════════════
    //  2. supplier_ledger
    // ═══════════════════════════════════════════════════════════════

    private function partitionSupplierLedger(): void
    {
        if ($this->isAlreadyPartitioned('supplier_ledger')) {
            return;
        }

        // ── Drop indexes on old table ──
        $this->dropIndexesExceptPK('supplier_ledger');

        // ── Drop RLS policies on old table ──
        $this->dropRlsPolicies('supplier_ledger');

        // ── Rename old table ──
        DB::statement(
            'ALTER TABLE supplier_ledger RENAME TO supplier_ledger_unpartitioned'
        );

        // ── Create partitioned table ──
        DB::statement(<<<'SQL'
            CREATE TABLE supplier_ledger (
                id                INTEGER GENERATED BY DEFAULT AS IDENTITY,
                supplier_id       INTEGER NOT NULL,
                branch_id         INTEGER,
                transaction_date  DATE NOT NULL,
                transaction_type  VARCHAR(30) NOT NULL,
                reference_type    VARCHAR(30),
                reference_id      INTEGER,
                debit             NUMERIC(14,2) DEFAULT 0,
                credit            NUMERIC(14,2) DEFAULT 0,
                balance           NUMERIC(14,2) DEFAULT 0,
                is_reversed       BOOLEAN NOT NULL DEFAULT false,
                reversed_at       TIMESTAMP(0),
                reversed_by       BIGINT,
                description       TEXT,
                journal_entry_id  INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                created_by        INTEGER,
                created_at        TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (id, transaction_date)
            ) PARTITION BY RANGE (transaction_date)
        SQL);

        // ── Create partitions ──
        $this->createPreYearPartition('supplier_ledger', 'pre2026', '2026');
        $this->createMonthlyPartitions('supplier_ledger', '2026');

        // ── Copy data ──
        DB::statement(<<<'SQL'
            INSERT INTO supplier_ledger (
                id, supplier_id, branch_id, transaction_date, transaction_type,
                reference_type, reference_id, debit, credit, balance,
                is_reversed, reversed_at, reversed_by, description,
                journal_entry_id, created_by, created_at
            )
            OVERRIDING SYSTEM VALUE
            SELECT
                id, supplier_id, branch_id, transaction_date, transaction_type,
                reference_type, reference_id, debit, credit, balance,
                is_reversed, reversed_at, reversed_by, description,
                journal_entry_id, created_by, created_at
            FROM supplier_ledger_unpartitioned
            ORDER BY transaction_date, id
        SQL);

        // ── Flush deferred FK triggers before creating indexes ──
        DB::statement('SET CONSTRAINTS ALL IMMEDIATE');

        // ── Fix sequence ──
        $this->fixSequence('supplier_ledger');

        // ── Recreate indexes on parent ──
        DB::statement(
            'CREATE INDEX idx_sl_supplier_date ON supplier_ledger (supplier_id, transaction_date)'
        );
        DB::statement(
            'CREATE INDEX idx_sl_reference ON supplier_ledger (reference_type, reference_id)'
        );
        DB::statement(
            'CREATE INDEX idx_sl_journal ON supplier_ledger (journal_entry_id)'
        );
        DB::statement(
            'CREATE INDEX idx_sl_supplier_branch ON supplier_ledger (supplier_id, branch_id)'
        );
        // Partial index for outstanding balances
        DB::statement(<<<'SQL'
            CREATE INDEX idx_sl_outstanding
                ON supplier_ledger (supplier_id, transaction_date, balance)
                WHERE balance > 0
        SQL);
        // BRIN index on partition key
        DB::statement(<<<'SQL'
            CREATE INDEX idx_sl_transaction_date_brin
                ON supplier_ledger USING BRIN (transaction_date)
                WITH (pages_per_range = 32)
        SQL);
        DB::statement(<<<'SQL'
            CREATE INDEX idx_sl_created_at_brin
                ON supplier_ledger USING BRIN (created_at)
                WITH (pages_per_range = 32)
        SQL);

        // ── Recreate RLS policies ──
        DB::statement('ALTER TABLE supplier_ledger ENABLE ROW LEVEL SECURITY');
        DB::statement('ALTER TABLE supplier_ledger FORCE ROW LEVEL SECURITY');

        DB::statement(<<<'SQL'
            CREATE POLICY rls_supplier_ledger_select ON supplier_ledger
                FOR SELECT USING (
                    current_setting('app.is_admin', true) = 'true'
                    OR branch_id = current_setting('app.branch_id')::int
                )
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_supplier_ledger_insert ON supplier_ledger
                FOR INSERT WITH CHECK (
                    current_setting('app.is_admin', true) = 'true'
                    OR branch_id = current_setting('app.branch_id')::int
                )
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_supplier_ledger_update ON supplier_ledger
                FOR UPDATE USING (
                    current_setting('app.is_admin', true) = 'true'
                    OR branch_id = current_setting('app.branch_id')::int
                )
                WITH CHECK (
                    current_setting('app.is_admin', true) = 'true'
                    OR branch_id = current_setting('app.branch_id')::int
                )
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_supplier_ledger_delete ON supplier_ledger
                FOR DELETE USING (
                    current_setting('app.is_admin', true) = 'true'
                    OR branch_id = current_setting('app.branch_id')::int
                )
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_supplier_ledger_admin ON supplier_ledger
                FOR ALL USING (
                    current_setting('app.is_admin', true) = 'true'
                )
                WITH CHECK (
                    current_setting('app.is_admin', true) = 'true'
                )
        SQL);

        // ── Drop old table ──
        DB::statement('DROP TABLE supplier_ledger_unpartitioned');

        // ── Register with pg_partman ──
        $this->registerPartman('supplier_ledger', 'transaction_date', '2027-01-01');

        // ── Configure retention (7 years = 84 months) ──
        if ($this->hasPgPartman()) {
            DB::statement(<<<'SQL'
                UPDATE partman.part_config
                SET retention = '84 months',
                    retention_keep_table = true,
                    retention_schema = 'archive'
                WHERE parent_table = 'public.supplier_ledger'
            SQL);
        }

        // ── Analyze ──
        DB::statement('ANALYZE supplier_ledger');
    }

    // ═══════════════════════════════════════════════════════════════
    //  3. employee_ledger
    // ═══════════════════════════════════════════════════════════════

    private function partitionEmployeeLedger(): void
    {
        if ($this->isAlreadyPartitioned('employee_ledger')) {
            return;
        }

        // ── Drop indexes on old table ──
        $this->dropIndexesExceptPK('employee_ledger');

        // ── Drop RLS policies on old table ──
        $this->dropRlsPolicies('employee_ledger');

        // ── Rename old table ──
        DB::statement(
            'ALTER TABLE employee_ledger RENAME TO employee_ledger_unpartitioned'
        );

        // ── Create partitioned table ──
        DB::statement(<<<'SQL'
            CREATE TABLE employee_ledger (
                id                INTEGER GENERATED BY DEFAULT AS IDENTITY,
                employee_id       INTEGER NOT NULL,
                branch_id         INTEGER,
                transaction_date  DATE NOT NULL,
                transaction_type  VARCHAR(30) NOT NULL CHECK (transaction_type IN ('advance','loan','repayment','salary','deduction','adjustment')),
                reference_type    VARCHAR(30),
                reference_id      INTEGER,
                debit             NUMERIC(14,2) DEFAULT 0,
                credit            NUMERIC(14,2) DEFAULT 0,
                balance           NUMERIC(14,2) DEFAULT 0,
                is_reversed       BOOLEAN NOT NULL DEFAULT false,
                reversed_at       TIMESTAMP(0),
                reversed_by       BIGINT,
                description       TEXT,
                journal_entry_id  INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                created_by        INTEGER,
                created_at        TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (id, transaction_date)
            ) PARTITION BY RANGE (transaction_date)
        SQL);

        // ── Create partitions ──
        $this->createPreYearPartition('employee_ledger', 'pre2026', '2026');
        $this->createMonthlyPartitions('employee_ledger', '2026');

        // ── Copy data ──
        DB::statement(<<<'SQL'
            INSERT INTO employee_ledger (
                id, employee_id, branch_id, transaction_date, transaction_type,
                reference_type, reference_id, debit, credit, balance,
                is_reversed, reversed_at, reversed_by, description,
                journal_entry_id, created_by, created_at
            )
            OVERRIDING SYSTEM VALUE
            SELECT
                id, employee_id, branch_id, transaction_date, transaction_type,
                reference_type, reference_id, debit, credit, balance,
                is_reversed, reversed_at, reversed_by, description,
                journal_entry_id, created_by, created_at
            FROM employee_ledger_unpartitioned
            ORDER BY transaction_date, id
        SQL);

        // ── Flush deferred FK triggers before creating indexes ──
        DB::statement('SET CONSTRAINTS ALL IMMEDIATE');

        // ── Fix sequence ──
        $this->fixSequence('employee_ledger');

        // ── Recreate indexes on parent ──
        DB::statement(
            'CREATE INDEX idx_el_employee_date ON employee_ledger (employee_id, transaction_date)'
        );
        // BRIN index on partition key
        DB::statement(<<<'SQL'
            CREATE INDEX idx_el_transaction_date_brin
                ON employee_ledger USING BRIN (transaction_date)
                WITH (pages_per_range = 32)
        SQL);

        // ── Recreate RLS policies ──
        DB::statement('ALTER TABLE employee_ledger ENABLE ROW LEVEL SECURITY');
        DB::statement('ALTER TABLE employee_ledger FORCE ROW LEVEL SECURITY');

        DB::statement(<<<'SQL'
            CREATE POLICY rls_employee_ledger_select ON employee_ledger
                FOR SELECT USING (
                    current_setting('app.is_admin', true) = 'true'
                    OR branch_id = current_setting('app.branch_id')::int
                )
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_employee_ledger_insert ON employee_ledger
                FOR INSERT WITH CHECK (
                    current_setting('app.is_admin', true) = 'true'
                    OR branch_id = current_setting('app.branch_id')::int
                )
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_employee_ledger_update ON employee_ledger
                FOR UPDATE USING (
                    current_setting('app.is_admin', true) = 'true'
                    OR branch_id = current_setting('app.branch_id')::int
                )
                WITH CHECK (
                    current_setting('app.is_admin', true) = 'true'
                    OR branch_id = current_setting('app.branch_id')::int
                )
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_employee_ledger_delete ON employee_ledger
                FOR DELETE USING (
                    current_setting('app.is_admin', true) = 'true'
                    OR branch_id = current_setting('app.branch_id')::int
                )
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_employee_ledger_admin ON employee_ledger
                FOR ALL USING (
                    current_setting('app.is_admin', true) = 'true'
                )
                WITH CHECK (
                    current_setting('app.is_admin', true) = 'true'
                )
        SQL);

        // ── Drop old table ──
        DB::statement('DROP TABLE employee_ledger_unpartitioned');

        // ── Register with pg_partman ──
        $this->registerPartman('employee_ledger', 'transaction_date', '2027-01-01');

        // ── Configure retention (7 years = 84 months) ──
        if ($this->hasPgPartman()) {
            DB::statement(<<<'SQL'
                UPDATE partman.part_config
                SET retention = '84 months',
                    retention_keep_table = true,
                    retention_schema = 'archive'
                WHERE parent_table = 'public.employee_ledger'
            SQL);
        }

        // ── Analyze ──
        DB::statement('ANALYZE employee_ledger');
    }

    // ═══════════════════════════════════════════════════════════════
    //  4. cash_ledger
    // ═══════════════════════════════════════════════════════════════
    //
    // SPECIAL: Uses `amount` instead of `debit`/`credit`
    //          branch_id is NOT NULL
    //          No `is_reversed` column
    //          created_by has explicit FK → users(id)

    private function partitionCashLedger(): void
    {
        if ($this->isAlreadyPartitioned('cash_ledger')) {
            return;
        }

        // ── Drop indexes on old table ──
        $this->dropIndexesExceptPK('cash_ledger');

        // ── Drop RLS policies on old table ──
        $this->dropRlsPolicies('cash_ledger');

        // ── Rename old table ──
        DB::statement(
            'ALTER TABLE cash_ledger RENAME TO cash_ledger_unpartitioned'
        );

        // ── Create partitioned table ──
        // NOTE: cash_ledger uses `amount` (not debit/credit) and has no is_reversed
        // branch_id is NOT NULL with FK → branches(id) DEFERRABLE INITIALLY DEFERRED
        // created_by has FK → users(id)
        DB::statement(<<<'SQL'
            CREATE TABLE cash_ledger (
                id                INTEGER GENERATED BY DEFAULT AS IDENTITY,
                branch_id         INTEGER NOT NULL REFERENCES branches(id) DEFERRABLE INITIALLY DEFERRED,
                transaction_date  DATE NOT NULL,
                transaction_type  VARCHAR(30) NOT NULL,
                reference_type    VARCHAR(30),
                reference_id      INTEGER,
                amount            NUMERIC(15,2) DEFAULT 0,
                balance           NUMERIC(15,2) DEFAULT 0,
                description       TEXT,
                journal_entry_id  INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                created_by        INTEGER REFERENCES users(id),
                created_at        TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (id, transaction_date)
            ) PARTITION BY RANGE (transaction_date)
        SQL);

        // ── Create partitions ──
        $this->createPreYearPartition('cash_ledger', 'pre2026', '2026');
        $this->createMonthlyPartitions('cash_ledger', '2026');

        // ── Copy data ──
        DB::statement(<<<'SQL'
            INSERT INTO cash_ledger (
                id, branch_id, transaction_date, transaction_type,
                reference_type, reference_id, amount, balance,
                description, journal_entry_id, created_by, created_at
            )
            OVERRIDING SYSTEM VALUE
            SELECT
                id, branch_id, transaction_date, transaction_type,
                reference_type, reference_id, amount, balance,
                description, journal_entry_id, created_by, created_at
            FROM cash_ledger_unpartitioned
            ORDER BY transaction_date, id
        SQL);

        // ── Flush deferred FK triggers before creating indexes ──
        DB::statement('SET CONSTRAINTS ALL IMMEDIATE');

        // ── Fix sequence ──
        $this->fixSequence('cash_ledger');

        // ── Recreate indexes on parent ──
        DB::statement(
            'CREATE INDEX idx_cashl_branch_date ON cash_ledger (branch_id, transaction_date)'
        );
        // BRIN index on partition key
        DB::statement(<<<'SQL'
            CREATE INDEX idx_cashl_transaction_date_brin
                ON cash_ledger USING BRIN (transaction_date)
                WITH (pages_per_range = 32)
        SQL);

        // ── Recreate RLS policies ──
        DB::statement('ALTER TABLE cash_ledger ENABLE ROW LEVEL SECURITY');
        DB::statement('ALTER TABLE cash_ledger FORCE ROW LEVEL SECURITY');

        DB::statement(<<<'SQL'
            CREATE POLICY rls_cash_ledger_select ON cash_ledger
                FOR SELECT USING (
                    current_setting('app.is_admin', true) = 'true'
                    OR branch_id = current_setting('app.branch_id')::int
                )
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_cash_ledger_insert ON cash_ledger
                FOR INSERT WITH CHECK (
                    current_setting('app.is_admin', true) = 'true'
                    OR branch_id = current_setting('app.branch_id')::int
                )
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_cash_ledger_update ON cash_ledger
                FOR UPDATE USING (
                    current_setting('app.is_admin', true) = 'true'
                    OR branch_id = current_setting('app.branch_id')::int
                )
                WITH CHECK (
                    current_setting('app.is_admin', true) = 'true'
                    OR branch_id = current_setting('app.branch_id')::int
                )
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_cash_ledger_delete ON cash_ledger
                FOR DELETE USING (
                    current_setting('app.is_admin', true) = 'true'
                    OR branch_id = current_setting('app.branch_id')::int
                )
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_cash_ledger_admin ON cash_ledger
                FOR ALL USING (
                    current_setting('app.is_admin', true) = 'true'
                )
                WITH CHECK (
                    current_setting('app.is_admin', true) = 'true'
                )
        SQL);

        // ── Drop old table ──
        DB::statement('DROP TABLE cash_ledger_unpartitioned');

        // ── Register with pg_partman ──
        $this->registerPartman('cash_ledger', 'transaction_date', '2027-01-01');

        // ── Configure retention (7 years = 84 months) ──
        if ($this->hasPgPartman()) {
            DB::statement(<<<'SQL'
                UPDATE partman.part_config
                SET retention = '84 months',
                    retention_keep_table = true,
                    retention_schema = 'archive'
                WHERE parent_table = 'public.cash_ledger'
            SQL);
        }

        // ── Analyze ──
        DB::statement('ANALYZE cash_ledger');
    }

    // ═══════════════════════════════════════════════════════════════
    //  5. branch_ledger
    // ═══════════════════════════════════════════════════════════════
    //
    // SPECIAL: Dual-branch RLS (from_branch_id OR to_branch_id)
    //          Uses `running_balance` instead of `balance`
    //          Uses `remarks` instead of `description`
    //          reference_type is varchar(50) not varchar(30)
    //          debit/credit are numeric(12,2) not numeric(14,2)

    private function partitionBranchLedger(): void
    {
        if ($this->isAlreadyPartitioned('branch_ledger')) {
            return;
        }

        // ── Drop indexes on old table ──
        $this->dropIndexesExceptPK('branch_ledger');

        // ── Drop RLS policies on old table ──
        $this->dropRlsPolicies('branch_ledger');

        // ── Rename old table ──
        DB::statement(
            'ALTER TABLE branch_ledger RENAME TO branch_ledger_unpartitioned'
        );

        // ── Create partitioned table ──
        DB::statement(<<<'SQL'
            CREATE TABLE branch_ledger (
                id                INTEGER GENERATED BY DEFAULT AS IDENTITY,
                transaction_date  DATE NOT NULL,
                from_branch_id    INTEGER NOT NULL REFERENCES branches(id) DEFERRABLE INITIALLY DEFERRED,
                to_branch_id      INTEGER NOT NULL REFERENCES branches(id) DEFERRABLE INITIALLY DEFERRED,
                reference_type    VARCHAR(50) NOT NULL DEFAULT 'adjustment',
                reference_id      INTEGER DEFAULT NULL,
                journal_entry_id  INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                debit             NUMERIC(12,2) DEFAULT 0,
                credit            NUMERIC(12,2) DEFAULT 0,
                running_balance   NUMERIC(12,2) DEFAULT NULL,
                remarks           TEXT,
                is_reversed       BOOLEAN NOT NULL DEFAULT false,
                created_by        INTEGER DEFAULT NULL,
                created_at        TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (id, transaction_date)
            ) PARTITION BY RANGE (transaction_date)
        SQL);

        // ── Create partitions ──
        $this->createPreYearPartition('branch_ledger', 'pre2026', '2026');
        $this->createMonthlyPartitions('branch_ledger', '2026');

        // ── Copy data ──
        DB::statement(<<<'SQL'
            INSERT INTO branch_ledger (
                id, transaction_date, from_branch_id, to_branch_id,
                reference_type, reference_id, journal_entry_id,
                debit, credit, running_balance, remarks,
                is_reversed, created_by, created_at
            )
            OVERRIDING SYSTEM VALUE
            SELECT
                id, transaction_date, from_branch_id, to_branch_id,
                reference_type, reference_id, journal_entry_id,
                debit, credit, running_balance, remarks,
                is_reversed, created_by, created_at
            FROM branch_ledger_unpartitioned
            ORDER BY transaction_date, id
        SQL);

        // ── Flush deferred FK triggers before creating indexes ──
        DB::statement('SET CONSTRAINTS ALL IMMEDIATE');

        // ── Fix sequence ──
        $this->fixSequence('branch_ledger');

        // ── Recreate indexes on parent ──
        DB::statement(
            'CREATE INDEX idx_bl_branches ON branch_ledger (from_branch_id, to_branch_id)'
        );
        DB::statement(
            'CREATE INDEX idx_bl_reference ON branch_ledger (reference_type, reference_id)'
        );
        DB::statement(
            'CREATE INDEX idx_bl_date ON branch_ledger (transaction_date)'
        );
        // Partial index for active (non-reversed) entries
        DB::statement(<<<'SQL'
            CREATE INDEX idx_bl_active
                ON branch_ledger (from_branch_id, to_branch_id, transaction_date)
                WHERE is_reversed = false
        SQL);
        // BRIN index on partition key
        DB::statement(<<<'SQL'
            CREATE INDEX idx_bl_transaction_date_brin
                ON branch_ledger USING BRIN (transaction_date)
                WITH (pages_per_range = 32)
        SQL);

        // ── Recreate RLS policies (DUAL-BRANCH: from_branch_id OR to_branch_id) ──
        DB::statement('ALTER TABLE branch_ledger ENABLE ROW LEVEL SECURITY');
        DB::statement('ALTER TABLE branch_ledger FORCE ROW LEVEL SECURITY');

        DB::statement(<<<'SQL'
            CREATE POLICY rls_branch_ledger_select ON branch_ledger
                FOR SELECT USING (
                    current_setting('app.is_admin', true) = 'true'
                    OR from_branch_id = current_setting('app.branch_id')::int
                    OR to_branch_id = current_setting('app.branch_id')::int
                )
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_branch_ledger_insert ON branch_ledger
                FOR INSERT WITH CHECK (
                    current_setting('app.is_admin', true) = 'true'
                    OR from_branch_id = current_setting('app.branch_id')::int
                    OR to_branch_id = current_setting('app.branch_id')::int
                )
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_branch_ledger_update ON branch_ledger
                FOR UPDATE USING (
                    current_setting('app.is_admin', true) = 'true'
                    OR from_branch_id = current_setting('app.branch_id')::int
                    OR to_branch_id = current_setting('app.branch_id')::int
                )
                WITH CHECK (
                    current_setting('app.is_admin', true) = 'true'
                    OR from_branch_id = current_setting('app.branch_id')::int
                    OR to_branch_id = current_setting('app.branch_id')::int
                )
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_branch_ledger_delete ON branch_ledger
                FOR DELETE USING (
                    current_setting('app.is_admin', true) = 'true'
                    OR from_branch_id = current_setting('app.branch_id')::int
                    OR to_branch_id = current_setting('app.branch_id')::int
                )
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_branch_ledger_admin ON branch_ledger
                FOR ALL USING (
                    current_setting('app.is_admin', true) = 'true'
                )
                WITH CHECK (
                    current_setting('app.is_admin', true) = 'true'
                )
        SQL);

        // ── Drop old table ──
        DB::statement('DROP TABLE branch_ledger_unpartitioned');

        // ── Register with pg_partman ──
        $this->registerPartman('branch_ledger', 'transaction_date', '2027-01-01');

        // ── Configure retention (7 years = 84 months) ──
        if ($this->hasPgPartman()) {
            DB::statement(<<<'SQL'
                UPDATE partman.part_config
                SET retention = '84 months',
                    retention_keep_table = true,
                    retention_schema = 'archive'
                WHERE parent_table = 'public.branch_ledger'
            SQL);
        }

        // ── Analyze ──
        DB::statement('ANALYZE branch_ledger');
    }

    // ── Rollback ──────────────────────────────────────────────────

    /**
     * Rollback strategy: For each table, detach all partitions from the
     * partitioned parent, then create a new non-partitioned table and copy
     * all data back. This is the safest approach but requires enough disk
     * space to hold both copies temporarily.
     *
     * ⚠️  Rollback is expensive — run during a maintenance window.
     */
    public function down(): void
    {
        // ── Drop materialized views first ──
        $this->dropMaterializedViews();

        $this->rollbackCustomerLedger();
        $this->rollbackSupplierLedger();
        $this->rollbackEmployeeLedger();
        $this->rollbackCashLedger();
        $this->rollbackBranchLedger();

        // ── Recreate materialized views against non-partitioned tables ──
        $this->recreateMaterializedViews();
    }

    /**
     * Generic rollback helper: detach all partitions, create a flat table,
     * copy data, drop partitioned parent, rename flat table.
     */
    private function rollbackPartitionedTable(
        string $tableName,
        string $createFlatSQL,
        array $columns,
        array $indexDefinitions,
        array $rlsPolicyDefinitions
    ): void {
        // Check if the table is actually partitioned
        if (! $this->isAlreadyPartitioned($tableName)) {
            return;
        }

        $tempName = "{$tableName}_flat";

        // ── Detach all partitions ──
        $partitions = DB::select("
            SELECT c.relname
            FROM pg_inherits i
            JOIN pg_class c ON c.oid = i.inhrelid
            JOIN pg_class p ON p.oid = i.inhparent
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE p.relname = ? AND n.nspname = current_schema()
        ", [$tableName]);

        foreach ($partitions as $part) {
            DB::statement("ALTER TABLE {$tableName} DETACH PARTITION {$part->relname}");
        }

        // ── Create flat table with original PK(id) ──
        DB::statement($createFlatSQL);

        // ── Copy data from each partition ──
        $colList = implode(', ', $columns);
        foreach ($partitions as $part) {
            DB::statement(<<<SQL
                INSERT INTO {$tempName} ({$colList})
                OVERRIDING SYSTEM VALUE
                SELECT {$colList} FROM {$part->relname}
                ORDER BY id
            SQL);
        }
        // Also copy from the parent (in case data remains there)
        $parentCount = DB::selectOne("SELECT count(*) AS cnt FROM ONLY {$tableName}")->cnt;
        if ($parentCount > 0) {
            DB::statement(<<<SQL
                INSERT INTO {$tempName} ({$colList})
                OVERRIDING SYSTEM VALUE
                SELECT {$colList} FROM ONLY {$tableName}
                ORDER BY id
            SQL);
        }

        // ── Fix sequence ──
        $this->fixSequence($tempName);

        // ── Recreate indexes ──
        foreach ($indexDefinitions as $idxSQL) {
            DB::statement($idxSQL);
        }

        // ── Drop old partitioned parent and its detached partitions ──
        DB::statement("DROP TABLE {$tableName}");
        foreach ($partitions as $part) {
            DB::statement("DROP TABLE IF EXISTS {$part->relname}");
        }

        // ── Rename flat table to original name ──
        DB::statement("ALTER TABLE {$tempName} RENAME TO {$tableName}");

        // ── Recreate RLS policies ──
        DB::statement("ALTER TABLE {$tableName} ENABLE ROW LEVEL SECURITY");
        DB::statement("ALTER TABLE {$tableName} FORCE ROW LEVEL SECURITY");
        foreach ($rlsPolicyDefinitions as $policySQL) {
            DB::statement($policySQL);
        }

        // ── Analyze ──
        DB::statement("ANALYZE {$tableName}");
    }

    private function rollbackCustomerLedger(): void
    {
        $this->rollbackPartitionedTable(
            'customer_ledger',
            <<<'SQL'
                CREATE TABLE customer_ledger_flat (
                    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    customer_id       INTEGER NOT NULL,
                    branch_id         INTEGER,
                    transaction_date  DATE NOT NULL,
                    transaction_type  VARCHAR(30) NOT NULL,
                    reference_type    VARCHAR(30),
                    reference_id      INTEGER,
                    debit             NUMERIC(14,2) DEFAULT 0,
                    credit            NUMERIC(14,2) DEFAULT 0,
                    balance           NUMERIC(14,2) DEFAULT 0,
                    is_reversed       BOOLEAN NOT NULL DEFAULT false,
                    reversed_at       TIMESTAMP(0),
                    reversed_by       BIGINT,
                    description       TEXT,
                    journal_entry_id  INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                    created_by        INTEGER,
                    created_at        TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP
                )
            SQL,
            ['id', 'customer_id', 'branch_id', 'transaction_date', 'transaction_type',
             'reference_type', 'reference_id', 'debit', 'credit', 'balance',
             'is_reversed', 'reversed_at', 'reversed_by', 'description',
             'journal_entry_id', 'created_by', 'created_at'],
            [
                'CREATE INDEX idx_cl_customer_date ON customer_ledger_flat (customer_id, transaction_date)',
                'CREATE INDEX idx_cl_reference ON customer_ledger_flat (reference_type, reference_id)',
                'CREATE INDEX idx_cl_branch ON customer_ledger_flat (branch_id)',
                'CREATE INDEX idx_cl_journal ON customer_ledger_flat (journal_entry_id)',
                'CREATE INDEX idx_cl_customer_branch ON customer_ledger_flat (customer_id, branch_id)',
                "CREATE INDEX idx_cl_balance_covering ON customer_ledger_flat (customer_id, is_reversed) INCLUDE (debit, credit)",
                "CREATE INDEX idx_cl_outstanding ON customer_ledger_flat (customer_id, transaction_date, balance) WHERE balance > 0",
            ],
            [
                "CREATE POLICY rls_customer_ledger_select ON customer_ledger FOR SELECT USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)",
                "CREATE POLICY rls_customer_ledger_insert ON customer_ledger FOR INSERT WITH CHECK (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)",
                "CREATE POLICY rls_customer_ledger_update ON customer_ledger FOR UPDATE USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int) WITH CHECK (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)",
                "CREATE POLICY rls_customer_ledger_delete ON customer_ledger FOR DELETE USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)",
                "CREATE POLICY rls_customer_ledger_admin ON customer_ledger FOR ALL USING (current_setting('app.is_admin', true) = 'true') WITH CHECK (current_setting('app.is_admin', true) = 'true')",
            ]
        );
    }

    private function rollbackSupplierLedger(): void
    {
        $this->rollbackPartitionedTable(
            'supplier_ledger',
            <<<'SQL'
                CREATE TABLE supplier_ledger_flat (
                    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    supplier_id       INTEGER NOT NULL,
                    branch_id         INTEGER,
                    transaction_date  DATE NOT NULL,
                    transaction_type  VARCHAR(30) NOT NULL,
                    reference_type    VARCHAR(30),
                    reference_id      INTEGER,
                    debit             NUMERIC(14,2) DEFAULT 0,
                    credit            NUMERIC(14,2) DEFAULT 0,
                    balance           NUMERIC(14,2) DEFAULT 0,
                    is_reversed       BOOLEAN NOT NULL DEFAULT false,
                    reversed_at       TIMESTAMP(0),
                    reversed_by       BIGINT,
                    description       TEXT,
                    journal_entry_id  INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                    created_by        INTEGER,
                    created_at        TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP
                )
            SQL,
            ['id', 'supplier_id', 'branch_id', 'transaction_date', 'transaction_type',
             'reference_type', 'reference_id', 'debit', 'credit', 'balance',
             'is_reversed', 'reversed_at', 'reversed_by', 'description',
             'journal_entry_id', 'created_by', 'created_at'],
            [
                'CREATE INDEX idx_sl_supplier_date ON supplier_ledger_flat (supplier_id, transaction_date)',
                'CREATE INDEX idx_sl_reference ON supplier_ledger_flat (reference_type, reference_id)',
                'CREATE INDEX idx_sl_journal ON supplier_ledger_flat (journal_entry_id)',
                'CREATE INDEX idx_sl_supplier_branch ON supplier_ledger_flat (supplier_id, branch_id)',
                "CREATE INDEX idx_sl_outstanding ON supplier_ledger_flat (supplier_id, transaction_date, balance) WHERE balance > 0",
            ],
            [
                "CREATE POLICY rls_supplier_ledger_select ON supplier_ledger FOR SELECT USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)",
                "CREATE POLICY rls_supplier_ledger_insert ON supplier_ledger FOR INSERT WITH CHECK (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)",
                "CREATE POLICY rls_supplier_ledger_update ON supplier_ledger FOR UPDATE USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int) WITH CHECK (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)",
                "CREATE POLICY rls_supplier_ledger_delete ON supplier_ledger FOR DELETE USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)",
                "CREATE POLICY rls_supplier_ledger_admin ON supplier_ledger FOR ALL USING (current_setting('app.is_admin', true) = 'true') WITH CHECK (current_setting('app.is_admin', true) = 'true')",
            ]
        );
    }

    private function rollbackEmployeeLedger(): void
    {
        $this->rollbackPartitionedTable(
            'employee_ledger',
            <<<'SQL'
                CREATE TABLE employee_ledger_flat (
                    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    employee_id       INTEGER NOT NULL,
                    branch_id         INTEGER,
                    transaction_date  DATE NOT NULL,
                    transaction_type  VARCHAR(30) NOT NULL CHECK (transaction_type IN ('advance','loan','repayment','salary','deduction','adjustment')),
                    reference_type    VARCHAR(30),
                    reference_id      INTEGER,
                    debit             NUMERIC(14,2) DEFAULT 0,
                    credit            NUMERIC(14,2) DEFAULT 0,
                    balance           NUMERIC(14,2) DEFAULT 0,
                    is_reversed       BOOLEAN NOT NULL DEFAULT false,
                    reversed_at       TIMESTAMP(0),
                    reversed_by       BIGINT,
                    description       TEXT,
                    journal_entry_id  INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                    created_by        INTEGER,
                    created_at        TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP
                )
            SQL,
            ['id', 'employee_id', 'branch_id', 'transaction_date', 'transaction_type',
             'reference_type', 'reference_id', 'debit', 'credit', 'balance',
             'is_reversed', 'reversed_at', 'reversed_by', 'description',
             'journal_entry_id', 'created_by', 'created_at'],
            [
                'CREATE INDEX idx_el_employee_date ON employee_ledger_flat (employee_id, transaction_date)',
            ],
            [
                "CREATE POLICY rls_employee_ledger_select ON employee_ledger FOR SELECT USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)",
                "CREATE POLICY rls_employee_ledger_insert ON employee_ledger FOR INSERT WITH CHECK (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)",
                "CREATE POLICY rls_employee_ledger_update ON employee_ledger FOR UPDATE USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int) WITH CHECK (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)",
                "CREATE POLICY rls_employee_ledger_delete ON employee_ledger FOR DELETE USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)",
                "CREATE POLICY rls_employee_ledger_admin ON employee_ledger FOR ALL USING (current_setting('app.is_admin', true) = 'true') WITH CHECK (current_setting('app.is_admin', true) = 'true')",
            ]
        );
    }

    private function rollbackCashLedger(): void
    {
        $this->rollbackPartitionedTable(
            'cash_ledger',
            <<<'SQL'
                CREATE TABLE cash_ledger_flat (
                    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    branch_id         INTEGER NOT NULL REFERENCES branches(id) DEFERRABLE INITIALLY DEFERRED,
                    transaction_date  DATE NOT NULL,
                    transaction_type  VARCHAR(30) NOT NULL,
                    reference_type    VARCHAR(30),
                    reference_id      INTEGER,
                    amount            NUMERIC(15,2) DEFAULT 0,
                    balance           NUMERIC(15,2) DEFAULT 0,
                    description       TEXT,
                    journal_entry_id  INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                    created_by        INTEGER REFERENCES users(id),
                    created_at        TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP
                )
            SQL,
            ['id', 'branch_id', 'transaction_date', 'transaction_type',
             'reference_type', 'reference_id', 'amount', 'balance',
             'description', 'journal_entry_id', 'created_by', 'created_at'],
            [
                'CREATE INDEX idx_cashl_branch_date ON cash_ledger_flat (branch_id, transaction_date)',
            ],
            [
                "CREATE POLICY rls_cash_ledger_select ON cash_ledger FOR SELECT USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)",
                "CREATE POLICY rls_cash_ledger_insert ON cash_ledger FOR INSERT WITH CHECK (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)",
                "CREATE POLICY rls_cash_ledger_update ON cash_ledger FOR UPDATE USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int) WITH CHECK (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)",
                "CREATE POLICY rls_cash_ledger_delete ON cash_ledger FOR DELETE USING (current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int)",
                "CREATE POLICY rls_cash_ledger_admin ON cash_ledger FOR ALL USING (current_setting('app.is_admin', true) = 'true') WITH CHECK (current_setting('app.is_admin', true) = 'true')",
            ]
        );
    }

    private function rollbackBranchLedger(): void
    {
        $this->rollbackPartitionedTable(
            'branch_ledger',
            <<<'SQL'
                CREATE TABLE branch_ledger_flat (
                    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    transaction_date  DATE NOT NULL,
                    from_branch_id    INTEGER NOT NULL REFERENCES branches(id) DEFERRABLE INITIALLY DEFERRED,
                    to_branch_id      INTEGER NOT NULL REFERENCES branches(id) DEFERRABLE INITIALLY DEFERRED,
                    reference_type    VARCHAR(50) NOT NULL DEFAULT 'adjustment',
                    reference_id      INTEGER DEFAULT NULL,
                    journal_entry_id  INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                    debit             NUMERIC(12,2) DEFAULT 0,
                    credit            NUMERIC(12,2) DEFAULT 0,
                    running_balance   NUMERIC(12,2) DEFAULT NULL,
                    remarks           TEXT,
                    is_reversed       BOOLEAN NOT NULL DEFAULT false,
                    created_by        INTEGER DEFAULT NULL,
                    created_at        TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP
                )
            SQL,
            ['id', 'transaction_date', 'from_branch_id', 'to_branch_id',
             'reference_type', 'reference_id', 'journal_entry_id',
             'debit', 'credit', 'running_balance', 'remarks',
             'is_reversed', 'created_by', 'created_at'],
            [
                'CREATE INDEX idx_bl_branches ON branch_ledger_flat (from_branch_id, to_branch_id)',
                'CREATE INDEX idx_bl_reference ON branch_ledger_flat (reference_type, reference_id)',
                'CREATE INDEX idx_bl_date ON branch_ledger_flat (transaction_date)',
                "CREATE INDEX idx_bl_active ON branch_ledger_flat (from_branch_id, to_branch_id, transaction_date) WHERE is_reversed = false",
            ],
            [
                "CREATE POLICY rls_branch_ledger_select ON branch_ledger FOR SELECT USING (current_setting('app.is_admin', true) = 'true' OR from_branch_id = current_setting('app.branch_id')::int OR to_branch_id = current_setting('app.branch_id')::int)",
                "CREATE POLICY rls_branch_ledger_insert ON branch_ledger FOR INSERT WITH CHECK (current_setting('app.is_admin', true) = 'true' OR from_branch_id = current_setting('app.branch_id')::int OR to_branch_id = current_setting('app.branch_id')::int)",
                "CREATE POLICY rls_branch_ledger_update ON branch_ledger FOR UPDATE USING (current_setting('app.is_admin', true) = 'true' OR from_branch_id = current_setting('app.branch_id')::int OR to_branch_id = current_setting('app.branch_id')::int) WITH CHECK (current_setting('app.is_admin', true) = 'true' OR from_branch_id = current_setting('app.branch_id')::int OR to_branch_id = current_setting('app.branch_id')::int)",
                "CREATE POLICY rls_branch_ledger_delete ON branch_ledger FOR DELETE USING (current_setting('app.is_admin', true) = 'true' OR from_branch_id = current_setting('app.branch_id')::int OR to_branch_id = current_setting('app.branch_id')::int)",
                "CREATE POLICY rls_branch_ledger_admin ON branch_ledger FOR ALL USING (current_setting('app.is_admin', true) = 'true') WITH CHECK (current_setting('app.is_admin', true) = 'true')",
            ]
        );
    }
};
