<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Phase 1.3 — Add demand_send, demand_receive, demand_reversal to
 * stock_transactions.reference_type CHECK constraint.
 *
 * The legacy system uses three distinct reference types for branch demand
 * stock movements:
 *   - demand_send:     Stock OUT from supplier warehouse
 *   - demand_receive:  Stock IN to requester warehouse
 *   - demand_reversal: Reversal of both send/receive
 *
 * The current PostgreSQL CHECK only allows the generic 'branch_demand'.
 * This migration adds the three sub-types for granular traceability.
 * The generic 'branch_demand' is kept as a fallback.
 */
return new class extends Migration
{
    public function up(): void
    {
        // Drop the existing CHECK constraint on all partitions and the default partition.
        // The constraint name is auto-generated by PG as stock_transactions_reference_type_check
        // but it may differ per partition. We use a loop to handle all.
        DB::statement("
            DO \$\$
            DECLARE
                tbl text;
                con text;
            BEGIN
                -- Drop constraint from the main (partitioned) table
                FOR con IN
                    SELECT conname FROM pg_constraint
                    WHERE conrelid = 'stock_transactions'::regclass
                      AND contype = 'c'
                      AND conname LIKE '%reference_type%'
                LOOP
                    EXECUTE format('ALTER TABLE stock_transactions DROP CONSTRAINT %I', con);
                END LOOP;

                -- Drop constraint from the default partition if it exists
                FOR con IN
                    SELECT conname FROM pg_constraint
                    WHERE conrelid = 'stock_transactions_default'::regclass
                      AND contype = 'c'
                      AND conname LIKE '%reference_type%'
                LOOP
                    EXECUTE format('ALTER TABLE stock_transactions_default DROP CONSTRAINT %I', con);
                END LOOP;

                -- Drop constraint from any monthly partition
                FOR tbl IN
                    SELECT inhrelid::regclass::text
                    FROM pg_inherits
                    WHERE inhparent = 'stock_transactions'::regclass
                      AND inhrelid::regclass::text != 'stock_transactions_default'
                LOOP
                    FOR con IN
                        SELECT conname FROM pg_constraint
                        WHERE conrelid = tbl::regclass
                          AND contype = 'c'
                          AND conname LIKE '%reference_type%'
                    LOOP
                        EXECUTE format('ALTER TABLE %I DROP CONSTRAINT %I', tbl, con);
                    END LOOP;
                END LOOP;
            END;
            \$\$
        ");

        // Add the new CHECK constraint with the three new reference types
        DB::statement("
            ALTER TABLE stock_transactions
            ADD CONSTRAINT stock_transactions_reference_type_check
            CHECK (reference_type IN (
                'purchase_receive','purchase_return','sales_challan','sales_return',
                'stock_adjustment','stock_take','warehouse_transfer','damage',
                'branch_demand','demand_send','demand_receive','demand_reversal',
                'opening_balance','reversal'
            ))
        ");
    }

    public function down(): void
    {
        // Remove the new constraint
        DB::statement("
            ALTER TABLE stock_transactions
            DROP CONSTRAINT IF EXISTS stock_transactions_reference_type_check
        ");

        // Restore the original constraint (without the three new types)
        DB::statement("
            ALTER TABLE stock_transactions
            ADD CONSTRAINT stock_transactions_reference_type_check
            CHECK (reference_type IN (
                'purchase_receive','purchase_return','sales_challan','sales_return',
                'stock_adjustment','stock_take','warehouse_transfer','damage',
                'branch_demand','opening_balance','reversal'
            ))
        ");
    }
};
