<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

/**
 * Phase 10.1 — Phase 5: Multi-FK Transaction Header Partitioning.
 *
 * Partitions 6 transaction header tables by their natural date column:
 *
 *   1. customer_payments     — by payment_date     (children: invoice_payment_allocations,
 *                                                   branch_demand_customer_payment_settlements)
 *   2. supplier_payments     — by payment_date     (child:  supplier_payment_settlements)
 *   3. sales_challans        — by challan_date     (child:  sales_challan_items)
 *   4. warehouse_transfers   — by transfer_date    (children: warehouse_transfer_items,
 *                                                   branch_demands)
 *   5. stock_adjustments     — by adjustment_date  (children: stock_adjustment_items,
 *                                                   stock_adjustment_audit_log)
 *   6. stock_take_sessions   — by session_date     (children: stock_take_warehouses,
 *                                                   stock_take_items,
 *                                                   stock_take_audit_log)
 *
 * 11 child-table FK conversions to trigger-based (revised from original plan's 8 —
 * see roadmap §4.1.1 for the schema-audit findings that revealed the extra 3):
 *
 *   - invoice_payment_allocations.payment_id                       → customer_payments(id) CASCADE
 *   - branch_demand_customer_payment_settlements.payment_id        → customer_payments(id) CASCADE
 *   - supplier_payment_settlements.payment_id                      → supplier_payments(id)   CASCADE
 *   - sales_challan_items.sales_challan_id                         → sales_challans(id)      CASCADE
 *   - warehouse_transfer_items.warehouse_transfer_id               → warehouse_transfers(id) CASCADE
 *   - branch_demands.warehouse_transfer_id                         → warehouse_transfers(id) SET NULL
 *   - stock_adjustment_items.stock_adjustment_id                   → stock_adjustments(id)   CASCADE
 *   - stock_adjustment_audit_log.stock_adjustment_id               → stock_adjustments(id)   CASCADE
 *   - stock_take_warehouses.stock_take_session_id                  → stock_take_sessions(id) CASCADE
 *   - stock_take_items.stock_take_session_id                       → stock_take_sessions(id) CASCADE
 *   - stock_take_audit_log.stock_take_session_id                   → stock_take_sessions(id) CASCADE
 *
 * Each FK conversion follows the Phase 4 pattern:
 *   1. Look up the declarative FK constraint name from pg_constraint.
 *   2. Drop the declarative FK.
 *   3. Create a BEFORE INSERT OR UPDATE check trigger on the child table.
 *   4. If ON DELETE CASCADE, create an AFTER DELETE cascade trigger on the parent.
 *   5. If ON DELETE SET NULL, create an AFTER DELETE set-null trigger on the parent.
 *
 * DESIGN NOTES
 * ------------
 * - PK(id) → PK(id, date_column) for partitioned parents (PostgreSQL requirement).
 * - GENERATED ALWAYS → GENERATED BY DEFAULT for OVERRIDING SYSTEM VALUE data copy.
 * - UNIQUE(code) → UNIQUE(code, date_column) — PostgreSQL requires the partition key
 *   in every UNIQUE constraint on a partitioned table.
 * - Declarative FKs to journal_entries(id) are PRESERVED (Phase 6 converts them).
 * - sales_challans.sales_invoice_id is already trigger-based (trg_fk_sc_si) — preserved.
 * - stock_adjustment_items.sai_stock_tx_fk is a composite declarative FK to
 *   stock_transactions(id, transaction_date) — preserved (out of scope for Phase 5).
 * - All 6 parents: deleted_at (soft deletes), created_at/updated_at, branch_id (RLS).
 *   warehouse_transfers uses dual-branch RLS (from_branch_id OR to_branch_id).
 * - Triggers preserved on parents: updated_at, financial_audit (customer_payments +
 *   supplier_payments only), LISTEN/NOTIFY (customer_payments + sales_challans),
 *   trg_fk_sc_si (sales_challans only), trg_enforce_same_branch_transfer
 *   (warehouse_transfers only).
 *
 * IDEMPOTENT: each partition method early-returns if the table is already partitioned.
 *
 * ⚠️  Run during a maintenance window — locks tables during the data copy phase.
 */
return new class extends Migration
{
    private ?bool $hasPgPartman = null;

    // ═══════════════════════════════════════════════════════════════
    //  Helpers (same patterns as Phase 4 migration)
    // ═══════════════════════════════════════════════════════════════

    private function hasPgPartman(): bool
    {
        if ($this->hasPgPartman !== null) {
            return $this->hasPgPartman;
        }
        $row = DB::selectOne("
            SELECT EXISTS (
                SELECT 1 FROM pg_available_extensions WHERE name = 'pg_partman'
            ) AS installed
        ");
        $this->hasPgPartman = (bool) ($row->installed ?? false);
        if (! $this->hasPgPartman) {
            logger()->warning('pg_partman is not installed. Automatic partition maintenance is disabled.');
        }
        return $this->hasPgPartman;
    }

    private function isAlreadyPartitioned(string $tableName): bool
    {
        $row = DB::selectOne("
            SELECT 1
            FROM pg_partitioned_table pt
            JOIN pg_class c ON c.oid = pt.partrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relname = ? AND n.nspname = current_schema()
            LIMIT 1
        ", [$tableName]);
        return $row !== null;
    }

    private function relationExists(string $name): bool
    {
        $row = DB::selectOne("
            SELECT 1
            FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relname = ? AND n.nspname = current_schema()
            LIMIT 1
        ", [$name]);
        return $row !== null;
    }

    private function createMonthlyPartitions(string $parent, string $year): void
    {
        for ($m = 1; $m <= 12; $m++) {
            $from = sprintf('%s-%02d-01', $year, $m);
            $to   = $m < 12
                ? sprintf('%s-%02d-01', $year, $m + 1)
                : sprintf('%d-01-01', (int) $year + 1);
            $name = sprintf('%s_%s_%02d', $parent, $year, $m);

            if (! $this->relationExists($name)) {
                DB::statement(
                    "CREATE TABLE {$name} PARTITION OF {$parent}
                     FOR VALUES FROM ('{$from}') TO ('{$to}')"
                );
            }
        }

        $defaultName = "{$parent}_default";
        if (! $this->relationExists($defaultName)) {
            DB::statement(
                "CREATE TABLE {$defaultName} PARTITION OF {$parent} DEFAULT"
            );
        }
    }

    private function createPreYearPartition(string $parent, string $preYear, string $startYear): void
    {
        $name = "{$parent}_{$preYear}";
        if (! $this->relationExists($name)) {
            DB::statement(
                "CREATE TABLE {$name} PARTITION OF {$parent}
                 FOR VALUES FROM ('2020-01-01') TO ('{$startYear}-01-01')"
            );
        }
    }

    private function registerPartman(string $parent, string $control, string $startPartition): void
    {
        if (! $this->hasPgPartman()) {
            return;
        }
        try {
            DB::statement(<<<SQL
                SELECT partman.create_parent(
                    p_parent_table    := 'public.{$parent}',
                    p_control         := '{$control}',
                    p_type            := 'range',
                    p_interval        := '1 month',
                    p_premake         := 6,
                    p_start_partition := '{$startPartition}'
                )
            SQL);
        } catch (\Throwable $e) {
            // Already registered with pg_partman — safe to ignore.
        }
    }

    private function fixSequence(string $table): void
    {
        DB::statement(<<<SQL
            SELECT setval(
                pg_get_serial_sequence('{$table}', 'id'),
                GREATEST(COALESCE((SELECT MAX(id) FROM {$table}), 0), 1)
            )
        SQL);
    }

    private function dropRlsPolicies(string $tableName): void
    {
        $policies = DB::select("
            SELECT polname
            FROM pg_policy p
            JOIN pg_class c ON c.oid = p.polrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relname = ? AND n.nspname = current_schema()
        ", [$tableName]);

        foreach ($policies as $policy) {
            DB::statement("DROP POLICY IF EXISTS {$policy->polname} ON {$tableName}");
        }
    }

    private function dropIndexesExceptPK(string $tableName): void
    {
        $indexes = DB::select("
            SELECT indexname
            FROM pg_indexes
            WHERE tablename = ? AND indexname NOT LIKE '%_pkey'
        ", [$tableName]);

        foreach ($indexes as $idx) {
            DB::statement("DROP INDEX IF EXISTS {$idx->indexname}");
        }
    }

    /**
     * Drop a declarative FK constraint by table + constraint name.
     */
    private function dropFkConstraint(string $table, string $constraintName): void
    {
        DB::statement("ALTER TABLE {$table} DROP CONSTRAINT IF EXISTS {$constraintName}");
    }

    /**
     * Drop ALL declarative FKs from a child table to a given parent.
     * Used when the constraint name is auto-generated (not known ahead of time).
     * Returns the list of (constraint_name, fk_column, on_delete) that were dropped.
     *
     * @return list<array{conname: string, col: string, deltype: string}>
     */
    private function dropAllFksToParent(string $childTable, string $parentTable): array
    {
        $fks = DB::select(<<<SQL
            SELECT c.conname, a.attname AS col, c.confdeltype AS deltype
            FROM pg_constraint c
            JOIN pg_class t ON t.oid = c.conrelid
            JOIN pg_namespace n ON n.oid = t.relnamespace
            JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = ANY(c.conkey)
            JOIN pg_class rt ON rt.oid = c.confrelid
            JOIN pg_namespace rn ON rn.oid = rt.relnamespace
            WHERE t.relname = ?
              AND n.nspname = 'public'
              AND c.contype = 'f'
              AND rt.relname = ?
              AND rn.nspname = 'public'
        SQL, [$childTable, $parentTable]);

        $dropped = [];
        foreach ($fks as $fk) {
            DB::statement("ALTER TABLE {$childTable} DROP CONSTRAINT IF EXISTS {$fk->conname}");
            $dropped[] = ['conname' => $fk->conname, 'col' => $fk->col, 'deltype' => $fk->deltype];
            Log::info("Phase 5: Dropped declarative FK {$fk->conname} on {$childTable}.{$fk->col} → {$parentTable}(id)");
        }
        return $dropped;
    }

    /**
     * Create a trigger-based FK check function + trigger for a child→parent reference.
     * Replaces declarative FK when the parent is partitioned.
     */
    private function createTriggerFkCheck(
        string $childTable,
        string $fkColumn,
        string $parentTable,
        string $triggerFuncName,
        string $triggerName
    ): void {
        DB::statement("DROP TRIGGER IF EXISTS {$triggerName} ON {$childTable}");

        DB::statement(<<<SQL
            CREATE OR REPLACE FUNCTION {$triggerFuncName}()
            RETURNS TRIGGER AS \$\$
            BEGIN
                IF NEW.{$fkColumn} IS NOT NULL THEN
                    IF NOT EXISTS (
                        SELECT 1 FROM {$parentTable}
                        WHERE id = NEW.{$fkColumn}
                    ) THEN
                        RAISE EXCEPTION 'FK violation: {$parentTable}(id=%) not found for {$childTable}.{$fkColumn}',
                            NEW.{$fkColumn};
                    END IF;
                END IF;
                RETURN NEW;
            END;
            \$\$ LANGUAGE plpgsql
        SQL);

        DB::statement(<<<SQL
            CREATE TRIGGER {$triggerName}
                BEFORE INSERT OR UPDATE OF {$fkColumn} ON {$childTable}
                FOR EACH ROW EXECUTE FUNCTION {$triggerFuncName}()
        SQL);
    }

    /**
     * Create a trigger-based cascade delete function + trigger on the parent.
     */
    private function createTriggerFkCascadeDelete(
        string $childTable,
        string $fkColumn,
        string $parentTable,
        string $triggerFuncName,
        string $triggerName
    ): void {
        DB::statement("DROP TRIGGER IF EXISTS {$triggerName} ON {$parentTable}");

        DB::statement(<<<SQL
            CREATE OR REPLACE FUNCTION {$triggerFuncName}()
            RETURNS TRIGGER AS \$\$
            BEGIN
                DELETE FROM {$childTable} WHERE {$fkColumn} = OLD.id;
                RETURN OLD;
            END;
            \$\$ LANGUAGE plpgsql
        SQL);

        DB::statement(<<<SQL
            CREATE TRIGGER {$triggerName}
                AFTER DELETE ON {$parentTable}
                FOR EACH ROW EXECUTE FUNCTION {$triggerFuncName}()
        SQL);
    }

    /**
     * Create a trigger-based SET NULL function + trigger on the parent.
     */
    private function createTriggerFkSetNull(
        string $childTable,
        string $fkColumn,
        string $parentTable,
        string $triggerFuncName,
        string $triggerName
    ): void {
        DB::statement("DROP TRIGGER IF EXISTS {$triggerName} ON {$parentTable}");

        DB::statement(<<<SQL
            CREATE OR REPLACE FUNCTION {$triggerFuncName}()
            RETURNS TRIGGER AS \$\$
            BEGIN
                UPDATE {$childTable} SET {$fkColumn} = NULL WHERE {$fkColumn} = OLD.id;
                RETURN OLD;
            END;
            \$\$ LANGUAGE plpgsql
        SQL);

        DB::statement(<<<SQL
            CREATE TRIGGER {$triggerName}
                AFTER DELETE ON {$parentTable}
                FOR EACH ROW EXECUTE FUNCTION {$triggerFuncName}()
        SQL);
    }

    /**
     * Re-enable single-branch RLS with the standard 5-policy pattern.
     */
    private function enableSingleBranchRls(string $table): void
    {
        DB::statement("ALTER TABLE {$table} ENABLE ROW LEVEL SECURITY");
        DB::statement("ALTER TABLE {$table} FORCE ROW LEVEL SECURITY");

        $cond = "current_setting('app.is_admin', true) = 'true' OR branch_id = current_setting('app.branch_id')::int";
        DB::statement("CREATE POLICY rls_{$table}_select ON {$table} FOR SELECT USING ({$cond})");
        DB::statement("CREATE POLICY rls_{$table}_insert ON {$table} FOR INSERT WITH CHECK ({$cond})");
        DB::statement("CREATE POLICY rls_{$table}_update ON {$table} FOR UPDATE USING ({$cond}) WITH CHECK ({$cond})");
        DB::statement("CREATE POLICY rls_{$table}_delete ON {$table} FOR DELETE USING ({$cond})");
        DB::statement("CREATE POLICY rls_{$table}_admin ON {$table} FOR ALL USING (current_setting('app.is_admin', true) = 'true') WITH CHECK (current_setting('app.is_admin', true) = 'true')");
    }

    /**
     * Re-enable dual-branch RLS (from_branch_id OR to_branch_id) — used by warehouse_transfers.
     */
    private function enableDualBranchRls(string $table): void
    {
        DB::statement("ALTER TABLE {$table} ENABLE ROW LEVEL SECURITY");
        DB::statement("ALTER TABLE {$table} FORCE ROW LEVEL SECURITY");

        $cond = "current_setting('app.is_admin', true) = 'true' OR from_branch_id = current_setting('app.branch_id')::int OR to_branch_id = current_setting('app.branch_id')::int";
        DB::statement("CREATE POLICY rls_{$table}_select ON {$table} FOR SELECT USING ({$cond})");
        DB::statement("CREATE POLICY rls_{$table}_insert ON {$table} FOR INSERT WITH CHECK ({$cond})");
        DB::statement("CREATE POLICY rls_{$table}_update ON {$table} FOR UPDATE USING ({$cond}) WITH CHECK ({$cond})");
        DB::statement("CREATE POLICY rls_{$table}_delete ON {$table} FOR DELETE USING ({$cond})");
        DB::statement("CREATE POLICY rls_{$table}_admin ON {$table} FOR ALL USING (current_setting('app.is_admin', true) = 'true') WITH CHECK (current_setting('app.is_admin', true) = 'true')");
    }

    // ═══════════════════════════════════════════════════════════════
    //  up()
    // ═══════════════════════════════════════════════════════════════

    public function up(): void
    {
        if ($this->hasPgPartman()) {
            DB::statement('CREATE EXTENSION IF NOT EXISTS pg_partman');
            DB::statement('CREATE SCHEMA IF NOT EXISTS partman');
        }

        $this->partitionCustomerPayments();
        $this->partitionSupplierPayments();
        $this->partitionSalesChallans();
        $this->partitionWarehouseTransfers();
        $this->partitionStockAdjustments();
        $this->partitionStockTakeSessions();
    }

    // ═══════════════════════════════════════════════════════════════
    //  1. customer_payments  (children: invoice_payment_allocations,
    //                                  branch_demand_customer_payment_settlements)
    // ═══════════════════════════════════════════════════════════════

    private function partitionCustomerPayments(): void
    {
        if ($this->isAlreadyPartitioned('customer_payments')) {
            return;
        }

        // ── Convert inbound FKs to trigger-based BEFORE partitioning ──
        // 1. invoice_payment_allocations.payment_id → customer_payments(id) ON DELETE CASCADE
        $this->dropFkConstraint('invoice_payment_allocations', 'ipa_payment_id_foreign');
        $this->createTriggerFkCheck(
            'invoice_payment_allocations', 'payment_id', 'customer_payments',
            'trg_fk_ipa_cp_check', 'trg_ipa_cp_fk_check'
        );
        $this->createTriggerFkCascadeDelete(
            'invoice_payment_allocations', 'payment_id', 'customer_payments',
            'trg_fk_cp_cascade_ipa', 'trg_cp_cascade_ipa'
        );

        // 2. branch_demand_customer_payment_settlements.payment_id → customer_payments(id) ON DELETE CASCADE
        //    FK is inline-auto-named — discover + drop all FKs to this parent.
        $this->dropAllFksToParent('branch_demand_customer_payment_settlements', 'customer_payments');
        $this->createTriggerFkCheck(
            'branch_demand_customer_payment_settlements', 'payment_id', 'customer_payments',
            'trg_fk_bdcpss_cp_check', 'trg_bdcpss_cp_fk_check'
        );
        $this->createTriggerFkCascadeDelete(
            'branch_demand_customer_payment_settlements', 'payment_id', 'customer_payments',
            'trg_fk_cp_cascade_bdcpss', 'trg_cp_cascade_bdcpss'
        );

        // ── Partition customer_payments ──
        $this->dropIndexesExceptPK('customer_payments');
        $this->dropRlsPolicies('customer_payments');

        DB::statement('ALTER TABLE customer_payments RENAME TO customer_payments_unpartitioned');

        DB::statement(<<<'SQL'
            CREATE TABLE customer_payments (
                id                            INTEGER GENERATED BY DEFAULT AS IDENTITY,
                payment_code                  VARCHAR(30) NOT NULL,
                payment_date                  DATE NOT NULL,
                customer_id                   INTEGER NOT NULL,
                branch_id                     INTEGER NOT NULL REFERENCES branches(id) DEFERRABLE INITIALLY DEFERRED,
                bank_id                       INTEGER REFERENCES banks(id) DEFERRABLE INITIALLY DEFERRED,
                collected_by                  INTEGER,
                payment_mode                  VARCHAR(20) NOT NULL CHECK (payment_mode IN ('cash','bank','mobile_banking','cheque','adjustment')),
                transaction_type              VARCHAR(20) NOT NULL DEFAULT 'receive' CHECK (transaction_type IN ('receive','payment','discount','write_off')),
                reference_no                  VARCHAR(100),
                amount                        NUMERIC(14,2) NOT NULL DEFAULT 0,
                discount_amount               NUMERIC(14,2) DEFAULT 0,
                journal_entry_id              INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                intercompany_journal_entry_id INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                is_reversed                   BOOLEAN NOT NULL DEFAULT false,
                reversed_at                   TIMESTAMP(0),
                reversed_by                   INTEGER,
                reverse_reason                TEXT,
                notes                         TEXT,
                created_by                    INTEGER,
                created_at                    TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                updated_at                    TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                deleted_at                    TIMESTAMP(0),
                PRIMARY KEY (id, payment_date),
                CONSTRAINT customer_payments_code_unique UNIQUE (payment_code, payment_date)
            ) PARTITION BY RANGE (payment_date)
        SQL);

        $this->createPreYearPartition('customer_payments', 'pre2026', '2026');
        $this->createMonthlyPartitions('customer_payments', '2026');

        DB::statement(<<<'SQL'
            INSERT INTO customer_payments (
                id, payment_code, payment_date, customer_id, branch_id,
                bank_id, collected_by, payment_mode, transaction_type, reference_no,
                amount, discount_amount, journal_entry_id, intercompany_journal_entry_id,
                is_reversed, reversed_at, reversed_by, reverse_reason,
                notes, created_by, created_at, updated_at, deleted_at
            )
            OVERRIDING SYSTEM VALUE
            SELECT
                id, payment_code, payment_date, customer_id, branch_id,
                bank_id, collected_by, payment_mode, transaction_type, reference_no,
                amount, discount_amount, journal_entry_id, intercompany_journal_entry_id,
                is_reversed, reversed_at, reversed_by, reverse_reason,
                notes, created_by, created_at, updated_at, deleted_at
            FROM customer_payments_unpartitioned
            ORDER BY payment_date, id
        SQL);

        DB::statement('SET CONSTRAINTS ALL IMMEDIATE');

        $this->fixSequence('customer_payments');

        // Recreate indexes
        DB::statement('CREATE INDEX idx_cp_customer ON customer_payments (customer_id)');
        DB::statement('CREATE INDEX idx_cp_bank ON customer_payments (bank_id)');
        DB::statement('CREATE INDEX idx_cp_branch ON customer_payments (branch_id)');
        DB::statement('CREATE INDEX idx_cp_journal ON customer_payments (journal_entry_id)');
        DB::statement('CREATE INDEX idx_cp_reference_no ON customer_payments (reference_no) WHERE reference_no IS NOT NULL');
        DB::statement('CREATE INDEX idx_cp_active ON customer_payments (customer_id, payment_date) WHERE is_reversed = false');
        DB::statement('CREATE INDEX idx_cp_active_by_branch ON customer_payments (branch_id, payment_date) WHERE is_reversed = false');
        DB::statement(<<<'SQL'
            CREATE INDEX idx_cp_listing_covering ON customer_payments (branch_id, payment_date DESC, id DESC)
                INCLUDE (customer_id, payment_code, payment_mode, amount, is_reversed)
        SQL);
        DB::statement('CREATE INDEX idx_cp_perf_user_date ON customer_payments (created_by, payment_date) WHERE is_reversed = false');
        DB::statement(<<<'SQL'
            CREATE INDEX idx_cp_payment_date_brin
                ON customer_payments USING BRIN (payment_date)
                WITH (pages_per_range = 32)
        SQL);
        DB::statement(<<<'SQL'
            CREATE INDEX idx_cp_created_at_brin
                ON customer_payments USING BRIN (created_at)
                WITH (pages_per_range = 32)
        SQL);

        // Recreate updated_at trigger (function exists globally)
        DB::statement(<<<'SQL'
            CREATE TRIGGER trg_customer_payments_updated_at
                BEFORE UPDATE ON customer_payments
                FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()
        SQL);

        // Recreate LISTEN/NOTIFY trigger (function rcerp_notify_customer_payment exists)
        DB::statement(<<<'SQL'
            CREATE TRIGGER trg_notify_customer_payments
                AFTER INSERT OR UPDATE ON customer_payments
                FOR EACH ROW EXECUTE FUNCTION rcerp_notify_customer_payment()
        SQL);

        // Recreate financial audit trigger (function fn_financial_audit_trigger exists)
        DB::statement(<<<'SQL'
            CREATE TRIGGER trg_audit_customer_payments
                AFTER INSERT OR UPDATE OR DELETE ON customer_payments
                FOR EACH ROW EXECUTE FUNCTION fn_financial_audit_trigger()
        SQL);

        $this->enableSingleBranchRls('customer_payments');

        DB::statement('DROP TABLE customer_payments_unpartitioned');
        $this->registerPartman('customer_payments', 'payment_date', '2027-01-01');
        DB::statement('ANALYZE customer_payments');
    }

    // ═══════════════════════════════════════════════════════════════
    //  2. supplier_payments  (child: supplier_payment_settlements)
    // ═══════════════════════════════════════════════════════════════

    private function partitionSupplierPayments(): void
    {
        if ($this->isAlreadyPartitioned('supplier_payments')) {
            return;
        }

        // ── Convert inbound FK to trigger-based ──
        // supplier_payment_settlements.payment_id → supplier_payments(id) ON DELETE CASCADE (auto-named)
        $this->dropAllFksToParent('supplier_payment_settlements', 'supplier_payments');
        $this->createTriggerFkCheck(
            'supplier_payment_settlements', 'payment_id', 'supplier_payments',
            'trg_fk_sps_sp_check', 'trg_sps_sp_fk_check'
        );
        $this->createTriggerFkCascadeDelete(
            'supplier_payment_settlements', 'payment_id', 'supplier_payments',
            'trg_fk_sp_cascade_sps', 'trg_sp_cascade_sps'
        );

        // ── Partition supplier_payments ──
        $this->dropIndexesExceptPK('supplier_payments');
        $this->dropRlsPolicies('supplier_payments');

        DB::statement('ALTER TABLE supplier_payments RENAME TO supplier_payments_unpartitioned');

        DB::statement(<<<'SQL'
            CREATE TABLE supplier_payments (
                id                            INTEGER GENERATED BY DEFAULT AS IDENTITY,
                payment_code                  VARCHAR(30) NOT NULL,
                payment_date                  DATE NOT NULL,
                supplier_id                   INTEGER NOT NULL REFERENCES suppliers(id) DEFERRABLE INITIALLY DEFERRED,
                branch_id                     INTEGER NOT NULL REFERENCES branches(id) DEFERRABLE INITIALLY DEFERRED,
                bank_id                       INTEGER REFERENCES banks(id) DEFERRABLE INITIALLY DEFERRED,
                payment_mode                  VARCHAR(20) NOT NULL CHECK (payment_mode IN ('cash','bank','mobile_banking','cheque','adjustment')),
                transaction_type              VARCHAR(20) NOT NULL DEFAULT 'payment'
                    CONSTRAINT supplier_payments_transaction_type_check
                    CHECK (transaction_type IN ('payment','advance','receive')),
                amount                        NUMERIC(14,2) NOT NULL DEFAULT 0,
                discount_amount               NUMERIC(14,2) DEFAULT 0,
                reference_no                  VARCHAR(100),
                collected_by                  INTEGER REFERENCES employees(id) ON DELETE SET NULL,
                journal_entry_id              INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                intercompany_journal_entry_id INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                is_reversed                   BOOLEAN NOT NULL DEFAULT false,
                reversed_at                   TIMESTAMP(0),
                reversed_by                   INTEGER,
                reverse_reason                TEXT,
                notes                         TEXT,
                created_by                    INTEGER,
                created_at                    TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                updated_at                    TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                deleted_at                    TIMESTAMP(0),
                PRIMARY KEY (id, payment_date),
                CONSTRAINT supplier_payments_code_unique UNIQUE (payment_code, payment_date)
            ) PARTITION BY RANGE (payment_date)
        SQL);

        $this->createPreYearPartition('supplier_payments', 'pre2026', '2026');
        $this->createMonthlyPartitions('supplier_payments', '2026');

        DB::statement(<<<'SQL'
            INSERT INTO supplier_payments (
                id, payment_code, payment_date, supplier_id, branch_id,
                bank_id, payment_mode, transaction_type, amount, discount_amount,
                reference_no, collected_by, journal_entry_id, intercompany_journal_entry_id,
                is_reversed, reversed_at, reversed_by, reverse_reason,
                notes, created_by, created_at, updated_at, deleted_at
            )
            OVERRIDING SYSTEM VALUE
            SELECT
                id, payment_code, payment_date, supplier_id, branch_id,
                bank_id, payment_mode, transaction_type, amount, discount_amount,
                reference_no, collected_by, journal_entry_id, intercompany_journal_entry_id,
                is_reversed, reversed_at, reversed_by, reverse_reason,
                notes, created_by, created_at, updated_at, deleted_at
            FROM supplier_payments_unpartitioned
            ORDER BY payment_date, id
        SQL);

        DB::statement('SET CONSTRAINTS ALL IMMEDIATE');

        $this->fixSequence('supplier_payments');

        // Recreate indexes
        DB::statement('CREATE INDEX idx_sp_supplier ON supplier_payments (supplier_id)');
        DB::statement('CREATE INDEX idx_sp_bank ON supplier_payments (bank_id)');
        DB::statement('CREATE INDEX idx_sp_branch ON supplier_payments (branch_id)');
        DB::statement('CREATE INDEX idx_sp_collected_by ON supplier_payments (collected_by)');
        DB::statement('CREATE INDEX idx_sp_journal ON supplier_payments (journal_entry_id)');
        DB::statement('CREATE INDEX idx_sp_active ON supplier_payments (supplier_id, payment_date) WHERE is_reversed = false');
        DB::statement('CREATE INDEX idx_sp_active_by_branch ON supplier_payments (branch_id, payment_date) WHERE is_reversed = false');
        DB::statement(<<<'SQL'
            CREATE INDEX idx_sp_listing_covering ON supplier_payments (branch_id, payment_date DESC, id DESC)
                INCLUDE (supplier_id, payment_code, payment_mode, amount, is_reversed)
        SQL);
        DB::statement(<<<'SQL'
            CREATE INDEX idx_sp_payment_date_brin
                ON supplier_payments USING BRIN (payment_date)
                WITH (pages_per_range = 32)
        SQL);
        DB::statement(<<<'SQL'
            CREATE INDEX idx_sp_created_at_brin
                ON supplier_payments USING BRIN (created_at)
                WITH (pages_per_range = 32)
        SQL);

        // Recreate updated_at trigger
        DB::statement(<<<'SQL'
            CREATE TRIGGER trg_supplier_payments_updated_at
                BEFORE UPDATE ON supplier_payments
                FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()
        SQL);

        // Recreate financial audit trigger (function exists)
        DB::statement(<<<'SQL'
            CREATE TRIGGER trg_audit_supplier_payments
                AFTER INSERT OR UPDATE OR DELETE ON supplier_payments
                FOR EACH ROW EXECUTE FUNCTION fn_financial_audit_trigger()
        SQL);

        $this->enableSingleBranchRls('supplier_payments');

        DB::statement('DROP TABLE supplier_payments_unpartitioned');
        $this->registerPartman('supplier_payments', 'payment_date', '2027-01-01');
        DB::statement('ANALYZE supplier_payments');
    }

    // ═══════════════════════════════════════════════════════════════
    //  3. sales_challans  (child: sales_challan_items)
    // ═══════════════════════════════════════════════════════════════

    private function partitionSalesChallans(): void
    {
        if ($this->isAlreadyPartitioned('sales_challans')) {
            return;
        }

        // ── Convert inbound FK to trigger-based ──
        // sales_challan_items.sales_challan_id → sales_challans(id) ON DELETE CASCADE
        $this->dropFkConstraint('sales_challan_items', 'fk_sci_challan');
        $this->createTriggerFkCheck(
            'sales_challan_items', 'sales_challan_id', 'sales_challans',
            'trg_fk_sci_sc_check', 'trg_sci_sc_fk_check'
        );
        $this->createTriggerFkCascadeDelete(
            'sales_challan_items', 'sales_challan_id', 'sales_challans',
            'trg_fk_sc_cascade_sci', 'trg_sc_cascade_sci'
        );

        // ── Partition sales_challans ──
        $this->dropIndexesExceptPK('sales_challans');
        $this->dropRlsPolicies('sales_challans');

        DB::statement('ALTER TABLE sales_challans RENAME TO sales_challans_unpartitioned');

        DB::statement(<<<'SQL'
            CREATE TABLE sales_challans (
                id                          INTEGER GENERATED BY DEFAULT AS IDENTITY,
                challan_code                VARCHAR(30) NOT NULL,
                challan_date                DATE NOT NULL,
                sales_invoice_id            INTEGER NOT NULL,
                branch_id                   INTEGER NOT NULL REFERENCES branches(id) DEFERRABLE INITIALLY DEFERRED,
                transport_name              VARCHAR(100),
                transport_phone             VARCHAR(30),
                vehicle_number              VARCHAR(50),
                driver_name                 VARCHAR(100),
                transport_cost              NUMERIC(12,2) DEFAULT 0,
                transport_adjustment        NUMERIC(12,2) DEFAULT 0,
                adjustment_journal_entry_id INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                journal_entry_id            INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                is_reversed                 BOOLEAN NOT NULL DEFAULT false,
                reversed_at                 TIMESTAMP(0),
                reversed_by                 INTEGER,
                reverse_reason              TEXT,
                issue_cost                  NUMERIC(14,2) DEFAULT 0,
                is_dispatch_soft_hold       BOOLEAN NOT NULL DEFAULT false,
                created_by                  INTEGER,
                created_at                  TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                updated_at                  TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                deleted_at                  TIMESTAMP(0),
                PRIMARY KEY (id, challan_date),
                CONSTRAINT sales_challans_code_unique UNIQUE (challan_code, challan_date)
            ) PARTITION BY RANGE (challan_date)
        SQL);

        $this->createPreYearPartition('sales_challans', 'pre2026', '2026');
        $this->createMonthlyPartitions('sales_challans', '2026');

        DB::statement(<<<'SQL'
            INSERT INTO sales_challans (
                id, challan_code, challan_date, sales_invoice_id, branch_id,
                transport_name, transport_phone, vehicle_number, driver_name,
                transport_cost, transport_adjustment,
                adjustment_journal_entry_id, journal_entry_id,
                is_reversed, reversed_at, reversed_by, reverse_reason,
                issue_cost, is_dispatch_soft_hold,
                created_by, created_at, updated_at, deleted_at
            )
            OVERRIDING SYSTEM VALUE
            SELECT
                id, challan_code, challan_date, sales_invoice_id, branch_id,
                transport_name, transport_phone, vehicle_number, driver_name,
                transport_cost, transport_adjustment,
                adjustment_journal_entry_id, journal_entry_id,
                is_reversed, reversed_at, reversed_by, reverse_reason,
                issue_cost, is_dispatch_soft_hold,
                created_by, created_at, updated_at, deleted_at
            FROM sales_challans_unpartitioned
            ORDER BY challan_date, id
        SQL);

        DB::statement('SET CONSTRAINTS ALL IMMEDIATE');

        $this->fixSequence('sales_challans');

        // Recreate indexes
        DB::statement('CREATE INDEX idx_sc_invoice ON sales_challans (sales_invoice_id)');
        DB::statement('CREATE INDEX idx_sc_journal ON sales_challans (journal_entry_id)');
        DB::statement('CREATE INDEX idx_sc_adj_journal ON sales_challans (adjustment_journal_entry_id)');
        DB::statement(<<<'SQL'
            CREATE INDEX idx_sc_listing_covering ON sales_challans (branch_id, challan_date DESC, id DESC)
                INCLUDE (sales_invoice_id, challan_code, is_reversed, issue_cost, transport_cost)
        SQL);
        DB::statement(<<<'SQL'
            CREATE INDEX idx_sc_challan_date_brin
                ON sales_challans USING BRIN (challan_date)
                WITH (pages_per_range = 32)
        SQL);

        // Recreate updated_at trigger
        DB::statement(<<<'SQL'
            CREATE TRIGGER trg_sales_challans_updated_at
                BEFORE UPDATE ON sales_challans
                FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()
        SQL);

        // Recreate LISTEN/NOTIFY trigger (function rcerp_notify_sales_challan exists)
        DB::statement(<<<'SQL'
            CREATE TRIGGER trg_notify_sales_challans
                AFTER INSERT OR UPDATE ON sales_challans
                FOR EACH ROW EXECUTE FUNCTION rcerp_notify_sales_challan()
        SQL);

        // Recreate trigger-based FK: sales_challans.sales_invoice_id → sales_invoices(id)
        // (sales_invoices is already partitioned; preserve this trigger.)
        DB::statement(<<<'SQL'
            CREATE CONSTRAINT TRIGGER trg_fk_sc_si
                AFTER INSERT OR UPDATE ON sales_challans
                FROM sales_invoices
                DEFERRABLE INITIALLY IMMEDIATE
                FOR EACH ROW EXECUTE FUNCTION fn_fk_si_check('sales_invoice_id')
        SQL);

        $this->enableSingleBranchRls('sales_challans');

        DB::statement('DROP TABLE sales_challans_unpartitioned');
        $this->registerPartman('sales_challans', 'challan_date', '2027-01-01');
        DB::statement('ANALYZE sales_challans');
    }

    // ═══════════════════════════════════════════════════════════════
    //  4. warehouse_transfers  (children: warehouse_transfer_items,
    //                                     branch_demands)
    // ═══════════════════════════════════════════════════════════════

    private function partitionWarehouseTransfers(): void
    {
        if ($this->isAlreadyPartitioned('warehouse_transfers')) {
            return;
        }

        // ── Convert inbound FKs to trigger-based ──
        // 1. warehouse_transfer_items.warehouse_transfer_id → warehouse_transfers(id) ON DELETE CASCADE (auto-named)
        $this->dropAllFksToParent('warehouse_transfer_items', 'warehouse_transfers');
        $this->createTriggerFkCheck(
            'warehouse_transfer_items', 'warehouse_transfer_id', 'warehouse_transfers',
            'trg_fk_wti_wt_check', 'trg_wti_wt_fk_check'
        );
        $this->createTriggerFkCascadeDelete(
            'warehouse_transfer_items', 'warehouse_transfer_id', 'warehouse_transfers',
            'trg_fk_wt_cascade_wti', 'trg_wt_cascade_wti'
        );

        // 2. branch_demands.warehouse_transfer_id → warehouse_transfers(id) ON DELETE SET NULL (auto-named)
        $this->dropAllFksToParent('branch_demands', 'warehouse_transfers');
        $this->createTriggerFkCheck(
            'branch_demands', 'warehouse_transfer_id', 'warehouse_transfers',
            'trg_fk_bd_wt_check', 'trg_bd_wt_fk_check'
        );
        $this->createTriggerFkSetNull(
            'branch_demands', 'warehouse_transfer_id', 'warehouse_transfers',
            'trg_fk_wt_setnull_bd', 'trg_wt_setnull_bd'
        );

        // ── Partition warehouse_transfers ──
        $this->dropIndexesExceptPK('warehouse_transfers');
        $this->dropRlsPolicies('warehouse_transfers');

        DB::statement('ALTER TABLE warehouse_transfers RENAME TO warehouse_transfers_unpartitioned');

        DB::statement(<<<'SQL'
            CREATE TABLE warehouse_transfers (
                id                       INTEGER GENERATED BY DEFAULT AS IDENTITY,
                transfer_code            VARCHAR(30) NOT NULL,
                transfer_date            DATE NOT NULL,
                from_warehouse_id        INTEGER NOT NULL REFERENCES warehouses(id) DEFERRABLE INITIALLY DEFERRED,
                to_warehouse_id          INTEGER NOT NULL REFERENCES warehouses(id) DEFERRABLE INITIALLY DEFERRED,
                from_branch_id           INTEGER NOT NULL REFERENCES branches(id) DEFERRABLE INITIALLY DEFERRED,
                to_branch_id             INTEGER NOT NULL REFERENCES branches(id) DEFERRABLE INITIALLY DEFERRED,
                status                   VARCHAR(20) NOT NULL DEFAULT 'draft'
                    CHECK (status IN ('draft','confirmed','cancelled')),
                journal_entry_id         INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                journal_entry_id_debtor  INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                is_interbranch           BOOLEAN NOT NULL DEFAULT false,
                branch_demand_id         INTEGER REFERENCES branch_demands(id) ON DELETE SET NULL,
                is_reversed              BOOLEAN NOT NULL DEFAULT false,
                reversed_at              TIMESTAMP(0),
                reversed_by              INTEGER,
                reverse_reason           TEXT,
                notes                    TEXT,
                created_by               INTEGER,
                created_at               TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                updated_at               TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                deleted_at               TIMESTAMP(0),
                PRIMARY KEY (id, transfer_date),
                CONSTRAINT warehouse_transfers_code_unique UNIQUE (transfer_code, transfer_date)
            ) PARTITION BY RANGE (transfer_date)
        SQL);

        $this->createPreYearPartition('warehouse_transfers', 'pre2026', '2026');
        $this->createMonthlyPartitions('warehouse_transfers', '2026');

        DB::statement(<<<'SQL'
            INSERT INTO warehouse_transfers (
                id, transfer_code, transfer_date,
                from_warehouse_id, to_warehouse_id, from_branch_id, to_branch_id,
                status, journal_entry_id, journal_entry_id_debtor,
                is_interbranch, branch_demand_id,
                is_reversed, reversed_at, reversed_by, reverse_reason,
                notes, created_by, created_at, updated_at, deleted_at
            )
            OVERRIDING SYSTEM VALUE
            SELECT
                id, transfer_code, transfer_date,
                from_warehouse_id, to_warehouse_id, from_branch_id, to_branch_id,
                status, journal_entry_id, journal_entry_id_debtor,
                is_interbranch, branch_demand_id,
                is_reversed, reversed_at, reversed_by, reverse_reason,
                notes, created_by, created_at, updated_at, deleted_at
            FROM warehouse_transfers_unpartitioned
            ORDER BY transfer_date, id
        SQL);

        DB::statement('SET CONSTRAINTS ALL IMMEDIATE');

        $this->fixSequence('warehouse_transfers');

        // Recreate indexes
        DB::statement('CREATE INDEX idx_wt_journal_from ON warehouse_transfers (journal_entry_id)');
        DB::statement('CREATE INDEX idx_wt_journal_to ON warehouse_transfers (journal_entry_id_debtor)');
        DB::statement('CREATE INDEX idx_wt_branch_demand_id ON warehouse_transfers (branch_demand_id)');
        DB::statement(<<<'SQL'
            CREATE INDEX idx_wt_transfer_date_brin
                ON warehouse_transfers USING BRIN (transfer_date)
                WITH (pages_per_range = 32)
        SQL);

        // Recreate updated_at trigger
        DB::statement(<<<'SQL'
            CREATE TRIGGER trg_warehouse_transfers_updated_at
                BEFORE UPDATE ON warehouse_transfers
                FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()
        SQL);

        // Recreate enforce_same_branch_transfer trigger (function exists)
        DB::statement(<<<'SQL'
            CREATE TRIGGER trg_enforce_same_branch_transfer
                BEFORE INSERT OR UPDATE OF from_branch_id, to_branch_id ON warehouse_transfers
                FOR EACH ROW EXECUTE FUNCTION enforce_same_branch_transfer()
        SQL);

        // Dual-branch RLS (from_branch_id OR to_branch_id)
        $this->enableDualBranchRls('warehouse_transfers');

        DB::statement('DROP TABLE warehouse_transfers_unpartitioned');
        $this->registerPartman('warehouse_transfers', 'transfer_date', '2027-01-01');
        DB::statement('ANALYZE warehouse_transfers');
    }

    // ═══════════════════════════════════════════════════════════════
    //  5. stock_adjustments  (children: stock_adjustment_items,
    //                                     stock_adjustment_audit_log)
    // ═══════════════════════════════════════════════════════════════

    private function partitionStockAdjustments(): void
    {
        if ($this->isAlreadyPartitioned('stock_adjustments')) {
            return;
        }

        // ── Convert inbound FKs to trigger-based ──
        // 1. stock_adjustment_items.stock_adjustment_id → stock_adjustments(id) ON DELETE CASCADE (auto-named)
        $this->dropAllFksToParent('stock_adjustment_items', 'stock_adjustments');
        $this->createTriggerFkCheck(
            'stock_adjustment_items', 'stock_adjustment_id', 'stock_adjustments',
            'trg_fk_sai_sa_check', 'trg_sai_sa_fk_check'
        );
        $this->createTriggerFkCascadeDelete(
            'stock_adjustment_items', 'stock_adjustment_id', 'stock_adjustments',
            'trg_fk_sa_cascade_sai', 'trg_sa_cascade_sai'
        );

        // 2. stock_adjustment_audit_log.stock_adjustment_id → stock_adjustments(id) ON DELETE CASCADE (auto-named)
        //    Note: stock_adjustment_audit_log is itself PARTITION BY RANGE (created_at) (Phase 1).
        //    The trigger is created on the partitioned parent and propagates to all partitions.
        $this->dropAllFksToParent('stock_adjustment_audit_log', 'stock_adjustments');
        $this->createTriggerFkCheck(
            'stock_adjustment_audit_log', 'stock_adjustment_id', 'stock_adjustments',
            'trg_fk_saal_sa_check', 'trg_saal_sa_fk_check'
        );
        $this->createTriggerFkCascadeDelete(
            'stock_adjustment_audit_log', 'stock_adjustment_id', 'stock_adjustments',
            'trg_fk_sa_cascade_saal', 'trg_sa_cascade_saal'
        );

        // ── Partition stock_adjustments ──
        $this->dropIndexesExceptPK('stock_adjustments');
        $this->dropRlsPolicies('stock_adjustments');

        DB::statement('ALTER TABLE stock_adjustments RENAME TO stock_adjustments_unpartitioned');

        DB::statement(<<<'SQL'
            CREATE TABLE stock_adjustments (
                id                    INTEGER GENERATED BY DEFAULT AS IDENTITY,
                adjustment_code       VARCHAR(30) NOT NULL,
                adjustment_date       DATE NOT NULL,
                warehouse_id          INTEGER NOT NULL REFERENCES warehouses(id) DEFERRABLE INITIALLY DEFERRED,
                branch_id             INTEGER NOT NULL REFERENCES branches(id) DEFERRABLE INITIALLY DEFERRED,
                adjustment_type       VARCHAR(20) NOT NULL CHECK (adjustment_type IN ('increase','decrease')),
                adjustment_category   VARCHAR(40) NOT NULL DEFAULT 'other'
                    CONSTRAINT sa_category_check CHECK (adjustment_category IN (
                        'opening_balance','data_migration','uom_correction',
                        'post_conversion_fix','legacy_cleanup','reconciliation_variance','other'
                    )),
                total_amount          NUMERIC(14,2) NOT NULL DEFAULT 0,
                reason                TEXT,
                status                VARCHAR(20) NOT NULL DEFAULT 'draft'
                    CONSTRAINT stock_adjustments_status_check
                    CHECK (status IN ('draft','submitted','approved','confirmed','cancelled','rejected')),
                journal_entry_id      INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                is_reversed           BOOLEAN NOT NULL DEFAULT false,
                reversed_at           TIMESTAMP(0),
                reversed_by           INTEGER,
                reverse_reason        TEXT,
                cancel_reason         TEXT,
                submitted_by          INTEGER,
                submitted_at          TIMESTAMP(0),
                approved_by           INTEGER,
                approved_at           TIMESTAMP(0),
                approval_comments     TEXT,
                confirmed_by          INTEGER,
                confirmed_at          TIMESTAMP(0),
                confirm_reason        TEXT,
                created_by            INTEGER,
                created_at            TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                updated_at            TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                deleted_at            TIMESTAMP(0),
                PRIMARY KEY (id, adjustment_date),
                CONSTRAINT stock_adjustments_code_unique UNIQUE (adjustment_code, adjustment_date)
            ) PARTITION BY RANGE (adjustment_date)
        SQL);

        $this->createPreYearPartition('stock_adjustments', 'pre2026', '2026');
        $this->createMonthlyPartitions('stock_adjustments', '2026');

        DB::statement(<<<'SQL'
            INSERT INTO stock_adjustments (
                id, adjustment_code, adjustment_date, warehouse_id, branch_id,
                adjustment_type, adjustment_category, total_amount, reason, status,
                journal_entry_id, is_reversed, reversed_at, reversed_by, reverse_reason,
                cancel_reason, submitted_by, submitted_at,
                approved_by, approved_at, approval_comments,
                confirmed_by, confirmed_at, confirm_reason,
                created_by, created_at, updated_at, deleted_at
            )
            OVERRIDING SYSTEM VALUE
            SELECT
                id, adjustment_code, adjustment_date, warehouse_id, branch_id,
                adjustment_type, adjustment_category, total_amount, reason, status,
                journal_entry_id, is_reversed, reversed_at, reversed_by, reverse_reason,
                cancel_reason, submitted_by, submitted_at,
                approved_by, approved_at, approval_comments,
                confirmed_by, confirmed_at, confirm_reason,
                created_by, created_at, updated_at, deleted_at
            FROM stock_adjustments_unpartitioned
            ORDER BY adjustment_date, id
        SQL);

        DB::statement('SET CONSTRAINTS ALL IMMEDIATE');

        $this->fixSequence('stock_adjustments');

        // Recreate indexes
        DB::statement('CREATE INDEX idx_sa_warehouse ON stock_adjustments (warehouse_id)');
        DB::statement('CREATE INDEX idx_sa_journal ON stock_adjustments (journal_entry_id)');
        DB::statement('CREATE INDEX idx_sa_category ON stock_adjustments (adjustment_category)');
        DB::statement('CREATE INDEX idx_sa_submitted ON stock_adjustments (branch_id, submitted_at) WHERE status = \'submitted\'');
        DB::statement('CREATE INDEX idx_sa_perf_approver ON stock_adjustments (approved_by, approved_at) WHERE is_reversed = false AND deleted_at IS NULL');
        DB::statement(<<<'SQL'
            CREATE INDEX idx_sa_adjustment_date_brin
                ON stock_adjustments USING BRIN (adjustment_date)
                WITH (pages_per_range = 32)
        SQL);

        // Recreate updated_at trigger
        DB::statement(<<<'SQL'
            CREATE TRIGGER trg_stock_adjustments_updated_at
                BEFORE UPDATE ON stock_adjustments
                FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()
        SQL);

        $this->enableSingleBranchRls('stock_adjustments');

        DB::statement('DROP TABLE stock_adjustments_unpartitioned');
        $this->registerPartman('stock_adjustments', 'adjustment_date', '2027-01-01');
        DB::statement('ANALYZE stock_adjustments');
    }

    // ═══════════════════════════════════════════════════════════════
    //  6. stock_take_sessions  (children: stock_take_warehouses,
    //                                     stock_take_items,
    //                                     stock_take_audit_log)
    // ═══════════════════════════════════════════════════════════════

    private function partitionStockTakeSessions(): void
    {
        if ($this->isAlreadyPartitioned('stock_take_sessions')) {
            return;
        }

        // ── Convert inbound FKs to trigger-based ──
        // 1. stock_take_warehouses.stock_take_session_id → stock_take_sessions(id) ON DELETE CASCADE (auto-named)
        $this->dropAllFksToParent('stock_take_warehouses', 'stock_take_sessions');
        $this->createTriggerFkCheck(
            'stock_take_warehouses', 'stock_take_session_id', 'stock_take_sessions',
            'trg_fk_stw_sts_check', 'trg_stw_sts_fk_check'
        );
        $this->createTriggerFkCascadeDelete(
            'stock_take_warehouses', 'stock_take_session_id', 'stock_take_sessions',
            'trg_fk_sts_cascade_stw', 'trg_sts_cascade_stw'
        );

        // 2. stock_take_items.stock_take_session_id → stock_take_sessions(id) ON DELETE CASCADE (auto-named)
        $this->dropAllFksToParent('stock_take_items', 'stock_take_sessions');
        $this->createTriggerFkCheck(
            'stock_take_items', 'stock_take_session_id', 'stock_take_sessions',
            'trg_fk_sti_sts_check', 'trg_sti_sts_fk_check'
        );
        $this->createTriggerFkCascadeDelete(
            'stock_take_items', 'stock_take_session_id', 'stock_take_sessions',
            'trg_fk_sts_cascade_sti', 'trg_sts_cascade_sti'
        );

        // 3. stock_take_audit_log.stock_take_session_id → stock_take_sessions(id) ON DELETE CASCADE (auto-named)
        //    Note: stock_take_audit_log is itself PARTITION BY RANGE (created_at) (Phase 1).
        $this->dropAllFksToParent('stock_take_audit_log', 'stock_take_sessions');
        $this->createTriggerFkCheck(
            'stock_take_audit_log', 'stock_take_session_id', 'stock_take_sessions',
            'trg_fk_stal_sts_check', 'trg_stal_sts_fk_check'
        );
        $this->createTriggerFkCascadeDelete(
            'stock_take_audit_log', 'stock_take_session_id', 'stock_take_sessions',
            'trg_fk_sts_cascade_stal', 'trg_sts_cascade_stal'
        );

        // ── Partition stock_take_sessions ──
        $this->dropIndexesExceptPK('stock_take_sessions');
        $this->dropRlsPolicies('stock_take_sessions');

        DB::statement('ALTER TABLE stock_take_sessions RENAME TO stock_take_sessions_unpartitioned');

        DB::statement(<<<'SQL'
            CREATE TABLE stock_take_sessions (
                id                    INTEGER GENERATED BY DEFAULT AS IDENTITY,
                session_code          VARCHAR(30) NOT NULL,
                session_date          DATE NOT NULL,
                branch_id             INTEGER NOT NULL REFERENCES branches(id) DEFERRABLE INITIALLY DEFERRED,
                status                VARCHAR(20) NOT NULL DEFAULT 'draft'
                    CONSTRAINT stock_take_sessions_status_check
                    CHECK (status IN ('draft','counting','submitted','approved','posted','cancelled','reversed')),
                journal_entry_id      INTEGER REFERENCES journal_entries(id) DEFERRABLE INITIALLY DEFERRED,
                is_reversed           BOOLEAN NOT NULL DEFAULT false,
                reversed_at           TIMESTAMP(0),
                reversed_by           INTEGER,
                reverse_reason        TEXT,
                frozen_at             TIMESTAMP(0),
                freeze_outbound       BOOLEAN NOT NULL DEFAULT false,
                count_snapshot        JSONB,
                submitted_by          INTEGER,
                submitted_at          TIMESTAMP(0),
                approved_by           INTEGER,
                approved_at           TIMESTAMP(0),
                approval_comments     TEXT,
                count_scope           VARCHAR(20) NOT NULL DEFAULT 'full'
                    CONSTRAINT stock_take_sessions_count_scope_check
                    CHECK (count_scope IN ('full','category','abc','group','ad_hoc','negative_only','zero_only')),
                count_scope_payload   JSONB,
                re_open_count         INTEGER NOT NULL DEFAULT 0,
                last_reopened_at      TIMESTAMP(0),
                last_reopened_by      INTEGER REFERENCES users(id) ON DELETE SET NULL,
                reversal_of_entry_id  INTEGER REFERENCES journal_entries(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
                notes                 TEXT,
                created_by            INTEGER,
                created_at            TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                updated_at            TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                deleted_at            TIMESTAMP(0),
                PRIMARY KEY (id, session_date),
                CONSTRAINT stock_take_session_code_unique UNIQUE (session_code, session_date)
            ) PARTITION BY RANGE (session_date)
        SQL);

        $this->createPreYearPartition('stock_take_sessions', 'pre2026', '2026');
        $this->createMonthlyPartitions('stock_take_sessions', '2026');

        DB::statement(<<<'SQL'
            INSERT INTO stock_take_sessions (
                id, session_code, session_date, branch_id, status,
                journal_entry_id, is_reversed, reversed_at, reversed_by, reverse_reason,
                frozen_at, freeze_outbound, count_snapshot,
                submitted_by, submitted_at, approved_by, approved_at, approval_comments,
                count_scope, count_scope_payload,
                re_open_count, last_reopened_at, last_reopened_by, reversal_of_entry_id,
                notes, created_by, created_at, updated_at, deleted_at
            )
            OVERRIDING SYSTEM VALUE
            SELECT
                id, session_code, session_date, branch_id, status,
                journal_entry_id, is_reversed, reversed_at, reversed_by, reverse_reason,
                frozen_at, freeze_outbound, count_snapshot,
                submitted_by, submitted_at, approved_by, approved_at, approval_comments,
                count_scope, count_scope_payload,
                re_open_count, last_reopened_at, last_reopened_by, reversal_of_entry_id,
                notes, created_by, created_at, updated_at, deleted_at
            FROM stock_take_sessions_unpartitioned
            ORDER BY session_date, id
        SQL);

        DB::statement('SET CONSTRAINTS ALL IMMEDIATE');

        $this->fixSequence('stock_take_sessions');

        // Recreate indexes
        DB::statement('CREATE INDEX idx_sts_branch ON stock_take_sessions (branch_id)');
        DB::statement('CREATE INDEX idx_sts_is_reversed ON stock_take_sessions (is_reversed) WHERE is_reversed = true');
        DB::statement('CREATE INDEX idx_sts_reversed ON stock_take_sessions (branch_id, reversed_at) WHERE status = \'reversed\'');
        DB::statement('CREATE INDEX idx_sts_freeze_outbound ON stock_take_sessions (branch_id) WHERE freeze_outbound = true');
        DB::statement('CREATE INDEX idx_sts_submitted ON stock_take_sessions (branch_id, submitted_at) WHERE status = \'submitted\'');
        DB::statement(<<<'SQL'
            CREATE INDEX idx_sts_session_date_brin
                ON stock_take_sessions USING BRIN (session_date)
                WITH (pages_per_range = 32)
        SQL);

        // Recreate updated_at trigger
        DB::statement(<<<'SQL'
            CREATE TRIGGER trg_stock_take_sessions_updated_at
                BEFORE UPDATE ON stock_take_sessions
                FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()
        SQL);

        $this->enableSingleBranchRls('stock_take_sessions');

        DB::statement('DROP TABLE stock_take_sessions_unpartitioned');
        $this->registerPartman('stock_take_sessions', 'session_date', '2027-01-01');
        DB::statement('ANALYZE stock_take_sessions');
    }

    // ═══════════════════════════════════════════════════════════════
    //  down() — rollback is manual (trigger-based FK reversal is complex)
    // ═══════════════════════════════════════════════════════════════

    public function down(): void
    {
        // Rollback of a partitioned-+-trigger-based-FK migration is non-trivial:
        //   1. Re-create the declarative FK on each child (requires data integrity check).
        //   2. Detach all partitions, copy data back to a flat table, drop partitioned parent.
        //   3. Rename flat table back, re-create all indexes/triggers/RLS policies.
        //
        // Per the Phase 4 migration's precedent (which leaves Group B rollbacks as
        // manual operations), we document the rollback procedure but do not
        // implement an automated one. Restoring from a pre-migration DB snapshot
        // is the recommended rollback path.
        Log::warning(
            'Phase 5 rollback: automated down() is intentionally a no-op. '
            . 'Restoring from a pre-migration DB snapshot is the recommended rollback path. '
            . 'Manual rollback requires: (1) re-creating declarative FKs on 11 child tables, '
            . '(2) detaching all partitions, (3) copying data back to flat tables, '
            . '(4) re-creating indexes/triggers/RLS policies per the original schema.'
        );
    }
};
