<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

/**
 * Phase 10.1 — Phase 6.4: Partition journal_lines by denormalized entry_date.
 *
 * CRITICAL: must use IDENTICAL partition boundaries to journal_entries
 * (Phase 6.3 / migration 000002). This is REQUIRED for partition-wise
 * joins — PostgreSQL can only do a partition-wise join between two
 * partitioned tables if their partition boundaries match exactly.
 *
 * Pre-requisites:
 *   - Phase 6.2 (migration 000001) added entry_date to journal_lines
 *     and backfilled it from journal_entries.entry_date.
 *   - Phase 6.3 (migration 000002) partitioned journal_entries by entry_date.
 *     The declarative FK journal_lines.journal_entry_id → journal_entries(id)
 *     was DROPPED in that migration (PostgreSQL rejects partitioning a
 *     parent that has declarative FK references from a non-partitioned
 *     child). Phase 6.6 (migration 000004) will re-create it as a
 *     trigger-based FK AFTER this migration runs.
 *
 * Schema source: laravel/database/sql/02_accounting.sql lines 55-71 +
 *   migration 2026_08_10_000002_create_budgeting_and_cost_centers.php
 *     line 105-112 (adds dimension_value_id + idx_jl_dim_value) +
 *   migration 2026_08_12_000001_create_bank_reconciliation.php
 *     lines 165-172 (adds is_bank_reconciled, bank_reconciliation_id
 *     + idx_jl_reconciled_ledger).
 *
 * Triggers to preserve on journal_lines:
 *   - trg_jl_sync_entry_date  (BEFORE INSERT OR UPDATE OF journal_entry_id)
 *                              — created in Phase 6.2 / migration 000001.
 *   - trg_journal_balanced    (AFTER INSERT OR UPDATE OR DELETE)
 *                              — created in 02_accounting.sql lines 94-96.
 *   - trg_audit_journal_lines (AFTER INSERT OR UPDATE OR DELETE)
 *                              — created in 02_accounting.sql line 447.
 *
 * The trg_journal_balanced trigger JOINs journal_entries by id at runtime
 * — it transparently uses the new partitioned parent (migration 000002).
 *
 * DESIGN NOTES
 * ------------
 * - PK(id) → PK(id, entry_date) for partitioned parent (PostgreSQL requirement).
 * - GENERATED ALWAYS → GENERATED BY DEFAULT for OVERRIDING SYSTEM VALUE data copy.
 * - journal_lines has NO soft-delete column (deleted_at). Rows are append-only
 *   (reversals create new rows, never delete old ones).
 * - journal_lines has NO RLS (confirmed by reading
 *   2025_01_20_000007_add_rls_branch_isolation.php — journal_lines is
 *   NOT in the single-branch or dual-branch list). RLS is enforced on
 *   the parent (journal_entries) — when joined via journal_entry_id,
 *   the parent's RLS policy filters the visible rows.
 * - journal_lines.journal_entry_id does NOT have a declarative FK to
 *   journal_entries(id) — Phase 6.6 (migration 000004) adds a
 *   trigger-based FK instead. (PostgreSQL would require the FK column
 *   list to include the parent's partition key, i.e.,
 *   REFERENCES journal_entries(id, entry_date) — but that means
 *   journal_lines would need to know entry_date matches the parent,
 *   which is exactly what the sync trigger enforces. A trigger-based
 *   FK is simpler and equivalent in practice.)
 *
 * IDEMPOTENT: early-returns if journal_lines is already partitioned.
 *
 * ⚠️  Run during a maintenance window — locks the table during the data copy phase.
 */
return new class extends Migration
{
    private ?bool $hasPgPartman = null;

    // ═══════════════════════════════════════════════════════════════
    //  Helpers (copied verbatim from the Phase 5 migration pattern)
    // ═══════════════════════════════════════════════════════════════

    private function hasPgPartman(): bool
    {
        if ($this->hasPgPartman !== null) {
            return $this->hasPgPartman;
        }
        $row = DB::selectOne("
            SELECT EXISTS (
                SELECT 1 FROM pg_available_extensions WHERE name = 'pg_partman'
            ) AS installed
        ");
        $this->hasPgPartman = (bool) ($row->installed ?? false);
        if (! $this->hasPgPartman) {
            logger()->warning('pg_partman is not installed. Automatic partition maintenance is disabled.');
        }
        return $this->hasPgPartman;
    }

    private function isAlreadyPartitioned(string $tableName): bool
    {
        $row = DB::selectOne("
            SELECT 1
            FROM pg_partitioned_table pt
            JOIN pg_class c ON c.oid = pt.partrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relname = ? AND n.nspname = current_schema()
            LIMIT 1
        ", [$tableName]);
        return $row !== null;
    }

    private function relationExists(string $name): bool
    {
        $row = DB::selectOne("
            SELECT 1
            FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relname = ? AND n.nspname = current_schema()
            LIMIT 1
        ", [$name]);
        return $row !== null;
    }

    private function createMonthlyPartitions(string $parent, string $year): void
    {
        for ($m = 1; $m <= 12; $m++) {
            $from = sprintf('%s-%02d-01', $year, $m);
            $to   = $m < 12
                ? sprintf('%s-%02d-01', $year, $m + 1)
                : sprintf('%d-01-01', (int) $year + 1);
            $name = sprintf('%s_%s_%02d', $parent, $year, $m);

            if (! $this->relationExists($name)) {
                DB::statement(
                    "CREATE TABLE {$name} PARTITION OF {$parent}
                     FOR VALUES FROM ('{$from}') TO ('{$to}')"
                );
            }
        }

        $defaultName = "{$parent}_default";
        if (! $this->relationExists($defaultName)) {
            DB::statement(
                "CREATE TABLE {$defaultName} PARTITION OF {$parent} DEFAULT"
            );
        }
    }

    private function createMonthlyPartitionsRange(string $parent, string $year, int $fromMonth, int $toMonth): void
    {
        for ($m = $fromMonth; $m <= $toMonth; $m++) {
            $from = sprintf('%s-%02d-01', $year, $m);
            $to   = $m < 12
                ? sprintf('%s-%02d-01', $year, $m + 1)
                : sprintf('%d-01-01', (int) $year + 1);
            $name = sprintf('%s_%s_%02d', $parent, $year, $m);

            if (! $this->relationExists($name)) {
                DB::statement(
                    "CREATE TABLE {$name} PARTITION OF {$parent}
                     FOR VALUES FROM ('{$from}') TO ('{$to}')"
                );
            }
        }
    }

    private function createPreYearPartition(string $parent, string $preYear, string $startYear): void
    {
        $name = "{$parent}_{$preYear}";
        if (! $this->relationExists($name)) {
            DB::statement(
                "CREATE TABLE {$name} PARTITION OF {$parent}
                 FOR VALUES FROM ('2020-01-01') TO ('{$startYear}-01-01')"
            );
        }
    }

    private function registerPartman(string $parent, string $control, string $startPartition): void
    {
        if (! $this->hasPgPartman()) {
            return;
        }
        try {
            DB::statement(<<<SQL
                SELECT partman.create_parent(
                    p_parent_table    := 'public.{$parent}',
                    p_control         := '{$control}',
                    p_type            := 'range',
                    p_interval        := '1 month',
                    p_premake         := 6,
                    p_start_partition := '{$startPartition}'
                )
            SQL);
        } catch (\Throwable $e) {
            // Already registered with pg_partman — safe to ignore.
        }
    }

    private function fixSequence(string $table): void
    {
        DB::statement(<<<SQL
            SELECT setval(
                pg_get_serial_sequence('{$table}', 'id'),
                GREATEST(COALESCE((SELECT MAX(id) FROM {$table}), 0), 1)
            )
        SQL);
    }

    private function dropIndexesExceptPK(string $tableName): void
    {
        // ── First, drop UNIQUE / EXCLUDE constraints ──
        // These constraints own a backing index that CANNOT be dropped directly
        // via DROP INDEX — PostgreSQL raises SQLSTATE 2BP01 ("cannot drop index
        // ... because constraint ... requires it"). We must DROP CONSTRAINT
        // instead; the backing index is removed automatically. PK constraints
        // (contype='p') are preserved — the old table (renamed later) carries
        // its PK until it is dropped wholesale at the end of partitioning.
        $constraints = DB::select("
            SELECT c.conname
            FROM pg_constraint c
            JOIN pg_class cl ON cl.oid = c.conrelid
            JOIN pg_namespace n ON n.oid = cl.relnamespace
            WHERE cl.relname = ?
              AND n.nspname = current_schema()
              AND c.contype IN ('u', 'x')
        ", [$tableName]);

        foreach ($constraints as $c) {
            DB::statement("ALTER TABLE {$tableName} DROP CONSTRAINT IF EXISTS {$c->conname}");
        }

        // ── Then drop any remaining standalone indexes (excluding PK backing index) ──
        $indexes = DB::select("
            SELECT indexname
            FROM pg_indexes
            WHERE tablename = ? AND indexname NOT LIKE '%_pkey'
        ", [$tableName]);

        foreach ($indexes as $idx) {
            DB::statement("DROP INDEX IF EXISTS {$idx->indexname}");
        }
    }

    /**
     * Drop ALL declarative FK constraints that reference $parentTable.
     * Used BEFORE renaming/partitioning a parent — PostgreSQL blocks
     * DROP TABLE on a table that has inbound declarative FKs (RESTRICT
     * is the default). The trigger-based replacements are created in
     * createTriggerFkToJournalLines() below (called after the new
     * partitioned parent is in place).
     *
     * Returns the list of (child_table, constraint_name, fk_column, deltype)
     * that were dropped.
     *
     * @return list<array{child: string, conname: string, col: string, deltype: string}>
     */
    private function dropAllDeclarativeFksToParent(string $parentTable): array
    {
        $fks = DB::select(<<<SQL
            SELECT
                child.relname  AS child_table,
                c.conname      AS conname,
                a.attname      AS col,
                c.confdeltype  AS deltype
            FROM pg_constraint c
            JOIN pg_class child       ON child.oid  = c.conrelid
            JOIN pg_namespace childns ON childns.oid = child.relnamespace
            JOIN pg_class parent      ON parent.oid = c.confrelid
            JOIN pg_namespace parentns ON parentns.oid = parent.relnamespace
            JOIN pg_attribute a ON a.attrelid = child.oid AND a.attnum = ANY(c.conkey)
            WHERE parent.relname = ?
              AND parentns.nspname = 'public'
              AND childns.nspname = 'public'
              AND c.contype = 'f'
            ORDER BY child.relname, a.attname
        SQL, [$parentTable]);

        $dropped = [];
        foreach ($fks as $fk) {
            DB::statement(
                "ALTER TABLE {$fk->child_table} DROP CONSTRAINT IF EXISTS {$fk->conname}"
            );
            $dropped[] = [
                'child'    => $fk->child_table,
                'conname'  => $fk->conname,
                'col'      => $fk->col,
                'deltype'  => $fk->deltype,
            ];
            Log::info("Phase 6.4: Dropped declarative FK {$fk->conname} on {$fk->child_table}.{$fk->col} → {$parentTable}(id) [deltype={$fk->deltype}] — will be re-created as trigger-based below.");
        }
        return $dropped;
    }

    /**
     * Create a trigger-based FK check function + trigger for a child→journal_lines reference.
     * Replaces the declarative FK that was dropped in dropAllDeclarativeFksToParent().
     */
    private function createTriggerFkToJournalLines(
        string $childTable,
        string $fkColumn,
        string $onDelete // 'CASCADE' | 'SET NULL' | 'NO_ACTION' | 'RESTRICT'
    ): void {
        $funcName = $this->sanitizeIdentifier("fn_trg_{$childTable}_{$fkColumn}_jl_fk");
        $triggerName = $this->sanitizeIdentifier("trg_{$childTable}_{$fkColumn}_jl_fk");

        DB::statement(<<<SQL
            CREATE OR REPLACE FUNCTION {$funcName}()
            RETURNS TRIGGER AS \$\$
            BEGIN
                IF NEW.{$fkColumn} IS NOT NULL THEN
                    IF NOT EXISTS (
                        SELECT 1 FROM journal_lines
                        WHERE id = NEW.{$fkColumn}
                    ) THEN
                        RAISE EXCEPTION 'FK violation: journal_lines(id=%) not found for {$childTable}.{$fkColumn}',
                            NEW.{$fkColumn};
                    END IF;
                END IF;
                RETURN NEW;
            END;
            \$\$ LANGUAGE plpgsql
        SQL);

        DB::statement("DROP TRIGGER IF EXISTS {$triggerName} ON {$childTable}");
        DB::statement(<<<SQL
            CREATE TRIGGER {$triggerName}
                BEFORE INSERT OR UPDATE OF {$fkColumn} ON {$childTable}
                FOR EACH ROW EXECUTE FUNCTION {$funcName}()
        SQL);

        // Handle ON DELETE behavior — create the corresponding AFTER DELETE
        // trigger on journal_lines (the parent).
        $cascadeFunc = $this->sanitizeIdentifier("fn_trg_{$childTable}_{$fkColumn}_jl_cascade");
        $cascadeTrigger = $this->sanitizeIdentifier("trg_jl_del_cascade_{$childTable}_{$fkColumn}");

        if ($onDelete === 'CASCADE') {
            DB::statement("DROP TRIGGER IF EXISTS {$cascadeTrigger} ON journal_lines");
            DB::statement(<<<SQL
                CREATE OR REPLACE FUNCTION {$cascadeFunc}()
                RETURNS TRIGGER AS \$\$
                BEGIN
                    DELETE FROM {$childTable} WHERE {$fkColumn} = OLD.id;
                    RETURN OLD;
                END;
                \$\$ LANGUAGE plpgsql
            SQL);
            DB::statement(<<<SQL
                CREATE TRIGGER {$cascadeTrigger}
                    AFTER DELETE ON journal_lines
                    FOR EACH ROW EXECUTE FUNCTION {$cascadeFunc}()
            SQL);
            Log::info("Phase 6.4: Created CASCADE trigger on journal_lines for {$childTable}.{$fkColumn}");
        } elseif ($onDelete === 'SET NULL') {
            DB::statement("DROP TRIGGER IF EXISTS {$cascadeTrigger} ON journal_lines");
            DB::statement(<<<SQL
                CREATE OR REPLACE FUNCTION {$cascadeFunc}()
                RETURNS TRIGGER AS \$\$
                BEGIN
                    UPDATE {$childTable} SET {$fkColumn} = NULL WHERE {$fkColumn} = OLD.id;
                    RETURN OLD;
                END;
                \$\$ LANGUAGE plpgsql
            SQL);
            DB::statement(<<<SQL
                CREATE TRIGGER {$cascadeTrigger}
                    AFTER DELETE ON journal_lines
                    FOR EACH ROW EXECUTE FUNCTION {$cascadeFunc}()
            SQL);
            Log::info("Phase 6.4: Created SET NULL trigger on journal_lines for {$childTable}.{$fkColumn}");
        } else {
            // NO_ACTION / RESTRICT — prevent parent delete if child rows exist.
            DB::statement("DROP TRIGGER IF EXISTS {$cascadeTrigger} ON journal_lines");
            DB::statement(<<<SQL
                CREATE OR REPLACE FUNCTION {$cascadeFunc}()
                RETURNS TRIGGER AS \$\$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM {$childTable} WHERE {$fkColumn} = OLD.id
                    ) THEN
                        RAISE EXCEPTION 'Cannot delete journal_lines(id=%): referenced by {$childTable}.{$fkColumn}',
                            OLD.id;
                    END IF;
                    RETURN OLD;
                END;
                \$\$ LANGUAGE plpgsql
            SQL);
            DB::statement(<<<SQL
                CREATE CONSTRAINT TRIGGER {$cascadeTrigger}
                    AFTER DELETE ON journal_lines
                    DEFERRABLE INITIALLY IMMEDIATE
                    FOR EACH ROW EXECUTE FUNCTION {$cascadeFunc}()
            SQL);
            Log::info("Phase 6.4: Created RESTRICT trigger on journal_lines for {$childTable}.{$fkColumn}");
        }
    }

    /**
     * Sanitize a string for use as a PostgreSQL identifier.
     * Replaces non-alphanumeric characters with underscores.
     */
    private function sanitizeIdentifier(string $name): string
    {
        return preg_replace('/[^a-zA-Z0-9_]/', '_', $name);
    }

    // ═══════════════════════════════════════════════════════════════
    //  up()
    // ═══════════════════════════════════════════════════════════════

    public function up(): void
    {
        if ($this->hasPgPartman()) {
            DB::statement('CREATE EXTENSION IF NOT EXISTS pg_partman');
            DB::statement('CREATE SCHEMA IF NOT EXISTS partman');
        }

        $this->partitionJournalLines();
    }

    private function partitionJournalLines(): void
    {
        if ($this->isAlreadyPartitioned('journal_lines')) {
            return;
        }

        // ============================================================
        // 0. CRITICAL: Drop ALL declarative FKs that reference
        //    journal_lines BEFORE partitioning. PostgreSQL blocks
        //    DROP TABLE on a table that has inbound declarative FKs
        //    (RESTRICT is the default).
        //
        //    Known declarative FKs to journal_lines(id):
        //      - bank_reconciliation_items.journal_line_id  (CASCADE) [2026_08_12_000001:140-142]
        //      - stock_take_items.journal_line_id           (SET NULL) [2025_07_26_000004:51-53]
        //      - stock_take_items.revaluation_line_id       (SET NULL) [2025_08_02_000001:122]
        //
        //    We capture the (child, col, deltype) for each dropped FK
        //    so we can re-create them as trigger-based after the new
        //    partitioned parent is in place.
        // ============================================================
        $droppedFks = $this->dropAllDeclarativeFksToParent('journal_lines');

        // ============================================================
        // 0a. Drop the dependent view v_journal_entries_with_lines.
        //     The view reads FROM journal_entries JOIN journal_lines —
        //     it depends on journal_lines by OID. Migration 000002
        //     recreated this view after partitioning journal_entries;
        //     now that we're about to rename + drop journal_lines, we
        //     must drop the view again and recreate it after the new
        //     partitioned parent is in place.
        // ============================================================
        DB::statement('DROP VIEW IF EXISTS v_journal_entries_with_lines');

        // ============================================================
        // 0b. Drop 5 ADDITIONAL dependent views / materialized views
        //     that reference journal_lines by OID. These were recreated
        //     by migration 000002 (step 13a) after journal_entries was
        //     partitioned — but they ALL also JOIN journal_lines, so
        //     they now depend on journal_lines by OID and would block
        //     DROP TABLE journal_lines_unpartitioned with the SAME
        //     SQLSTATE 2BP01 dependency error:
        //       - mv_ledger_balances              (materialized view)
        //       - mv_journal_entry_summary        (materialized view)
        //       - budget_vs_actual                (view)
        //       - mv_consolidated_trial_balance   (materialized view)
        //       - v_unreconciled_bank_entries     (view)
        //     Each is recreated in step 11a after the new partitioned
        //     journal_lines is in place. After 000003 completes, BOTH
        //     journal_entries and journal_lines are partitioned by
        //     entry_date, enabling partition-wise joins (when
        //     enable_partitionwise_join=on, set by Phase 0.7).
        //     CASCADE handles any downstream dependents (none today
        //     per scope audit, but future-proofs the drop).
        // ============================================================
        DB::statement('DROP MATERIALIZED VIEW IF EXISTS mv_ledger_balances CASCADE');
        DB::statement('DROP MATERIALIZED VIEW IF EXISTS mv_journal_entry_summary CASCADE');
        DB::statement('DROP VIEW IF EXISTS budget_vs_actual CASCADE');
        DB::statement('DROP MATERIALIZED VIEW IF EXISTS mv_consolidated_trial_balance CASCADE');
        DB::statement('DROP VIEW IF EXISTS v_unreconciled_bank_entries CASCADE');

        // ============================================================
        // 1. Drop triggers ON journal_lines (the table being renamed).
        //    These follow the table through the rename but the renamed
        //    table is dropped at the end — we recreate them on the new
        //    partitioned parent.
        //
        //    Triggers to drop:
        //      - trg_jl_sync_entry_date  (created in migration 000001)
        //      - trg_journal_balanced    (created in 02_accounting.sql:94-96)
        //      - trg_audit_journal_lines (created in 02_accounting.sql:447)
        //
        //    The trigger FUNCTIONS (fn_jl_sync_entry_date,
        //    enforce_balanced_journal_entry, fn_financial_audit_trigger)
        //    are NOT dropped — they live in the global namespace and
        //    will be re-used when we re-create the triggers on the new
        //    parent. We DO re-create fn_jl_sync_entry_date and
        //    enforce_balanced_journal_entry below just to be safe
        //    (idempotent CREATE OR REPLACE).
        // ============================================================
        DB::statement('DROP TRIGGER IF EXISTS trg_jl_sync_entry_date ON journal_lines');
        DB::statement('DROP TRIGGER IF EXISTS trg_journal_balanced ON journal_lines');
        DB::statement('DROP TRIGGER IF EXISTS trg_audit_journal_lines ON journal_lines');

        // ============================================================
        // 2. Drop indexes except PK.
        //    journal_lines has NO RLS — confirmed by reading
        //    2025_01_20_000007_add_rls_branch_isolation.php (it's
        //    NOT in the single-branch or dual-branch list).
        // ============================================================
        $this->dropIndexesExceptPK('journal_lines');

        // ============================================================
        // 3. Rename the existing table to _unpartitioned.
        // ============================================================
        DB::statement('ALTER TABLE journal_lines RENAME TO journal_lines_unpartitioned');

        // ============================================================
        // 4. Create the new partitioned parent.
        //    Schema source: 02_accounting.sql lines 55-71 + Phase 9.x
        //    additions for dimension_value_id, is_bank_reconciled,
        //    bank_reconciliation_id (verified by grepping migrations for
        //    `ALTER TABLE journal_lines ADD COLUMN` — only the
        //    Schema::table('journal_lines', ...) calls in
        //    2026_08_10_000002 and 2026_08_12_000001).
        // ============================================================
        DB::statement(<<<'SQL'
            CREATE TABLE journal_lines (
                id                       INTEGER GENERATED BY DEFAULT AS IDENTITY,
                journal_entry_id         INTEGER NOT NULL,
                entry_date               DATE NOT NULL,
                ledger_id                INTEGER NOT NULL,
                debit                    NUMERIC(15,2) NOT NULL DEFAULT 0,
                credit                   NUMERIC(15,2) NOT NULL DEFAULT 0,
                entity_type              VARCHAR(30),
                entity_id                INTEGER,
                memo                     TEXT,
                dimension_value_id       INTEGER,
                is_bank_reconciled       BOOLEAN NOT NULL DEFAULT false,
                bank_reconciliation_id   INTEGER,
                created_at               TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (id, entry_date),
                CONSTRAINT jl_balanced_check CHECK (debit >= 0 AND credit >= 0),
                CONSTRAINT jl_not_both_zero_check CHECK (debit > 0 OR credit > 0)
            ) PARTITION BY RANGE (entry_date)
        SQL);

        // Re-add the FK to bank_reconciliations(id) (non-partitioned parent,
        // so this is fine — PostgreSQL allows FK from partitioned child).
        // ON DELETE SET NULL preserves the original behaviour from
        // migration 2026_08_12_000001 (nullOnDelete).
        // Make it DEFERRABLE INITIALLY DEFERRED to match the pattern of
        // other FKs in the system (see 2025_01_21_000005).
        DB::statement(<<<'SQL'
            ALTER TABLE journal_lines
                ADD CONSTRAINT fk_jl_bank_reconciliation
                FOREIGN KEY (bank_reconciliation_id)
                REFERENCES bank_reconciliations(id)
                ON DELETE SET NULL
                DEFERRABLE INITIALLY DEFERRED
        SQL);

        // Also re-add the FK to dimension_values(id) (non-partitioned parent).
        // ON DELETE SET NULL preserves the original behaviour from
        // migration 2026_08_10_000002 (nullOnDelete).
        DB::statement(<<<'SQL'
            ALTER TABLE journal_lines
                ADD CONSTRAINT fk_jl_dim_value
                FOREIGN KEY (dimension_value_id)
                REFERENCES dimension_values(id)
                ON DELETE SET NULL
                DEFERRABLE INITIALLY DEFERRED
        SQL);

        // ============================================================
        // 4. Create partitions with IDENTICAL boundaries to journal_entries.
        //    REQUIRED for partition-wise joins (plan §3.2 principle 8).
        // ============================================================
        $this->createPreYearPartition('journal_lines', 'pre2026', '2026');
        $this->createMonthlyPartitions('journal_lines', '2026');
        $this->createMonthlyPartitionsRange('journal_lines', '2027', 1, 6);

        // ============================================================
        // 5. Copy data from the unpartitioned table into the partitioned
        //    parent. OVERRIDING SYSTEM VALUE allows inserting explicit
        //    id values into the IDENTITY column.
        // ============================================================
        DB::statement(<<<'SQL'
            INSERT INTO journal_lines (
                id, journal_entry_id, entry_date, ledger_id,
                debit, credit, entity_type, entity_id, memo,
                dimension_value_id, is_bank_reconciled, bank_reconciliation_id,
                created_at
            )
            OVERRIDING SYSTEM VALUE
            SELECT
                id, journal_entry_id, entry_date, ledger_id,
                debit, credit, entity_type, entity_id, memo,
                dimension_value_id, is_bank_reconciled, bank_reconciliation_id,
                created_at
            FROM journal_lines_unpartitioned
            ORDER BY entry_date, id
        SQL);

        // Flush any deferred constraint triggers before dropping the old table.
        DB::statement('SET CONSTRAINTS ALL IMMEDIATE');

        // ============================================================
        // 6. Fix the identity sequence.
        // ============================================================
        $this->fixSequence('journal_lines');

        // ============================================================
        // 7. Recreate indexes (B-tree only — BRIN is added in Phase 6.5
        //    / migration 000004).
        //
        //    Index inventory (verified by grepping migrations + sql files):
        //      - idx_jl_journal_entry         (journal_entry_id)           [02_accounting.sql:68]
        //      - idx_jl_ledger                (ledger_id)                  [02_accounting.sql:69]
        //      - idx_jl_entity                (entity_type, entity_id)     [02_accounting.sql:70]
        //      - idx_jl_entry_covering        (journal_entry_id)
        //                                     INCLUDE (id, ledger_id, debit, credit,
        //                                              entity_type, entity_id, memo)
        //                                                                  [2025_01_20_000002:74-81]
        //      - idx_jl_ledger_date_covering  (ledger_id, journal_entry_id)
        //                                     INCLUDE (debit, credit)
        //                                                                  [2025_01_20_000002:86-93]
        //      - idx_jl_reconciled_ledger     (is_bank_reconciled, ledger_id)
        //                                                                  [2026_08_12_000001:171]
        //      - idx_jl_dim_value             (dimension_value_id)         [2026_08_10_000002:111]
        //
        //    NOTE: The temporary idx_jl_entry_date B-tree (created in
        //    migration 000001) was DROPPED above by dropIndexesExceptPK
        //    — wait, no, we renamed journal_lines → journal_lines_unpartitioned.
        //    The index followed the table. But it gets dropped when we
        //    DROP journal_lines_unpartitioned at the end. Phase 6.5
        //    (migration 000004) will create a BRIN replacement.
        // ============================================================
        DB::statement('CREATE INDEX IF NOT EXISTS idx_jl_journal_entry ON journal_lines (journal_entry_id)');
        DB::statement('CREATE INDEX IF NOT EXISTS idx_jl_ledger ON journal_lines (ledger_id)');
        DB::statement('CREATE INDEX IF NOT EXISTS idx_jl_entity ON journal_lines (entity_type, entity_id)');
        DB::statement(<<<'SQL'
            CREATE INDEX IF NOT EXISTS idx_jl_entry_covering
                ON journal_lines (journal_entry_id)
                INCLUDE (id, ledger_id, debit, credit, entity_type, entity_id, memo)
        SQL);
        DB::statement(<<<'SQL'
            CREATE INDEX IF NOT EXISTS idx_jl_ledger_date_covering
                ON journal_lines (ledger_id, journal_entry_id)
                INCLUDE (debit, credit)
        SQL);
        DB::statement(<<<'SQL'
            CREATE INDEX IF NOT EXISTS idx_jl_reconciled_ledger
                ON journal_lines (is_bank_reconciled, ledger_id)
        SQL);
        DB::statement('CREATE INDEX IF NOT EXISTS idx_jl_dim_value ON journal_lines (dimension_value_id)');

        // ============================================================
        // 8. Recreate trigger FUNCTIONS + triggers ON journal_lines (parent).
        //    Creating a trigger on the partitioned parent automatically
        //    applies it to all current AND future partitions (PostgreSQL
        //    13+ behavior).
        // ============================================================
        // 8a. fn_jl_sync_entry_date() — sync entry_date from journal_entries.
        //     Recreated here (idempotent CREATE OR REPLACE) in case it
        //     was somehow dropped.
        DB::statement(<<<'SQL'
            CREATE OR REPLACE FUNCTION fn_jl_sync_entry_date()
            RETURNS TRIGGER AS $$
            BEGIN
                NEW.entry_date := (
                    SELECT entry_date FROM journal_entries WHERE id = NEW.journal_entry_id
                );
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql
        SQL);
        DB::statement(<<<'SQL'
            CREATE TRIGGER trg_jl_sync_entry_date
                BEFORE INSERT OR UPDATE OF journal_entry_id ON journal_lines
                FOR EACH ROW EXECUTE FUNCTION fn_jl_sync_entry_date()
        SQL);

        // 8b. enforce_balanced_journal_entry() — Dr=Cr enforcement.
        //     Verbatim copy from 02_accounting.sql lines 74-92.
        //     Function body queries journal_lines WHERE journal_entry_id =
        //     COALESCE(NEW.journal_entry_id, OLD.journal_entry_id) — since
        //     the trigger is now ON the partitioned parent, the query
        //     transparently prunes to the correct partition(s).
        DB::statement(<<<'SQL'
            CREATE OR REPLACE FUNCTION enforce_balanced_journal_entry()
            RETURNS TRIGGER AS $$
            DECLARE
                total_debit numeric(15,2);
                total_credit numeric(15,2);
            BEGIN
                SELECT COALESCE(SUM(debit), 0), COALESCE(SUM(credit), 0)
                INTO total_debit, total_credit
                FROM journal_lines
                WHERE journal_entry_id = COALESCE(NEW.journal_entry_id, OLD.journal_entry_id);

                IF total_debit <> total_credit THEN
                    RAISE EXCEPTION 'Journal entry % is not balanced: debits (%) do not equal credits (%)',
                        COALESCE(NEW.journal_entry_id, OLD.journal_entry_id), total_debit, total_credit
                        USING ERRCODE = 'check_violation';
                END IF;
                RETURN COALESCE(NEW, OLD);
            END;
            $$ LANGUAGE plpgsql
        SQL);
        DB::statement(<<<'SQL'
            CREATE TRIGGER trg_journal_balanced
                AFTER INSERT OR UPDATE OR DELETE ON journal_lines
                FOR EACH ROW EXECUTE FUNCTION enforce_balanced_journal_entry()
        SQL);

        // 8c. Financial audit trigger (function fn_financial_audit_trigger exists).
        DB::statement(<<<'SQL'
            CREATE TRIGGER trg_audit_journal_lines
                AFTER INSERT OR UPDATE OR DELETE ON journal_lines
                FOR EACH ROW EXECUTE FUNCTION fn_financial_audit_trigger()
        SQL);

        // ============================================================
        // 8d. Re-create trigger-based FKs to journal_lines that were
        //     dropped in step 0. We use the $droppedFks list captured
        //     there to know which (child, col, deltype) to re-create.
        //     If $droppedFks is empty (idempotent re-run), nothing happens.
        // ============================================================
        foreach ($droppedFks as $fk) {
            $onDelete = match ($fk['deltype']) {
                'c'     => 'CASCADE',
                'n'     => 'SET NULL',
                default => 'NO_ACTION', // 'a' = NO ACTION, 'r' = RESTRICT, 'd' = SET DEFAULT
            };
            $this->createTriggerFkToJournalLines($fk['child'], $fk['col'], $onDelete);
        }

        // ============================================================
        // 9. Drop the unpartitioned table.
        //    Safe now — all declarative FKs to journal_lines were dropped
        //    in step 0, and the dependent view was dropped in step 0a.
        // ============================================================
        DB::statement('DROP TABLE journal_lines_unpartitioned');

        // ============================================================
        // 10. Register with pg_partman + configure 84-month retention.
        // ============================================================
        $this->registerPartman('journal_lines', 'entry_date', '2027-07-01');

        if ($this->hasPgPartman()) {
            try {
                DB::statement(<<<SQL
                    UPDATE partman.part_config
                    SET retention = '84 months',
                        retention_keep_table = true,
                        retention_schema = 'archive'
                    WHERE parent_table = 'public.journal_lines'
                SQL);
            } catch (\Throwable $e) {
                Log::warning("Phase 6.4: Failed to set retention for journal_lines: {$e->getMessage()}");
            }
        }

        // ============================================================
        // 11. Recreate the dependent view (dropped in step 0a).
        //     Now that both journal_entries and journal_lines are
        //     partitioned by entry_date, the view's JOIN can benefit
        //     from partition-wise joins (when enable_partitionwise_join=on,
        //     set by Phase 0.7 / migration 2026_08_15_000005).
        // ============================================================
        DB::statement(<<<'SQL'
            CREATE OR REPLACE VIEW v_journal_entries_with_lines AS
            SELECT
                je.id AS journal_entry_id,
                je.entry_no,
                je.entry_date,
                je.reference_type,
                je.reference_id,
                je.branch_id,
                je.description,
                je.is_reversed,
                je.created_at,
                jl.id AS journal_line_id,
                jl.ledger_id,
                l.ledger_code,
                l.ledger_name,
                l.account_type,
                l.ledger_nature,
                jl.debit,
                jl.credit,
                jl.entity_type,
                jl.entity_id,
                jl.memo
            FROM journal_entries je
            JOIN journal_lines jl ON jl.journal_entry_id = je.id
            LEFT JOIN ledgers l ON l.id = jl.ledger_id
        SQL);

        // ============================================================
        // 11a. Recreate the 5 dependent views / materialized views
        //      dropped in step 0b. CREATE statements are copied
        //      VERBATIM from their original migrations (same as
        //      migration 000002 step 13a):
        //        - mv_ledger_balances            (2025_01_03_000001:30-51)
        //        - mv_journal_entry_summary      (2025_01_03_000001:155-177)
        //        - budget_vs_actual              (2026_08_10_000002:118-162)
        //        - mv_consolidated_trial_balance (2026_08_11_000001:464-503)
        //        - v_unreconciled_bank_entries   (2026_08_12_000001:185-222)
        //      None schema-qualify journal_lines (or journal_entries),
        //      so they resolve to the NEW partitioned parents by name
        //      at query time. CREATE MATERIALIZED VIEW populates the
        //      MV with data immediately (WITH DATA default). The 8
        //      indexes (3+4+1) are recreated right after each MV.
        //      All 5 are mutually independent (no inter-view deps).
        // ============================================================

        // ── mv_ledger_balances ──────────────────────────────────────
        DB::statement(<<<'SQL'
            CREATE MATERIALIZED VIEW IF NOT EXISTS mv_ledger_balances AS
            SELECT
                l.id AS ledger_id,
                l.ledger_code,
                l.ledger_name,
                l.account_type,
                l.ledger_nature,
                l.is_control_account,
                l.is_active,
                l.parent_id,
                COALESCE(SUM(jl.debit), 0) AS total_debit,
                COALESCE(SUM(jl.credit), 0) AS total_credit,
                COALESCE(SUM(jl.debit), 0) - COALESCE(SUM(jl.credit), 0) AS net_debit,
                COUNT(jl.id) AS line_count,
                MAX(je.entry_date) AS last_entry_date
            FROM ledgers l
            LEFT JOIN journal_lines jl ON jl.ledger_id = l.id
            LEFT JOIN journal_entries je ON je.id = jl.journal_entry_id AND COALESCE(je.is_reversed, false) = false
            GROUP BY l.id, l.ledger_code, l.ledger_name, l.account_type, l.ledger_nature,
                     l.is_control_account, l.is_active, l.parent_id
        SQL);
        DB::statement('CREATE UNIQUE INDEX IF NOT EXISTS mv_ledger_balances_ledger_id_idx ON mv_ledger_balances (ledger_id)');
        DB::statement('CREATE INDEX IF NOT EXISTS mv_ledger_balances_account_type_idx ON mv_ledger_balances (account_type)');
        DB::statement('CREATE INDEX IF NOT EXISTS mv_ledger_balances_nature_idx ON mv_ledger_balances (ledger_nature)');

        // ── mv_journal_entry_summary ────────────────────────────────
        DB::statement(<<<'SQL'
            CREATE MATERIALIZED VIEW IF NOT EXISTS mv_journal_entry_summary AS
            SELECT
                je.id AS journal_entry_id,
                je.entry_no,
                je.entry_date,
                je.reference_type,
                je.reference_id,
                je.branch_id,
                je.description,
                je.is_reversed,
                je.created_by,
                je.created_at,
                b.branch_name,
                COALESCE(SUM(jl.debit), 0) AS total_debit,
                COALESCE(SUM(jl.credit), 0) AS total_credit,
                COUNT(jl.id) AS line_count
            FROM journal_entries je
            LEFT JOIN journal_lines jl ON jl.journal_entry_id = je.id
            LEFT JOIN branches b ON b.id = je.branch_id
            GROUP BY je.id, je.entry_no, je.entry_date, je.reference_type, je.reference_id,
                     je.branch_id, je.description, je.is_reversed, je.created_by, je.created_at, b.branch_name
        SQL);
        DB::statement('CREATE UNIQUE INDEX IF NOT EXISTS mv_journal_entry_summary_je_id_idx ON mv_journal_entry_summary (journal_entry_id)');
        DB::statement('CREATE INDEX IF NOT EXISTS mv_journal_entry_summary_date_idx ON mv_journal_entry_summary (entry_date)');
        DB::statement('CREATE INDEX IF NOT EXISTS mv_journal_entry_summary_branch_idx ON mv_journal_entry_summary (branch_id)');
        DB::statement('CREATE INDEX IF NOT EXISTS mv_journal_entry_summary_ref_idx ON mv_journal_entry_summary (reference_type, reference_id)');

        // ── budget_vs_actual ────────────────────────────────────────
        DB::statement(<<<'SQL'
            CREATE OR REPLACE VIEW budget_vs_actual AS
            SELECT
                bl.id AS budget_line_id,
                b.id AS budget_id,
                b.name AS budget_name,
                b.fiscal_year,
                b.branch_id AS budget_branch_id,
                bl.ledger_id,
                l.ledger_code,
                l.ledger_name,
                l.account_type,
                l.normal_balance,
                bl.period,
                bl.amount AS budget_amount,
                COALESCE(actual.actual_amount, 0) AS actual_amount,
                bl.amount - COALESCE(actual.actual_amount, 0) AS variance_amount,
                CASE
                    WHEN bl.amount = 0 THEN NULL
                    ELSE ROUND(
                        ((bl.amount - COALESCE(actual.actual_amount, 0)) / bl.amount) * 100,
                        2
                    )
                END AS variance_percent
            FROM budget_lines bl
            JOIN budgets b ON b.id = bl.budget_id
            JOIN ledgers l ON l.id = bl.ledger_id
            LEFT JOIN LATERAL (
                SELECT SUM(
                    CASE l.normal_balance
                        WHEN 'debit'  THEN jl2.debit  - jl2.credit
                        WHEN 'credit' THEN jl2.credit - jl2.debit
                    END
                ) AS actual_amount
                FROM journal_lines jl2
                JOIN journal_entries je2 ON je2.id = jl2.journal_entry_id
                WHERE jl2.ledger_id = bl.ledger_id
                  AND je2.is_reversed = false
                  AND EXTRACT(YEAR FROM je2.entry_date)::text = b.fiscal_year
                  AND EXTRACT(MONTH FROM je2.entry_date) = bl.period
                  AND (b.branch_id IS NULL OR je2.branch_id = b.branch_id)
            ) actual ON true
            WHERE b.deleted_at IS NULL
              AND l.deleted_at IS NULL
        SQL);

        // ── mv_consolidated_trial_balance ───────────────────────────
        DB::statement(<<<'SQL'
            CREATE MATERIALIZED VIEW IF NOT EXISTS mv_consolidated_trial_balance AS
            SELECT
                l.id AS ledger_id,
                l.ledger_code,
                l.ledger_name,
                l.account_type,
                l.ledger_nature,
                l.normal_balance,
                l.is_elimination,
                -- Aggregate across all branches
                COALESCE(SUM(jl.debit), 0) AS total_debit,
                COALESCE(SUM(jl.credit), 0) AS total_credit,
                -- Elimination adjustment (from elimination entries)
                COALESCE(elim.elim_debit, 0) AS elimination_debit,
                COALESCE(elim.elim_credit, 0) AS elimination_credit,
                -- Consolidated (net of elimination)
                COALESCE(SUM(jl.debit), 0) - COALESCE(elim.elim_debit, 0) AS consolidated_debit,
                COALESCE(SUM(jl.credit), 0) - COALESCE(elim.elim_credit, 0) AS consolidated_credit
            FROM ledgers l
            LEFT JOIN journal_lines jl ON jl.ledger_id = l.id
            LEFT JOIN journal_entries je ON je.id = jl.journal_entry_id
                AND COALESCE(je.is_reversed, false) = false
                AND je.source != 'elimination'
            LEFT JOIN LATERAL (
                SELECT
                    SUM(elim_jl.debit) AS elim_debit,
                    SUM(elim_jl.credit) AS elim_credit
                FROM elimination_entries ee
                JOIN consolidation_runs cr ON cr.id = ee.consolidation_run_id
                JOIN journal_entries elim_je ON elim_je.id = ee.journal_entry_id
                JOIN journal_lines elim_jl ON elim_jl.journal_entry_id = elim_je.id
                WHERE elim_jl.ledger_id = l.id
                  AND cr.status = 'posted'
                  AND COALESCE(elim_je.is_reversed, false) = false
            ) elim ON TRUE
            WHERE l.is_active = true
            GROUP BY l.id, l.ledger_code, l.ledger_name, l.account_type, l.ledger_nature,
                     l.normal_balance, l.is_elimination, elim.elim_debit, elim.elim_credit
        SQL);
        DB::statement('CREATE UNIQUE INDEX IF NOT EXISTS mv_ctb_ledger_idx ON mv_consolidated_trial_balance (ledger_id)');

        // ── v_unreconciled_bank_entries ─────────────────────────────
        DB::statement(<<<'SQL'
            CREATE OR REPLACE VIEW v_unreconciled_bank_entries AS
            SELECT
                jl.id AS journal_line_id,
                jl.journal_entry_id,
                je.entry_no,
                je.entry_date,
                je.description AS entry_description,
                je.source AS entry_source,
                je.reference_type,
                je.reference_id,
                jl.ledger_id,
                jl.debit,
                jl.credit,
                jl.memo,
                jl.is_bank_reconciled,
                l.ledger_code,
                l.ledger_name,
                b.id AS bank_id,
                b.bank_name,
                b.account_number,
                blm.bank_id AS mapping_bank_id,
                je.branch_id,
                br.branch_name
            FROM journal_lines jl
            JOIN journal_entries je ON je.id = jl.journal_entry_id
            JOIN ledgers l ON l.id = jl.ledger_id
            LEFT JOIN bank_ledger_mappings blm ON blm.ledger_id = l.id
            LEFT JOIN banks b ON b.id = blm.bank_id
            LEFT JOIN branches br ON br.id = je.branch_id
            WHERE jl.is_bank_reconciled = false
              AND COALESCE(je.is_reversed, false) = false
              AND blm.bank_id IS NOT NULL
              AND l.deleted_at IS NULL
              AND l.is_active = true
            ORDER BY je.entry_date, je.entry_no
        SQL);

        // ============================================================
        // 12. ANALYZE to refresh planner statistics.
        // ============================================================
        DB::statement('ANALYZE journal_lines');
    }

    // ═══════════════════════════════════════════════════════════════
    //  down() — rollback is manual (trigger-based FK reversal is complex)
    // ═══════════════════════════════════════════════════════════════

    public function down(): void
    {
        // Same rationale as Phase 6.3 — manual rollback via DB snapshot.
        Log::warning(
            'Phase 6.4 rollback: automated down() is intentionally a no-op. '
            . 'Restoring from a pre-migration DB snapshot is the recommended rollback path.'
        );
    }
};
