<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Phase 10.1 — Phase 1: Audit Log Partitioning (Lowest Risk).
 *
 * Partitions all 6 audit/log tables that have zero FK children.
 * These are append-only, high-growth tables that benefit most from
 * date-range partitioning and BRIN indexes.
 *
 * Tables (in order):
 *   1. financial_audit_log       — partition by created_at  (0 FK children, no RLS)
 *   2. user_audit_log            — partition by created_at  (0 FK children, no RLS)
 *   3. stock_take_audit_log      — partition by created_at  (0 FK children, RLS)
 *   4. stock_adjustment_audit_log— partition by created_at  (0 FK children, RLS)
 *   5. branch_demand_audit_log   — partition by created_at  (0 FK children, RLS)
 *   6. journal_posting_logs      — partition by performed_at (0 FK children, no RLS)
 *
 * DESIGN DECISIONS:
 *
 * 1. Partition key: All audit logs use RANGE by their timestamp column
 *    (created_at or performed_at) with monthly partitions. This enables:
 *    - Partition pruning for date-range queries
 *    - Easy archival of old months (DETACH PARTITION)
 *    - Faster VACUUM per partition
 *
 * 2. Composite PK: On partitioned tables, the PK must include the partition
 *    key. All tables change from PK(id) to PK(id, timestamp_column).
 *    GENERATED ALWAYS AS IDENTITY → GENERATED BY DEFAULT AS IDENTITY to
 *    allow OVERRIDING SYSTEM VALUE during data copy.
 *
 * 3. BRIN indexes: Replace B-tree indexes on the partition key column with
 *    BRIN indexes. Audit logs are append-only and naturally ordered by
 *    created_at, making BRIN 100-300x smaller and equally effective.
 *
 * 4. Outbound FKs: FKs FROM these tables TO other tables (e.g.
 *    stock_take_audit_log → stock_take_sessions) work normally on partitioned
 *    tables. They are included in the CREATE TABLE statement.
 *
 * 5. RLS: RLS policies defined on the parent table automatically apply to
 *    all partitions. We drop policies on the old table and recreate on the
 *    new partitioned parent.
 *
 * 6. financial_audit_log special handling:
 *    - Has cryptographic hash chain (prev_hash/row_hash). The trigger
 *      fn_financial_audit_trigger() inserts by name — works with partitioned
 *      table. We temporarily disable audit triggers on the 10 financial
 *      tables during the data copy to prevent hash-chain continuity issues.
 *    - Has REVOKE UPDATE/DELETE (immutable). Must be re-applied.
 *    - Has view v_financial_audit_chain_verification. Must be recreated.
 *
 * 7. journal_posting_logs FK → journal_entries(id):
 *    This is an outbound FK from a partitioned table to a non-partitioned
 *    table — fully supported. When journal_entries is later partitioned
 *    (Phase 6), this FK will need to be converted to trigger-based.
 *
 * MIGRATION STRATEGY (per table):
 *   a. Drop indexes on old table
 *   b. Drop RLS policies on old table (if any)
 *   c. Rename old table to _unpartitioned
 *   d. Create new partitioned table with composite PK + outbound FKs
 *   e. Create monthly partitions (2026-01 to 2026-12) + default partition
 *   f. Copy data from old table (OVERRIDING SYSTEM VALUE)
 *   g. Fix identity sequence
 *   h. Recreate indexes on parent (propagated to partitions)
 *   i. Recreate RLS policies on parent (if any)
 *   j. Re-apply REVOKE (for financial_audit_log)
 *   k. Drop old table
 *   l. Register with pg_partman
 *   m. Analyze
 *
 * ⚠️  This migration should be run during a maintenance window.
 *     It locks tables during the data copy phase.
 */
return new class extends Migration
{
    private ?bool $hasPgPartman = null;

    // ── Helper methods ──────────────────────────────────────────────

    private function hasPgPartman(): bool
    {
        if ($this->hasPgPartman !== null) {
            return $this->hasPgPartman;
        }
        $row = DB::selectOne("
            SELECT EXISTS (
                SELECT 1 FROM pg_available_extensions WHERE name = 'pg_partman'
            ) AS installed
        ");
        $this->hasPgPartman = (bool) ($row->installed ?? false);
        if (! $this->hasPgPartman) {
            logger()->warning('pg_partman is not installed. Automatic partition maintenance is disabled.');
        }
        return $this->hasPgPartman;
    }

    private function isAlreadyPartitioned(string $tableName): bool
    {
        $row = DB::selectOne("
            SELECT 1
            FROM pg_partitioned_table pt
            JOIN pg_class c ON c.oid = pt.partrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relname = ? AND n.nspname = current_schema()
            LIMIT 1
        ", [$tableName]);
        return $row !== null;
    }

    private function relationExists(string $name): bool
    {
        $row = DB::selectOne("
            SELECT 1
            FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relname = ? AND n.nspname = current_schema()
            LIMIT 1
        ", [$name]);
        return $row !== null;
    }

    private function indexExists(string $indexName): bool
    {
        $row = DB::selectOne(
            "SELECT 1 FROM pg_indexes WHERE indexname = ? LIMIT 1",
            [$indexName]
        );
        return $row !== null;
    }

    /**
     * Create 12 monthly partitions for a given year + a default partition.
     * Idempotent — skips partitions that already exist.
     */
    private function createMonthlyPartitions(string $parent, string $year, string $dateType = 'date'): void
    {
        for ($m = 1; $m <= 12; $m++) {
            $from = sprintf('%s-%02d-01', $year, $m);
            $to   = $m < 12
                ? sprintf('%s-%02d-01', $year, $m + 1)
                : sprintf('%d-01-01', (int) $year + 1);
            $name = sprintf('%s_%s_%02d', $parent, $year, $m);

            if (! $this->relationExists($name)) {
                DB::statement(
                    "CREATE TABLE {$name} PARTITION OF {$parent}
                     FOR VALUES FROM ('{$from}') TO ('{$to}')"
                );
            }
        }

        $defaultName = "{$parent}_default";
        if (! $this->relationExists($defaultName)) {
            DB::statement(
                "CREATE TABLE {$defaultName} PARTITION OF {$parent} DEFAULT"
            );
        }
    }

    /**
     * Create a pre-year catch-all partition for historical data.
     * Idempotent — skips if it already exists.
     */
    private function createPreYearPartition(string $parent, string $preYear, string $startYear): void
    {
        $name = "{$parent}_{$preYear}";
        if (! $this->relationExists($name)) {
            DB::statement(
                "CREATE TABLE {$name} PARTITION OF {$parent}
                 FOR VALUES FROM ('2020-01-01') TO ('{$startYear}-01-01')"
            );
        }
    }

    /**
     * Register a table with pg_partman for automatic monthly partition creation.
     * Wrapped in try/catch so re-runs don't fail if already registered.
     */
    private function registerPartman(string $parent, string $control, string $startPartition): void
    {
        if (! $this->hasPgPartman()) {
            return;
        }
        try {
            DB::statement(<<<SQL
                SELECT partman.create_parent(
                    p_parent_table    := 'public.{$parent}',
                    p_control         := '{$control}',
                    p_type            := 'range',
                    p_interval        := '1 month',
                    p_premake         := 6,
                    p_start_partition := '{$startPartition}'
                )
            SQL);
        } catch (\Throwable $e) {
            // Already registered with pg_partman — safe to ignore.
        }
    }

    /**
     * Fix the identity sequence after data copy.
     */
    private function fixSequence(string $table): void
    {
        DB::statement(<<<SQL
            SELECT setval(
                pg_get_serial_sequence('{$table}', 'id'),
                GREATEST(COALESCE((SELECT MAX(id) FROM {$table}), 0), 1)
            )
        SQL);
    }

    // ── Main up() ───────────────────────────────────────────────────

    public function up(): void
    {
        // Install pg_partman if available
        if ($this->hasPgPartman()) {
            DB::statement('CREATE EXTENSION IF NOT EXISTS pg_partman');
            DB::statement('CREATE SCHEMA IF NOT EXISTS partman');
        }

        $this->partitionFinancialAuditLog();
        $this->partitionUserAuditLog();
        $this->partitionStockTakeAuditLog();
        $this->partitionStockAdjustmentAuditLog();
        $this->partitionBranchDemandAuditLog();
        $this->partitionJournalPostingLogs();
    }

    // ═══════════════════════════════════════════════════════════════
    //  1. financial_audit_log
    // ═══════════════════════════════════════════════════════════════

    private function partitionFinancialAuditLog(): void
    {
        if ($this->isAlreadyPartitioned('financial_audit_log')) {
            return;
        }

        // ── Temporarily disable audit triggers on the 10 financial tables ──
        // Prevents hash-chain continuity issues during the data copy.
        $auditTables = [
            'journal_entries', 'journal_lines', 'manual_journals',
            'manual_journal_lines', 'customer_payments', 'supplier_payments',
            'money_transfers', 'other_incomes', 'other_expenses',
            'employee_transactions',
        ];
        foreach ($auditTables as $table) {
            DB::statement(
                "ALTER TABLE {$table} DISABLE TRIGGER trg_audit_{$table}"
            );
        }

        // ── Drop indexes on old table ──
        $falIndexes = [
            'idx_fal_table_record', 'idx_fal_operation', 'idx_fal_performed_by',
            'idx_fal_branch', 'idx_fal_created_at', 'idx_fal_table_op',
        ];
        foreach ($falIndexes as $idx) {
            DB::statement("DROP INDEX IF EXISTS {$idx}");
        }

        // ── Drop the verification view (references the old table) ──
        DB::statement('DROP VIEW IF EXISTS v_financial_audit_chain_verification');

        // ── Rename old table ──
        DB::statement(
            'ALTER TABLE financial_audit_log RENAME TO financial_audit_log_unpartitioned'
        );

        // ── Create partitioned table ──
        // PK must include partition key: (id, created_at)
        // GENERATED ALWAYS → GENERATED BY DEFAULT for OVERRIDING SYSTEM VALUE
        DB::statement(<<<'SQL'
            CREATE TABLE financial_audit_log (
                id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
                table_name      VARCHAR(64) NOT NULL,
                operation       VARCHAR(6)  NOT NULL CHECK (operation IN ('INSERT','UPDATE','DELETE')),
                record_id       BIGINT NOT NULL,
                before_data     JSONB,
                after_data      JSONB,
                changed_columns TEXT[],
                performed_by    VARCHAR(100),
                db_session_user VARCHAR(100),
                branch_id       INTEGER,
                transaction_id  XID,
                request_path    VARCHAR(500),
                request_ip      VARCHAR(45),
                request_id      VARCHAR(100),
                prev_hash       VARCHAR(64),
                row_hash        VARCHAR(64),
                created_at      TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (id, created_at)
            ) PARTITION BY RANGE (created_at)
        SQL);

        // ── Create partitions ──
        $this->createPreYearPartition('financial_audit_log', 'pre2026', '2026');
        $this->createMonthlyPartitions('financial_audit_log', '2026');

        // ── Copy data ──
        DB::statement(<<<'SQL'
            INSERT INTO financial_audit_log (
                id, table_name, operation, record_id, before_data, after_data,
                changed_columns, performed_by, db_session_user, branch_id,
                transaction_id, request_path, request_ip, request_id,
                prev_hash, row_hash, created_at
            )
            OVERRIDING SYSTEM VALUE
            SELECT
                id, table_name, operation, record_id, before_data, after_data,
                changed_columns, performed_by, db_session_user, branch_id,
                transaction_id, request_path, request_ip, request_id,
                prev_hash, row_hash, created_at
            FROM financial_audit_log_unpartitioned
            ORDER BY created_at, id
        SQL);

        // ── Fix sequence ──
        $this->fixSequence('financial_audit_log');

        // ── Recreate indexes (on parent → propagated to partitions) ──
        // Replace B-tree idx_fal_created_at with BRIN (append-only)
        DB::statement(
            'CREATE INDEX idx_fal_table_record ON financial_audit_log (table_name, record_id)'
        );
        DB::statement(
            'CREATE INDEX idx_fal_operation ON financial_audit_log (operation)'
        );
        DB::statement(
            'CREATE INDEX idx_fal_performed_by ON financial_audit_log (performed_by)'
        );
        DB::statement(
            'CREATE INDEX idx_fal_branch ON financial_audit_log (branch_id)'
        );
        DB::statement(
            'CREATE INDEX idx_fal_table_op ON financial_audit_log (table_name, operation)'
        );
        // BRIN index on partition key — much smaller than B-tree for append-only
        DB::statement(<<<'SQL'
            CREATE INDEX idx_fal_created_at_brin
                ON financial_audit_log USING BRIN (created_at)
                WITH (pages_per_range = 32)
        SQL);

        // ── Re-apply REVOKE UPDATE/DELETE (immutable) ──
        DB::statement('REVOKE UPDATE, DELETE ON financial_audit_log FROM PUBLIC');
        $roles = DB::select("SELECT rolname FROM pg_roles WHERE rolname IN ('postgres', 'remote_center')");
        foreach ($roles as $role) {
            DB::statement(
                "REVOKE UPDATE, DELETE ON financial_audit_log FROM {$role->rolname}"
            );
        }

        // ── Drop old table ──
        DB::statement('DROP TABLE financial_audit_log_unpartitioned');

        // ── Recreate verification view ──
        DB::statement(<<<'SQL'
            CREATE OR REPLACE VIEW v_financial_audit_chain_verification AS
            SELECT
                id,
                table_name,
                operation,
                record_id,
                prev_hash,
                row_hash,
                CASE
                    WHEN id = 1 THEN
                        prev_hash = '0000000000000000000000000000000000000000000000000000000000000000'
                    ELSE
                        prev_hash = LAG(row_hash) OVER (ORDER BY id)
                END AS chain_valid,
                created_at
            FROM financial_audit_log
            ORDER BY id
        SQL);

        // ── Re-enable audit triggers on the 10 financial tables ──
        foreach ($auditTables as $table) {
            DB::statement(
                "ALTER TABLE {$table} ENABLE TRIGGER trg_audit_{$table}"
            );
        }

        // ── Register with pg_partman ──
        $this->registerPartman('financial_audit_log', 'created_at', '2027-01-01');

        // ── Configure retention (7 years = 84 months) ──
        if ($this->hasPgPartman()) {
            DB::statement(<<<'SQL'
                UPDATE partman.part_config
                SET retention = '84 months',
                    retention_keep_table = true,
                    retention_schema = 'archive'
                WHERE parent_table = 'public.financial_audit_log'
            SQL);
        }

        // ── Analyze ──
        DB::statement('ANALYZE financial_audit_log');
    }

    // ═══════════════════════════════════════════════════════════════
    //  2. user_audit_log
    // ═══════════════════════════════════════════════════════════════

    private function partitionUserAuditLog(): void
    {
        if ($this->isAlreadyPartitioned('user_audit_log')) {
            return;
        }

        // ── Drop indexes on old table ──
        $ualIndexes = [
            'idx_ual_user', 'idx_ual_action', 'idx_ual_created',
            'idx_ual_created_at_brin',
        ];
        foreach ($ualIndexes as $idx) {
            DB::statement("DROP INDEX IF EXISTS {$idx}");
        }

        // ── Rename old table ──
        DB::statement(
            'ALTER TABLE user_audit_log RENAME TO user_audit_log_unpartitioned'
        );

        // ── Create partitioned table ──
        DB::statement(<<<'SQL'
            CREATE TABLE user_audit_log (
                id            INTEGER GENERATED BY DEFAULT AS IDENTITY,
                user_id       INTEGER,
                action        VARCHAR(50) NOT NULL,
                target_user_id INTEGER,
                branch_id     INTEGER,
                record_id     INTEGER,
                details       JSONB,
                ip_address    VARCHAR(45),
                user_agent    TEXT,
                created_at    TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (id, created_at)
            ) PARTITION BY RANGE (created_at)
        SQL);

        // ── Create partitions ──
        $this->createPreYearPartition('user_audit_log', 'pre2026', '2026');
        $this->createMonthlyPartitions('user_audit_log', '2026');

        // ── Copy data ──
        DB::statement(<<<'SQL'
            INSERT INTO user_audit_log (
                id, user_id, action, target_user_id, branch_id, record_id,
                details, ip_address, user_agent, created_at
            )
            OVERRIDING SYSTEM VALUE
            SELECT
                id, user_id, action, target_user_id, branch_id, record_id,
                details, ip_address, user_agent, created_at
            FROM user_audit_log_unpartitioned
            ORDER BY created_at, id
        SQL);

        // ── Fix sequence ──
        $this->fixSequence('user_audit_log');

        // ── Recreate indexes ──
        DB::statement(
            'CREATE INDEX idx_ual_user ON user_audit_log (user_id)'
        );
        DB::statement(
            'CREATE INDEX idx_ual_action ON user_audit_log (action)'
        );
        // BRIN replaces B-tree on created_at for append-only table
        DB::statement(<<<'SQL'
            CREATE INDEX idx_ual_created_at_brin
                ON user_audit_log USING BRIN (created_at)
                WITH (pages_per_range = 64)
        SQL);

        // ── Drop old table ──
        DB::statement('DROP TABLE user_audit_log_unpartitioned');

        // ── Register with pg_partman ──
        $this->registerPartman('user_audit_log', 'created_at', '2027-01-01');

        // ── Configure retention (3 years = 36 months) ──
        if ($this->hasPgPartman()) {
            DB::statement(<<<'SQL'
                UPDATE partman.part_config
                SET retention = '36 months',
                    retention_keep_table = true,
                    retention_schema = 'archive'
                WHERE parent_table = 'public.user_audit_log'
            SQL);
        }

        // ── Analyze ──
        DB::statement('ANALYZE user_audit_log');
    }

    // ═══════════════════════════════════════════════════════════════
    //  3. stock_take_audit_log
    // ═══════════════════════════════════════════════════════════════

    private function partitionStockTakeAuditLog(): void
    {
        if ($this->isAlreadyPartitioned('stock_take_audit_log')) {
            return;
        }

        // ── Drop RLS policies on old table (will recreate on new) ──
        foreach (['select', 'insert', 'update', 'delete', 'admin'] as $verb) {
            DB::statement(
                "DROP POLICY IF EXISTS rls_stock_take_audit_log_{$verb} ON stock_take_audit_log"
            );
        }
        DB::statement('ALTER TABLE stock_take_audit_log NO FORCE ROW LEVEL SECURITY');
        DB::statement('ALTER TABLE stock_take_audit_log DISABLE ROW LEVEL SECURITY');

        // ── Drop indexes on old table ──
        $stalIndexes = [
            'idx_stal_session', 'idx_stal_critical', 'idx_stal_branch', 'idx_stal_actor',
        ];
        foreach ($stalIndexes as $idx) {
            DB::statement("DROP INDEX IF EXISTS {$idx}");
        }

        // ── Rename old table ──
        DB::statement(
            'ALTER TABLE stock_take_audit_log RENAME TO stock_take_audit_log_unpartitioned'
        );

        // ── Create partitioned table ──
        // Outbound FKs are included — they work normally on partitioned tables
        DB::statement(<<<'SQL'
            CREATE TABLE stock_take_audit_log (
                id                      INTEGER GENERATED BY DEFAULT AS IDENTITY,
                stock_take_session_id   INTEGER NOT NULL REFERENCES stock_take_sessions(id) ON DELETE CASCADE,
                stock_take_warehouse_id INTEGER REFERENCES warehouses(id) ON DELETE SET NULL,
                stock_take_item_id      INTEGER REFERENCES stock_take_items(id) ON DELETE SET NULL,
                action VARCHAR(40) NOT NULL CHECK (
                    action IN ('create','setup','save_count','mark_complete','submit',
                               'approve','reject','post','reverse','re_open','delete',
                               'cancel','recount','scan_count','bulk_upsert','csv_import','autosave')
                ),
                actor_id    INTEGER,
                from_status VARCHAR(20),
                to_status   VARCHAR(20),
                payload     JSONB,
                branch_id   INTEGER NOT NULL REFERENCES branches(id),
                created_at  TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (id, created_at)
            ) PARTITION BY RANGE (created_at)
        SQL);

        // ── Create partitions ──
        $this->createPreYearPartition('stock_take_audit_log', 'pre2026', '2026');
        $this->createMonthlyPartitions('stock_take_audit_log', '2026');

        // ── Copy data ──
        DB::statement(<<<'SQL'
            INSERT INTO stock_take_audit_log (
                id, stock_take_session_id, stock_take_warehouse_id,
                stock_take_item_id, action, actor_id, from_status,
                to_status, payload, branch_id, created_at
            )
            OVERRIDING SYSTEM VALUE
            SELECT
                id, stock_take_session_id, stock_take_warehouse_id,
                stock_take_item_id, action, actor_id, from_status,
                to_status, payload, branch_id, created_at
            FROM stock_take_audit_log_unpartitioned
            ORDER BY created_at, id
        SQL);

        // ── Fix sequence ──
        $this->fixSequence('stock_take_audit_log');

        // ── Recreate indexes ──
        DB::statement(
            'CREATE INDEX idx_stal_session ON stock_take_audit_log (stock_take_session_id, created_at)'
        );
        DB::statement(<<<'SQL'
            CREATE INDEX idx_stal_critical ON stock_take_audit_log (stock_take_session_id)
                WHERE action IN ('post','reverse','re_open','recount')
        SQL);
        DB::statement(
            'CREATE INDEX idx_stal_branch ON stock_take_audit_log (branch_id, created_at)'
        );
        DB::statement(
            'CREATE INDEX idx_stal_actor ON stock_take_audit_log (actor_id, created_at)'
        );
        // BRIN on partition key
        DB::statement(<<<'SQL'
            CREATE INDEX idx_stal_created_at_brin
                ON stock_take_audit_log USING BRIN (created_at)
                WITH (pages_per_range = 32)
        SQL);

        // ── Drop old table ──
        DB::statement('DROP TABLE stock_take_audit_log_unpartitioned');

        // ── Recreate RLS policies on parent (propagated to partitions) ──
        DB::statement('ALTER TABLE stock_take_audit_log ENABLE ROW LEVEL SECURITY');
        DB::statement('ALTER TABLE stock_take_audit_log FORCE ROW LEVEL SECURITY');

        DB::statement(<<<'SQL'
            CREATE POLICY rls_stock_take_audit_log_select ON stock_take_audit_log
                FOR SELECT USING (
                    current_setting('app.is_admin', true) = 'true'
                    OR branch_id = current_setting('app.branch_id', true)::integer
                )
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_stock_take_audit_log_insert ON stock_take_audit_log
                FOR INSERT WITH CHECK (
                    current_setting('app.is_admin', true) = 'true'
                    OR branch_id = current_setting('app.branch_id', true)::integer
                )
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_stock_take_audit_log_update ON stock_take_audit_log
                FOR UPDATE USING (
                    current_setting('app.is_admin', true) = 'true'
                    OR branch_id = current_setting('app.branch_id', true)::integer
                )
                WITH CHECK (
                    current_setting('app.is_admin', true) = 'true'
                    OR branch_id = current_setting('app.branch_id', true)::integer
                )
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_stock_take_audit_log_delete ON stock_take_audit_log
                FOR DELETE USING (
                    current_setting('app.is_admin', true) = 'true'
                    OR branch_id = current_setting('app.branch_id', true)::integer
                )
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_stock_take_audit_log_admin ON stock_take_audit_log
                FOR ALL
                USING (current_setting('app.is_admin', true) = 'true')
                WITH CHECK (current_setting('app.is_admin', true) = 'true')
        SQL);

        // ── Register with pg_partman ──
        $this->registerPartman('stock_take_audit_log', 'created_at', '2027-01-01');

        // ── Configure retention (3 years = 36 months) ──
        if ($this->hasPgPartman()) {
            DB::statement(<<<'SQL'
                UPDATE partman.part_config
                SET retention = '36 months',
                    retention_keep_table = true,
                    retention_schema = 'archive'
                WHERE parent_table = 'public.stock_take_audit_log'
            SQL);
        }

        // ── Analyze ──
        DB::statement('ANALYZE stock_take_audit_log');
    }

    // ═══════════════════════════════════════════════════════════════
    //  4. stock_adjustment_audit_log
    // ═══════════════════════════════════════════════════════════════

    private function partitionStockAdjustmentAuditLog(): void
    {
        if ($this->isAlreadyPartitioned('stock_adjustment_audit_log')) {
            return;
        }

        // ── Drop RLS policies on old table ──
        foreach (['select', 'insert', 'update', 'delete', 'admin'] as $verb) {
            DB::statement(
                "DROP POLICY IF EXISTS rls_stock_adjustment_audit_log_{$verb} ON stock_adjustment_audit_log"
            );
        }
        DB::statement('ALTER TABLE stock_adjustment_audit_log NO FORCE ROW LEVEL SECURITY');
        DB::statement('ALTER TABLE stock_adjustment_audit_log DISABLE ROW LEVEL SECURITY');

        // ── Drop indexes on old table ──
        $saalIndexes = [
            'idx_saal_adjustment', 'idx_saal_critical', 'idx_saal_branch', 'idx_saal_actor',
        ];
        foreach ($saalIndexes as $idx) {
            DB::statement("DROP INDEX IF EXISTS {$idx}");
        }

        // ── Rename old table ──
        DB::statement(
            'ALTER TABLE stock_adjustment_audit_log RENAME TO stock_adjustment_audit_log_unpartitioned'
        );

        // ── Create partitioned table ──
        // Note: original uses bigserial, we switch to GENERATED BY DEFAULT AS IDENTITY
        // for consistency with partitioned table pattern
        DB::statement(<<<'SQL'
            CREATE TABLE stock_adjustment_audit_log (
                id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
                stock_adjustment_id INTEGER NOT NULL REFERENCES stock_adjustments(id) ON DELETE CASCADE,
                branch_id           INTEGER NOT NULL REFERENCES branches(id),
                action VARCHAR(40) NOT NULL CHECK (
                    action IN ('create','update','submit','approve','reject','confirm',
                               'cancel','reverse','force_confirm','reopen','delete','export','print')
                ),
                actor_id   BIGINT,
                actor_role VARCHAR(40),
                payload    JSONB,
                ip_address VARCHAR(45),
                user_agent VARCHAR(255),
                created_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (id, created_at)
            ) PARTITION BY RANGE (created_at)
        SQL);

        // ── Create partitions ──
        $this->createPreYearPartition('stock_adjustment_audit_log', 'pre2026', '2026');
        $this->createMonthlyPartitions('stock_adjustment_audit_log', '2026');

        // ── Copy data ──
        DB::statement(<<<'SQL'
            INSERT INTO stock_adjustment_audit_log (
                id, stock_adjustment_id, branch_id, action, actor_id,
                actor_role, payload, ip_address, user_agent, created_at
            )
            OVERRIDING SYSTEM VALUE
            SELECT
                id, stock_adjustment_id, branch_id, action, actor_id,
                actor_role, payload, ip_address, user_agent, created_at
            FROM stock_adjustment_audit_log_unpartitioned
            ORDER BY created_at, id
        SQL);

        // ── Fix sequence ──
        $this->fixSequence('stock_adjustment_audit_log');

        // ── Recreate indexes ──
        DB::statement(
            'CREATE INDEX idx_saal_adjustment ON stock_adjustment_audit_log (stock_adjustment_id, created_at)'
        );
        DB::statement(<<<'SQL'
            CREATE INDEX idx_saal_critical ON stock_adjustment_audit_log (stock_adjustment_id)
                WHERE action IN ('confirm','cancel','reverse','force_confirm')
        SQL);
        DB::statement(
            'CREATE INDEX idx_saal_branch ON stock_adjustment_audit_log (branch_id, created_at)'
        );
        DB::statement(
            'CREATE INDEX idx_saal_actor ON stock_adjustment_audit_log (actor_id, created_at)'
        );
        DB::statement(<<<'SQL'
            CREATE INDEX idx_saal_created_at_brin
                ON stock_adjustment_audit_log USING BRIN (created_at)
                WITH (pages_per_range = 32)
        SQL);

        // ── Drop old table ──
        DB::statement('DROP TABLE stock_adjustment_audit_log_unpartitioned');

        // ── Recreate RLS policies ──
        DB::statement('ALTER TABLE stock_adjustment_audit_log ENABLE ROW LEVEL SECURITY');
        DB::statement('ALTER TABLE stock_adjustment_audit_log FORCE ROW LEVEL SECURITY');

        DB::statement(<<<'SQL'
            CREATE POLICY rls_stock_adjustment_audit_log_select ON stock_adjustment_audit_log
                FOR SELECT USING (
                    current_setting('app.is_admin', true) = 'true'
                    OR branch_id = current_setting('app.branch_id', true)::integer
                )
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_stock_adjustment_audit_log_insert ON stock_adjustment_audit_log
                FOR INSERT WITH CHECK (
                    current_setting('app.is_admin', true) = 'true'
                    OR branch_id = current_setting('app.branch_id', true)::integer
                )
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_stock_adjustment_audit_log_update ON stock_adjustment_audit_log
                FOR UPDATE USING (
                    current_setting('app.is_admin', true) = 'true'
                    OR branch_id = current_setting('app.branch_id', true)::integer
                )
                WITH CHECK (
                    current_setting('app.is_admin', true) = 'true'
                    OR branch_id = current_setting('app.branch_id', true)::integer
                )
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_stock_adjustment_audit_log_delete ON stock_adjustment_audit_log
                FOR DELETE USING (
                    current_setting('app.is_admin', true) = 'true'
                    OR branch_id = current_setting('app.branch_id', true)::integer
                )
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY rls_stock_adjustment_audit_log_admin ON stock_adjustment_audit_log
                FOR ALL
                USING (current_setting('app.is_admin', true) = 'true')
                WITH CHECK (current_setting('app.is_admin', true) = 'true')
        SQL);

        // ── Register with pg_partman ──
        $this->registerPartman('stock_adjustment_audit_log', 'created_at', '2027-01-01');

        // ── Configure retention (3 years = 36 months) ──
        if ($this->hasPgPartman()) {
            DB::statement(<<<'SQL'
                UPDATE partman.part_config
                SET retention = '36 months',
                    retention_keep_table = true,
                    retention_schema = 'archive'
                WHERE parent_table = 'public.stock_adjustment_audit_log'
            SQL);
        }

        // ── Analyze ──
        DB::statement('ANALYZE stock_adjustment_audit_log');
    }

    // ═══════════════════════════════════════════════════════════════
    //  5. branch_demand_audit_log
    // ═══════════════════════════════════════════════════════════════

    private function partitionBranchDemandAuditLog(): void
    {
        if ($this->isAlreadyPartitioned('branch_demand_audit_log')) {
            return;
        }

        // ── Drop RLS policies on old table ──
        $bdalPolicies = [
            'bdal_branch_read', 'bdal_admin_read', 'bdal_insert',
            'bdal_no_update', 'bdal_no_delete',
        ];
        foreach ($bdalPolicies as $policy) {
            DB::statement(
                "DROP POLICY IF EXISTS {$policy} ON branch_demand_audit_log"
            );
        }
        DB::statement('ALTER TABLE branch_demand_audit_log DISABLE ROW LEVEL SECURITY');

        // ── Drop indexes on old table ──
        $bdalIndexes = [
            'idx_bdal_demand', 'idx_bdal_branch', 'idx_bdal_actor', 'idx_bdal_critical',
        ];
        foreach ($bdalIndexes as $idx) {
            DB::statement("DROP INDEX IF EXISTS {$idx}");
        }

        // ── Rename old table ──
        DB::statement(
            'ALTER TABLE branch_demand_audit_log RENAME TO branch_demand_audit_log_unpartitioned'
        );

        // ── Create partitioned table ──
        // Note: original uses $table->id() (unsigned bigserial), we switch to
        // GENERATED BY DEFAULT AS IDENTITY for consistency
        DB::statement(<<<'SQL'
            CREATE TABLE branch_demand_audit_log (
                id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
                branch_demand_id BIGINT NOT NULL REFERENCES branch_demands(id) ON DELETE CASCADE,
                branch_id       BIGINT,
                action VARCHAR(40) CHECK (
                    action IN (
                        'create', 'send', 'confirm_receipt', 'reverse', 'delete',
                        'reject', 'reprice', 'settle', 'settlement_reverse',
                        'export', 'print'
                    )
                ),
                actor_id   BIGINT,
                actor_role VARCHAR(50),
                payload    JSONB,
                ip_address VARCHAR(45),
                user_agent VARCHAR(255),
                created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (id, created_at)
            ) PARTITION BY RANGE (created_at)
        SQL);

        // ── Create partitions ──
        $this->createPreYearPartition('branch_demand_audit_log', 'pre2026', '2026');
        $this->createMonthlyPartitions('branch_demand_audit_log', '2026');

        // ── Copy data ──
        DB::statement(<<<'SQL'
            INSERT INTO branch_demand_audit_log (
                id, branch_demand_id, branch_id, action, actor_id,
                actor_role, payload, ip_address, user_agent, created_at
            )
            OVERRIDING SYSTEM VALUE
            SELECT
                id, branch_demand_id, branch_id, action, actor_id,
                actor_role, payload, ip_address, user_agent, created_at
            FROM branch_demand_audit_log_unpartitioned
            ORDER BY created_at, id
        SQL);

        // ── Fix sequence ──
        $this->fixSequence('branch_demand_audit_log');

        // ── Recreate indexes ──
        DB::statement(
            'CREATE INDEX idx_bdal_demand ON branch_demand_audit_log (branch_demand_id)'
        );
        DB::statement(
            'CREATE INDEX idx_bdal_branch ON branch_demand_audit_log (branch_id)'
        );
        DB::statement(
            'CREATE INDEX idx_bdal_actor ON branch_demand_audit_log (actor_id)'
        );
        DB::statement(<<<'SQL'
            CREATE INDEX idx_bdal_critical ON branch_demand_audit_log (branch_demand_id, action)
                WHERE action IN ('reverse', 'delete', 'reprice', 'settlement_reverse')
        SQL);
        DB::statement(<<<'SQL'
            CREATE INDEX idx_bdal_created_at_brin
                ON branch_demand_audit_log USING BRIN (created_at)
                WITH (pages_per_range = 32)
        SQL);

        // ── Drop old table ──
        DB::statement('DROP TABLE branch_demand_audit_log_unpartitioned');

        // ── Recreate RLS policies (note: uses app.current_branch_id, not app.branch_id) ──
        DB::statement('ALTER TABLE branch_demand_audit_log ENABLE ROW LEVEL SECURITY');

        DB::statement(<<<'SQL'
            CREATE POLICY bdal_branch_read ON branch_demand_audit_log
                FOR SELECT
                USING (branch_id = current_setting('app.current_branch_id')::bigint
                       OR current_setting('app.is_admin', true) = 'true')
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY bdal_admin_read ON branch_demand_audit_log
                FOR SELECT
                USING (current_setting('app.is_admin', true) = 'true')
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY bdal_insert ON branch_demand_audit_log
                FOR INSERT
                WITH CHECK (true)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY bdal_no_update ON branch_demand_audit_log
                FOR UPDATE
                USING (false)
        SQL);
        DB::statement(<<<'SQL'
            CREATE POLICY bdal_no_delete ON branch_demand_audit_log
                FOR DELETE
                USING (false)
        SQL);

        // ── Register with pg_partman ──
        $this->registerPartman('branch_demand_audit_log', 'created_at', '2027-01-01');

        // ── Configure retention (3 years = 36 months) ──
        if ($this->hasPgPartman()) {
            DB::statement(<<<'SQL'
                UPDATE partman.part_config
                SET retention = '36 months',
                    retention_keep_table = true,
                    retention_schema = 'archive'
                WHERE parent_table = 'public.branch_demand_audit_log'
            SQL);
        }

        // ── Analyze ──
        DB::statement('ANALYZE branch_demand_audit_log');
    }

    // ═══════════════════════════════════════════════════════════════
    //  6. journal_posting_logs
    // ═══════════════════════════════════════════════════════════════

    private function partitionJournalPostingLogs(): void
    {
        if ($this->isAlreadyPartitioned('journal_posting_logs')) {
            return;
        }

        // ── Drop indexes on old table ──
        $jplIndexes = [
            'idx_jpl_entry', 'idx_jpl_performed_at_brin',
        ];
        foreach ($jplIndexes as $idx) {
            DB::statement("DROP INDEX IF EXISTS {$idx}");
        }

        // ── Rename old table ──
        DB::statement(
            'ALTER TABLE journal_posting_logs RENAME TO journal_posting_logs_unpartitioned'
        );

        // ── Create partitioned table ──
        // Note: FK to journal_entries(id) is an outbound FK — works on partitioned tables.
        // When journal_entries is partitioned (Phase 6), this FK will need to be
        // converted to trigger-based. For now, it's a standard FK to a non-partitioned table.
        DB::statement(<<<'SQL'
            CREATE TABLE journal_posting_logs (
                id               INTEGER GENERATED BY DEFAULT AS IDENTITY,
                journal_entry_id INTEGER NOT NULL REFERENCES journal_entries(id) ON DELETE CASCADE,
                action           VARCHAR(20) NOT NULL CHECK (action IN ('posted','reversed','edited')),
                performed_by     INTEGER,
                performed_at     TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                remarks          TEXT,
                PRIMARY KEY (id, performed_at)
            ) PARTITION BY RANGE (performed_at)
        SQL);

        // ── Create partitions ──
        $this->createPreYearPartition('journal_posting_logs', 'pre2026', '2026');
        $this->createMonthlyPartitions('journal_posting_logs', '2026');

        // ── Copy data ──
        DB::statement(<<<'SQL'
            INSERT INTO journal_posting_logs (
                id, journal_entry_id, action, performed_by, performed_at, remarks
            )
            OVERRIDING SYSTEM VALUE
            SELECT
                id, journal_entry_id, action, performed_by, performed_at, remarks
            FROM journal_posting_logs_unpartitioned
            ORDER BY performed_at, id
        SQL);

        // ── Fix sequence ──
        $this->fixSequence('journal_posting_logs');

        // ── Recreate indexes ──
        DB::statement(
            'CREATE INDEX idx_jpl_entry ON journal_posting_logs (journal_entry_id)'
        );
        DB::statement(<<<'SQL'
            CREATE INDEX idx_jpl_performed_at_brin
                ON journal_posting_logs USING BRIN (performed_at)
                WITH (pages_per_range = 64)
        SQL);

        // ── Drop old table ──
        DB::statement('DROP TABLE journal_posting_logs_unpartitioned');

        // ── Register with pg_partman ──
        $this->registerPartman('journal_posting_logs', 'performed_at', '2027-01-01');

        // ── Configure retention (7 years = 84 months — financial records) ──
        if ($this->hasPgPartman()) {
            DB::statement(<<<'SQL'
                UPDATE partman.part_config
                SET retention = '84 months',
                    retention_keep_table = true,
                    retention_schema = 'archive'
                WHERE parent_table = 'public.journal_posting_logs'
            SQL);
        }

        // ── Analyze ──
        DB::statement('ANALYZE journal_posting_logs');
    }

    // ═══════════════════════════════════════════════════════════════
    //  Rollback (limited — partitioning is a one-way operation)
    // ═══════════════════════════════════════════════════════════════

    public function down(): void
    {
        // ⚠️  Partitioning is a one-way operation. Full rollback requires
        //     detaching all partitions, creating a non-partitioned table,
        //     copying data back, and dropping the partitioned parent.
        //     This is complex and should be done manually if needed.
        //
        //     The individual table methods above handle the forward
        //     transformation idempotently (isAlreadyPartitioned check),
        //     so re-running up() after a partial failure is safe.
        //
        //     For a full rollback, see the Phase 10.1 plan document
        //     Section 15 (Rollback Strategy).

        logger()->warning(
            'Phase 10.1 Phase 1 (audit log partitioning): rollback is not automated. ' .
            'See doc/Phase_10.1_Partitioning_and_Archival_Plan.md Section 15.'
        );
    }
};
