<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

/**
 * Restore basic data from the snapshot file.
 *
 * Usage:
 *   php artisan db:restore-basic [--force] [--stop-on-error] [--verbose]
 *
 * What it does:
 *   - Reads database/sql/basic_data_snapshot.sql (generated by db:snapshot-basic).
 *   - Strips backward-compat SET session_replication_role lines (older snapshots
 *     had them; they require PG SUPERUSER and break restore for non-superuser
 *     accounts — see commit history for the postmortem).
 *   - Splits the SQL into individual statements using a string-aware splitter
 *     (so semicolons inside string literals don't break things).
 *   - Executes each statement individually via DB::unprepared().
 *     By default continues on error and reports a summary at the end.
 *     Use --stop-on-error to abort on first failure.
 *   - Resets all sequences (so future AUTO-INSERTs don't collide with
 *     restored explicit-id rows).
 *
 * Requires a snapshot file to exist. If not, prints instructions to create one.
 *
 * Typical workflow:
 *   1. (one-time) php artisan db:snapshot-basic     # capture current state
 *   2. php artisan db:make-empty                    # wipe everything
 *   3. php artisan db:restore-basic                 # restore basic data
 *
 * Or to "reset to basic state" from any state:
 *   php artisan db:make-empty --force && php artisan db:restore-basic --force
 */
class DbRestoreBasic extends Command
{
    protected $signature = 'db:restore-basic
                            {--force : Skip confirmation prompt}
                            {--stop-on-error : Abort on first SQL error (default: continue and report)}
                            {--verbose : Print each statement as it executes}';

    protected $description = 'Restore basic-data tables from database/sql/basic_data_snapshot.sql';

    public function handle(): int
    {
        $this->info('=== DB RESTORE (BASIC DATA) ===');
        $this->newLine();

        $path = database_path('sql/basic_data_snapshot.sql');

        // ---- Check snapshot exists ----
        if (!file_exists($path)) {
            $this->error('✗ Snapshot file not found: ' . $path);
            $this->newLine();
            $this->warn('To create a snapshot, run:');
            $this->line('  php artisan db:snapshot-basic');
            $this->newLine();
            $this->warn('Then commit database/sql/basic_data_snapshot.sql to the repo.');
            return self::FAILURE;
        }

        $size = filesize($path);
        $mtime = date('Y-m-d H:i:s', filemtime($path));
        $this->info("Snapshot file: {$path}");
        $this->info("Size: {$size} bytes | Last modified: {$mtime}");
        $this->newLine();

        // ---- Confirm ----
        if (!$this->option('force')) {
            if (!$this->confirm('Restore basic data from snapshot? (This will INSERT/REPLACE rows in basic-data tables)', false)) {
                $this->info('Aborted. No changes made.');
                return self::SUCCESS;
            }
        }

        // ---- Read snapshot ----
        $sql = file_get_contents($path);
        if ($sql === false || trim($sql) === '') {
            $this->error('✗ Snapshot file is empty or unreadable.');
            return self::FAILURE;
        }

        // ---- Strip backward-compat SET session_replication_role lines ----
        // Older snapshots included `SET session_replication_role = 'replica';`
        // and `SET session_replication_role = 'origin';`. These require PG
        // SUPERUSER and break restore for non-superuser DB accounts. Newer
        // snapshots don't include them, but we strip them here so old
        // snapshots still work.
        $sql = preg_replace(
            '/^\s*SET\s+session_replication_role\s*=\s*[\'"]\w+[\'"]\s*;\s*$/im',
            '',
            $sql
        );

        // ---- Split into statements (string-aware) ----
        $statements = $this->splitSqlStatements($sql);
        $totalStatements = count($statements);
        $this->info("Found {$totalStatements} SQL statement(s) to execute.");
        $this->newLine();

        // ---- Show BEFORE counts for sanity check ----
        $beforeCounts = $this->getTableCounts([
            'branches', 'warehouses', 'employees', 'users', 'customers',
            'suppliers', 'products', 'ledgers', 'menus',
        ]);

        // ---- Execute statements one by one ----
        $this->info('Executing statements...');
        $succeeded = 0;
        $failed = 0;
        $failedStatements = [];
        $currentTable = '(unknown)';

        foreach ($statements as $i => $stmt) {
            $stmt = trim($stmt);
            if ($stmt === '') {
                continue;
            }

            // Track which table we're working on for error reporting.
            if (preg_match('/^(INSERT|DELETE)\s+INTO\s+"(\w+)"/i', $stmt, $m)
                || preg_match('/^DELETE\s+FROM\s+"(\w+)"/i', $stmt, $m)) {
                $currentTable = $m[2] ?? $m[1] ?? $currentTable;
            }

            if ($this->option('verbose')) {
                $preview = substr($stmt, 0, 120);
                $this->line("  [" . ($i + 1) . "/{$totalStatements}] {$preview}...");
            }

            try {
                DB::unprepared($stmt);
                $succeeded++;
            } catch (\Throwable $e) {
                $failed++;
                $errMsg = $e->getMessage();
                $failedStatements[] = [
                    'index' => $i + 1,
                    'table' => $currentTable,
                    'error' => $errMsg,
                    'statement' => substr($stmt, 0, 200),
                ];
                $this->error("  ✗ [{$currentTable}] {$errMsg}");
                if ($this->option('stop-on-error')) {
                    $this->warn('  --stop-on-error: aborting.');
                    break;
                }
            }
        }

        // ---- Summary ----
        $this->newLine();
        $this->info("Statements: {$succeeded} succeeded, {$failed} failed, " . ($totalStatements - $succeeded - $failed) . " skipped.");

        if (!empty($failedStatements) && !$this->option('stop-on-error')) {
            $this->newLine();
            $this->warn('Failed statements (first 10):');
            foreach (array_slice($failedStatements, 0, 10) as $f) {
                $this->line("  [{$f['index']}] table={$f['table']}");
                $this->line("      error:   {$f['error']}");
                $this->line("      stmt:    {$f['statement']}");
            }
            if (count($failedStatements) > 10) {
                $this->line("  ... and " . (count($failedStatements) - 10) . " more.");
            }
        }

        // ---- Reset sequences ----
        $this->newLine();
        $this->info('Resetting ID sequences to MAX(id)...');
        $this->resetSequences();

        // ---- Verify ----
        $this->newLine();
        $this->info('✓ Restore complete. Verifying...');
        $afterCounts = $this->getTableCounts(array_keys($beforeCounts));

        $this->newLine();
        $this->info('Row counts (before → after):');
        foreach ($afterCounts as $table => $after) {
            $before = $beforeCounts[$table] ?? '?';
            $this->line("  {$table}: {$before} → {$after}");
        }

        $this->newLine();
        if ($failed > 0) {
            $this->warn("Done with {$failed} error(s). Some tables may be incomplete.");
            $this->warn('To retry: php artisan db:make-empty --force && php artisan db:restore-basic --force');
            return self::FAILURE;
        }
        $this->info('Done. Basic data restored successfully.');
        return self::SUCCESS;
    }

    /**
     * Split a multi-statement SQL string into individual statements.
     *
     * String-aware: a semicolon inside a single-quoted string literal is NOT
     * treated as a statement terminator. Handles SQL standard single-quote
     * escaping ('' = literal ').
     *
     * Comment-aware: lines starting with -- are skipped (treated as whitespace).
     *
     * @return string[]
     */
    private function splitSqlStatements(string $sql): array
    {
        $statements = [];
        $current = '';
        $inString = false;
        $len = strlen($sql);
        $i = 0;

        while ($i < $len) {
            $ch = $sql[$i];
            $next = ($i + 1 < $len) ? $sql[$i + 1] : '';

            // Inside a single-quoted string.
            if ($inString) {
                $current .= $ch;
                if ($ch === "'" && $next === "'") {
                    // Escaped '' — consume both chars.
                    $current .= $next;
                    $i += 2;
                    continue;
                }
                if ($ch === "'") {
                    $inString = false;
                }
                $i++;
                continue;
            }

            // Line comment — skip until end of line.
            if ($ch === '-' && $next === '-') {
                while ($i < $len && $sql[$i] !== "\n") {
                    $i++;
                }
                continue;
            }

            // Entering a single-quoted string.
            if ($ch === "'") {
                $inString = true;
                $current .= $ch;
                $i++;
                continue;
            }

            // Statement terminator.
            if ($ch === ';') {
                $stmt = trim($current);
                if ($stmt !== '') {
                    $statements[] = $stmt;
                }
                $current = '';
                $i++;
                continue;
            }

            $current .= $ch;
            $i++;
        }

        // Append any trailing statement (no terminating ; — shouldn't happen
        // in well-formed SQL, but be safe).
        $stmt = trim($current);
        if ($stmt !== '') {
            $statements[] = $stmt;
        }

        return $statements;
    }

    /**
     * Get row counts for a list of tables (skips missing/uncountable tables).
     *
     * @param string[] $tables
     * @return array<string,int>
     */
    private function getTableCounts(array $tables): array
    {
        $counts = [];
        foreach ($tables as $t) {
            try {
                $count = DB::table($t)->count();
                $counts[$t] = $count;
            } catch (\Throwable $e) {
                // Skip — table doesn't exist or is a view.
            }
        }
        return $counts;
    }

    /**
     * Reset all identity sequences to MAX(id) so future AUTO-INSERTs don't
     * collide with restored explicit-id rows.
     */
    private function resetSequences(): void
    {
        $identityCols = DB::table('information_schema.columns')
            ->where('table_schema', 'public')
            ->where('is_identity', 'YES')
            ->orderBy('table_name')
            ->orderBy('column_name')
            ->get(['table_name', 'column_name']);

        if ($identityCols->isEmpty()) {
            $this->line('  No identity columns found.');
            return;
        }

        $reset = 0;
        foreach ($identityCols as $col) {
            $table = $col->table_name;
            $column = $col->column_name;
            $seqName = "{$table}_{$column}_seq";

            $seqExists = DB::table('information_schema.sequences')
                ->where('sequence_schema', 'public')
                ->where('sequence_name', $seqName)
                ->exists();

            if (!$seqExists) {
                // Fall back to the conventional "{table}_id_seq" name used by
                // older migrations.
                $seqName = "{$table}_id_seq";
                $seqExists = DB::table('information_schema.sequences')
                    ->where('sequence_schema', 'public')
                    ->where('sequence_name', $seqName)
                    ->exists();
            }

            if (!$seqExists) {
                continue;
            }

            try {
                DB::statement(
                    "SELECT setval('{$seqName}', GREATEST((SELECT COALESCE(MAX(\"{$column}\"), 0) FROM \"{$table}\"), 1), true)"
                );
                $reset++;
            } catch (\Throwable $e) {
                $this->warn("  Could not reset {$seqName}: " . $e->getMessage());
            }
        }

        $this->line("  Reset {$reset} sequence(s).");
    }
}
