<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

/**
 * Restore basic data from the snapshot file.
 *
 * Usage:
 *   php artisan db:restore-basic
 *
 * What it does:
 *   - Reads database/sql/basic_data_snapshot.sql (generated by db:snapshot-basic).
 *   - Executes the SQL via DB::unprepared().
 *   - Resets all sequences (so future AUTO-INSERTs don't collide with
 *     restored explicit-id rows).
 *
 * Requires a snapshot file to exist. If not, prints instructions to create one.
 *
 * This is the equivalent of FULL_WITH_BASIC_DATA the user asked for,
 * implemented as an Artisan command (so it can be run repeatedly).
 *
 * Typical workflow:
 *   1. (one-time) php artisan db:snapshot-basic     # capture current state
 *   2. php artisan db:make-empty                    # wipe everything
 *   3. php artisan db:restore-basic                 # restore basic data
 *
 * Or to "reset to basic state" from any state:
 *   php artisan db:make-empty --force && php artisan db:restore-basic
 */
class DbRestoreBasic extends Command
{
    protected $signature = 'db:restore-basic
                            {--force : Skip confirmation prompt}';

    protected $description = 'Restore basic-data tables from database/sql/basic_data_snapshot.sql';

    public function handle(): int
    {
        $this->info('=== DB RESTORE (BASIC DATA) ===');
        $this->newLine();

        $path = database_path('sql/basic_data_snapshot.sql');

        // ---- Check snapshot exists ----
        if (!file_exists($path)) {
            $this->error('✗ Snapshot file not found: ' . $path);
            $this->newLine();
            $this->warn('To create a snapshot, run:');
            $this->line('  php artisan db:snapshot-basic');
            $this->newLine();
            $this->warn('Then commit database/sql/basic_data_snapshot.sql to the repo.');
            return self::FAILURE;
        }

        $size = filesize($path);
        $mtime = date('Y-m-d H:i:s', filemtime($path));
        $this->info("Snapshot file: {$path}");
        $this->info("Size: {$size} bytes | Last modified: {$mtime}");
        $this->newLine();

        // ---- Confirm ----
        if (!$this->option('force')) {
            if (!$this->confirm('Restore basic data from snapshot? (This will INSERT/REPLACE rows in basic-data tables)', false)) {
                $this->info('Aborted. No changes made.');
                return self::SUCCESS;
            }
        }

        // ---- Read snapshot ----
        $sql = file_get_contents($path);
        if ($sql === false || trim($sql) === '') {
            $this->error('✗ Snapshot file is empty or unreadable.');
            return self::FAILURE;
        }

        // ---- Execute restore ----
        $this->info('Executing snapshot SQL...');

        // Show BEFORE counts for sanity check (read from a few key tables).
        $beforeCounts = $this->getTableCounts([
            'branches', 'warehouses', 'employees', 'users', 'customers',
            'suppliers', 'products', 'ledgers', 'menus',
        ]);

        try {
            // Execute the snapshot. The SQL contains:
            //   SET session_replication_role = 'replica';
            //   DELETE FROM ...; INSERT INTO ... OVERRIDING SYSTEM VALUE ...;
            //   SET session_replication_role = 'origin';
            DB::unprepared($sql);
        } catch (\Throwable $e) {
            $this->error('✗ Restore failed: ' . $e->getMessage());
            $this->newLine();
            $this->warn('The database may be in a partial state. You may need to:');
            $this->line('  1. Run `php artisan db:make-empty --force` to wipe everything.');
            $this->line('  2. Fix the snapshot file (or re-run `php artisan db:snapshot-basic`).');
            $this->line('  3. Re-run `php artisan db:restore-basic`.');
            return self::FAILURE;
        }

        // ---- Reset sequences ----
        $this->info('Resetting ID sequences to MAX(id)...');
        $this->resetSequences();

        // ---- Verify ----
        $this->newLine();
        $this->info('✓ Restore complete. Verifying...');
        $afterCounts = $this->getTableCounts(array_keys($beforeCounts));

        $this->newLine();
        $this->info('Row counts (before → after):');
        foreach ($afterCounts as $table => $after) {
            $before = $beforeCounts[$table] ?? '?';
            $this->line("  {$table}: {$before} → {$after}");
        }

        $this->newLine();
        $this->info('Done. Basic data restored.');
        return self::SUCCESS;
    }

    /**
     * Get row counts for a list of tables (skips missing/uncountable tables).
     *
     * @param string[] $tables
     * @return array<string,int>
     */
    private function getTableCounts(array $tables): array
    {
        $counts = [];
        foreach ($tables as $t) {
            try {
                $count = DB::table($t)->count();
                $counts[$t] = $count;
            } catch (\Throwable $e) {
                // Skip — table doesn't exist or is a view.
            }
        }
        return $counts;
    }

    /**
     * Reset all identity sequences to MAX(id) so future AUTO-INSERTs don't
     * collide with restored explicit-id rows.
     */
    private function resetSequences(): void
    {
        // Find every table+column that uses an identity sequence.
        $identityCols = DB::table('information_schema.columns')
            ->where('table_schema', 'public')
            ->where('is_identity', 'YES')
            ->orderBy('table_name')
            ->orderBy('column_name')
            ->get(['table_name', 'column_name']);

        if ($identityCols->isEmpty()) {
            $this->line('  No identity columns found.');
            return;
        }

        $reset = 0;
        foreach ($identityCols as $col) {
            $table = $col->table_name;
            $column = $col->column_name;
            $seqName = "{$table}_{$column}_seq";

            // Verify the sequence exists.
            $seqExists = DB::table('information_schema.sequences')
                ->where('sequence_schema', 'public')
                ->where('sequence_name', $seqName)
                ->exists();

            if (!$seqExists) {
                // Fall back to the conventional "{table}_id_seq" name used by
                // older migrations (some Laravel migrations create sequences
                // named "{table}_id_seq" instead of using IDENTITY).
                $seqName = "{$table}_id_seq";
                $seqExists = DB::table('information_schema.sequences')
                    ->where('sequence_schema', 'public')
                    ->where('sequence_name', $seqName)
                    ->exists();
            }

            if (!$seqExists) {
                continue;
            }

            try {
                DB::statement(
                    "SELECT setval('{$seqName}', GREATEST((SELECT COALESCE(MAX(\"{$column}\"), 0) FROM \"{$table}\"), 1), true)"
                );
                $reset++;
            } catch (\Throwable $e) {
                $this->warn("  Could not reset {$seqName}: " . $e->getMessage());
            }
        }

        $this->line("  Reset {$reset} sequence(s).");
    }
}
