<?php

/**
 * Help System — Action Registry (Phase 3 fallback layer).
 *
 * Maps Controller@action -> menu_key, plus Controller@* wildcards.
 * Auto-generated from docs/help-inventory.csv by build_action_registry.py.
 * Total per-action mappings: 214
 * Total wildcard mappings:   59 (one per controller)
 *
 * Resolution priority in HelpService::menuKeyForRoute():
 *   1. Exact route-name match (registry.php).
 *   2. controller@action match (this file).
 *   3. controller@* wildcard (this file).
 *   4. null -> empty-state card.
 *
 * Duplicate controller@action pairs (first-wins):
 *   BranchDemandController@index -> finance.branch-demand (row 149)
 *                              NOT inventory.branch-demand (row 186, legacy alias)
 *
 * @return array<string,string>
 */
return [

    // -----------------------------------------------------------------------
    // Per-action mappings (controller@action -> menu_key)
    // -----------------------------------------------------------------------
    'AccountingPeriodController@index' => 'accounting.period-close',
    'ApprovalController@queue' => 'accounting.approvals',
    'ApprovalController@workflows' => 'accounting.approvals-workflows',
    'ArchiveController@customerLedger' => 'system.archive-customerLedger',
    'ArchiveController@index' => 'system.archive',
    'ArchiveController@supplierLedger' => 'system.archive-supplierLedger',
    'BankController@audit' => 'master-data.banks-audit',
    'BankController@index' => 'master-data.banks',
    'BankController@print' => 'master-data.banks-print',
    'BankReconciliationController@create' => 'accounting.bank-reconciliation-create',
    'BankReconciliationController@importStatementPage' => 'accounting.bank-reconciliation-import-statement',
    'BankReconciliationController@index' => 'accounting.bank-reconciliation',
    'BankReconciliationController@show' => 'accounting.bank-reconciliation-show',
    'BankReconciliationController@unreconciled' => 'accounting.bank-reconciliation-unreconciled',
    'BranchController@audit' => 'master-data.branches-audit',
    'BranchController@index' => 'master-data.branches',
    'BranchController@print' => 'master-data.branches-print',
    'BranchDemandController@audit' => 'finance.branch-demand-audit',
    'BranchDemandController@checklist' => 'finance.branch-demand-checklist',
    'BranchDemandController@index' => 'finance.branch-demand',
    'BranchDemandController@pending' => 'finance.branch-demand-pending',
    'BranchDemandController@pendingReceipt' => 'finance.branch-demand-pending-receipt',
    'BranchDemandController@priceRangeComparison' => 'finance.branch-demand-price-range-comparison',
    'BranchDemandController@reconcile' => 'finance.branch-demand-reconcile',
    'BranchDemandReportController@drillDown' => 'finance.branch-demand-weekly-report-drill-down',
    'BranchDemandReportController@weekly' => 'finance.branch-demand-weekly-report',
    'BranchDemandShadowController@comparisonDetail' => 'finance.branch-demand-shadow-comparison-detail',
    'BranchDemandShadowController@comparisons' => 'finance.branch-demand-shadow-comparisons',
    'BranchDemandShadowController@cutover' => 'finance.branch-demand-shadow-cutover',
    'BranchDemandShadowController@index' => 'finance.branch-demand-shadow',
    'BudgetController@index' => 'finance.budgets',
    'BudgetController@varianceReport' => 'finance.budgets-variance',
    'CommissionRuleController@create' => 'sales.commission-rules-create',
    'CommissionRuleController@index' => 'sales.commission-rules',
    'CommissionRuleController@show' => 'sales.commission-rules-show',
    'ConsolidationController@companiesIndex' => 'finance.consolidation-companies',
    'ConsolidationController@consolidatedBalanceSheet' => 'finance.consolidation-consolidated-bs',
    'ConsolidationController@consolidatedProfitAndLoss' => 'finance.consolidation-consolidated-pnl',
    'ConsolidationController@consolidatedTrialBalance' => 'finance.consolidation-consolidated-tb',
    'ConsolidationController@create' => 'finance.consolidation-create',
    'ConsolidationController@index' => 'finance.consolidation',
    'ConsolidationController@intercompanyReconciliation' => 'finance.consolidation-intercompany-reconciliation',
    'ConsolidationController@rulesIndex' => 'finance.consolidation-rules',
    'ConsolidationController@show' => 'finance.consolidation-show',
    'CsvExportController@exportChallans' => 'reports.csv-export-export-challans',
    'CsvExportController@exportInvoices' => 'reports.csv-export',
    'CustomerController@audit' => 'master-data.customers-audit',
    'CustomerController@index' => 'master-data.customers',
    'CustomerController@print' => 'master-data.customers-print',
    'CustomerPaymentController@audit' => 'sales.customer-payments-audit',
    'CustomerPaymentController@index' => 'sales.customer-payments',
    'CustomerPaymentController@printReceipt' => 'sales.customer-payments-print-receipt',
    'CustomerPaymentController@slip' => 'sales.customer-payments-slip',
    'CustomerPerformanceController@index' => 'reports.customer-performance',
    'DamageController@downloadAttachment' => 'inventory.damages-download-attachment',
    'DamageController@index' => 'inventory.damages',
    'DamageController@print' => 'inventory.damages-print',
    'DamageController@show' => 'inventory.damages-show',
    'DamageController@viewAttachment' => 'inventory.damages-view-attachment',
    'DimensionController@index' => 'finance.dimensions',
    'DimensionController@segmentBs' => 'finance.dimensions-segment-bs',
    'DimensionController@segmentPnl' => 'finance.dimensions-segment-pnl',
    'EmployeeController@account' => 'master-data.employees-account',
    'EmployeeController@audit' => 'master-data.employees-audit',
    'EmployeeController@index' => 'master-data.employees',
    'EmployeeController@print' => 'master-data.employees-print',
    'EmployeeTransactionController@audit' => 'accounting.employee-transactions-audit',
    'EmployeeTransactionController@index' => 'accounting.employee-transactions',
    'EmployeeTransactionController@show' => 'accounting.employee-transactions-show',
    'EmployeeTransactionController@slip' => 'accounting.employee-transactions-slip',
    'FiscalYearController@closeLog' => 'finance.fiscal-years-close-log',
    'FiscalYearController@index' => 'finance.fiscal-years',
    'FixedAssetController@depreciation' => 'finance.fixed-assets-depreciation',
    'FixedAssetController@disposals' => 'finance.fixed-assets-disposals',
    'FixedAssetController@index' => 'finance.fixed-assets',
    'FixedAssetController@showDisposal' => 'finance.fixed-assets-show-disposal',
    'GlobalAuditController@index' => 'system.audit',
    'GlobalAuditController@show' => 'system.audit-show',
    'GoLiveChecklistController@index' => 'sales.go-live-checklist',
    'LedgerController@audit' => 'master-data.ledgers-audit',
    'LedgerController@index' => 'master-data.ledgers',
    'LedgerController@print' => 'master-data.ledgers-print',
    'ManualJournalController@audit' => 'accounting.manual-journals-audit',
    'ManualJournalController@index' => 'accounting.manual-journals',
    'ManualJournalController@show' => 'accounting.manual-journals-show',
    'MoneyTransferController@audit' => 'accounting.money-transfers-audit',
    'MoneyTransferController@index' => 'accounting.money-transfers',
    'MoneyTransferController@show' => 'accounting.money-transfers-show',
    'MoneyTransferController@slip' => 'accounting.money-transfers-slip',
    'NotificationController@inbox' => 'system.notifications-inbox',
    'NotificationController@rules' => 'system.notifications',
    'OtherExpenseController@audit' => 'accounting.other-expenses-audit',
    'OtherExpenseController@index' => 'accounting.other-expenses',
    'OtherExpenseController@show' => 'accounting.other-expenses-show',
    'OtherExpenseController@slip' => 'accounting.other-expenses-slip',
    'OtherIncomeController@audit' => 'accounting.other-incomes-audit',
    'OtherIncomeController@index' => 'accounting.other-incomes',
    'OtherIncomeController@show' => 'accounting.other-incomes-show',
    'OtherIncomeController@slip' => 'accounting.other-incomes-slip',
    'PartitionHealthController@index' => 'system.partition-health',
    'ProductCategoryController@audit' => 'master-data.product-categories-audit',
    'ProductCategoryController@index' => 'master-data.product-categories',
    'ProductController@audit' => 'master-data.products-audit',
    'ProductController@index' => 'master-data.products',
    'ProductController@priceHistory' => 'master-data.products-price-history',
    'ProductController@print' => 'master-data.products-print',
    'ProductGroupController@audit' => 'master-data.product-groups-audit',
    'ProductGroupController@index' => 'master-data.product-groups',
    'PurchaseAuditController@checklist' => 'purchasing.purchase-audit',
    'PurchaseOrderController@audit' => 'purchasing.purchase-orders-audit',
    'PurchaseOrderController@index' => 'purchasing.purchase-orders',
    'PurchaseReceiveController@audit' => 'purchasing.purchase-receives-audit',
    'PurchaseReceiveController@index' => 'purchasing.purchase-receives',
    'PurchaseReturnController@audit' => 'purchasing.purchase-returns-audit',
    'PurchaseReturnController@index' => 'purchasing.purchase-returns',
    'PurchaseReturnController@slip' => 'purchasing.purchase-returns-slip',
    'ReconciliationController@index' => 'accounting.reconciliation',
    'ReconciliationController@section' => 'accounting.reconciliation-section',
    'ReportController@arAgingCte' => 'reports.reports-hub-arAgingCte',
    'ReportController@balanceSheet' => 'reports.reports-hub-balanceSheet',
    'ReportController@branchDemandWeekly' => 'reports.reports-hub-branchDemandWeekly',
    'ReportController@branchIntercompany' => 'reports.reports-hub-branchIntercompany',
    'ReportController@branchWiseLedger' => 'reports.reports-hub-branchWiseLedger',
    'ReportController@cashFlow' => 'reports.reports-hub-cashFlow',
    'ReportController@dailyCashBook' => 'reports.reports-hub-dailyCashBook',
    'ReportController@damageReport' => 'reports.reports-hub-damageReport',
    'ReportController@damageReportExport' => 'reports.reports-hub-damageReportExport',
    'ReportController@generalLedger' => 'reports.reports-hub-generalLedger',
    'ReportController@generalLedgerCte' => 'reports.reports-hub-generalLedgerCte',
    'ReportController@grossMargin' => 'reports.reports-hub-grossMargin',
    'ReportController@grossMarginCte' => 'reports.reports-hub-grossMarginCte',
    'ReportController@index' => 'reports.reports-hub',
    'ReportController@journalEntries' => 'reports.reports-hub-journalEntries',
    'ReportController@payableAging' => 'reports.reports-hub-payableAging',
    'ReportController@productMovement' => 'reports.reports-hub-productMovement',
    'ReportController@productStockAnalysis' => 'reports.reports-hub-productStockAnalysis',
    'ReportController@profitAndLoss' => 'reports.reports-hub-profitAndLoss',
    'ReportController@purchaseAudit' => 'reports.reports-hub-purchaseAudit',
    'ReportController@receivableAging' => 'reports.reports-hub-receivableAging',
    'ReportController@revenueOverview' => 'reports.reports-hub-revenueOverview',
    'ReportController@salesAuditChecklist' => 'reports.reports-hub-salesAuditChecklist',
    'ReportController@salesAuditRun' => 'reports.reports-hub-salesAuditRun',
    'ReportController@stocktakeVariance' => 'reports.reports-hub-stocktakeVariance',
    'ReportController@stocktakeVarianceExport' => 'reports.reports-hub-stocktakeVarianceExport',
    'ReportController@stocktakeWeekly' => 'reports.reports-hub-stocktakeWeekly',
    'ReportController@stocktakeWeeklyExport' => 'reports.reports-hub-stocktakeWeeklyExport',
    'ReportController@supplierWisePurchase' => 'reports.reports-hub-supplierWisePurchase',
    'ReportController@todaySummaryCte' => 'reports.reports-hub-todaySummaryCte',
    'ReportController@trialBalance' => 'reports.reports-hub-trialBalance',
    'SalesCartController@index' => 'sales.cart',
    'SalesChallanController@blankGodownForm' => 'sales.challans-blank-godown-form',
    'SalesChallanController@challanForm' => 'sales.challans-challan-form',
    'SalesChallanController@godown' => 'sales.challans-godown',
    'SalesChallanController@index' => 'sales.challans',
    'SalesChallanController@printChallan' => 'sales.challans-print-challan',
    'SalesFunnelController@index' => 'reports.sales-funnel',
    'SalesGuideController@guide' => 'sales.guide',
    'SalesInvoiceController@auditTrail' => 'sales.invoices-audit',
    'SalesInvoiceController@index' => 'sales.invoices',
    'SalesInvoiceController@printBlankGodown' => 'sales.invoices-print-blank-godown',
    'SalesInvoiceController@printGodown' => 'sales.invoices-print-godown',
    'SalesInvoiceController@printInvoice' => 'sales.invoices-print-invoice',
    'SalesInvoiceController@receiveModal' => 'sales.invoices-receive-modal',
    'SalesReturnController@audit' => 'sales.returns-audit',
    'SalesReturnController@index' => 'sales.returns',
    'SalesReturnController@printSlip' => 'sales.returns-print-slip',
    'SalesReturnController@reversePreview' => 'sales.returns-reverse-preview',
    'ShadowModeController@comparisonDetail' => 'finance.shadow-mode-comparison-detail',
    'ShadowModeController@comparisons' => 'finance.shadow-mode-comparisons',
    'ShadowModeController@cutover' => 'finance.shadow-mode-cutover',
    'ShadowModeController@index' => 'finance.shadow-mode',
    'SseController@events' => 'system.sse',
    'SseController@status' => 'system.sse-status',
    'StockAdjustmentController@audit' => 'inventory.stock-adjustments-audit',
    'StockAdjustmentController@checklist' => 'inventory.stock-adjustments-checklist',
    'StockAdjustmentController@index' => 'inventory.stock-adjustments',
    'StockAdjustmentController@print' => 'inventory.stock-adjustments-print',
    'StockAdjustmentController@reconcile' => 'inventory.stock-adjustments-reconcile',
    'StockAdjustmentController@show' => 'inventory.stock-adjustments-show',
    'StockTakeController@abcReport' => 'inventory.stock-take-abc-report',
    'StockTakeController@audit' => 'inventory.stock-take-audit',
    'StockTakeController@checklist' => 'inventory.stock-take-checklist',
    'StockTakeController@count' => 'inventory.stock-take-count',
    'StockTakeController@healthSummary' => 'inventory.stock-take-health-summary',
    'StockTakeController@index' => 'inventory.stock-take',
    'StockTakeController@setupCounts' => 'inventory.stock-take-setup',
    'StockTransactionController@drift' => 'inventory.stock-transactions-drift',
    'StockTransactionController@index' => 'inventory.stock-transactions',
    'StockTransactionController@show' => 'inventory.stock-transactions-show',
    'StockTransactionController@warehouseStock' => 'inventory.stock-transactions-warehouse-stock',
    'SupplierController@audit' => 'master-data.suppliers-audit',
    'SupplierController@index' => 'master-data.suppliers',
    'SupplierController@print' => 'master-data.suppliers-print',
    'SupplierTransactionController@audit' => 'accounting.supplier-transactions-audit',
    'SupplierTransactionController@index' => 'accounting.supplier-transactions',
    'SupplierTransactionController@show' => 'accounting.supplier-transactions-show',
    'SupplierTransactionController@slip' => 'accounting.supplier-transactions-slip',
    'SystemHealthController@index' => 'system.system-health',
    'SystemPolicyController@index' => 'system.compliance',
    'UserController@audit' => 'system.users-audit',
    'UserController@index' => 'system.users',
    'UserController@menuPermissions' => 'system.users-menu-permissions',
    'UserController@print' => 'system.users-print',
    'UserController@securityAudit' => 'system.users-security-audit',
    'UserPerformanceDashboardController@index' => 'reports.dashboard',
    'WarehouseController@audit' => 'master-data.warehouses-audit',
    'WarehouseController@index' => 'master-data.warehouses',
    'WarehouseController@print' => 'master-data.warehouses-print',
    'WarehouseTransferController@audit' => 'inventory.warehouse-transfers-audit',
    'WarehouseTransferController@checklist' => 'inventory.warehouse-transfers-checklist',
    'WarehouseTransferController@index' => 'inventory.warehouse-transfers',
    'WarehouseTransferController@print' => 'inventory.warehouse-transfers-print',
    'WarehouseTransferController@reconcile' => 'inventory.warehouse-transfers-reconcile',
    'WarehouseTransferController@summary' => 'inventory.warehouse-transfers-summary',

    // -----------------------------------------------------------------------
    // Wildcard mappings (controller@* -> primary menu_key)
    // Catches collapsed resource actions (create/store/show/edit/update/destroy)
    // and any route not explicitly registered in registry.php.
    // -----------------------------------------------------------------------
    'AccountingPeriodController@*' => 'accounting.period-close',
    'ApprovalController@*' => 'accounting.approvals',
    'ArchiveController@*' => 'system.archive',
    'BankController@*' => 'master-data.banks',
    'BankReconciliationController@*' => 'accounting.bank-reconciliation',
    'BranchController@*' => 'master-data.branches',
    'BranchDemandController@*' => 'finance.branch-demand',
    'BranchDemandReportController@*' => 'finance.branch-demand-weekly-report-drill-down',
    'BranchDemandShadowController@*' => 'finance.branch-demand-shadow',
    'BudgetController@*' => 'finance.budgets',
    'CommissionRuleController@*' => 'sales.commission-rules',
    'ConsolidationController@*' => 'finance.consolidation',
    'CsvExportController@*' => 'reports.csv-export-export-challans',
    'CustomerController@*' => 'master-data.customers',
    'CustomerPaymentController@*' => 'sales.customer-payments',
    'CustomerPerformanceController@*' => 'reports.customer-performance',
    'DamageController@*' => 'inventory.damages',
    'DimensionController@*' => 'finance.dimensions',
    'EmployeeController@*' => 'master-data.employees',
    'EmployeeTransactionController@*' => 'accounting.employee-transactions',
    'FiscalYearController@*' => 'finance.fiscal-years',
    'FixedAssetController@*' => 'finance.fixed-assets',
    'GlobalAuditController@*' => 'system.audit',
    'GoLiveChecklistController@*' => 'sales.go-live-checklist',
    'LedgerController@*' => 'master-data.ledgers',
    'ManualJournalController@*' => 'accounting.manual-journals',
    'MoneyTransferController@*' => 'accounting.money-transfers',
    'NotificationController@*' => 'system.notifications-inbox',
    'OtherExpenseController@*' => 'accounting.other-expenses',
    'OtherIncomeController@*' => 'accounting.other-incomes',
    'PartitionHealthController@*' => 'system.partition-health',
    'ProductCategoryController@*' => 'master-data.product-categories',
    'ProductController@*' => 'master-data.products',
    'ProductGroupController@*' => 'master-data.product-groups',
    'PurchaseAuditController@*' => 'purchasing.purchase-audit',
    'PurchaseOrderController@*' => 'purchasing.purchase-orders',
    'PurchaseReceiveController@*' => 'purchasing.purchase-receives',
    'PurchaseReturnController@*' => 'purchasing.purchase-returns',
    'ReconciliationController@*' => 'accounting.reconciliation',
    'ReportController@*' => 'reports.reports-hub',
    'SalesCartController@*' => 'sales.cart',
    'SalesChallanController@*' => 'sales.challans',
    'SalesFunnelController@*' => 'reports.sales-funnel',
    'SalesGuideController@*' => 'sales.guide',
    'SalesInvoiceController@*' => 'sales.invoices',
    'SalesReturnController@*' => 'sales.returns',
    'ShadowModeController@*' => 'finance.shadow-mode',
    'SseController@*' => 'system.sse',
    'StockAdjustmentController@*' => 'inventory.stock-adjustments',
    'StockTakeController@*' => 'inventory.stock-take',
    'StockTransactionController@*' => 'inventory.stock-transactions',
    'SupplierController@*' => 'master-data.suppliers',
    'SupplierTransactionController@*' => 'accounting.supplier-transactions',
    'SystemHealthController@*' => 'system.system-health',
    'SystemPolicyController@*' => 'system.compliance',
    'UserController@*' => 'system.users',
    'UserPerformanceDashboardController@*' => 'reports.dashboard',
    'WarehouseController@*' => 'master-data.warehouses',
    'WarehouseTransferController@*' => 'inventory.warehouse-transfers',
];
