<?php

/**
 * Help System — Module Registry (Phase 2 scaffold).
 *
 * Metadata for the 8 functional modules + the list of menu_keys under each.
 * Auto-generated from docs/help-inventory.csv (Phase 1).
 * Total modules: 8; total menu_keys: 215
 *
 * Each module: key, title_bn, title_en, icon, color, tagline, menus[].
 * 'menus' lists ALL menu_keys (primary + sub-pages). Phase 7 will mark
 * primary vs sub-page for display purposes; for now the module offcanvas
 * shows the full list.
 *
 * @return array<string,array>
 */
return [
    'master-data' => [
        'key' => 'master-data',
        'title_bn' => 'মাস্টার ডেটা',
        'title_en' => 'Master Data',
        'icon' => 'fa-database',
        'color' => 'slate',
        'tagline' => 'পণ্য, খদ্দের, সাপ্লায়ার, কর্মচারী, ব্যাংক, লেজার — ব্যবসার মূল তথ্য।',
        'menus' => [
            'master-data.banks',
            'master-data.banks-audit',
            'master-data.banks-print',
            'master-data.branches',
            'master-data.branches-audit',
            'master-data.branches-print',
            'master-data.customers',
            'master-data.customers-audit',
            'master-data.customers-print',
            'master-data.employees',
            'master-data.employees-account',
            'master-data.employees-audit',
            'master-data.employees-print',
            'master-data.ledgers',
            'master-data.ledgers-audit',
            'master-data.ledgers-print',
            'master-data.product-categories',
            'master-data.product-categories-audit',
            'master-data.product-groups',
            'master-data.product-groups-audit',
            'master-data.products',
            'master-data.products-audit',
            'master-data.products-price-history',
            'master-data.products-print',
            'master-data.suppliers',
            'master-data.suppliers-audit',
            'master-data.suppliers-print',
            'master-data.warehouses',
            'master-data.warehouses-audit',
            'master-data.warehouses-print',
        ],
        'updated_at' => '2026-08-06',
    ],
    'inventory' => [
        'key' => 'inventory',
        'title_bn' => 'ইনভেন্টরি',
        'title_en' => 'Inventory',
        'icon' => 'fa-boxes-stacked',
        'color' => 'amber',
        'tagline' => 'স্টক লেজার, ফিজিক্যাল কাউন্ট, ক্ষতি, ওয়্যারহাউস ট্রান্সফার — মালামালের হিসাব।',
        'menus' => [
            'inventory.damages',
            'inventory.damages-download-attachment',
            'inventory.damages-print',
            'inventory.damages-show',
            'inventory.damages-view-attachment',
            'inventory.stock-adjustments',
            'inventory.stock-adjustments-audit',
            'inventory.stock-adjustments-checklist',
            'inventory.stock-adjustments-print',
            'inventory.stock-adjustments-reconcile',
            'inventory.stock-adjustments-show',
            'inventory.stock-take',
            'inventory.stock-take-abc-report',
            'inventory.stock-take-audit',
            'inventory.stock-take-checklist',
            'inventory.stock-take-count',
            'inventory.stock-take-health-summary',
            'inventory.stock-take-setup',
            'inventory.stock-transactions',
            'inventory.stock-transactions-drift',
            'inventory.stock-transactions-show',
            'inventory.stock-transactions-warehouse-stock',
            'inventory.warehouse-transfers',
            'inventory.warehouse-transfers-audit',
            'inventory.warehouse-transfers-checklist',
            'inventory.warehouse-transfers-print',
            'inventory.warehouse-transfers-reconcile',
            'inventory.warehouse-transfers-summary',
        ],
        'updated_at' => '2026-08-06',
    ],
    'purchasing' => [
        'key' => 'purchasing',
        'title_bn' => 'ক্রয়',
        'title_en' => 'Purchasing',
        'icon' => 'fa-truck-ramp-box',
        'color' => 'sky',
        'tagline' => 'পি. অর্ডার, রিসিভ, রিটার্ন — সাপ্লায়ার থেকে মাল কেনা।',
        'menus' => [
            'purchasing.purchase-audit',
            'purchasing.purchase-orders',
            'purchasing.purchase-orders-audit',
            'purchasing.purchase-receives',
            'purchasing.purchase-receives-audit',
            'purchasing.purchase-returns',
            'purchasing.purchase-returns-audit',
            'purchasing.purchase-returns-slip',
        ],
        'updated_at' => '2026-08-06',
    ],
    'sales' => [
        'key' => 'sales',
        'title_bn' => 'সেলস',
        'title_en' => 'Sales',
        'icon' => 'fa-cart-shopping',
        'color' => 'emerald',
        'tagline' => 'কার্ট, ইনভয়েস, চালান, রিটার্ন, পেমেন্ট — খদ্দেরকে বিক্রি।',
        'menus' => [
            'sales.cart',
            'sales.challans',
            'sales.challans-blank-godown-form',
            'sales.challans-challan-form',
            'sales.challans-godown',
            'sales.challans-print-challan',
            'sales.commission-rules',
            'sales.commission-rules-create',
            'sales.commission-rules-show',
            'sales.customer-payments',
            'sales.customer-payments-audit',
            'sales.customer-payments-print-receipt',
            'sales.customer-payments-slip',
            'sales.go-live-checklist',
            'sales.guide',
            'sales.invoices',
            'sales.invoices-audit',
            'sales.invoices-print-blank-godown',
            'sales.invoices-print-godown',
            'sales.invoices-print-invoice',
            'sales.invoices-receive-modal',
            'sales.returns',
            'sales.returns-audit',
            'sales.returns-print-slip',
            'sales.returns-reverse-preview',
        ],
        'updated_at' => '2026-08-06',
    ],
    'accounting' => [
        'key' => 'accounting',
        'title_bn' => 'হিসাব',
        'title_en' => 'Accounting',
        'icon' => 'fa-calculator',
        'color' => 'violet',
        'tagline' => 'জার্নাল, ট্রান্সফার, সাব-লেজার, রিকনসিলিয়েশন, পিরিয়ড ক্লোজ — ডাবল-এন্ট্রি হিসাব।',
        'menus' => [
            'accounting.approvals',
            'accounting.approvals-workflows',
            'accounting.bank-reconciliation',
            'accounting.bank-reconciliation-create',
            'accounting.bank-reconciliation-import-statement',
            'accounting.bank-reconciliation-show',
            'accounting.bank-reconciliation-unreconciled',
            'accounting.employee-transactions',
            'accounting.employee-transactions-audit',
            'accounting.employee-transactions-show',
            'accounting.employee-transactions-slip',
            'accounting.manual-journals',
            'accounting.manual-journals-audit',
            'accounting.manual-journals-show',
            'accounting.money-transfers',
            'accounting.money-transfers-audit',
            'accounting.money-transfers-show',
            'accounting.money-transfers-slip',
            'accounting.other-expenses',
            'accounting.other-expenses-audit',
            'accounting.other-expenses-show',
            'accounting.other-expenses-slip',
            'accounting.other-incomes',
            'accounting.other-incomes-audit',
            'accounting.other-incomes-show',
            'accounting.other-incomes-slip',
            'accounting.period-close',
            'accounting.reconciliation',
            'accounting.reconciliation-section',
            'accounting.supplier-transactions',
            'accounting.supplier-transactions-audit',
            'accounting.supplier-transactions-show',
            'accounting.supplier-transactions-slip',
        ],
        'updated_at' => '2026-08-06',
    ],
    'finance' => [
        'key' => 'finance',
        'title_bn' => 'ফাইন্যান্স',
        'title_en' => 'Finance',
        'icon' => 'fa-coins',
        'color' => 'rose',
        'tagline' => 'ফিক্সড অ্যাসেট, বাজেট, কনসলিডেশন, ব্র্যাঞ্চ ডিমান্ড — দীর্ঘমেয়াদি আর্থিক ব্যবস্থাপনা।',
        'menus' => [
            'finance.branch-demand',
            'finance.branch-demand-audit',
            'finance.branch-demand-checklist',
            'finance.branch-demand-pending',
            'finance.branch-demand-pending-receipt',
            'finance.branch-demand-price-range-comparison',
            'finance.branch-demand-reconcile',
            'finance.branch-demand-shadow',
            'finance.branch-demand-shadow-comparison-detail',
            'finance.branch-demand-shadow-comparisons',
            'finance.branch-demand-shadow-cutover',
            'finance.branch-demand-weekly-report',
            'finance.branch-demand-weekly-report-drill-down',
            'finance.budgets',
            'finance.budgets-variance',
            'finance.consolidation',
            'finance.consolidation-companies',
            'finance.consolidation-consolidated-bs',
            'finance.consolidation-consolidated-pnl',
            'finance.consolidation-consolidated-tb',
            'finance.consolidation-create',
            'finance.consolidation-intercompany-reconciliation',
            'finance.consolidation-rules',
            'finance.consolidation-show',
            'finance.dimensions',
            'finance.dimensions-segment-bs',
            'finance.dimensions-segment-pnl',
            'finance.fiscal-years',
            'finance.fiscal-years-close-log',
            'finance.fixed-assets',
            'finance.fixed-assets-depreciation',
            'finance.fixed-assets-disposals',
            'finance.fixed-assets-show-disposal',
            'finance.shadow-mode',
            'finance.shadow-mode-comparison-detail',
            'finance.shadow-mode-comparisons',
            'finance.shadow-mode-cutover',
            'inventory.branch-demand',
        ],
        'updated_at' => '2026-08-06',
    ],
    'reports' => [
        'key' => 'reports',
        'title_bn' => 'রিপোর্ট',
        'title_en' => 'Reports',
        'icon' => 'fa-chart-pie',
        'color' => 'teal',
        'tagline' => 'ড্যাশবোর্ড, রিপোর্ট হাব, সিএসভি এক্সপোর্ট — সব রিপোর্ট এক জায়গায়।',
        'menus' => [
            'reports.csv-export',
            'reports.csv-export-export-challans',
            'reports.customer-performance',
            'reports.dashboard',
            'reports.reports-hub',
            'reports.reports-hub-arAgingCte',
            'reports.reports-hub-balanceSheet',
            'reports.reports-hub-branchDemandWeekly',
            'reports.reports-hub-branchIntercompany',
            'reports.reports-hub-branchWiseLedger',
            'reports.reports-hub-cashFlow',
            'reports.reports-hub-dailyCashBook',
            'reports.reports-hub-damageReport',
            'reports.reports-hub-damageReportExport',
            'reports.reports-hub-generalLedger',
            'reports.reports-hub-generalLedgerCte',
            'reports.reports-hub-grossMargin',
            'reports.reports-hub-grossMarginCte',
            'reports.reports-hub-journalEntries',
            'reports.reports-hub-payableAging',
            'reports.reports-hub-productMovement',
            'reports.reports-hub-productStockAnalysis',
            'reports.reports-hub-profitAndLoss',
            'reports.reports-hub-purchaseAudit',
            'reports.reports-hub-receivableAging',
            'reports.reports-hub-revenueOverview',
            'reports.reports-hub-salesAuditChecklist',
            'reports.reports-hub-salesAuditRun',
            'reports.reports-hub-stocktakeVariance',
            'reports.reports-hub-stocktakeVarianceExport',
            'reports.reports-hub-stocktakeWeekly',
            'reports.reports-hub-stocktakeWeeklyExport',
            'reports.reports-hub-supplierWisePurchase',
            'reports.reports-hub-todaySummaryCte',
            'reports.reports-hub-trialBalance',
            'reports.sales-funnel',
        ],
        'updated_at' => '2026-08-06',
    ],
    'system' => [
        'key' => 'system',
        'title_bn' => 'সিস্টেম',
        'title_en' => 'System',
        'icon' => 'fa-gear',
        'color' => 'indigo',
        'tagline' => 'ইউজার, নোটিফিকেশন, অডিট, পলিসি, আর্কাইভ — সিস্টেম প্রশাসন।',
        'menus' => [
            'system.archive',
            'system.archive-customerLedger',
            'system.archive-supplierLedger',
            'system.audit',
            'system.audit-show',
            'system.compliance',
            'system.notifications',
            'system.notifications-inbox',
            'system.partition-health',
            'system.sse',
            'system.sse-status',
            'system.system-health',
            'system.users',
            'system.users-audit',
            'system.users-menu-permissions',
            'system.users-print',
            'system.users-security-audit',
        ],
        'updated_at' => '2026-08-06',
    ],
];
